from src.backend.features.game_catalog.skills.dto.catalog import SkillCategory, SkillDTO, SkillGroup, SkillUiGroup

CRAFTING_SKILLS = [
    SkillDTO(
        skill_key="skill_alchemy",
        name_en="Alchemy",
        name_ru="Алхимия",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.CRAFTING,
        ui_group=SkillUiGroup.CRAFTING,
        stat_weights={"intellect": 2, "memory": 1, "prediction": 1},
        rate_mod=1.5,
        wall_mod=1.0,
        description="Создание зелий, эликсиров и трансмутация веществ.",
    ),
    SkillDTO(
        skill_key="skill_weapon_craft",
        name_en="Weapon Crafting",
        name_ru="Оружейное дело",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.CRAFTING,
        ui_group=SkillUiGroup.CRAFTING,
        stat_weights={"strength": 2, "agility": 1, "perception": 1},
        rate_mod=2.0,
        wall_mod=1.0,
        description="Изготовление и ремонт оружия.",
    ),
    SkillDTO(
        skill_key="skill_armor_craft",
        name_en="Armor Crafting",
        name_ru="Бронное дело",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.CRAFTING,
        ui_group=SkillUiGroup.CRAFTING,
        stat_weights={"strength": 2, "endurance": 2},
        rate_mod=2.0,
        wall_mod=1.0,
        description="Изготовление и ремонт доспехов.",
    ),
    SkillDTO(
        skill_key="skill_jewelry_craft",
        name_en="Jewelry Crafting",
        name_ru="Ювелирное дело",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.CRAFTING,
        ui_group=SkillUiGroup.CRAFTING,
        stat_weights={"agility": 2, "perception": 1, "prediction": 1},
        rate_mod=2.0,
        wall_mod=1.0,
        description="Создание ювелирных украшений и огранка камней.",
    ),
    SkillDTO(
        skill_key="skill_artifact_craft",
        name_en="Artifact Crafting",
        name_ru="Создание артефактов",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.CRAFTING,
        ui_group=SkillUiGroup.CRAFTING,
        stat_weights={"mental": 2, "intellect": 1, "memory": 1},
        rate_mod=2.5,
        wall_mod=1.5,
        description="Создание магических артефактов и предметов силы.",
    ),
    SkillDTO(
        skill_key="skill_engineering",
        name_en="Engineering",
        name_ru="Инженерия",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.CRAFTING,
        ui_group=SkillUiGroup.CRAFTING,
        stat_weights={"intellect": 2, "agility": 1, "perception": 1},
        rate_mod=2.0,
        wall_mod=1.0,
        description="Создание механизмов, инструментов, ловушек и технических устройств.",
    ),
]
