from src.backend.features.game_catalog.skills.dto.catalog import SkillCategory, SkillDTO, SkillGroup, SkillUiGroup

GATHERING_SKILLS = [
    SkillDTO(
        skill_key="skill_mining",
        name_en="Mining",
        name_ru="Горное дело",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.WORLD,
        ui_group=SkillUiGroup.GATHERING,
        stat_weights={"strength": 2, "endurance": 2},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Добыча руды и драгоценных камней.",
    ),
    SkillDTO(
        skill_key="skill_herbalism",
        name_en="Herbalism",
        name_ru="Травничество",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.WORLD,
        ui_group=SkillUiGroup.GATHERING,
        stat_weights={"perception": 2, "memory": 1, "intellect": 1},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Сбор трав, грибов и других растений.",
    ),
    SkillDTO(
        skill_key="skill_skinning",
        name_en="Skinning",
        name_ru="Снятие шкур",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.WORLD,
        ui_group=SkillUiGroup.GATHERING,
        stat_weights={"agility": 2, "perception": 1, "endurance": 1},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Снятие шкур с убитых животных.",
    ),
    SkillDTO(
        skill_key="skill_woodcutting",
        name_en="Woodcutting",
        name_ru="Лесорубство",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.WORLD,
        ui_group=SkillUiGroup.GATHERING,
        stat_weights={"strength": 2, "endurance": 2},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Рубка деревьев и заготовка древесины.",
    ),
    SkillDTO(
        skill_key="skill_hunting",
        name_en="Hunting",
        name_ru="Охота",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.WORLD,
        ui_group=SkillUiGroup.GATHERING,
        stat_weights={"perception": 2, "agility": 1, "endurance": 1},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Выслеживание и добыча диких животных.",
    ),
    SkillDTO(
        skill_key="skill_archaeology",
        name_en="Archaeology",
        name_ru="Археология",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.WORLD,
        ui_group=SkillUiGroup.GATHERING,
        stat_weights={"perception": 2, "memory": 1, "intellect": 1},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Поиск и изучение древних артефактов.",
    ),
]
