from src.backend.features.game_catalog.skills.dto.catalog import SkillCategory, SkillDTO, SkillGroup, SkillUiGroup

SURVIVAL_SKILLS = [
    SkillDTO(
        skill_key="skill_taming",
        name_en="Taming",
        name_ru="Приручение",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.WORLD,
        ui_group=SkillUiGroup.SURVIVAL,
        stat_weights={"projection": 2, "memory": 1, "mental": 1},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Способность приручать диких животных и управлять ими.",
    ),
    SkillDTO(
        skill_key="skill_adaptation",
        name_en="Adaptation",
        name_ru="Адаптация",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.WORLD,
        ui_group=SkillUiGroup.SURVIVAL,
        stat_weights={"endurance": 2, "mental": 2},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Умение выживать в агрессивной среде, сопротивляться погодным условиям и болезням.",
    ),
    SkillDTO(
        skill_key="skill_scouting",
        name_en="Scouting",
        name_ru="Выслеживание",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.WORLD,
        ui_group=SkillUiGroup.SURVIVAL,
        stat_weights={"perception": 2, "memory": 1, "agility": 1},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Умение находить безопасные пути, избегать нежелательных встреч и выслеживать цели.",
    ),
    SkillDTO(
        skill_key="skill_pathfinder",
        name_en="Pathfinder",
        name_ru="Навигация",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.WORLD,
        ui_group=SkillUiGroup.SURVIVAL,
        stat_weights={"perception": 2, "endurance": 1, "agility": 1},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Поиск маршрутов, чтение местности и работа с дорожными опасностями.",
    ),
]
