"""
ЭКИПИРОВКА МОНСТРОВ: ОБОРОТНИ
=============================
"""

WEREWOLVES_EQUIPMENT = {
    # --- ОРУЖИЕ ---
    "claw_weak": {
        "id": "claw_weak",
        "name_ru": "Слабые когти",
        "slot": "main_hand",
        "type": "weapon",
        "base_power": 4,
        "damage_spread": 0.2,
        "implicit_bonuses": {"bleed_damage_bonus": 0.10},
    },
    "claw_wolf": {
        "id": "claw_wolf",
        "name_ru": "Волчьи когти",
        "slot": "main_hand",
        "type": "weapon",
        "base_power": 8,
        "damage_spread": 0.15,
        "implicit_bonuses": {"physical_crit_chance": 0.10, "bleed_damage_bonus": 0.15},
    },
    "fang_wolf": {
        "id": "fang_wolf",
        "name_ru": "Волчьи клыки",
        "slot": "main_hand",
        "type": "weapon",
        "base_power": 10,
        "damage_spread": 0.1,
        "implicit_bonuses": {"physical_penetration": 0.10},
    },
    "claw_razor": {
        "id": "claw_razor",
        "name_ru": "Когти-бритвы",
        "slot": "main_hand",
        "type": "weapon",
        "base_power": 12,
        "damage_spread": 0.05,
        "implicit_bonuses": {"physical_crit_chance": 0.20, "bleed_damage_bonus": 0.30},
    },
    "claw_assassin": {
        "id": "claw_assassin",
        "name_ru": "Когти убийцы",
        "slot": "main_hand",
        "type": "weapon",
        "base_power": 14,
        "damage_spread": 0.05,
        "implicit_bonuses": {"physical_crit_power_float": 0.5, "stealth_bonus": 0.2},
    },
    "fist_heavy": {
        "id": "fist_heavy",
        "name_ru": "Тяжелый кулак",
        "slot": "main_hand",
        "type": "weapon",
        "base_power": 18,
        "damage_spread": 0.2,
        "implicit_bonuses": {"stun_chance": 0.15},
    },
    "fang_vampiric": {
        "id": "fang_vampiric",
        "name_ru": "Вампирские клыки",
        "slot": "main_hand",
        "type": "weapon",
        "base_power": 16,
        "damage_spread": 0.1,
        "implicit_bonuses": {"lifesteal": 0.15},
    },
    "claw_serrated": {
        "id": "claw_serrated",
        "name_ru": "Зазубренные когти",
        "slot": "off_hand",
        "type": "weapon",
        "base_power": 14,
        "damage_spread": 0.1,
        "implicit_bonuses": {"bleed_damage_bonus": 0.50},
    },
    "totem_wolf_paw": {
        "id": "totem_wolf_paw",
        "name_ru": "Тотем волчьей лапы",
        "slot": "main_hand",
        "type": "weapon",
        "base_power": 12,
        "damage_spread": 0.1,
        "implicit_bonuses": {"magical_damage_bonus": 0.20},
    },
    "claw_alpha": {
        "id": "claw_alpha",
        "name_ru": "Когти Альфы",
        "slot": "main_hand",
        "type": "weapon",
        "base_power": 25,
        "damage_spread": 0.1,
        "implicit_bonuses": {"physical_damage_bonus": 0.20, "physical_crit_chance": 0.15},
    },
    "fang_alpha": {
        "id": "fang_alpha",
        "name_ru": "Клыки Альфы",
        "slot": "off_hand",
        "type": "weapon",
        "base_power": 22,
        "damage_spread": 0.1,
        "implicit_bonuses": {"physical_penetration": 0.30},
    },
    "claw_ancient": {
        "id": "claw_ancient",
        "name_ru": "Древние когти",
        "slot": "main_hand",
        "type": "weapon",
        "base_power": 35,
        "damage_spread": 0.0,
        "implicit_bonuses": {"physical_damage_bonus": 0.50},
    },
    "claw_moon_infused": {
        "id": "claw_moon_infused",
        "name_ru": "Лунные когти",
        "slot": "main_hand",
        "type": "weapon",
        "base_power": 40,
        "damage_spread": 0.1,
        "implicit_bonuses": {"magical_damage_bonus": 0.50},
    },
    "claw_void": {
        "id": "claw_void",
        "name_ru": "Когти Пустоты",
        "slot": "off_hand",
        "type": "weapon",
        "base_power": 38,
        "damage_spread": 0.1,
        "implicit_bonuses": {"physical_penetration": 1.0},
    },
    # --- ОДЕЖДА / БРОНЯ ---
    "rags_dirty": {
        "id": "rags_dirty",
        "name_ru": "Грязные лохмотья",
        "slot": "chest_garment",
        "type": "garment",
        "base_power": 0,
        "implicit_bonuses": {"environment_bio_resistance": 1.0},
    },
    "pants_torn": {
        "id": "pants_torn",
        "name_ru": "Рваные штаны",
        "slot": "legs_garment",
        "type": "garment",
        "base_power": 0,
        "implicit_bonuses": {},
    },
    "cloak_shredded": {
        "id": "cloak_shredded",
        "name_ru": "Изодранный плащ",
        "slot": "outer_garment",
        "type": "garment",
        "base_power": 0,
        "implicit_bonuses": {"stealth_bonus": 0.1},
    },
    "leather_harness": {
        "id": "leather_harness",
        "name_ru": "Кожаная перевязь",
        "slot": "chest_armor",
        "type": "armor",
        "base_power": 4,
        "implicit_bonuses": {"dodge_chance": 0.05},
    },
    "padded_wraps": {
        "id": "padded_wraps",
        "name_ru": "Мягкие обмотки",
        "slot": "feet_armor",
        "type": "armor",
        "base_power": 2,
        "implicit_bonuses": {"stealth_bonus": 0.1},
    },
    "chain_scraps": {
        "id": "chain_scraps",
        "name_ru": "Обрывки кольчуги",
        "slot": "chest_armor",
        "type": "armor",
        "base_power": 8,
        "implicit_bonuses": {"physical_resistance": 0.05},
    },
    "plate_greaves_broken": {
        "id": "plate_greaves_broken",
        "name_ru": "Сломанные поножи",
        "slot": "legs_armor",
        "type": "armor",
        "base_power": 6,
        "implicit_bonuses": {},
    },
    "war_paint_blood": {
        "id": "war_paint_blood",
        "name_ru": "Кровавая раскраска",
        "slot": "chest_garment",
        "type": "garment",
        "base_power": 0,
        "implicit_bonuses": {"intimidation": 0.2},
    },
    "robe_shredded": {
        "id": "robe_shredded",
        "name_ru": "Рваная мантия",
        "slot": "chest_armor",
        "type": "armor",
        "base_power": 2,
        "implicit_bonuses": {"magical_resistance": 0.10},
    },
    "breastplate_leather_masterwork": {
        "id": "breastplate_leather_masterwork",
        "name_ru": "Мастерская кожаная кираса",
        "slot": "chest_armor",
        "type": "armor",
        "base_power": 12,
        "implicit_bonuses": {"dodge_chance": 0.10},
    },
    "pants_noble_shredded": {
        "id": "pants_noble_shredded",
        "name_ru": "Рваные штаны аристократа",
        "slot": "legs_armor",
        "type": "armor",
        "base_power": 5,
        "implicit_bonuses": {},
    },
    "armor_ancient_hero": {
        "id": "armor_ancient_hero",
        "name_ru": "Броня древнего героя",
        "slot": "chest_armor",
        "type": "armor",
        "base_power": 20,
        "implicit_bonuses": {"physical_resistance": 0.20},
    },
    "aura_moonlight": {
        "id": "aura_moonlight",
        "name_ru": "Лунная аура",
        "slot": "chest_garment",
        "type": "garment",
        "base_power": 0,
        "implicit_bonuses": {"magical_resistance": 0.50},
    },
    # --- АКСЕССУАРЫ ---
    "tooth_necklace": {
        "id": "tooth_necklace",
        "name_ru": "Ожерелье из зубов",
        "slot": "amulet",
        "type": "accessory",
        "base_power": 0,
        "implicit_bonuses": {"strength": 2},
    },
    "moon_stone": {
        "id": "moon_stone",
        "name_ru": "Лунный камень",
        "slot": "amulet",
        "type": "accessory",
        "base_power": 0,
        "implicit_bonuses": {"men": 5},
    },
    "ring_pack_leader": {
        "id": "ring_pack_leader",
        "name_ru": "Кольцо вожака",
        "slot": "ring_1",
        "type": "accessory",
        "base_power": 0,
        "implicit_bonuses": {"charisma": 5, "leadership": 0.2},
    },
    "amulet_ancestors": {
        "id": "amulet_ancestors",
        "name_ru": "Амулет предков",
        "slot": "amulet",
        "type": "accessory",
        "base_power": 0,
        "implicit_bonuses": {"wisdom": 10},
    },
}
