from __future__ import annotations

from pydantic import AliasChoices, Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class BotSettings(BaseSettings):
    """
    Dynamic configuration for the Telegram Bot 'tg_bot'.
    Automatically generated by codex-bot CLI.
    """

    # --- 1. Base Infrastructure ---
    bot_token: str = Field(alias="BOT_TOKEN")
    secret_key: str = Field(alias="SECRET_KEY")
    debug: bool = Field(default=True, alias="DEBUG")
    telegram_channel_id: str = Field(default="", alias="TELEGRAM_CHANNEL_ID")
    domain_name: str = Field(default="localhost:8000", alias="DOMAIN_NAME")

    # Infrastructure Service Flags
    use_redis: bool = Field(default=True, alias="USE_REDIS")
    use_redis_fsm: bool = Field(default=True, alias="USE_REDIS_FSM")
    use_redis_streams: bool = Field(default=True, alias="USE_REDIS_STREAMS")

    # Redis is required for FSM and Stream Processing
    redis_url: str = Field(default="redis://localhost:6379/0", alias="REDIS_URL")

    # Redis Stream Configuration
    redis_stream_name: str = Field(
        validation_alias=AliasChoices("REDIS_STREAM_NAME", "GAME_STREAM_NAME"), default="game_events"
    )
    redis_consumer_group: str = Field(
        validation_alias=AliasChoices("REDIS_CONSUMER_GROUP", "STREAM_CONSUMER_GROUP"), default="tg_bot"
    )

    # --- 2. Bot Behavior ---
    bot_throttling_rate: float = Field(default=1.0, alias="BOT_THROTTLING_RATE")
    bot_allowed_updates: list[str] = Field(
        default=["message", "callback_query", "inline_query"], alias="BOT_ALLOWED_UPDATES"
    )

    # --- 3. Access Control ---
    superuser_ids: str = Field(default="", alias="SUPERUSER_IDS")
    owner_ids: str = Field(default="", alias="OWNER_IDS")

    # --- 4. API Mode Configuration ---
    backend_base_url: str = Field(
        validation_alias=AliasChoices("BACKEND_BASE_URL", "BACKEND_API_URL"), default="http://127.0.0.1:8001"
    )
    backend_api_key: str | None = Field(default=None, alias="BACKEND_API_KEY")
    backend_api_timeout: float = Field(default=10.0, alias="BACKEND_API_TIMEOUT")

    @property
    def superuser_ids_list(self) -> list[int]:
        """Helper to convert comma-separated string to list of integers."""
        if not self.superuser_ids:
            return []
        try:
            return [int(x.strip()) for x in self.superuser_ids.split(",") if x.strip()]
        except ValueError:
            return []

    @property
    def owner_ids_list(self) -> list[int]:
        """Helper to convert comma-separated string to list of integers."""
        if not self.owner_ids:
            return []
        try:
            return [int(x.strip()) for x in self.owner_ids.split(",") if x.strip()]
        except ValueError:
            return []

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
        populate_by_name=True,
    )
