from ..monster_structs import MonsterFamily

BANDITS_FAMILY: MonsterFamily = {
    "id": "bandit_gang",
    "archetype": "humanoid",
    "organization_type": "gang",  # TSP Base: 50
    "default_tags": ["human", "outlaw", "survivor", "marauder"],
    "hierarchy": {
        "minions": ["bandit_thug", "bandit_poacher"],
        "veterans": ["bandit_cutthroat"],
        "elites": ["bandit_captain", "bandit_hedge_wizard"],
        "boss": ["bandit_kingpin"],
    },
    "variants": {
        # === 1. Мелкая сошка (Minions) [TSP ~50] ===
        "bandit_thug": {
            "id": "bandit_thug",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 2,
            "narrative_hint": "A desperate settler turned marauder, armed with a crude axe and a wooden shield.",
            "base_stats": {
                "strength": 10,
                "agility": 8,
                "endurance": 10,
                "intelligence": 4,
                "wisdom": 3,
                "men": 5,
                "perception": 6,
                "charisma": 2,
                "luck": 5,  # Итого: 53
            },
            "fixed_loadout": {
                "main_hand": "hatchet",
                "off_hand": "buckler",
                "chest_armor": "jerkin",
                "belt_accessory": "belt",
            },
            "skills": ["dirty_blow"],
        },
        "bandit_poacher": {
            "id": "bandit_poacher",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 2,
            "narrative_hint": "A former hunter, now an outlaw. Uses a simple short bow and wears leather scraps.",
            "base_stats": {
                "strength": 8,
                "agility": 12,
                "endurance": 8,
                "intelligence": 5,
                "wisdom": 4,
                "men": 6,
                "perception": 10,
                "charisma": 2,
                "luck": 6,  # Итого: 61
            },
            "fixed_loadout": {
                "main_hand": "shortbow",
                "chest_armor": "jerkin",
                "legs_armor": "breeches",
                "belt_accessory": "belt",
            },
            "skills": ["aimed_shot"],
        },
        # === 2. Головорезы (Veterans) [TSP ~75] ===
        "bandit_cutthroat": {
            "id": "bandit_cutthroat",
            "role": "veteran",
            "cost": 50,
            "min_tier": 0,
            "max_tier": 2,
            "narrative_hint": "A quick and ruthless fighter with two daggers, likely a former city rogue.",
            "base_stats": {
                "strength": 10,
                "agility": 18,
                "endurance": 10,
                "intelligence": 6,
                "wisdom": 4,
                "men": 8,
                "perception": 10,
                "charisma": 3,
                "luck": 10,  # Итого: 79
            },
            "fixed_loadout": {
                "main_hand": "dagger",
                "off_hand": "dagger",
                "chest_armor": "jerkin",
                "gloves_garment": "work_gloves",
                "belt_accessory": "belt",
            },
            "skills": ["poison_stab", "evasion"],
        },
        # === 3. Элита (Elites) [TSP ~125] ===
        "bandit_captain": {
            "id": "bandit_captain",
            "role": "elite",
            "cost": 150,
            "min_tier": 1,
            "max_tier": 2,
            "narrative_hint": "The leader of this small gang, a hardened survivor with a stolen longsword and chainmail.",
            "base_stats": {
                "strength": 20,
                "agility": 14,
                "endurance": 20,
                "intelligence": 8,
                "wisdom": 6,
                "men": 12,
                "perception": 10,
                "charisma": 12,
                "luck": 6,  # Итого: 108
            },
            "fixed_loadout": {
                "main_hand": "sword",
                "off_hand": "shield",
                "chest_armor": "plate_chest",
                "head_armor": "helmet",
                "amulet": "amulet",
                "belt_accessory": "belt",
            },
            "skills": ["shield_bash", "rally_cry"],
        },
        "bandit_hedge_wizard": {
            "id": "bandit_hedge_wizard",
            "role": "elite",
            "cost": 150,
            "min_tier": 1,
            "max_tier": 2,
            "narrative_hint": "An outcast who dabbles in forbidden magic, using a crude staff to cast chaotic spells.",
            "base_stats": {
                "strength": 6,
                "agility": 10,
                "endurance": 10,
                "intelligence": 20,
                "wisdom": 14,
                "men": 20,
                "perception": 10,
                "charisma": 6,
                "luck": 4,  # Итого: 100
            },
            "fixed_loadout": {
                "main_hand": "quarterstaff",
                "chest_armor": "robe",
                "head_armor": "hood",
                "ring_1": "ring",
                "belt_accessory": "belt",
            },
            "skills": ["lightning_bolt", "confusion", "smoke_bomb"],
        },
        # === 4. Босс (Bosses) [TSP ~200] ===
        "bandit_kingpin": {
            "id": "bandit_kingpin",
            "role": "boss",
            "cost": 600,
            "min_tier": 2,
            "max_tier": 2,
            "narrative_hint": "The ruthless leader of all local marauders. Wields a heavy two-handed axe and is surprisingly quick.",
            "base_stats": {
                "strength": 30,
                "agility": 20,
                "endurance": 30,
                "intelligence": 14,
                "wisdom": 10,
                "men": 15,
                "perception": 15,
                "charisma": 20,
                "luck": 15,  # Итого: 169
            },
            "fixed_loadout": {
                "main_hand": "warhammer",
                "chest_armor": "plate_chest",
                "head_armor": "helmet",
                "arms_armor": "gauntlets",
                "legs_armor": "greaves",
                "feet_armor": "sabatons",
                "outer_garment": "winter_cloak",
                "gloves_garment": "work_gloves",
                "amulet": "amulet",
                "ring_1": "ring",
                "ring_2": "ring",
                "belt_accessory": "belt",
            },
            "skills": ["dirty_trick_blind", "call_reinforcements", "cleave"],
        },
    },
}
