"""
СЕМЕЙСТВО: ДЕМОНЫ (Хаос, огонь, страх)
======================================
Логика: хаос -> огонь -> страх
"""

from ..monster_structs import MonsterFamily

DEMONS_FAMILY: MonsterFamily = {
    "id": "demon_legion",
    "archetype": "humanoid",
    "organization_type": "legion",  # TSP Base: 70
    "default_tags": ["demon", "chaos", "fire", "evil"],
    "hierarchy": {
        "minions": ["imp", "flame_servant", "lesser_fiend", "chaos_spawn"],
        "veterans": ["hellhound", "fire_imp", "shadow_fiend", "abyss_warrior"],
        "elites": ["demon_knight", "flame_lord", "abyss_warlord", "infernal_champion"],
        "boss": ["archdemon", "infernal_overlord", "doom_bringer", "hell_tyrant"],
    },
    "variants": {
        # --- 1. Мелкие (Minions) [TSP ~70] ---
        "imp": {
            "id": "imp",
            "role": "minion",
            "cost": 20,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A small, red-skinned demon with bat wings. Giggles maliciously.",
            "extra_tags": ["imp", "flying", "ranged"],
            "base_stats": {
                "strength": 6,
                "agility": 16,
                "endurance": 6,
                "intelligence": 10,
                "wisdom": 6,
                "men": 10,
                "perception": 10,
                "charisma": 2,
                "luck": 10,  # Итого: 76
            },
            "fixed_loadout": {},
            "skills": ["attack_ranged", "attack_basic", "debuff_weaken"],
        },
        "flame_servant": {
            "id": "flame_servant",
            "role": "minion",
            "cost": 20,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A humanoid shape made of flickering flames. Obeys without question.",
            "extra_tags": ["elemental", "fire"],
            "base_stats": {
                "strength": 10,
                "agility": 10,
                "endurance": 10,
                "intelligence": 8,
                "wisdom": 8,
                "men": 15,
                "perception": 8,
                "charisma": 1,
                "luck": 5,  # Итого: 75
            },
            "fixed_loadout": {},
            "skills": ["debuff_burn", "debuff_burn"],
        },
        "lesser_fiend": {
            "id": "lesser_fiend",
            "role": "minion",
            "cost": 20,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A twisted, hunched demon with sharp claws. Smells of sulfur.",
            "extra_tags": ["fiend", "melee"],
            "base_stats": {
                "strength": 14,
                "agility": 12,
                "endurance": 12,
                "intelligence": 4,
                "wisdom": 4,
                "men": 10,
                "perception": 10,
                "charisma": 1,
                "luck": 5,  # Итого: 72
            },
            "fixed_loadout": {},
            "skills": ["debuff_bleed", "attack_basic"],
        },
        "chaos_spawn": {
            "id": "chaos_spawn",
            "role": "minion",
            "cost": 20,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A shifting mass of flesh and teeth. Constantly mutating.",
            "extra_tags": ["chaos", "mutation"],
            "base_stats": {
                "strength": 12,
                "agility": 8,
                "endurance": 14,
                "intelligence": 2,
                "wisdom": 2,
                "men": 15,
                "perception": 6,
                "charisma": 1,
                "luck": 20,  # Итого: 80 (хаос)
            },
            "fixed_loadout": {},
            "skills": ["special_unique", "attack_basic"],
        },
        # --- 2. Охотники / Бойцы (Veterans) [TSP ~105] ---
        "hellhound": {
            "id": "hellhound",
            "role": "veteran",
            "cost": 50,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A massive black dog with burning eyes and fire in its maw.",
            "extra_tags": ["beast", "fire"],
            "base_stats": {
                "strength": 20,
                "agility": 18,
                "endurance": 18,
                "intelligence": 6,
                "wisdom": 6,
                "men": 12,
                "perception": 14,
                "charisma": 2,
                "luck": 5,  # Итого: 101
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "attack_basic", "debuff_weaken"],
        },
        "fire_imp": {
            "id": "fire_imp",
            "role": "veteran",
            "cost": 50,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A larger imp, wreathed in intense flames. Throws fireballs.",
            "extra_tags": ["imp", "fire", "ranged"],
            "base_stats": {
                "strength": 8,
                "agility": 18,
                "endurance": 10,
                "intelligence": 16,
                "wisdom": 12,
                "men": 15,
                "perception": 12,
                "charisma": 4,
                "luck": 10,  # Итого: 105
            },
            "fixed_loadout": {},
            "skills": ["attack_ranged", "buff_reflect"],
        },
        "shadow_fiend": {
            "id": "shadow_fiend",
            "role": "veteran",
            "cost": 50,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A demon made of solidified darkness. Hard to see, hard to hit.",
            "extra_tags": ["shadow", "stealth"],
            "base_stats": {
                "strength": 14,
                "agility": 22,
                "endurance": 12,
                "intelligence": 10,
                "wisdom": 8,
                "men": 15,
                "perception": 14,
                "charisma": 2,
                "luck": 8,  # Итого: 105
            },
            "fixed_loadout": {},
            "skills": ["attack_heavy", "debuff_weaken", "debuff_blind"],
        },
        "abyss_warrior": {
            "id": "abyss_warrior",
            "role": "veteran",
            "cost": 50,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A demon in jagged black armor, wielding a cruel blade.",
            "extra_tags": ["warrior", "abyss"],
            "base_stats": {
                "strength": 20,
                "agility": 14,
                "endurance": 20,
                "intelligence": 8,
                "wisdom": 8,
                "men": 15,
                "perception": 10,
                "charisma": 5,
                "luck": 5,  # Итого: 105
            },
            "fixed_loadout": {"main_hand": "sword", "chest_armor": "plate_chest"},
            "skills": ["attack_aoe", "attack_heavy"],
        },
        # --- 3. Элита (Elites) [TSP ~175] ---
        "demon_knight": {
            "id": "demon_knight",
            "role": "elite",
            "cost": 150,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A towering demon in hell-forged plate armor. Commands lesser demons.",
            "extra_tags": ["knight", "heavy_armor"],
            "base_stats": {
                "strength": 30,
                "agility": 12,
                "endurance": 30,
                "intelligence": 12,
                "wisdom": 12,
                "men": 20,
                "perception": 12,
                "charisma": 10,
                "luck": 5,  # Итого: 143 (но броня)
            },
            "fixed_loadout": {"main_hand": "greatsword", "chest_armor": "plate_chest", "head_armor": "helmet"},
            "skills": ["attack_heavy", "buff_rage", "debuff_weaken"],
        },
        "flame_lord": {
            "id": "flame_lord",
            "role": "elite",
            "cost": 150,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A demon whose body is a furnace. Wields a whip of fire.",
            "extra_tags": ["lord", "fire", "elemental"],
            "base_stats": {
                "strength": 20,
                "agility": 18,
                "endurance": 20,
                "intelligence": 20,
                "wisdom": 16,
                "men": 25,
                "perception": 14,
                "charisma": 12,
                "luck": 8,  # Итого: 153
            },
            "fixed_loadout": {"main_hand": "whip"},
            "skills": ["attack_fast", "attack_aoe", "summon_minion"],
        },
        "abyss_warlord": {
            "id": "abyss_warlord",
            "role": "elite",
            "cost": 150,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A massive, four-armed demon. A master of combats.",
            "extra_tags": ["warlord", "abyss", "dual_wield"],
            "base_stats": {
                "strength": 35,
                "agility": 18,
                "endurance": 30,
                "intelligence": 14,
                "wisdom": 12,
                "men": 20,
                "perception": 14,
                "charisma": 15,
                "luck": 5,  # Итого: 163
            },
            "fixed_loadout": {"main_hand": "axe", "off_hand": "sword"},
            "skills": ["attack_aoe", "buff_rage", "attack_execute"],
        },
        "infernal_champion": {
            "id": "infernal_champion",
            "role": "elite",
            "cost": 150,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "The champion of the pit. Undefeated in a thousand battles.",
            "extra_tags": ["champion", "infernal"],
            "base_stats": {
                "strength": 40,
                "agility": 14,
                "endurance": 35,
                "intelligence": 10,
                "wisdom": 10,
                "men": 25,
                "perception": 12,
                "charisma": 10,
                "luck": 10,  # Итого: 166
            },
            "fixed_loadout": {"main_hand": "warhammer", "chest_armor": "plate_chest"},
            "skills": ["attack_aoe", "debuff_weaken", "buff_defense"],
        },
        # --- 4. Древние / Боссы (Bosses) [TSP ~280] ---
        "archdemon": {
            "id": "archdemon",
            "role": "boss",
            "cost": 600,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "A demon of immense power, with giant wings and horns. Radiates terror.",
            "extra_tags": ["archdemon", "leader", "flying"],
            "base_stats": {
                "strength": 40,
                "agility": 25,
                "endurance": 50,
                "intelligence": 30,
                "wisdom": 30,
                "men": 50,
                "perception": 20,
                "charisma": 25,
                "luck": 15,  # Итого: 285
            },
            "fixed_loadout": {"main_hand": "greatsword"},
            "skills": ["attack_aoe", "attack_execute", "summon_minion"],
        },
        "infernal_overlord": {
            "id": "infernal_overlord",
            "role": "boss",
            "cost": 600,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "The ruler of a layer of hell. Sits on a throne of skulls.",
            "extra_tags": ["overlord", "ruler"],
            "base_stats": {
                "strength": 50,
                "agility": 15,
                "endurance": 60,
                "intelligence": 40,
                "wisdom": 40,
                "men": 60,
                "perception": 25,
                "charisma": 30,
                "luck": 20,  # Итого: 340
            },
            "fixed_loadout": {"main_hand": "scepter"},
            "skills": ["debuff_weaken", "attack_aoe", "buff_rage"],
        },
        "doom_bringer": {
            "id": "doom_bringer",
            "role": "boss",
            "cost": 600,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "A colossal demon beast, heralded by earthquakes and fire.",
            "extra_tags": ["colossal", "beast", "world_ender"],
            "base_stats": {
                "strength": 70,
                "agility": 10,
                "endurance": 80,
                "intelligence": 15,
                "wisdom": 15,
                "men": 40,
                "perception": 15,
                "charisma": 10,
                "luck": 5,  # Итого: 260 (чистая мощь)
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "attack_aoe", "attack_execute"],
        },
        "hell_tyrant": {
            "id": "hell_tyrant",
            "role": "boss",
            "cost": 600,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "The ultimate evil. A being of pure malice and destruction.",
            "extra_tags": ["tyrant", "godlike"],
            "base_stats": {
                "strength": 60,
                "agility": 30,
                "endurance": 70,
                "intelligence": 50,
                "wisdom": 50,
                "men": 80,
                "perception": 30,
                "charisma": 40,
                "luck": 25,  # Итого: 435
            },
            "fixed_loadout": {"main_hand": "sword_of_damnation"},
            "skills": ["special_unique", "attack_execute", "special_unique", "attack_aoe"],
        },
    },
}
