GIFT_FIRE_PHRASES = {
    "gift_cast": {
        "gift.fire.true_fire.cast.open": {
            "kind": "gift_cast",
            "text": "{gift} вспыхивает в руках {source}",
            "variables": ["gift", "source"],
            "tags": ["gift", "fire", "cast"],
        },
        "gift.fire.true_fire.cast.area": {
            "kind": "gift_cast",
            "text": "{source} раскрывает жар дара {gift}",
            "variables": ["source", "gift"],
            "tags": ["gift", "fire", "cast", "area"],
        },
    },
    "gift_target_result": {
        "gift.fire.true_fire.target.hit": {
            "kind": "gift_target_result",
            "text": "{target} получает {damage} огненного урона",
            "variables": ["target", "damage"],
            "tags": ["gift", "fire", "hit"],
        },
        "gift.fire.true_fire.target.apply_burn": {
            "kind": "gift_target_result",
            "text": "на {target} закрепляется {effect}",
            "variables": ["target", "effect"],
            "tags": ["gift", "fire", "effect"],
        },
        "gift.fire.true_fire.target.resist": {
            "kind": "gift_target_result",
            "text": "{target} сопротивляется жару {gift}",
            "variables": ["target", "gift"],
            "tags": ["gift", "fire", "resist"],
        },
    },
    "gift_resource": {
        "gift.fire.true_fire.resource.no_resource": {
            "kind": "gift_resource",
            "text": "дар {gift} гаснет в руках {source}: не хватает {resource}",
            "variables": ["gift", "source", "resource"],
            "tags": ["gift", "fire", "no_resource"],
        },
    },
}

FIRE_GIFT_TEMPLATE_EXAMPLES = (
    {
        "template_key": "combat.gift.gift_true_fire.cast.single",
        "resource_type": "gift",
        "resource_id": "gift_true_fire",
        "catalog_key": "combat.gift.gift_true_fire",
        "outcome": "cast",
        "delivery": "single",
        "pattern": "{cast}: {target_results}.",
        "phrase_keys": {"cast": "gift.fire.true_fire.cast.open"},
        "slots": {"target_results": "list"},
        "joiners": {"target_results": ", "},
        "tags": ["gift", "fire", "cast", "single"],
    },
    {
        "template_key": "combat.gift.gift_true_fire.cast.area",
        "resource_type": "gift",
        "resource_id": "gift_true_fire",
        "catalog_key": "combat.gift.gift_true_fire",
        "outcome": "area_result",
        "delivery": "area",
        "pattern": "{cast}: {target_results}.",
        "phrase_keys": {"cast": "gift.fire.true_fire.cast.area"},
        "slots": {"target_results": "list"},
        "joiners": {"target_results": ", "},
        "tags": ["gift", "fire", "cast", "area"],
    },
    {
        "template_key": "combat.gift.gift_true_fire.no_resource",
        "resource_type": "gift",
        "resource_id": "gift_true_fire",
        "catalog_key": "combat.gift.gift_true_fire",
        "outcome": "no_resource",
        "pattern": "{resource_result}.",
        "phrase_keys": {"resource_result": "gift.fire.true_fire.resource.no_resource"},
        "tags": ["gift", "fire", "no_resource"],
    },
    {
        "template_key": "combat.gift.gift_true_fire.target.hit.humanoid",
        "resource_type": "gift",
        "resource_id": "gift_true_fire",
        "catalog_key": "combat.gift.gift_true_fire",
        "outcome": "hit",
        "target_body": "humanoid",
        "pattern": "{target_result}",
        "phrase_keys": {"target_result": "gift.fire.true_fire.target.hit"},
        "tags": ["gift", "fire", "target", "hit", "humanoid"],
    },
    {
        "template_key": "combat.gift.gift_true_fire.target.apply.humanoid",
        "resource_type": "gift",
        "resource_id": "gift_true_fire",
        "catalog_key": "combat.gift.gift_true_fire",
        "outcome": "apply",
        "target_body": "humanoid",
        "pattern": "{target_result}",
        "phrase_keys": {"target_result": "gift.fire.true_fire.target.apply_burn"},
        "tags": ["gift", "fire", "target", "apply", "humanoid"],
    },
    {
        "template_key": "combat.gift.gift_true_fire.target.resist.humanoid",
        "resource_type": "gift",
        "resource_id": "gift_true_fire",
        "catalog_key": "combat.gift.gift_true_fire",
        "outcome": "resist",
        "target_body": "humanoid",
        "pattern": "{target_result}",
        "phrase_keys": {"target_result": "gift.fire.true_fire.target.resist"},
        "tags": ["gift", "fire", "target", "resist", "humanoid"],
    },
)
