GARMENT_DB = {
    "basic": {
        "apron": {
            "id": "apron",
            "name_ru": "Фартук",
            "slot": "chest_garment",
            "type": "garment",
            "allowed_materials": ["cloths", "leathers"],
            "base_power": 0,
            "base_durability": 25,
            "damage_spread": 0.0,
            "narrative_description": "Рабочий фартук с карманами для мелких инструментов и расходников.",
            "narrative_tags": ["apron", "garment", "workwear", "tools"],
            "implicit_bonuses": {},
        },
        "linen_shirt": {
            "id": "linen_shirt",
            "name_ru": "Льняная рубаха",
            "slot": "chest_garment",
            "type": "garment",
            "allowed_materials": ["cloths"],
            "base_power": 0,
            "base_durability": 20,
            "damage_spread": 0.0,
            "narrative_description": "Легкая рубаха пропускает воздух и защищает кожу от жары и пыли.",
            "narrative_tags": ["shirt", "garment", "light", "breathable"],
            "implicit_bonuses": {"environment_heat_resistance": 3.0},
        },
        "wool_tunic": {
            "id": "wool_tunic",
            "name_ru": "Шерстяная туника",
            "slot": "chest_garment",
            "type": "garment",
            "allowed_materials": ["cloths", "leathers"],
            "base_power": 1,
            "base_durability": 30,
            "damage_spread": 0.0,
            "narrative_description": "Плотная туника удерживает тепло и смягчает холодный ветер.",
            "narrative_tags": ["tunic", "garment", "warm"],
            "implicit_bonuses": {"environment_cold_resistance": 4.0},
        },
        "fur_pants": {
            "id": "fur_pants",
            "name_ru": "Меховые штаны",
            "slot": "legs_garment",
            "type": "garment",
            "allowed_materials": ["leathers"],
            "base_power": 1,
            "base_durability": 30,
            "damage_spread": 0.0,
            "narrative_description": "Меховые штаны защищают ноги от холода и долгого сидения на камне.",
            "narrative_tags": ["pants", "garment", "fur", "warm"],
            "implicit_bonuses": {"environment_cold_resistance": 4.0},
        },
        "work_gloves": {
            "id": "work_gloves",
            "name_ru": "Рабочие перчатки",
            "slot": "gloves_garment",
            "type": "garment",
            "allowed_materials": ["cloths", "leathers"],
            "base_power": 0,
            "base_durability": 25,
            "damage_spread": 0.0,
            "narrative_description": "Плотные перчатки для грубой работы, хватов и защиты ладоней.",
            "narrative_tags": ["gloves", "garment", "workwear", "grip"],
            "implicit_bonuses": {},
        },
        "winter_cloak": {
            "id": "winter_cloak",
            "name_ru": "Зимний плащ",
            "slot": "outer_garment",
            "type": "garment",
            "allowed_materials": ["cloths", "leathers"],
            "base_power": 0,
            "base_durability": 45,
            "damage_spread": 0.0,
            "narrative_description": "Тяжелый плащ от ветра и холода, который можно накинуть поверх брони.",
            "narrative_tags": ["cloak", "garment", "winter", "outerwear"],
            "implicit_bonuses": {"environment_cold_resistance": 6.0, "environment_heat_resistance": -2.0},
        },
    }
}

__all__ = ["GARMENT_DB"]
