"""
СЕМЕЙСТВО: МУРАВЬИ / РОЙ (Рой, численность, контроль)
=====================================================
Логика: рой -> численность -> контроль пространства
"""

from ..monster_structs import MonsterFamily

ANTS_FAMILY: MonsterFamily = {
    "id": "ant_colony",
    "archetype": "beast",
    "organization_type": "swarm",  # TSP Base: 30
    "default_tags": ["beast", "insect", "ant", "swarm"],
    "hierarchy": {
        "minions": ["tunnel_ant", "cave_beetle", "swarm_larva", "scuttler"],
        "veterans": ["venom_ant", "cave_spiderling", "stinger_beetle", "shadow_mite"],
        "elites": ["hive_guard", "web_spinner", "venom_queens_guard", "stalker_beetle"],
        "boss": ["hive_queen", "broodmother_spider", "ancient_beetle", "swarm_lord"],
    },
    "variants": {
        # --- 1. Мелкие (Minions) [TSP ~30] ---
        "tunnel_ant": {
            "id": "tunnel_ant",
            "role": "minion",
            "cost": 20,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A large ant with powerful mandibles for digging. Moves in a line.",
            "extra_tags": ["worker", "digger"],
            "base_stats": {
                "strength": 8,
                "agility": 6,
                "endurance": 8,
                "intelligence": 1,
                "wisdom": 1,
                "men": 2,
                "perception": 4,
                "charisma": 1,
                "luck": 2,  # Итого: 33
            },
            "fixed_loadout": {},
            "skills": ["attack_basic"],
        },
        "cave_beetle": {
            "id": "cave_beetle",
            "role": "minion",
            "cost": 20,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A hard-shelled beetle that scuttles across the floor.",
            "extra_tags": ["beetle", "armored"],
            "base_stats": {
                "strength": 4,
                "agility": 4,
                "endurance": 12,
                "intelligence": 1,
                "wisdom": 1,
                "men": 2,
                "perception": 2,
                "charisma": 1,
                "luck": 2,  # Итого: 29
            },
            "fixed_loadout": {},
            "skills": ["buff_defense", "attack_heavy"],
        },
        "swarm_larva": {
            "id": "swarm_larva",
            "role": "minion",
            "cost": 20,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A soft, wriggling larva. Explodes into acid when killed.",
            "extra_tags": ["larva", "explosive"],
            "base_stats": {
                "strength": 2,
                "agility": 2,
                "endurance": 4,
                "intelligence": 1,
                "wisdom": 1,
                "men": 1,
                "perception": 1,
                "charisma": 1,
                "luck": 10,  # Итого: 23 (но взрывается)
            },
            "fixed_loadout": {},
            "skills": ["debuff_armor_break"],
        },
        "scuttler": {
            "id": "scuttler",
            "role": "minion",
            "cost": 20,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A fast, multi-legged insect that distracts enemies.",
            "extra_tags": ["fast", "distraction"],
            "base_stats": {
                "strength": 2,
                "agility": 14,
                "endurance": 4,
                "intelligence": 1,
                "wisdom": 1,
                "men": 2,
                "perception": 6,
                "charisma": 1,
                "luck": 4,  # Итого: 35
            },
            "fixed_loadout": {},
            "skills": ["debuff_weaken"],
        },
        # --- 2. Охотники / Бойцы (Veterans) [TSP ~45] ---
        "venom_ant": {
            "id": "venom_ant",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "An ant with a glowing green abdomen. Spits acid.",
            "extra_tags": ["venom", "acid", "ranged"],
            "base_stats": {
                "strength": 6,
                "agility": 10,
                "endurance": 8,
                "intelligence": 2,
                "wisdom": 2,
                "men": 4,
                "perception": 8,
                "charisma": 1,
                "luck": 3,  # Итого: 44
            },
            "fixed_loadout": {},
            "skills": ["debuff_armor_break", "debuff_poison"],
        },
        "cave_spiderling": {
            "id": "cave_spiderling",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A small spider living symbiotically with the ants.",
            "extra_tags": ["spider", "web"],
            "base_stats": {
                "strength": 6,
                "agility": 12,
                "endurance": 6,
                "intelligence": 2,
                "wisdom": 2,
                "men": 4,
                "perception": 8,
                "charisma": 1,
                "luck": 3,  # Итого: 44
            },
            "fixed_loadout": {},
            "skills": ["debuff_slow", "attack_basic"],
        },
        "stinger_beetle": {
            "id": "stinger_beetle",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A beetle with a sharp stinger on its tail.",
            "extra_tags": ["beetle", "piercing"],
            "base_stats": {
                "strength": 10,
                "agility": 8,
                "endurance": 12,
                "intelligence": 1,
                "wisdom": 1,
                "men": 4,
                "perception": 4,
                "charisma": 1,
                "luck": 3,  # Итого: 44
            },
            "fixed_loadout": {},
            "skills": ["attack_pierce", "attack_pierce"],
        },
        "shadow_mite": {
            "id": "shadow_mite",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A tiny, dark insect that drains energy.",
            "extra_tags": ["mite", "shadow", "lifesteal"],
            "base_stats": {
                "strength": 2,
                "agility": 16,
                "endurance": 4,
                "intelligence": 2,
                "wisdom": 2,
                "men": 4,
                "perception": 10,
                "charisma": 1,
                "luck": 4,  # Итого: 45
            },
            "fixed_loadout": {},
            "skills": ["attack_lifesteal", "stealth"],
        },
        # --- 3. Элита (Elites) [TSP ~75] ---
        "hive_guard": {
            "id": "hive_guard",
            "role": "elite",
            "cost": 150,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A massive ant soldier with reinforced chitin armor.",
            "extra_tags": ["guardian", "heavy_armor"],
            "base_stats": {
                "strength": 20,
                "agility": 6,
                "endurance": 25,
                "intelligence": 3,
                "wisdom": 3,
                "men": 8,
                "perception": 6,
                "charisma": 2,
                "luck": 4,  # Итого: 77
            },
            "fixed_loadout": {},
            "skills": ["buff_defense", "attack_heavy", "buff_defense"],
        },
        "web_spinner": {
            "id": "web_spinner",
            "role": "elite",
            "cost": 150,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A large spider that weaves complex webs to trap intruders.",
            "extra_tags": ["spider", "trapper"],
            "base_stats": {
                "strength": 12,
                "agility": 16,
                "endurance": 14,
                "intelligence": 6,
                "wisdom": 6,
                "men": 8,
                "perception": 12,
                "charisma": 2,
                "luck": 4,  # Итого: 80
            },
            "fixed_loadout": {},
            "skills": ["debuff_slow", "debuff_stun", "special_trap"],
        },
        "venom_queens_guard": {
            "id": "venom_queens_guard",
            "role": "elite",
            "cost": 150,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "An elite ant warrior with deadly venom.",
            "extra_tags": ["elite_guard", "venom"],
            "base_stats": {
                "strength": 16,
                "agility": 14,
                "endurance": 16,
                "intelligence": 4,
                "wisdom": 4,
                "men": 8,
                "perception": 10,
                "charisma": 3,
                "luck": 4,  # Итого: 79
            },
            "fixed_loadout": {},
            "skills": ["debuff_poison", "buff_rage", "buff_defense"],
        },
        "stalker_beetle": {
            "id": "stalker_beetle",
            "role": "elite",
            "cost": 150,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A predatory beetle that hunts in the dark.",
            "extra_tags": ["beetle", "predator", "stealth"],
            "base_stats": {
                "strength": 14,
                "agility": 16,
                "endurance": 14,
                "intelligence": 4,
                "wisdom": 4,
                "men": 6,
                "perception": 14,
                "charisma": 1,
                "luck": 6,  # Итого: 79
            },
            "fixed_loadout": {},
            "skills": ["attack_heavy", "debuff_bleed", "buff_evasion"],
        },
        # --- 4. Короли / Боссы (Bosses) [TSP ~120] ---
        "hive_queen": {
            "id": "hive_queen",
            "role": "boss",
            "cost": 600,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "The bloated, immobile mother of the colony. Commands the swarm.",
            "extra_tags": ["queen", "leader", "summoner"],
            "base_stats": {
                "strength": 20,
                "agility": 2,
                "endurance": 40,
                "intelligence": 15,
                "wisdom": 15,
                "men": 20,
                "perception": 15,
                "charisma": 15,
                "luck": 10,  # Итого: 152
            },
            "fixed_loadout": {},
            "skills": ["summon_minion", "buff_rage", "debuff_armor_break", "debuff_stun"],
        },
        "broodmother_spider": {
            "id": "broodmother_spider",
            "role": "boss",
            "cost": 600,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A colossal spider, mother of thousands.",
            "extra_tags": ["spider", "broodmother"],
            "base_stats": {
                "strength": 30,
                "agility": 12,
                "endurance": 35,
                "intelligence": 10,
                "wisdom": 10,
                "men": 15,
                "perception": 15,
                "charisma": 8,
                "luck": 8,  # Итого: 143
            },
            "fixed_loadout": {},
            "skills": ["debuff_slow", "attack_execute", "debuff_poison", "summon_minion"],
        },
        "ancient_beetle": {
            "id": "ancient_beetle",
            "role": "boss",
            "cost": 600,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A beetle as large as a tank, with armor that deflects steel.",
            "extra_tags": ["beetle", "ancient", "heavy_armor"],
            "base_stats": {
                "strength": 40,
                "agility": 5,
                "endurance": 60,
                "intelligence": 6,
                "wisdom": 6,
                "men": 15,
                "perception": 8,
                "charisma": 5,
                "luck": 5,  # Итого: 150
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "buff_defense", "attack_aoe"],
        },
        "swarm_lord": {
            "id": "swarm_lord",
            "role": "boss",
            "cost": 600,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A humanoid figure composed entirely of insects. The hive mind manifest.",
            "extra_tags": ["lord", "hive_mind"],
            "base_stats": {
                "strength": 25,
                "agility": 25,
                "endurance": 30,
                "intelligence": 20,
                "wisdom": 20,
                "men": 30,
                "perception": 25,
                "charisma": 20,
                "luck": 10,  # Итого: 205
            },
            "fixed_loadout": {},
            "skills": ["buff_evasion", "attack_aoe", "attack_lifesteal", "summon_minion"],
        },
    },
}
