"""
СЕМЕЙСТВО: ЯЩЕРЫ (Среда, хладнокровие, тактика)
================================================
Логика: среда -> тактика -> кровотечение
"""

from ..monster_structs import MonsterFamily

LIZARDFOLK_FAMILY: MonsterFamily = {
    "id": "lizardfolk_clan",
    "archetype": "humanoid",
    "organization_type": "clan",  # TSP Base: 70
    "default_tags": ["lizardfolk", "reptile", "aquatic", "savage"],
    "hierarchy": {
        "minions": ["skink_scout", "bog_trotter", "hatchling_warrior"],
        "veterans": ["saurian_warrior", "scale_hunter", "swamp_shaman"],
        "elites": ["temple_guard", "kroxigor_brute", "venom_spitter"],
        "boss": ["slann_mage", "tyrant_king", "hydra_incarnate"],
    },
    "variants": {
        # --- 1. Мелкая чешуя (Minions) [TSP ~70] ---
        "skink_scout": {
            "id": "skink_scout",
            "role": "minion",
            "cost": 20,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A small, fast lizardman with a blowgun. Moves quickly through water.",
            "extra_tags": ["skink", "scout", "fast"],
            "base_stats": {
                "strength": 8,
                "agility": 20,
                "endurance": 10,
                "intelligence": 6,
                "wisdom": 4,
                "men": 6,
                "perception": 14,
                "charisma": 2,
                "luck": 5,  # Итого: 75
            },
            "fixed_loadout": {"main_hand": "blowgun"},
            "skills": ["attack_ranged", "debuff_poison"],
        },
        "bog_trotter": {
            "id": "bog_trotter",
            "role": "minion",
            "cost": 20,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A shared lizardman with a crude spear. At home in the swamp.",
            "extra_tags": ["swamp", "infantry"],
            "base_stats": {
                "strength": 14,
                "agility": 12,
                "endurance": 14,
                "intelligence": 4,
                "wisdom": 4,
                "men": 8,
                "perception": 10,
                "charisma": 2,
                "luck": 4,  # Итого: 72
            },
            "fixed_loadout": {"main_hand": "spear", "off_hand": "buckler"},
            "skills": ["attack_basic", "attack_pierce"],
        },
        "hatchling_warrior": {
            "id": "hatchling_warrior",
            "role": "minion",
            "cost": 20,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A young, aggressive lizardman with a club. Fights recklessly.",
            "extra_tags": ["young", "reckless"],
            "base_stats": {
                "strength": 16,
                "agility": 10,
                "endurance": 12,
                "intelligence": 2,
                "wisdom": 2,
                "men": 10,
                "perception": 8,
                "charisma": 2,
                "luck": 4,  # Итого: 66
            },
            "fixed_loadout": {"main_hand": "club"},
            "skills": ["attack_heavy", "buff_rage"],
        },
        # --- 2. Опытные бойцы (Veterans) [TSP ~105] ---
        "saurian_warrior": {
            "id": "saurian_warrior",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 6,
            "narrative_hint": "A disciplined warrior with a sharp obsidian sword and a shield.",
            "extra_tags": ["warrior", "shield"],
            "base_stats": {
                "strength": 20,
                "agility": 14,
                "endurance": 20,
                "intelligence": 6,
                "wisdom": 6,
                "men": 12,
                "perception": 12,
                "charisma": 4,
                "luck": 5,  # Итого: 99
            },
            "fixed_loadout": {"main_hand": "sword", "off_hand": "shield"},
            "skills": ["attack_heavy", "buff_defense"],
        },
        "scale_hunter": {
            "id": "scale_hunter",
            "role": "veteran",
            "cost": 50,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A lizardman with a powerful bow, skilled in hunting large beasts.",
            "extra_tags": ["hunter", "ranged"],
            "base_stats": {
                "strength": 16,
                "agility": 20,
                "endurance": 16,
                "intelligence": 8,
                "wisdom": 8,
                "men": 10,
                "perception": 18,
                "charisma": 3,
                "luck": 6,  # Итого: 105
            },
            "fixed_loadout": {"main_hand": "bow"},
            "skills": ["attack_ranged", "attack_pierce"],
        },
        "swamp_shaman": {
            "id": "swamp_shaman",
            "role": "veteran",
            "cost": 50,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A lizardman adorned with bones and feathers, chanting swamp magic.",
            "extra_tags": ["shaman", "magic"],
            "base_stats": {
                "strength": 8,
                "agility": 10,
                "endurance": 12,
                "intelligence": 18,
                "wisdom": 18,
                "men": 16,
                "perception": 14,
                "charisma": 6,
                "luck": 5,  # Итого: 107
            },
            "fixed_loadout": {"main_hand": "staff"},
            "skills": ["debuff_slow", "buff_heal", "attack_ranged"],
        },
        # --- 3. Элита (Elites) [TSP ~175] ---
        "temple_guard": {
            "id": "temple_guard",
            "role": "elite",
            "cost": 150,
            "min_tier": 3,
            "max_tier": 7,
            "narrative_hint": "A large lizardman in ornate armor, guarding a sacred site.",
            "extra_tags": ["guardian", "heavy_armor"],
            "base_stats": {
                "strength": 30,
                "agility": 12,
                "endurance": 35,
                "intelligence": 8,
                "wisdom": 10,
                "men": 20,
                "perception": 14,
                "charisma": 6,
                "luck": 5,  # Итого: 140 (но броня)
            },
            "fixed_loadout": {"main_hand": "halberd", "chest_armor": "plate_chest"},
            "skills": ["buff_defense", "attack_aoe", "debuff_stun"],
        },
        "kroxigor_brute": {
            "id": "kroxigor_brute",
            "role": "elite",
            "cost": 150,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A massive, crocodile-like lizardman of immense strength.",
            "extra_tags": ["brute", "kroxigor"],
            "base_stats": {
                "strength": 50,
                "agility": 8,
                "endurance": 50,
                "intelligence": 4,
                "wisdom": 4,
                "men": 15,
                "perception": 10,
                "charisma": 2,
                "luck": 5,  # Итого: 148 (чистая сила)
            },
            "fixed_loadout": {"main_hand": "warhammer"},
            "skills": ["attack_heavy", "attack_heavy", "debuff_armor_break"],
        },
        "venom_spitter": {
            "id": "venom_spitter",
            "role": "elite",
            "cost": 150,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A specialized lizardman with a throat pouch for spitting potent venom.",
            "extra_tags": ["venom", "ranged"],
            "base_stats": {
                "strength": 16,
                "agility": 25,
                "endurance": 20,
                "intelligence": 8,
                "wisdom": 8,
                "men": 15,
                "perception": 20,
                "charisma": 4,
                "luck": 5,  # Итого: 121 (яд)
            },
            "fixed_loadout": {},
            "skills": ["debuff_poison", "debuff_poison", "debuff_armor_break"],
        },
        # --- 4. Вожди (Bosses) [TSP ~280] ---
        "slann_mage": {
            "id": "slann_mage",
            "role": "boss",
            "cost": 600,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "An ancient, bloated frog-like mage floating on a palanquin. Wields immense power.",
            "extra_tags": ["slann", "mage", "leader"],
            "base_stats": {
                "strength": 10,
                "agility": 5,
                "endurance": 40,
                "intelligence": 50,
                "wisdom": 50,
                "men": 60,
                "perception": 30,
                "charisma": 25,
                "luck": 15,  # Итого: 285
            },
            "fixed_loadout": {},
            "skills": ["special_unique", "attack_aoe", "summon_minion", "buff_defense"],
        },
        "tyrant_king": {
            "id": "tyrant_king",
            "role": "boss",
            "cost": 600,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A colossal lizardman resembling a tyrannosaurus rex. A king of predators.",
            "extra_tags": ["tyrant", "king", "predator"],
            "base_stats": {
                "strength": 60,
                "agility": 20,
                "endurance": 60,
                "intelligence": 12,
                "wisdom": 12,
                "men": 30,
                "perception": 25,
                "charisma": 20,
                "luck": 10,  # Итого: 249
            },
            "fixed_loadout": {},
            "skills": ["attack_execute", "buff_rage", "attack_heavy", "debuff_weaken"],
        },
        "hydra_incarnate": {
            "id": "hydra_incarnate",
            "role": "boss",
            "cost": 600,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "A lizardman shaman who has merged with a hydra, sprouting multiple heads.",
            "extra_tags": ["hydra", "regenerating", "shaman"],
            "base_stats": {
                "strength": 40,
                "agility": 15,
                "endurance": 70,
                "intelligence": 20,
                "wisdom": 25,
                "men": 40,
                "perception": 30,
                "charisma": 15,
                "luck": 5,  # Итого: 260
            },
            "fixed_loadout": {},
            "skills": ["buff_heal", "attack_aoe", "attack_aoe", "debuff_poison"],
        },
    },
}
