"""
СЕМЕЙСТВО: ВАМПИРЫ (Ночь, кровь, подчинение)
============================================
Логика: тьма -> аристократия -> деградация
"""

from ..monster_structs import MonsterFamily

VAMPIRES_FAMILY: MonsterFamily = {
    "id": "vampire_coven",
    "archetype": "undead",
    "organization_type": "clan",  # TSP Base: 70
    "default_tags": ["undead", "vampire", "blood", "noble"],
    "hierarchy": {
        "minions": ["vampire_thrall", "blood_servant", "night_slave", "feral_vampire"],
        "veterans": ["vampire_stalker", "blood_drinker", "night_assassin", "shadow_fang"],
        "elites": ["vampire_knight", "blood_mage", "dark_noble", "crimson_lord"],
        "boss": ["ancient_vampire", "vampire_overlord", "nosferatu", "blood_patriarch"],
    },
    "variants": {
        # --- 1. Низшие / Падальщики (Minions) [TSP ~70] ---
        "vampire_thrall": {
            "id": "vampire_thrall",
            "role": "minion",
            "cost": 20,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A pale human with glazed eyes, obeying every command. Wears simple clothes.",
            "extra_tags": ["human", "thrall", "weak"],
            "base_stats": {
                "strength": 10,
                "agility": 10,
                "endurance": 10,
                "intelligence": 4,
                "wisdom": 4,
                "men": 10,
                "perception": 8,
                "charisma": 1,
                "luck": 5,  # Итого: 62
            },
            "fixed_loadout": {"main_hand": "dagger", "chest_garment": "shirt"},
            "skills": ["attack_basic", "attack_lifesteal"],
        },
        "blood_servant": {
            "id": "blood_servant",
            "role": "minion",
            "cost": 20,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A servant carrying a chalice of blood. Will fight to protect it.",
            "extra_tags": ["servant", "support"],
            "base_stats": {
                "strength": 8,
                "agility": 12,
                "endurance": 8,
                "intelligence": 8,
                "wisdom": 8,
                "men": 10,
                "perception": 10,
                "charisma": 5,
                "luck": 5,  # Итого: 74
            },
            "fixed_loadout": {"main_hand": "knife", "chest_garment": "tunic"},
            "skills": ["buff_heal"],
        },
        "night_slave": {
            "id": "night_slave",
            "role": "minion",
            "cost": 20,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A wretched creature that fears the sun. Moves in the shadows.",
            "extra_tags": ["slave", "coward"],
            "base_stats": {
                "strength": 8,
                "agility": 14,
                "endurance": 8,
                "intelligence": 4,
                "wisdom": 4,
                "men": 5,
                "perception": 12,
                "charisma": 1,
                "luck": 5,  # Итого: 61
            },
            "fixed_loadout": {},
            "skills": ["buff_defense", "attack_heavy"],
        },
        "feral_vampire": {
            "id": "feral_vampire",
            "role": "minion",
            "cost": 20,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A vampire that has lost its mind to hunger. Attacks like a beast.",
            "extra_tags": ["feral", "beast"],
            "base_stats": {
                "strength": 16,
                "agility": 16,
                "endurance": 12,
                "intelligence": 2,
                "wisdom": 2,
                "men": 10,
                "perception": 14,
                "charisma": 1,
                "luck": 5,  # Итого: 78
            },
            "fixed_loadout": {},
            "skills": ["buff_rage", "attack_basic"],
        },
        # --- 2. Охотники (Veterans) [TSP ~105] ---
        "vampire_stalker": {
            "id": "vampire_stalker",
            "role": "veteran",
            "cost": 50,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A vampire in dark leather armor, moving silently.",
            "extra_tags": ["stalker", "stealth"],
            "base_stats": {
                "strength": 14,
                "agility": 20,
                "endurance": 14,
                "intelligence": 10,
                "wisdom": 8,
                "men": 15,
                "perception": 14,
                "charisma": 5,
                "luck": 8,  # Итого: 108
            },
            "fixed_loadout": {"main_hand": "dagger", "off_hand": "dagger", "chest_armor": "jerkin"},
            "skills": ["stealth", "attack_heavy"],
        },
        "blood_drinker": {
            "id": "blood_drinker",
            "role": "veteran",
            "cost": 50,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A vampire with bloodstained lips. Heals when it strikes.",
            "extra_tags": ["lifesteal", "frenzied"],
            "base_stats": {
                "strength": 18,
                "agility": 16,
                "endurance": 16,
                "intelligence": 8,
                "wisdom": 8,
                "men": 15,
                "perception": 10,
                "charisma": 6,
                "luck": 5,  # Итого: 102
            },
            "fixed_loadout": {"main_hand": "sword"},
            "skills": ["attack_lifesteal", "buff_rage"],
        },
        "night_assassin": {
            "id": "night_assassin",
            "role": "veteran",
            "cost": 50,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "An elite killer of the coven. Strikes fast and hard.",
            "extra_tags": ["assassin", "poison"],
            "base_stats": {
                "strength": 14,
                "agility": 22,
                "endurance": 12,
                "intelligence": 12,
                "wisdom": 10,
                "men": 15,
                "perception": 16,
                "charisma": 4,
                "luck": 10,  # Итого: 115
            },
            "fixed_loadout": {"main_hand": "wakizashi", "off_hand": "tanto", "chest_armor": "jerkin"},
            "skills": ["attack_execute", "debuff_poison", "stealth"],
        },
        "shadow_fang": {
            "id": "shadow_fang",
            "role": "veteran",
            "cost": 50,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A vampire that seems to be made of shadows.",
            "extra_tags": ["shadow", "agile"],
            "base_stats": {
                "strength": 12,
                "agility": 20,
                "endurance": 12,
                "intelligence": 10,
                "wisdom": 10,
                "men": 15,
                "perception": 12,
                "charisma": 5,
                "luck": 7,  # Итого: 103
            },
            "fixed_loadout": {"main_hand": "rapier"},
            "skills": ["attack_heavy", "buff_evasion", "debuff_blind"],
        },
        # --- 3. Знать / Элита (Elites) [TSP ~175] ---
        "vampire_knight": {
            "id": "vampire_knight",
            "role": "elite",
            "cost": 150,
            "min_tier": 5,
            "max_tier": 8,
            "narrative_hint": "A vampire in ornate black plate armor. Wields a greatsword.",
            "extra_tags": ["knight", "heavy_armor"],
            "base_stats": {
                "strength": 30,
                "agility": 14,
                "endurance": 30,
                "intelligence": 12,
                "wisdom": 10,
                "men": 20,
                "perception": 10,
                "charisma": 10,
                "luck": 5,  # Итого: 141 (но броня)
            },
            "fixed_loadout": {"main_hand": "greatsword", "chest_armor": "plate_chest", "head_armor": "helmet"},
            "skills": ["attack_heavy", "buff_rage", "buff_rage"],
        },
        "blood_mage": {
            "id": "blood_mage",
            "role": "elite",
            "cost": 150,
            "min_tier": 5,
            "max_tier": 8,
            "narrative_hint": "A vampire in crimson robes, manipulating blood with magic.",
            "extra_tags": ["mage", "blood_magic"],
            "base_stats": {
                "strength": 10,
                "agility": 14,
                "endurance": 16,
                "intelligence": 30,
                "wisdom": 25,
                "men": 30,
                "perception": 14,
                "charisma": 12,
                "luck": 8,  # Итого: 159
            },
            "fixed_loadout": {"main_hand": "staff", "chest_garment": "robe"},
            "skills": ["debuff_bleed", "debuff_bleed", "attack_lifesteal"],
        },
        "dark_noble": {
            "id": "dark_noble",
            "role": "elite",
            "cost": 150,
            "min_tier": 5,
            "max_tier": 8,
            "narrative_hint": "An arrogant vampire in fine clothes. Radiates an aura of dread.",
            "extra_tags": ["noble", "duelist"],
            "base_stats": {
                "strength": 20,
                "agility": 25,
                "endurance": 20,
                "intelligence": 20,
                "wisdom": 20,
                "men": 25,
                "perception": 12,
                "charisma": 25,
                "luck": 10,  # Итого: 177
            },
            "fixed_loadout": {"main_hand": "rapier", "chest_garment": "cloak"},
            "skills": ["debuff_weaken", "debuff_stun", "special_unique"],
        },
        "crimson_lord": {
            "id": "crimson_lord",
            "role": "elite",
            "cost": 150,
            "min_tier": 5,
            "max_tier": 8,
            "narrative_hint": "A high-ranking vampire commander. Leads from the front.",
            "extra_tags": ["lord", "commander"],
            "base_stats": {
                "strength": 25,
                "agility": 18,
                "endurance": 25,
                "intelligence": 15,
                "wisdom": 15,
                "men": 25,
                "perception": 14,
                "charisma": 20,
                "luck": 8,  # Итого: 165
            },
            "fixed_loadout": {"main_hand": "sword", "off_hand": "shield", "chest_armor": "plate_chest"},
            "skills": ["attack_heavy", "summon_minion", "buff_defense"],
        },
        # --- 4. Древние / Владыки (Bosses) [TSP ~280] ---
        "ancient_vampire": {
            "id": "ancient_vampire",
            "role": "boss",
            "cost": 600,
            "min_tier": 6,
            "max_tier": 9,
            "narrative_hint": "A vampire centuries old. Moves with impossible grace.",
            "extra_tags": ["ancient", "graceful"],
            "base_stats": {
                "strength": 30,
                "agility": 40,
                "endurance": 35,
                "intelligence": 30,
                "wisdom": 30,
                "men": 50,
                "perception": 20,
                "charisma": 30,
                "luck": 15,  # Итого: 280
            },
            "fixed_loadout": {"main_hand": "longsword", "chest_garment": "cloak", "amulet": "amulet"},
            "skills": ["special_unique", "buff_evasion", "buff_rage"],
        },
        "vampire_overlord": {
            "id": "vampire_overlord",
            "role": "boss",
            "cost": 600,
            "min_tier": 6,
            "max_tier": 9,
            "narrative_hint": "The ruler of the region. Sits on a throne of bone.",
            "extra_tags": ["overlord", "ruler"],
            "base_stats": {
                "strength": 40,
                "agility": 25,
                "endurance": 45,
                "intelligence": 35,
                "wisdom": 35,
                "men": 60,
                "perception": 25,
                "charisma": 40,
                "luck": 20,  # Итого: 325
            },
            "fixed_loadout": {"main_hand": "greatsword", "chest_armor": "plate_chest", "head_armor": "helmet"},
            "skills": ["debuff_stun", "summon_minion", "attack_lifesteal"],
        },
        "nosferatu": {
            "id": "nosferatu",
            "role": "boss",
            "cost": 600,
            "min_tier": 6,
            "max_tier": 9,
            "narrative_hint": "A twisted, monstrous vampire. More beast than man, but with ancient cunning.",
            "extra_tags": ["monstrous", "feral", "ancient"],
            "base_stats": {
                "strength": 50,
                "agility": 20,
                "endurance": 60,
                "intelligence": 20,
                "wisdom": 20,
                "men": 40,
                "perception": 30,
                "charisma": 10,
                "luck": 10,  # Итого: 260 (чистая мощь)
            },
            "fixed_loadout": {},
            "skills": ["debuff_poison", "debuff_weaken", "debuff_bleed"],
        },
        "blood_patriarch": {
            "id": "blood_patriarch",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 10,
            "narrative_hint": "The progenitor of the bloodline. A god of blood and death.",
            "extra_tags": ["patriarch", "godlike", "blood_magic"],
            "base_stats": {
                "strength": 45,
                "agility": 35,
                "endurance": 60,
                "intelligence": 50,
                "wisdom": 50,
                "men": 100,
                "perception": 30,
                "charisma": 50,
                "luck": 25,  # Итого: 445
            },
            "fixed_loadout": {"main_hand": "staff", "chest_garment": "robe"},
            "skills": ["attack_aoe", "special_unique", "attack_execute", "summon_minion"],
        },
    },
}
