HUMANOID_WEAPON_FORM_PHRASES = {
    "weapon_form": {
        "body.humanoid.weapon_form.skill_swords.cutting_line": {
            "kind": "weapon_form",
            "text": "ведет рубящую линию",
            "variables": [],
            "tags": ["skill_swords", "slash", "weapon"],
        },
        "body.humanoid.weapon_form.skill_swords.short_cut": {
            "kind": "weapon_form",
            "text": "проводит короткий режущий удар",
            "variables": [],
            "tags": ["skill_swords", "cut", "weapon"],
        },
        "body.humanoid.weapon_form.skill_swords.guard_cut": {
            "kind": "weapon_form",
            "text": "режет через открытую линию защиты",
            "variables": [],
            "tags": ["skill_swords", "open_line", "weapon"],
        },
        "body.humanoid.weapon_form.skill_swords.heavy_arc": {
            "kind": "weapon_form",
            "text": "ведет тяжелую дугу оружием",
            "variables": [],
            "tags": ["skill_swords", "heavy", "weapon"],
        },
        "body.humanoid.weapon_form.skill_fencing.thrust": {
            "kind": "weapon_form",
            "text": "выводит острие в короткий выпад",
            "variables": [],
            "tags": ["skill_fencing", "pierce", "weapon"],
        },
        "body.humanoid.weapon_form.skill_fencing.point_line": {
            "kind": "weapon_form",
            "text": "держит точную линию укола",
            "variables": [],
            "tags": ["skill_fencing", "point", "weapon"],
        },
        "body.humanoid.weapon_form.skill_fencing.low_cut": {
            "kind": "weapon_form",
            "text": "подрезает нижнюю линию",
            "variables": [],
            "tags": ["skill_fencing", "cut", "low_line"],
        },
        "body.humanoid.weapon_form.skill_fencing.riposte_line": {
            "kind": "weapon_form",
            "text": "возвращает оружие в быструю ответную линию",
            "variables": [],
            "tags": ["skill_fencing", "riposte", "weapon"],
        },
        "body.humanoid.weapon_form.skill_polearms.long_reach": {
            "kind": "weapon_form",
            "text": "держит дистанцию длиной древка",
            "variables": [],
            "tags": ["skill_polearms", "reach", "weapon"],
        },
        "body.humanoid.weapon_form.skill_polearms.thrust": {
            "kind": "weapon_form",
            "text": "посылает древко в длинный выпад",
            "variables": [],
            "tags": ["skill_polearms", "pierce", "weapon"],
        },
        "body.humanoid.weapon_form.skill_polearms.hook": {
            "kind": "weapon_form",
            "text": "цепляет линию опоры древком",
            "variables": [],
            "tags": ["skill_polearms", "hook", "control"],
        },
        "body.humanoid.weapon_form.skill_polearms.sweep": {
            "kind": "weapon_form",
            "text": "ведет широкий удар древком",
            "variables": [],
            "tags": ["skill_polearms", "sweep", "weapon"],
        },
        "body.humanoid.weapon_form.skill_macing.crushing_arc": {
            "kind": "weapon_form",
            "text": "обрушивает дробящий замах",
            "variables": [],
            "tags": ["skill_macing", "crush", "weapon"],
        },
        "body.humanoid.weapon_form.skill_macing.press_guard": {
            "kind": "weapon_form",
            "text": "продавливает защиту тяжелым оружием",
            "variables": [],
            "tags": ["skill_macing", "pressure", "weapon"],
        },
        "body.humanoid.weapon_form.skill_macing.short_bash": {
            "kind": "weapon_form",
            "text": "бьет коротко и тяжело",
            "variables": [],
            "tags": ["skill_macing", "bash", "weapon"],
        },
        "body.humanoid.weapon_form.skill_macing.break_line": {
            "kind": "weapon_form",
            "text": "ломает линию защиты силовым ударом",
            "variables": [],
            "tags": ["skill_macing", "break_guard", "weapon"],
        },
        "body.humanoid.weapon_form.skill_archery.aimed_shot": {
            "kind": "weapon_form",
            "text": "выдерживает прицельный выстрел",
            "variables": [],
            "tags": ["skill_archery", "aim", "ranged"],
        },
        "body.humanoid.weapon_form.skill_archery.quick_shot": {
            "kind": "weapon_form",
            "text": "пускает быстрый снаряд",
            "variables": [],
            "tags": ["skill_archery", "quick", "ranged"],
        },
        "body.humanoid.weapon_form.skill_archery.fire_line": {
            "kind": "weapon_form",
            "text": "ловит чистую линию выстрела",
            "variables": [],
            "tags": ["skill_archery", "open_line", "ranged"],
        },
        "body.humanoid.weapon_form.skill_archery.moving_shot": {
            "kind": "weapon_form",
            "text": "стреляет на смещении",
            "variables": [],
            "tags": ["skill_archery", "movement", "ranged"],
        },
        "body.humanoid.weapon_form.skill_unarmed.straight": {
            "kind": "weapon_form",
            "text": "бьет коротко и прямо",
            "variables": [],
            "tags": ["skill_unarmed", "strike", "unarmed"],
        },
        "body.humanoid.weapon_form.skill_unarmed.elbow": {
            "kind": "weapon_form",
            "text": "вкладывает корпус в удар локтем",
            "variables": [],
            "tags": ["skill_unarmed", "elbow", "unarmed"],
        },
        "body.humanoid.weapon_form.skill_unarmed.grapple": {
            "kind": "weapon_form",
            "text": "входит в ближний захват",
            "variables": [],
            "tags": ["skill_unarmed", "grapple", "close"],
        },
        "body.humanoid.weapon_form.skill_unarmed.shoulder": {
            "kind": "weapon_form",
            "text": "давит плечом и корпусом",
            "variables": [],
            "tags": ["skill_unarmed", "body", "pressure"],
        },
        "body.humanoid.weapon_form.skill_shield_mastery.shield_press": {
            "kind": "weapon_form",
            "text": "ведет щит в силовое давление",
            "variables": [],
            "tags": ["skill_shield_mastery", "shield", "pressure"],
        },
        "body.humanoid.weapon_form.skill_shield_mastery.shield_bash": {
            "kind": "weapon_form",
            "text": "бьет щитом на короткой дистанции",
            "variables": [],
            "tags": ["skill_shield_mastery", "shield", "bash"],
        },
        "body.humanoid.weapon_form.skill_dual_wield.second_line": {
            "kind": "weapon_form",
            "text": "открывает вторую линию атаки",
            "variables": [],
            "tags": ["skill_dual_wield", "off_hand", "dual"],
        },
        "body.humanoid.weapon_form.skill_dual_wield.cross_pressure": {
            "kind": "weapon_form",
            "text": "давит двумя руками с разных сторон",
            "variables": [],
            "tags": ["skill_dual_wield", "pressure", "dual"],
        },
        "body.humanoid.weapon_form.skill_two_handed.full_weight": {
            "kind": "weapon_form",
            "text": "вкладывает обе руки в удар",
            "variables": [],
            "tags": ["skill_two_handed", "heavy", "tactical"],
        },
    },
}
