from src.backend.features.game_catalog.combat.resources.abilities.enums import AbilitySource, AbilityType
from src.backend.features.game_catalog.combat.resources.abilities.schemas import (
    AbilityCatalogEntryDTO,
    AbilityCostDTO,
    AbilityTechnicalDTO,
    PipelineMutationsDTO,
)
from src.backend.features.game_catalog.combat.resources.common.descriptions import (
    CombatEventTextSetDTO,
    build_combat_description,
)
from src.backend.features.game_catalog.combat.resources.common.modifier_applications import ModifierApplicationDTO
from src.backend.features.game_catalog.combat.resources.common.pipeline_mutations import pipeline_mutation
from src.backend.features.game_catalog.combat.resources.common.targeting import TargetType

BASIC_GIFT_ABILITY_IDS: tuple[str, ...] = (
    "basic_break_stance",
    "basic_expose_weakness",
    "basic_wipe_blood",
    "basic_last_push",
    "basic_slip_pain",
    "basic_blood_hunger",
    "basic_splinter_strike",
    "basic_cleave_gift",
)

_TACTICAL_INSTANT_STRIKE = PipelineMutationsDTO(
    preset="TACTICAL_INSTANT_STRIKE",
    applications=[
        pipeline_mutation("damage.physical", True),
        pipeline_mutation("damage.arcane", False),
        pipeline_mutation("damage_mult", 1.2),
    ],
)


BASIC_GIFT_ABILITIES_TECHNICAL: dict[str, AbilityTechnicalDTO] = {
    "basic_break_stance": AbilityTechnicalDTO(
        ability_id="basic_break_stance",
        source=AbilitySource.COMBAT,
        type=AbilityType.INSTANT,
        cost=AbilityCostDTO(tokens={"tempo": 3, "hit": 2}),
        target=TargetType.SINGLE_ENEMY,
        pipeline_mutations=_TACTICAL_INSTANT_STRIKE,
        modifier_applications=[
            ModifierApplicationDTO(
                modifier_id="physical_damage_bonus_add",
                target_actor="target",
                value_mode="source_main_hand_damage_multiplier",
                value_multiplier=-0.25,
                value_override=1.2,
                scope="duration",
                duration_exchanges=4,
            )
        ],
        ai_tags=["tempo", "hit", "debuff", "anti_defense"],
    ),
    "basic_expose_weakness": AbilityTechnicalDTO(
        ability_id="basic_expose_weakness",
        source=AbilitySource.COMBAT,
        type=AbilityType.INSTANT,
        cost=AbilityCostDTO(tokens={"tempo": 2, "crit": 2}),
        target=TargetType.SINGLE_ENEMY,
        pipeline_mutations=_TACTICAL_INSTANT_STRIKE,
        modifier_applications=[
            ModifierApplicationDTO(
                modifier_id="evasion_add",
                target_actor="target",
                value_override=-0.5,
                scope="duration",
                duration_exchanges=3,
            )
        ],
        ai_tags=["tempo", "crit", "debuff", "anti_evasion"],
    ),
    "basic_wipe_blood": AbilityTechnicalDTO(
        ability_id="basic_wipe_blood",
        source=AbilitySource.COMBAT,
        type=AbilityType.INSTANT,
        cost=AbilityCostDTO(energy=5, gift_tokens=1, tokens={"blood": 3, "block": 1}),
        target=TargetType.SELF,
        pipeline_mutations=PipelineMutationsDTO(preset="BUFF"),
        modifier_applications=[
            ModifierApplicationDTO(
                modifier_id="hp_regen_add",
                target_actor="self",
                value_mode="source_modifier_multiplier",
                source_modifier_id="hp_regen",
                value_multiplier=1.0,
                scope="duration",
                duration_exchanges=3,
                scale_value_with_symbiote=True,
                scale_duration_with_symbiote=True,
            ),
            ModifierApplicationDTO(
                modifier_id="parry_add",
                target_actor="self",
                value_override=0.05,
                scope="duration",
                duration_exchanges=3,
                scale_value_with_symbiote=True,
                scale_duration_with_symbiote=True,
            ),
            ModifierApplicationDTO(
                modifier_id="parry_cap_add",
                target_actor="self",
                value_override=0.05,
                scope="duration",
                duration_exchanges=3,
                scale_value_with_symbiote=True,
                scale_duration_with_symbiote=True,
            ),
        ],
        ai_tags=["blood", "block", "heal", "defense", "self_buff"],
    ),
    "basic_last_push": AbilityTechnicalDTO(
        ability_id="basic_last_push",
        source=AbilitySource.COMBAT,
        type=AbilityType.INSTANT,
        cost=AbilityCostDTO(energy=5, gift_tokens=1, tokens={"blood": 3, "parry": 1}),
        target=TargetType.SELF,
        pipeline_mutations=PipelineMutationsDTO(preset="BUFF"),
        modifier_applications=[
            ModifierApplicationDTO(
                modifier_id="hp_regen_add",
                target_actor="self",
                value_mode="source_modifier_multiplier",
                source_modifier_id="hp_regen",
                value_multiplier=1.0,
                scope="duration",
                duration_exchanges=3,
                scale_value_with_symbiote=True,
                scale_duration_with_symbiote=True,
            ),
            ModifierApplicationDTO(
                modifier_id="accuracy_add",
                target_actor="self",
                value_override=0.03,
                scope="duration",
                duration_exchanges=3,
                scale_value_with_symbiote=True,
                scale_duration_with_symbiote=True,
            ),
            ModifierApplicationDTO(
                modifier_id="accuracy_cap_add",
                target_actor="self",
                value_override=0.03,
                scope="duration",
                duration_exchanges=3,
                scale_value_with_symbiote=True,
                scale_duration_with_symbiote=True,
            ),
        ],
        ai_tags=["blood", "parry", "heal", "offense", "self_buff"],
    ),
    "basic_slip_pain": AbilityTechnicalDTO(
        ability_id="basic_slip_pain",
        source=AbilitySource.COMBAT,
        type=AbilityType.INSTANT,
        cost=AbilityCostDTO(energy=5, gift_tokens=1, tokens={"blood": 3, "dodge": 1}),
        target=TargetType.SELF,
        pipeline_mutations=PipelineMutationsDTO(preset="BUFF"),
        modifier_applications=[
            ModifierApplicationDTO(
                modifier_id="hp_regen_add",
                target_actor="self",
                value_mode="source_modifier_multiplier",
                source_modifier_id="hp_regen",
                value_multiplier=1.0,
                scope="duration",
                duration_exchanges=3,
                scale_value_with_symbiote=True,
                scale_duration_with_symbiote=True,
            ),
            ModifierApplicationDTO(
                modifier_id="incoming_damage_absorb_pct_add",
                target_actor="self",
                value_mode="source_modifier_scaled_clamped",
                source_modifier_id="evasion",
                value_override=0.03,
                value_multiplier=0.05,
                value_cap=0.15,
                scope="duration",
                duration_exchanges=3,
                scale_value_with_symbiote=True,
                scale_duration_with_symbiote=True,
            ),
        ],
        ai_tags=["blood", "dodge", "heal", "defense", "absorb", "self_buff"],
    ),
    "basic_blood_hunger": AbilityTechnicalDTO(
        ability_id="basic_blood_hunger",
        source=AbilitySource.COMBAT,
        type=AbilityType.INSTANT,
        cost=AbilityCostDTO(gift_tokens=1, tokens={"tempo": 5, "pressure": 5}),
        target=TargetType.SELF,
        pipeline_mutations=PipelineMutationsDTO(
            preset="BUFF",
            applications=[pipeline_mutation("damage.vampiric", True)],
        ),
        modifier_applications=[
            ModifierApplicationDTO(
                modifier_id="physical_damage_bonus_add",
                target_actor="self",
                value_mode="source_modifier_multiplier",
                source_modifier_id="hp_regen",
                value_multiplier=0.5,
                scope="duration",
                duration_exchanges=5,
                scale_value_with_symbiote=True,
                scale_duration_with_symbiote=True,
            ),
            ModifierApplicationDTO(
                modifier_id="vampiric_power_add",
                target_actor="self",
                value_override=0.15,
                scope="duration",
                duration_exchanges=5,
                scale_value_with_symbiote=True,
                scale_duration_with_symbiote=True,
            ),
        ],
        ai_tags=["blood", "tempo", "pressure", "heal", "vampiric", "self_buff"],
    ),
    "basic_splinter_strike": AbilityTechnicalDTO(
        ability_id="basic_splinter_strike",
        source=AbilitySource.COMBAT,
        type=AbilityType.INSTANT,
        cost=AbilityCostDTO(energy=5, gift_tokens=1, tokens={"hit": 3}),
        target=TargetType.RANDOM_ENEMY,
        target_count=3,
        secondary_damage_mult=0.50,
        pipeline_mutations=_TACTICAL_INSTANT_STRIKE,
        ai_tags=["hit", "damage", "multi_target"],
    ),
    "basic_cleave_gift": AbilityTechnicalDTO(
        ability_id="basic_cleave_gift",
        source=AbilitySource.COMBAT,
        type=AbilityType.INSTANT,
        cost=AbilityCostDTO(gift_tokens=3, tokens={"hit": 3, "pressure": 3}),
        target=TargetType.SELF,
        pipeline_mutations=PipelineMutationsDTO(preset="BUFF"),
        modifier_applications=[
            ModifierApplicationDTO(
                modifier_id="cleave_damage_mult_add",
                target_actor="self",
                value_override=0.30,
                scope="duration",
                duration_exchanges=3,
                scale_value_with_symbiote=True,
                scale_duration_with_symbiote=True,
            ),
            ModifierApplicationDTO(
                modifier_id="cleave_target_count_add",
                target_actor="self",
                value_override=2.0,
                scope="duration",
                duration_exchanges=3,
                scale_duration_with_symbiote=True,
            ),
        ],
        ai_tags=["hit", "pressure", "damage", "multi_target", "self_buff", "cleave"],
    ),
}


BASIC_GIFT_ABILITIES_DESCRIPTIVE = {
    "basic_break_stance": build_combat_description(
        resource_type="abilities",
        resource_id="basic_break_stance",
        icon="combat/abilities/basic_break_stance.svg",
        display_name="Сбить стойку",
        ui_label="Сбить стойку",
        short_description="Тратит темп и попадание, чтобы ослабить защитную стойку цели.",
        humanoid_event_texts=CombatEventTextSetDTO(
            use=["{source} сбивает стойку {target}."],
            hit=["{source} ломает устойчивость {target}"],
            apply_effect=["{target} теряет устойчивость: {effect}."],
            no_resource=["{source} не удерживает темп для сбития стойки"],
        ),
        beast_event_texts=CombatEventTextSetDTO(),
    ),
    "basic_expose_weakness": build_combat_description(
        resource_type="abilities",
        resource_id="basic_expose_weakness",
        icon="combat/abilities/basic_expose_weakness.svg",
        display_name="Открыть слабость",
        ui_label="Открыть слабость",
        short_description="Тратит темп и критический момент, чтобы подавить уклонение цели.",
        humanoid_event_texts=CombatEventTextSetDTO(
            use=["{source} отмечает слабое место {target}."],
            hit=["{source} бьёт в слабое место {target}"],
            apply_effect=["слабость {target} открыта: {effect}."],
            no_resource=["{source} видит слабость, но не может её открыть"],
        ),
        beast_event_texts=CombatEventTextSetDTO(),
    ),
    "basic_wipe_blood": build_combat_description(
        resource_type="abilities",
        resource_id="basic_wipe_blood",
        icon="combat/abilities/basic_wipe_blood.svg",
        display_name="Утереть кровь",
        ui_label="Утереть кровь",
        short_description="Тратит кровь, чтобы восстановить часть здоровья.",
        humanoid_event_texts=CombatEventTextSetDTO(
            use=["{source} заставляет кровь работать на выживание."],
            heal=["{source} собирается и закрывает раны"],
            no_resource=["{source} не находит в боли достаточно силы"],
        ),
        beast_event_texts=CombatEventTextSetDTO(),
    ),
    "basic_last_push": build_combat_description(
        resource_type="abilities",
        resource_id="basic_last_push",
        icon="combat/abilities/basic_last_push.svg",
        display_name="Последний рывок",
        ui_label="Последний рывок",
        short_description="Тратит кровь и парирование, чтобы усилить регенерацию, точность и предел точности.",
        humanoid_event_texts=CombatEventTextSetDTO(
            use=["{source} выжимает из себя последний рывок."],
            heal=["{source} возвращает себе часть сил"],
            apply_effect=["рывок усиливает {source}: {effect}."],
            no_resource=["{source} не находит сил для последнего рывка"],
        ),
        beast_event_texts=CombatEventTextSetDTO(),
    ),
    "basic_slip_pain": build_combat_description(
        resource_type="abilities",
        resource_id="basic_slip_pain",
        icon="combat/abilities/basic_wipe_blood.svg",
        display_name="Скользнуть сквозь боль",
        ui_label="Скользнуть сквозь боль",
        short_description="Тратит кровь и уклонение, чтобы усилить регенерацию и поглощение входящего урона.",
        humanoid_event_texts=CombatEventTextSetDTO(
            use=["{source} уходит с линии удара и держится на боли."],
            heal=["{source} переживает удар за счёт движения"],
            apply_effect=["движение усиливает {source}: {effect}."],
            no_resource=["{source} не может превратить уклонение в выживание"],
        ),
        beast_event_texts=CombatEventTextSetDTO(),
    ),
    "basic_blood_hunger": build_combat_description(
        resource_type="abilities",
        resource_id="basic_blood_hunger",
        icon="combat/abilities/basic_wipe_blood.svg",
        display_name="Кровавый голод",
        ui_label="Кровавый голод",
        short_description="Тратит темп и нажим, чтобы усилить урон и включить вампирик.",
        humanoid_event_texts=CombatEventTextSetDTO(
            use=["{source} превращает темп и нажим в кровавый голод."],
            heal=["{source} возвращает здоровье через нанесённый урон"],
            apply_effect=["голод усиливает {source}: {effect}."],
            no_resource=["{source} не может собрать темп и нажим"],
        ),
        beast_event_texts=CombatEventTextSetDTO(),
    ),
    "basic_splinter_strike": build_combat_description(
        resource_type="abilities",
        resource_id="basic_splinter_strike",
        icon="combat/abilities/basic_break_stance.svg",
        display_name="Осколочный удар",
        ui_label="Осколочный удар",
        short_description="Тратит попадание, энергию и дар, чтобы ударить до трёх случайных врагов со штрафом урона.",
        humanoid_event_texts=CombatEventTextSetDTO(
            use=["{source} дробит атаку на несколько целей."],
            hit=["осколочный удар достаёт {target}"],
            crit=["{source} пробивает {target} осколочным ударом"],
            miss=["{target} уходит от осколочного удара"],
            no_resource=["{source} не собирает попадание для осколочного удара"],
        ),
        beast_event_texts=CombatEventTextSetDTO(),
    ),
    "basic_cleave_gift": build_combat_description(
        resource_type="abilities",
        resource_id="basic_cleave_gift",
        icon="combat/abilities/basic_break_stance.svg",
        display_name="Дар рассечения",
        ui_label="Дар рассечения",
        short_description="Тратит попадание, нажим и дар, чтобы следующие успешные удары задевали соседние цели.",
        humanoid_event_texts=CombatEventTextSetDTO(
            use=["{source} раскрывает дар рассечения."],
            apply_effect=["дар рассечения усиливает {source}: {effect}."],
            no_resource=["{source} не может раскрыть дар рассечения"],
        ),
        beast_event_texts=CombatEventTextSetDTO(),
    ),
}


BASIC_GIFT_ABILITIES_CATALOG = {
    ability_id: AbilityCatalogEntryDTO(
        key=f"combat.ability.{ability_id}",
        technical=technical,
        descriptive=BASIC_GIFT_ABILITIES_DESCRIPTIVE[ability_id],
    )
    for ability_id, technical in BASIC_GIFT_ABILITIES_TECHNICAL.items()
}
