CHARACTER_ATTRIBUTE_TEXT: dict[str, dict[str, object]] = {
    "strength": {
        "title": "Сила",
        "title_en": "Strength",
        "short_title": "STR",
        "description": "Физическое давление персонажа: сила удара, переносимый вес и способность пробивать сопротивление.",
        "ui_tags": ["attribute", "physical"],
    },
    "agility": {
        "title": "Ловкость",
        "title_en": "Agility",
        "short_title": "AGI",
        "description": "Скорость тела и точность движения: уклонение, инициатива, баланс и быстрые атаки.",
        "ui_tags": ["attribute", "physical"],
    },
    "endurance": {
        "title": "Выносливость",
        "title_en": "Endurance",
        "short_title": "END",
        "description": "Запас тела: здоровье, стойкость, сопротивление усталости, боли и длительным нагрузкам.",
        "ui_tags": ["attribute", "physical"],
    },
    "intellect": {
        "title": "Интеллект",
        "title_en": "Intellect",
        "short_title": "INT",
        "description": "Способность анализировать, строить схемы, понимать устройства, формулы и скрытые связи.",
        "ui_tags": ["attribute", "mental"],
    },
    "memory": {
        "title": "Память",
        "title_en": "Memory",
        "short_title": "MEM",
        "description": "Удержание и восстановление опыта: знания, маршруты, приемы, детали событий и узнавание паттернов.",
        "ui_tags": ["attribute", "mental"],
    },
    "mental": {
        "title": "Ментальность",
        "title_en": "Mentality",
        "short_title": "MEN",
        "description": "Целостность сознания: воля, сопротивление ментальному воздействию и стабильность связи с миром.",
        "ui_tags": ["attribute", "mental"],
    },
    "perception": {
        "title": "Восприятие",
        "title_en": "Perception",
        "short_title": "PER",
        "description": "Острота чувств: замечать следы, угрозы, слабые места и детали, которые другие пропускают.",
        "ui_tags": ["attribute", "sense"],
    },
    "projection": {
        "title": "Проекция",
        "title_en": "Projection",
        "short_title": "PRJ",
        "description": "Способность направлять внутреннее состояние наружу: давление, образ, резонанс и влияние на среду.",
        "ui_tags": ["attribute", "sense"],
    },
    "prediction": {
        "title": "Предвидение",
        "title_en": "Prediction",
        "short_title": "PRD",
        "description": "Опережающее чтение будущего хода событий: угрозы, развилки, намерения и вероятные исходы.",
        "ui_tags": ["attribute", "sense"],
    },
}
