from src.backend.features.items.resources.schemas import BaseItemDTO

FENCING_DB = {
    "knife": BaseItemDTO(
        id="knife",
        name_ru="Нож",
        narrative_description="Короткий простой клинок, который можно держать как основное оружие или вторым в свободной руке.",
        slot="main_hand",
        extra_slots=["off_hand"],
        type="weapon",
        damage_type="physical",
        related_skill="skill_fencing",
        allowed_materials=["ingots"],
        base_power=2,
        damage_spread=0.06,
        base_durability=35,
        narrative_tags=["knife", "dagger", "fencing", "offhand", "swift"],
        implicit_bonuses={
            "physical_crit_chance": 0.06,
            "parry_chance": 0.02,
        },
        triggers=["crit.weapon_flat_armor_gap_crit"],
    ),
    "dagger": BaseItemDTO(
        id="dagger",
        name_ru="Кинжал",
        narrative_description="Короткий клинок для быстрых уколов, скрытого ношения и точного добивания вблизи.",
        slot="main_hand",
        extra_slots=["off_hand"],
        type="weapon",
        damage_type="physical",
        related_skill="skill_fencing",
        allowed_materials=["ingots"],
        base_power=3,
        damage_spread=0.08,
        base_durability=40,
        narrative_tags=["dagger", "fencing", "swift", "piercing"],
        implicit_bonuses={
            "physical_crit_chance": 0.07,
            "parry_chance": 0.025,
        },
        triggers=["crit.weapon_flat_armor_gap_crit"],
    ),
    "stiletto": BaseItemDTO(
        id="stiletto",
        name_ru="Стилет",
        narrative_description="Узкий колющий клинок для точного прохода в щели брони; подходит и для второй руки.",
        slot="main_hand",
        extra_slots=["off_hand"],
        type="weapon",
        damage_type="physical",
        related_skill="skill_fencing",
        allowed_materials=["ingots"],
        base_power=3,
        damage_spread=0.07,
        base_durability=38,
        narrative_tags=["stiletto", "dagger", "fencing", "piercing", "offhand"],
        implicit_bonuses={
            "physical_crit_chance": 0.075,
            "weapon_armor_penetration_pct": 0.10,
            "parry_chance": 0.02,
        },
        triggers=["crit.weapon_flat_armor_bypass_crit"],
    ),
    "rapier": BaseItemDTO(
        id="rapier",
        name_ru="Рапира",
        narrative_description="Легкий длинный клинок для фехтовального контроля линии, точного укола и работы на дистанции.",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_fencing",
        allowed_materials=["ingots"],
        base_power=5,
        damage_spread=0.08,
        base_durability=48,
        narrative_tags=["rapier", "fencing", "duelist", "precision"],
        implicit_bonuses={
            "physical_crit_chance": 0.08,
            "parry_chance": 0.035,
        },
        triggers=["crit.weapon_precision_crit"],
    ),
    "main_gauche": BaseItemDTO(
        id="main_gauche",
        name_ru="Дага",
        narrative_description="Парирующий кинжал для второй руки, рассчитанный на перехват клинка и короткий ответ.",
        slot="off_hand",
        extra_slots=["main_hand"],
        type="weapon",
        damage_type="physical",
        related_skill="skill_fencing",
        allowed_materials=["ingots"],
        base_power=2,
        damage_spread=0.08,
        base_durability=45,
        narrative_tags=["main_gauche", "dagger", "fencing", "parry", "offhand"],
        implicit_bonuses={
            "physical_crit_chance": 0.05,
            "parry_chance": 0.10,
        },
        triggers=["parry.weapon_riposte_on_parry"],
    ),
    "katar": BaseItemDTO(
        id="katar",
        name_ru="Катар",
        narrative_description="Кулачно-колющий клинок, который требует близкого входа и вознаграждает точный пробивающий удар.",
        slot="main_hand",
        extra_slots=["off_hand"],
        type="weapon",
        damage_type="physical",
        related_skill="skill_fencing",
        allowed_materials=["ingots"],
        base_power=4,
        damage_spread=0.10,
        base_durability=42,
        narrative_tags=["katar", "dagger", "fencing", "piercing", "unique"],
        implicit_bonuses={
            "physical_crit_chance": 0.085,
            "weapon_armor_penetration_pct": 0.12,
            "parry_chance": 0.02,
        },
        triggers=["crit.weapon_flat_armor_bypass_crit"],
    ),
}

__all__ = ["FENCING_DB"]
