from src.backend.features.items.resources.schemas import BaseItemDTO

MACING_DB = {
    "hatchet": BaseItemDTO(
        id="hatchet",
        name_ru="Топорик",
        narrative_description="Короткий рабочий топор, которым удобно рубить с близкой дистанции и цеплять защиту противника.",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_macing",
        allowed_materials=["ingots"],
        base_power=5,
        damage_spread=0.22,
        base_durability=45,
        narrative_tags=["axe", "macing", "crude", "chop"],
        implicit_bonuses={
            "main_hand_armor_penetration_pct": 0.05,
            "physical_crit_chance": 0.03,
        },
        triggers=["crit.weapon_heavy_crit"],
    ),
    "battle_axe": BaseItemDTO(
        id="battle_axe",
        name_ru="Боевой топор",
        narrative_description="Тяжелое рубящее оружие с агрессивным балансом, созданное раскалывать защиту сильным ударом.",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_macing",
        allowed_materials=["ingots"],
        base_power=7,
        damage_spread=0.28,
        base_durability=55,
        narrative_tags=["axe", "macing", "brutal", "chop"],
        implicit_bonuses={
            "main_hand_armor_penetration_pct": 0.12,
            "physical_crit_chance": 0.04,
        },
        triggers=["crit.weapon_heavy_crit"],
    ),
    "mace": BaseItemDTO(
        id="mace",
        name_ru="Булава",
        narrative_description="Простая ударная булава для проламывания слабой брони и сбивания стойки.",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_macing",
        allowed_materials=["ingots"],
        base_power=6,
        damage_spread=0.18,
        base_durability=60,
        narrative_tags=["mace", "macing", "blunt", "armor_break"],
        implicit_bonuses={
            "main_hand_armor_penetration_pct": 0.10,
            "physical_crit_chance": 0.025,
        },
        triggers=["crit.weapon_impact_stun_crit"],
    ),
    "warhammer": BaseItemDTO(
        id="warhammer",
        name_ru="Боевой Молот",
        narrative_description="Двуручный молот, переносящий силу удара в сокрушительный импульс против брони и щитов.",
        slot="two_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_macing",
        allowed_materials=["ingots"],
        base_power=13,
        damage_spread=0.26,
        base_durability=90,
        narrative_tags=["hammer", "macing", "smash", "heavy"],
        implicit_bonuses={
            "main_hand_armor_penetration_pct": 0.22,
            "physical_crit_chance": 0.035,
            "parry_chance": 0.02,
            "evasion_penalty": -0.10,
        },
        triggers=["crit.weapon_impact_stun_crit"],
    ),
    "flail": BaseItemDTO(
        id="flail",
        name_ru="Кистень",
        narrative_description="Цепное ударное оружие, которое обходит жесткую линию щита и наказывает статичную защиту.",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_macing",
        allowed_materials=["ingots"],
        base_power=6,
        damage_spread=0.30,
        base_durability=50,
        narrative_tags=["flail", "macing", "chain", "shield_bypass"],
        implicit_bonuses={
            "main_hand_armor_penetration_pct": 0.08,
            "physical_crit_chance": 0.04,
        },
        triggers=["crit.weapon_shieldbreaker_crit"],
    ),
}

__all__ = ["MACING_DB"]
