from src.backend.features.items.resources.schemas import BaseItemDTO

OFFHAND_DB = {
    "shield": BaseItemDTO(
        id="shield",
        name_ru="Круглый щит",
        narrative_description="Средний щит для надежного контакта, удержания линии и короткого ответа корпусом.",
        slot="off_hand",
        type="armor",
        defense_type="physical",
        related_skill="skill_shield_mastery",
        allowed_materials=["woods", "ingots"],
        base_power=6,
        base_durability=80,
        damage_spread=0.0,
        narrative_tags=["shield", "block", "protection", "round_shield"],
        implicit_bonuses={
            "main_hand_accuracy_penalty": 0.035,
            "evasion_penalty": -0.12,
            "parry_penalty": -0.02,
        },
        triggers=["block.weapon_shield_bash_on_block"],
    ),
    "buckler": BaseItemDTO(
        id="buckler",
        name_ru="Баклер",
        narrative_description="Малый быстрый щит для частого контакта и ответного давления на близкой дистанции.",
        slot="off_hand",
        type="armor",
        defense_type="physical",
        related_skill="skill_shield_mastery",
        allowed_materials=["woods", "ingots"],
        base_power=3,
        base_durability=50,
        damage_spread=0.0,
        narrative_tags=["buckler", "shield", "small_shield"],
        implicit_bonuses={
            "main_hand_accuracy_penalty": 0.025,
            "evasion_penalty": -0.08,
            "parry_penalty": -0.01,
        },
        triggers=["block.weapon_shield_bash_on_block"],
    ),
    "kite_shield": BaseItemDTO(
        id="kite_shield",
        name_ru="Каплевидный щит",
        narrative_description="Тяжелый строевой щит: медленнее входит в контакт, зато плотнее принимает удар.",
        slot="off_hand",
        type="armor",
        defense_type="physical",
        related_skill="skill_shield_mastery",
        allowed_materials=["woods", "ingots"],
        base_power=8,
        base_durability=95,
        damage_spread=0.0,
        narrative_tags=["shield", "block", "protection", "kite_shield"],
        implicit_bonuses={
            "main_hand_accuracy_penalty": 0.05,
            "evasion_penalty": -0.20,
            "parry_penalty": -0.035,
        },
        triggers=["block.weapon_shield_bash_on_block"],
    ),
    "tower_shield": BaseItemDTO(
        id="tower_shield",
        name_ru="Башенный щит",
        narrative_description="Массивная переносная стенка: редко успевает в линию, но сильно гасит контакт.",
        slot="off_hand",
        type="armor",
        defense_type="physical",
        related_skill="skill_shield_mastery",
        allowed_materials=["woods", "ingots"],
        base_power=12,
        base_durability=120,
        damage_spread=0.0,
        narrative_tags=["shield", "block", "protection", "tower_shield", "heavy_shield"],
        implicit_bonuses={
            "main_hand_accuracy_penalty": 0.075,
            "evasion_penalty": -0.30,
            "parry_penalty": -0.05,
        },
        triggers=["block.weapon_shield_bash_on_block"],
    ),
}

__all__ = ["OFFHAND_DB"]
