from src.backend.features.items.resources.schemas import BaseItemDTO

POLEARMS_DB = {
    "spear": BaseItemDTO(
        id="spear",
        name_ru="Копье",
        narrative_description="Длинное древковое оружие для удержания дистанции, прямых уколов и работы из-за щита.",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_polearms",
        allowed_materials=["woods", "ingots"],
        base_power=7,
        damage_spread=0.14,
        base_durability=65,
        narrative_tags=["spear", "polearm", "reach", "piercing"],
        implicit_bonuses={
            "accuracy_penalty": 0.10,
            "main_hand_armor_penetration_pct": 0.08,
            "physical_crit_chance": 0.04,
            "parry_chance": 0.04,
        },
        triggers=["crit.weapon_piercing_crit"],
    ),
    "pike": BaseItemDTO(
        id="pike",
        name_ru="Пика",
        narrative_description="Очень длинное древковое оружие для жесткого удержания линии и глубокого пробивающего укола.",
        slot="two_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_polearms",
        allowed_materials=["woods", "ingots"],
        base_power=9,
        damage_spread=0.18,
        base_durability=70,
        narrative_tags=["pike", "polearm", "reach", "piercing"],
        implicit_bonuses={
            "accuracy_penalty": 0.16,
            "main_hand_armor_penetration_pct": 0.16,
            "physical_crit_chance": 0.05,
            "parry_chance": 0.05,
            "evasion_penalty": -0.06,
        },
        triggers=["crit.weapon_piercing_crit"],
    ),
    "halberd": BaseItemDTO(
        id="halberd",
        name_ru="Алебарда",
        narrative_description="Древковое оружие с топорным лезвием и острием, рассчитанное на сильный рубящий размен.",
        slot="two_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_polearms",
        allowed_materials=["woods", "ingots"],
        base_power=11,
        damage_spread=0.24,
        base_durability=80,
        narrative_tags=["halberd", "polearm", "cleave", "heavy"],
        implicit_bonuses={
            "accuracy_penalty": 0.20,
            "main_hand_armor_penetration_pct": 0.12,
            "physical_crit_chance": 0.06,
            "parry_chance": 0.04,
            "evasion_penalty": -0.08,
        },
        triggers=["crit.weapon_heavy_crit"],
    ),
    "quarterstaff": BaseItemDTO(
        id="quarterstaff",
        name_ru="Боевой посох",
        narrative_description="Прочный посох для оборонительного боя, перехватов и быстрых ударов с обеих сторон.",
        slot="two_hand",
        type="weapon",
        damage_type="physical",
        defense_type="physical",
        related_skill="skill_polearms",
        allowed_materials=["woods"],
        base_power=8,
        damage_spread=0.12,
        base_durability=100,
        narrative_tags=["staff", "polearm", "defensive", "monk"],
        implicit_bonuses={
            "accuracy_penalty": 0.08,
            "physical_crit_chance": 0.02,
            "parry_chance": 0.10,
        },
        triggers=["crit.weapon_impact_stun_crit"],
    ),
    "trident": BaseItemDTO(
        id="trident",
        name_ru="Трезубец",
        narrative_description="Трехзубое копье, которым удобно цеплять движение противника и валить его с ритма.",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_polearms",
        allowed_materials=["woods", "ingots"],
        base_power=7,
        damage_spread=0.16,
        base_durability=60,
        narrative_tags=["trident", "polearm", "control", "hook"],
        implicit_bonuses={
            "accuracy_penalty": 0.12,
            "main_hand_armor_penetration_pct": 0.07,
            "physical_crit_chance": 0.04,
            "parry_chance": 0.06,
        },
        triggers=["control.weapon_knockdown_hit"],
    ),
}

__all__ = ["POLEARMS_DB"]
