from src.backend.features.items.resources.schemas import BaseItemDTO

SWORDS_DB = {
    "sword": BaseItemDTO(
        id="sword",
        name_ru="Меч",
        narrative_description="Сбалансированное одноручное оружие для рубящих и колющих ударов без явных слабостей.",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_swords",
        allowed_materials=["ingots"],
        base_power=6,
        damage_spread=0.1,
        base_durability=60,
        narrative_tags=["sword", "balanced", "blade"],
        implicit_bonuses={
            "accuracy_penalty": 0.08,
            "physical_crit_chance": 0.05,
            "parry_chance": 0.10,
        },
        triggers=["crit.weapon_serrated_bleed_crit"],
    ),
    "longsword": BaseItemDTO(
        id="longsword",
        name_ru="Длинный меч",
        narrative_description="Удлиненный клинок с надежным балансом для стабильных рубящих ударов и уверенного парирования.",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_swords",
        allowed_materials=["ingots"],
        base_power=7,
        damage_spread=0.12,
        base_durability=70,
        narrative_tags=["longsword", "sword", "balanced", "blade"],
        implicit_bonuses={
            "accuracy_penalty": 0.10,
            "physical_crit_chance": 0.06,
            "parry_chance": 0.12,
        },
        triggers=["crit.weapon_serrated_bleed_crit"],
    ),
    "greatsword": BaseItemDTO(
        id="greatsword",
        name_ru="Двуручный меч",
        narrative_description="Тяжелый двуручный клинок, который жертвует скоростью ради широкого и сокрушительного удара.",
        slot="two_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_swords",
        allowed_materials=["ingots"],
        base_power=12,
        damage_spread=0.20,
        base_durability=85,
        narrative_tags=["greatsword", "sword", "two_handed", "cleave"],
        implicit_bonuses={
            "accuracy_penalty": 0.20,
            "physical_crit_chance": 0.06,
            "parry_chance": 0.06,
            "evasion_penalty": -0.08,
        },
        triggers=["crit.weapon_heavy_crit"],
    ),
    "katana": BaseItemDTO(
        id="katana",
        name_ru="Катана",
        narrative_description="Изогнутый двуручный клинок, рассчитанный на быстрый чистый разрез и точный ритм боя.",
        slot="two_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_swords",
        allowed_materials=["ingots"],
        base_power=10,
        damage_spread=0.1,
        base_durability=65,
        narrative_tags=["katana", "samurai", "fast_blade"],
        implicit_bonuses={
            "accuracy_penalty": 0.12,
            "physical_crit_chance": 0.15,
            "parry_chance": 0.08,
            "bleed_damage_bonus": 0.20,
        },
        triggers=["crit.weapon_serrated_bleed_crit"],
    ),
    "scimitar": BaseItemDTO(
        id="scimitar",
        name_ru="Сабля",
        narrative_description="Изогнутый одноручный клинок для быстрых проходящих ударов и игры на темпе.",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_swords",
        allowed_materials=["ingots"],
        base_power=6,
        damage_spread=0.09,
        base_durability=55,
        narrative_tags=["scimitar", "sword", "flow", "fast_blade"],
        implicit_bonuses={
            "accuracy_penalty": 0.07,
            "physical_crit_chance": 0.09,
            "parry_chance": 0.07,
        },
        triggers=["crit.weapon_precision_crit"],
    ),
}

__all__ = ["SWORDS_DB"]
