from src.backend.features.items.resources.schemas import BaseItemDTO

SWORDS_DB = {
    "sword": BaseItemDTO(
        id="sword",
        name_ru="Меч",
        narrative_description="Сбалансированное одноручное оружие для рубящих и колющих ударов без явных слабостей.",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_swords",
        allowed_materials=["ingots"],
        base_power=7,
        damage_spread=0.1,
        base_durability=60,
        narrative_tags=["sword", "balanced", "blade"],
        implicit_bonuses={
            "main_hand_accuracy_penalty": 0.04,
            "physical_crit_chance": 0.03,
            "parry_chance": 0.04,
        },
        triggers=["crit.weapon_precision_crit"],
    ),
    "longsword": BaseItemDTO(
        id="longsword",
        name_ru="Длинный меч",
        narrative_description="Удлиненный клинок с надежным балансом для стабильных рубящих ударов и уверенного парирования.",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_swords",
        allowed_materials=["ingots"],
        base_power=8,
        damage_spread=0.12,
        base_durability=70,
        narrative_tags=["longsword", "sword", "balanced", "blade"],
        implicit_bonuses={
            "main_hand_accuracy_penalty": 0.05,
            "physical_crit_chance": 0.03,
            "parry_chance": 0.045,
        },
        triggers=["crit.weapon_heavy_crit"],
    ),
    "greatsword": BaseItemDTO(
        id="greatsword",
        name_ru="Двуручный меч",
        narrative_description="Тяжелый двуручный клинок, который жертвует скоростью ради широкого и сокрушительного удара.",
        slot="two_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_swords",
        allowed_materials=["ingots"],
        base_power=11,
        damage_spread=0.20,
        base_durability=85,
        narrative_tags=["greatsword", "sword", "two_handed", "cleave"],
        implicit_bonuses={
            "main_hand_accuracy_penalty": 0.12,
            "physical_crit_chance": 0.05,
            "parry_chance": 0.025,
            "evasion_penalty": -0.08,
        },
        triggers=["crit.weapon_heavy_crit"],
    ),
    "katana": BaseItemDTO(
        id="katana",
        name_ru="Катана",
        narrative_description="Изогнутый двуручный клинок, рассчитанный на быстрый чистый разрез и точный ритм боя.",
        slot="two_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_swords",
        allowed_materials=["ingots"],
        base_power=11,
        damage_spread=0.1,
        base_durability=65,
        narrative_tags=["katana", "samurai", "fast_blade"],
        implicit_bonuses={
            "main_hand_accuracy_penalty": 0.08,
            "physical_crit_chance": 0.05,
            "parry_chance": 0.035,
        },
        triggers=["crit.weapon_precision_crit"],
    ),
    "scimitar": BaseItemDTO(
        id="scimitar",
        name_ru="Сабля",
        narrative_description="Изогнутый одноручный клинок для быстрых проходящих ударов и игры на темпе.",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_swords",
        allowed_materials=["ingots"],
        base_power=7,
        damage_spread=0.09,
        base_durability=55,
        narrative_tags=["scimitar", "sword", "flow", "fast_blade"],
        implicit_bonuses={
            "main_hand_accuracy_penalty": 0.035,
            "physical_crit_chance": 0.03,
            "parry_chance": 0.03,
        },
        triggers=["crit.weapon_precision_crit"],
    ),
    "flamberge": BaseItemDTO(
        id="flamberge",
        name_ru="Фламберг",
        narrative_description="Двуручный меч с волнистым клинком, который рвет рану на критическом разрезе.",
        slot="two_hand",
        type="weapon",
        damage_type="physical",
        related_skill="skill_swords",
        allowed_materials=["ingots"],
        base_power=11,
        damage_spread=0.18,
        base_durability=80,
        narrative_tags=["flamberge", "sword", "two_handed", "serrated", "blade"],
        implicit_bonuses={
            "main_hand_accuracy_penalty": 0.11,
            "physical_crit_chance": 0.05,
            "parry_chance": 0.025,
            "evasion_penalty": -0.06,
        },
        triggers=["crit.weapon_serrated_bleed_crit"],
    ),
}

__all__ = ["SWORDS_DB"]
