from src.backend.features.game_catalog.combat.resources.basic_exchanges.schemas import (
    BasicExchangeCatalogEntryDTO,
    BasicExchangeTechnicalDTO,
)
from src.backend.features.game_catalog.combat.resources.common.descriptions import (
    CombatEventTextSetDTO,
    build_combat_description,
)

_BEAST_FALLBACK = CombatEventTextSetDTO(
    use=["{source} атакует {target}"],
    hit=["и попадает, нанося {damage} урона"],
    crit=["и наносит особенно сильный удар по {target}"],
    miss=["но промахивается"],
    dodge=["но {target} уклоняется"],
    parry=["но {target} отбивает удар"],
    block=["но {target} закрывается"],
)


def _make_entry(
    exchange_id: str,
    skill_key: str,
    source_type: str,
    weapon_class: str,
    hand: str,
    display_name: str,
    short_description: str,
    humanoid_event_texts: CombatEventTextSetDTO,
    beast_event_texts: CombatEventTextSetDTO | None = None,
) -> BasicExchangeCatalogEntryDTO:
    return BasicExchangeCatalogEntryDTO(
        key=f"combat.basic_exchange.{exchange_id}",
        technical=BasicExchangeTechnicalDTO(
            exchange_id=exchange_id,
            skill_key=skill_key,
            source_type=source_type,
            weapon_class=weapon_class,
            hand=hand,
        ),
        descriptive=build_combat_description(
            resource_type="basic_exchange",
            resource_id=exchange_id,
            display_name=display_name,
            short_description=short_description,
            humanoid_event_texts=humanoid_event_texts,
            beast_event_texts=beast_event_texts or _BEAST_FALLBACK,
        ),
    )


WEAPON_MASTERY_BASIC_EXCHANGES_CATALOG: dict[str, BasicExchangeCatalogEntryDTO] = {
    # ─── SWORDS ───────────────────────────────────────────────────────────────
    "skill_swords.main_hand": _make_entry(
        exchange_id="skill_swords.main_hand",
        skill_key="skill_swords",
        source_type="main_hand",
        weapon_class="swords",
        hand="main",
        display_name="Удар мечом",
        short_description="Базовый размен с оружием класса мечи.",
        humanoid_event_texts=CombatEventTextSetDTO(
            use=["{source} ведёт {weapon} по линии атаки на {target}"],
            hit=["и задевает {target}, нанося {damage} урона"],
            crit=["и ловит открытую линию {target}, нанося {damage} урона"],
            miss=["но удар проходит мимо {target}"],
            dodge=["но {target} уходит с линии атаки"],
            parry=["но {target} отводит клинок"],
            block=["но {target} принимает удар на защиту"],
        ),
    ),
    "skill_swords.off_hand": _make_entry(
        exchange_id="skill_swords.off_hand",
        skill_key="skill_swords",
        source_type="off_hand",
        weapon_class="swords",
        hand="off",
        display_name="Удар мечом (левая рука)",
        short_description="Удар вспомогательным мечом.",
        humanoid_event_texts=CombatEventTextSetDTO(
            use=["{source} бьёт {target} вторым клинком"],
            hit=["и достаёт {target}, нанося {damage} урона"],
            crit=["и пронзает незащищённый фланг {target}"],
            miss=["но удар уходит в пустоту"],
            dodge=["но {target} успевает убрать корпус"],
            parry=["но {target} перехватывает второй клинок"],
            block=["но {target} закрывается от удара"],
        ),
    ),
    # ─── FENCING ──────────────────────────────────────────────────────────────
    "skill_fencing.main_hand": _make_entry(
        exchange_id="skill_fencing.main_hand",
        skill_key="skill_fencing",
        source_type="main_hand",
        weapon_class="fencing",
        hand="main",
        display_name="Выпад",
        short_description="Базовый выпад колющим оружием.",
        humanoid_event_texts=CombatEventTextSetDTO(
            use=["{source} делает выпад клинком в сторону {target}"],
            hit=["и клинок находит цель, нанося {damage} урона"],
            crit=["и острие точно входит в щель доспеха {target}"],
            miss=["но {target} уходит с линии выпада"],
            dodge=["но {target} скользит в сторону"],
            parry=["но {target} отводит клинок в сторону"],
            block=["но {target} подставляет защиту"],
        ),
    ),
    "skill_fencing.off_hand": _make_entry(
        exchange_id="skill_fencing.off_hand",
        skill_key="skill_fencing",
        source_type="off_hand",
        weapon_class="fencing",
        hand="off",
        display_name="Выпад (левая рука)",
        short_description="Выпад вспомогательным колющим оружием.",
        humanoid_event_texts=CombatEventTextSetDTO(
            use=["{source} тычет {target} кинжалом с левой руки"],
            hit=["и задевает {target} на {damage} урона"],
            crit=["и вгоняет клинок в уязвимое место {target}"],
            miss=["но {target} уклоняется в последний миг"],
            dodge=["но {target} отступает назад"],
            parry=["но {target} успевает поймать руку {source}"],
            block=["но {target} прикрывается от укола"],
        ),
    ),
    # ─── POLEARMS ─────────────────────────────────────────────────────────────
    "skill_polearms.main_hand": _make_entry(
        exchange_id="skill_polearms.main_hand",
        skill_key="skill_polearms",
        source_type="main_hand",
        weapon_class="polearms",
        hand="main",
        display_name="Удар древковым",
        short_description="Базовый удар древковым оружием.",
        humanoid_event_texts=CombatEventTextSetDTO(
            use=["{source} заносит {weapon} для удара по {target}"],
            hit=["и обрушивает его на {target}, нанося {damage} урона"],
            crit=["и наносит сокрушительный удар по {target}"],
            miss=["но {target} отступает за пределы дистанции"],
            dodge=["но {target} ныряет под дугу удара"],
            parry=["но {target} отводит древко в сторону"],
            block=["но {target} подставляет щит под удар"],
        ),
    ),
    # ─── MACING ───────────────────────────────────────────────────────────────
    "skill_macing.main_hand": _make_entry(
        exchange_id="skill_macing.main_hand",
        skill_key="skill_macing",
        source_type="main_hand",
        weapon_class="macing",
        hand="main",
        display_name="Удар дробящим",
        short_description="Базовый удар дробящим оружием.",
        humanoid_event_texts=CombatEventTextSetDTO(
            use=["{source} замахивается {weapon} на {target}"],
            hit=["и бьёт {target} в полную силу, нанося {damage} урона"],
            crit=["и дробит защиту {target}, нанося {damage} урона"],
            miss=["но удар проходит мимо цели"],
            dodge=["но {target} отскакивает в сторону"],
            parry=["но {target} гасит удар"],
            block=["но {target} принимает удар на щит"],
        ),
    ),
    "skill_macing.off_hand": _make_entry(
        exchange_id="skill_macing.off_hand",
        skill_key="skill_macing",
        source_type="off_hand",
        weapon_class="macing",
        hand="off",
        display_name="Удар дробящим (левая рука)",
        short_description="Удар вспомогательным дробящим оружием.",
        humanoid_event_texts=CombatEventTextSetDTO(
            use=["{source} бьёт {target} с левой руки"],
            hit=["и попадает, нанося {damage} урона"],
            crit=["и наносит хлёсткий удар по {target}"],
            miss=["но {target} уходит от удара"],
            dodge=["но {target} шагает назад"],
            parry=["но {target} блокирует оружие {source}"],
            block=["но {target} закрывается щитом"],
        ),
    ),
    # ─── ARCHERY ──────────────────────────────────────────────────────────────
    "skill_archery.main_hand": _make_entry(
        exchange_id="skill_archery.main_hand",
        skill_key="skill_archery",
        source_type="main_hand",
        weapon_class="archery",
        hand="main",
        display_name="Выстрел",
        short_description="Прицельный выстрел из дистанционного оружия.",
        humanoid_event_texts=CombatEventTextSetDTO(
            use=["{source} берёт прицел на {target}"],
            hit=["и снаряд находит цель, нанося {damage} урона"],
            crit=["и выстрел точно бьёт в уязвимое место {target}, нанося {damage} урона"],
            miss=["но выстрел уходит в сторону"],
            dodge=["но {target} уходит с линии огня"],
            parry=["но {target} отбивает снаряд"],
            block=["но {target} прикрывается щитом"],
        ),
        beast_event_texts=CombatEventTextSetDTO(
            use=["{source} прицеливается в {target}"],
            hit=["и попадает, нанося {damage} урона"],
            crit=["и бьёт точно по {target}, нанося {damage} урона"],
            miss=["но промахивается"],
            dodge=["но {target} отпрыгивает"],
            parry=["но {target} уклоняется от снаряда"],
            block=["но снаряд отклоняется"],
        ),
    ),
    # ─── UNARMED ──────────────────────────────────────────────────────────────
    "skill_unarmed.main_hand": _make_entry(
        exchange_id="skill_unarmed.main_hand",
        skill_key="skill_unarmed",
        source_type="main_hand",
        weapon_class="unarmed",
        hand="main",
        display_name="Удар без оружия",
        short_description="Атака кулаком, ногой или иным телесным оружием.",
        humanoid_event_texts=CombatEventTextSetDTO(
            use=["{source} атакует {target} без оружия"],
            hit=["и наносит удар, причиняя {damage} урона"],
            crit=["и пробивает защиту {target}, нанося {damage} урона"],
            miss=["но {target} уходит от удара"],
            dodge=["но {target} скользит мимо"],
            parry=["но {target} перехватывает удар"],
            block=["но {target} принимает удар на блок"],
        ),
        beast_event_texts=CombatEventTextSetDTO(
            use=["{source} бросается на {target}"],
            hit=["и попадает, нанося {damage} урона"],
            crit=["и наносит сильный удар по {target}"],
            miss=["но промахивается"],
            dodge=["но {target} уходит"],
            parry=["но {target} встречает удар"],
            block=["но {target} закрывается"],
        ),
    ),
    "skill_unarmed.off_hand": _make_entry(
        exchange_id="skill_unarmed.off_hand",
        skill_key="skill_unarmed",
        source_type="off_hand",
        weapon_class="unarmed",
        hand="off",
        display_name="Удар без оружия (левая рука)",
        short_description="Атака второй рукой или ногой.",
        humanoid_event_texts=CombatEventTextSetDTO(
            use=["{source} бьёт {target} с левой"],
            hit=["и попадает, нанося {damage} урона"],
            crit=["и достигает болезненного места на {target}"],
            miss=["но {target} уходит от удара"],
            dodge=["но {target} делает шаг назад"],
            parry=["но {target} ловит руку {source}"],
            block=["но {target} прикрывается"],
        ),
    ),
}
