from src.backend.resources.game_data.items.schemas import BaseItemDTO

SWORDS_DB = {
    "dagger": BaseItemDTO(
        id="dagger",
        name_ru="Кинжал",
        slot="main_hand",
        extra_slots=["off_hand"],
        type="weapon",
        damage_type="physical",
        allowed_materials=["ingots"],
        base_power=3,
        damage_spread=0.05,
        base_durability=40,
        narrative_tags=["dagger", "swift", "stealth"],
        implicit_bonuses={
            "physical_crit_chance": 0.15,
            "physical_pierce_chance": 0.15,
            "physical_accuracy": 0.10,
        },
        triggers=["sword_crit_bleed"],
    ),
    "knife": BaseItemDTO(
        id="knife",
        name_ru="Нож",
        slot="main_hand",
        extra_slots=["off_hand"],
        type="weapon",
        damage_type="physical",
        allowed_materials=["ingots"],
        base_power=2,
        damage_spread=0.1,
        base_durability=35,
        narrative_tags=["knife", "tool", "simple"],
        implicit_bonuses={
            "physical_crit_chance": 0.05,
        },
        triggers=["sword_crit_bleed"],
    ),
    "tanto": BaseItemDTO(
        id="tanto",
        name_ru="Танто",
        slot="main_hand",
        extra_slots=["off_hand"],
        type="weapon",
        damage_type="physical",
        allowed_materials=["ingots"],
        base_power=4,
        damage_spread=0.05,
        base_durability=45,
        narrative_tags=["tanto", "samurai", "short"],
        implicit_bonuses={
            "physical_crit_chance": 0.10,
            "physical_pierce_chance": 0.10,
        },
        triggers=["sword_crit_bleed"],
    ),
    "wakizashi": BaseItemDTO(
        id="wakizashi",
        name_ru="Вакидзаси",
        slot="main_hand",
        extra_slots=["off_hand"],
        type="weapon",
        damage_type="physical",
        allowed_materials=["ingots"],
        base_power=4,
        damage_spread=0.1,
        base_durability=55,
        narrative_tags=["wakizashi", "samurai", "blade"],
        implicit_bonuses={
            "physical_accuracy": 0.15,
            "parry_chance": 0.10,
            "counter_attack_chance": 0.05,
        },
        triggers=["sword_crit_bleed"],
    ),
    "sword": BaseItemDTO(
        id="sword",
        name_ru="Меч",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        allowed_materials=["ingots"],
        base_power=5,
        damage_spread=0.1,
        base_durability=60,
        narrative_tags=["sword", "balanced", "blade"],
        implicit_bonuses={
            "physical_accuracy": 0.10,
            "parry_chance": 0.10,
        },
        triggers=["sword_crit_bleed"],
    ),
    "shortsword": BaseItemDTO(
        id="shortsword",
        name_ru="Короткий меч",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        allowed_materials=["ingots"],
        base_power=4,
        damage_spread=0.1,
        base_durability=55,
        narrative_tags=["sword", "short", "agile"],
        implicit_bonuses={
            "physical_accuracy": 0.10,
            "attack_speed": 0.05,
        },
        triggers=["sword_crit_bleed"],
    ),
    "scimitar": BaseItemDTO(
        id="scimitar",
        name_ru="Скимитар",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        allowed_materials=["ingots"],
        base_power=6,
        damage_spread=0.1,
        base_durability=60,
        narrative_tags=["scimitar", "curved", "slash"],
        implicit_bonuses={
            "bleed_chance": 0.10,
            "parry_chance": 0.05,
        },
        triggers=["sword_crit_bleed"],
    ),
    "longsword": BaseItemDTO(
        id="longsword",
        name_ru="Длинный меч",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        allowed_materials=["ingots"],
        base_power=7,
        damage_spread=0.1,
        base_durability=65,
        narrative_tags=["sword", "long", "knight"],
        implicit_bonuses={
            "parry_chance": 0.10,
            "physical_damage_bonus": 0.05,
        },
        triggers=["sword_crit_bleed"],
    ),
    "rapier": BaseItemDTO(
        id="rapier",
        name_ru="Рапира",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        allowed_materials=["ingots"],
        base_power=4,
        damage_spread=0.05,
        base_durability=45,
        narrative_tags=["rapier", "fencing", "piercing"],
        implicit_bonuses={
            "physical_accuracy": 0.20,
            "physical_pierce_chance": 0.10,
            "parry_chance": 0.05,
        },
        triggers=["sword_crit_bleed"],
    ),
    "greatsword": BaseItemDTO(
        id="greatsword",
        name_ru="Клеймор",
        slot="two_hand",
        type="weapon",
        damage_type="physical",
        allowed_materials=["ingots"],
        base_power=10,
        damage_spread=0.15,
        base_durability=70,
        narrative_tags=["greatsword", "massive", "cleave"],
        implicit_bonuses={
            "parry_chance": 0.15,
            "physical_damage_bonus": 0.15,
        },
        triggers=["sword_crit_bleed"],
    ),
    "katana": BaseItemDTO(
        id="katana",
        name_ru="Катана",
        slot="two_hand",
        type="weapon",
        damage_type="physical",
        allowed_materials=["ingots"],
        base_power=9,
        damage_spread=0.1,
        base_durability=65,
        narrative_tags=["katana", "samurai", "fast_blade"],
        implicit_bonuses={
            "physical_crit_chance": 0.15,
            "bleed_damage_bonus": 0.20,
            "physical_accuracy": 0.10,
        },
        triggers=["sword_crit_bleed"],
    ),
}
