from src.backend.features.world.resources.static.d4_types import StaticLocationMap

# D4 outer 5x5 block: X 55..59, Y 50..54.
STATIC_LOCATIONS: StaticLocationMap = {(55, 50): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['east'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Двор восточных корпусов',
                        'description': 'Узел ручной топологии в районе: восточный жилой разлом. Видимые ориентиры: '
                                       'жилые корпуса, дворы проверки и разорванные проходы за восточной аркой. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (56, 50): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'buildable_plot',
                      'terrain_type': 'ruined_foundation',
                      'topology_tags': ['buildable_plot',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls'],
                      'buildable': True,
                      'buildable_kind': 'house_plot'},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'buildable_plot',
            'terrain_type': 'ruined_foundation',
            'content': {'title': 'Пристенный жилой проход',
                        'description': 'Узел ручной топологии в районе: восточный жилой разлом. Видимые ориентиры: '
                                       'жилые корпуса, дворы проверки и разорванные проходы за восточной аркой. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'buildable_plot',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (57, 50): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Площадка проверки',
                        'description': 'Узел ручной топологии в районе: восточный жилой разлом. Видимые ориентиры: '
                                       'жилые корпуса, дворы проверки и разорванные проходы за восточной аркой. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (58, 50): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'buildable_plot',
                      'terrain_type': 'ruined_foundation',
                      'topology_tags': ['buildable_plot',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls'],
                      'buildable': True,
                      'buildable_kind': 'house_plot'},
            'movement_profile': {'has_road': False, 'blocked_exits': ['east'], 'travel_cost': 1.25},
            'node_type': 'buildable_plot',
            'terrain_type': 'ruined_foundation',
            'content': {'title': 'Двор снабжения',
                        'description': 'Узел ручной топологии в районе: восточный жилой разлом. Видимые ориентиры: '
                                       'жилые корпуса, дворы проверки и разорванные проходы за восточной аркой. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'buildable_plot',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (59, 50): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'outer_wall_walk',
                      'terrain_type': 'outer_monolith_wall_walk',
                      'topology_tags': ['outer_wall_walk',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['east'], 'travel_cost': 1.0},
            'node_type': 'outer_wall_walk',
            'terrain_type': 'outer_monolith_wall_walk',
            'content': {'title': 'Ход внешней монолитной стены',
                        'description': 'Клетка у внешней стены района: восточный жилой разлом. Наружная сторона '
                                       'закрыта красным контуром карты; движение идет только по отмеченным проходам '
                                       'внутри D4.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'outer_wall_walk',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (55, 51): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['west'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Площадка проверки',
                        'description': 'Узел ручной топологии в районе: восточный жилой разлом. Видимые ориентиры: '
                                       'жилые корпуса, дворы проверки и разорванные проходы за восточной аркой. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (56, 51): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Двор снабжения',
                        'description': 'Узел ручной топологии в районе: восточный жилой разлом. Видимые ориентиры: '
                                       'жилые корпуса, дворы проверки и разорванные проходы за восточной аркой. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (57, 51): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Улица между блоками',
                        'description': 'Узел ручной топологии в районе: восточный жилой разлом. Видимые ориентиры: '
                                       'жилые корпуса, дворы проверки и разорванные проходы за восточной аркой. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (58, 51): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['west'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Двор восточных корпусов',
                        'description': 'Узел ручной топологии в районе: восточный жилой разлом. Видимые ориентиры: '
                                       'жилые корпуса, дворы проверки и разорванные проходы за восточной аркой. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (59, 51): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'outer_wall_walk',
                      'terrain_type': 'outer_monolith_wall_walk',
                      'topology_tags': ['outer_wall_walk',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['east'], 'travel_cost': 1.0},
            'node_type': 'outer_wall_walk',
            'terrain_type': 'outer_monolith_wall_walk',
            'content': {'title': 'Ход внешней монолитной стены',
                        'description': 'Клетка у внешней стены района: восточный жилой разлом. Наружная сторона '
                                       'закрыта красным контуром карты; движение идет только по отмеченным проходам '
                                       'внутри D4.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'outer_wall_walk',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (55, 52): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'main_road',
                      'terrain_type': 'ruin_road_main',
                      'topology_tags': ['main_road',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': True, 'blocked_exits': ['north'], 'travel_cost': 1.0},
            'node_type': 'main_road',
            'terrain_type': 'ruin_road_main',
            'content': {'title': 'Восточная дорога старого города',
                        'description': 'Поперечная дорога от внутреннего кольца к восточным воротам. Закрытые фасады и '
                                       'завалы не считаются проходами.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'main_road',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (56, 52): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'main_road',
                      'terrain_type': 'ruin_road_main',
                      'topology_tags': ['main_road',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': True, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.0},
            'node_type': 'main_road',
            'terrain_type': 'ruin_road_main',
            'content': {'title': 'Восточная дорога старого города',
                        'description': 'Поперечная дорога от внутреннего кольца к восточным воротам. Закрытые фасады и '
                                       'завалы не считаются проходами.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'main_road',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (57, 52): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'main_road',
                      'terrain_type': 'ruin_road_main',
                      'topology_tags': ['main_road',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': True, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.0},
            'node_type': 'main_road',
            'terrain_type': 'ruin_road_main',
            'content': {'title': 'Восточная дорога старого города',
                        'description': 'Поперечная дорога от внутреннего кольца к восточным воротам. Закрытые фасады и '
                                       'завалы не считаются проходами.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'main_road',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (58, 52): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'main_road',
                      'terrain_type': 'ruin_road_main',
                      'topology_tags': ['main_road',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': True, 'blocked_exits': ['south'], 'travel_cost': 1.0},
            'node_type': 'main_road',
            'terrain_type': 'ruin_road_main',
            'content': {'title': 'Восточная дорога старого города',
                        'description': 'Поперечная дорога от внутреннего кольца к восточным воротам. Закрытые фасады и '
                                       'завалы не считаются проходами.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'main_road',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (59, 52): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'sealed_gate',
                      'terrain_type': 'city_gate_outer',
                      'topology_tags': ['sealed_gate',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls'],
                      'is_gate': True,
                      'gate_direction': 'east',
                      'exit_locked': True,
                      'unlock_condition': 'world_gate_unlock'},
            'movement_profile': {'has_road': True,
                                 'blocked_exits': [],
                                 'travel_cost': 1.0,
                                 'gated_exits': {'east': {'kind': 'outer_city_gate',
                                                          'state': 'locked',
                                                          'unlock_condition': 'world_gate_unlock',
                                                          'tags': ['city_gate',
                                                                   'sealed_gate',
                                                                   'old_capital_outer_wall']}}},
            'node_type': 'sealed_gate',
            'terrain_type': 'city_gate_outer',
            'content': {'title': 'Восточные внешние ворота D4',
                        'description': 'Ворота на границе региона. Внутренний путь остается частью текущей карты, а '
                                       'выход наружу закрыт до перехода в соседний регион.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'sealed_gate',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls',
                                             'gate',
                                             'locked_exit']}},
 (55, 53): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['west'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Пристенный жилой проход',
                        'description': 'Узел ручной топологии в районе: восточный жилой разлом. Видимые ориентиры: '
                                       'жилые корпуса, дворы проверки и разорванные проходы за восточной аркой. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (56, 53): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Площадка проверки',
                        'description': 'Узел ручной топологии в районе: восточный жилой разлом. Видимые ориентиры: '
                                       'жилые корпуса, дворы проверки и разорванные проходы за восточной аркой. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (57, 53): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Двор снабжения',
                        'description': 'Узел ручной топологии в районе: восточный жилой разлом. Видимые ориентиры: '
                                       'жилые корпуса, дворы проверки и разорванные проходы за восточной аркой. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (58, 53): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['west'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Улица между блоками',
                        'description': 'Узел ручной топологии в районе: восточный жилой разлом. Видимые ориентиры: '
                                       'жилые корпуса, дворы проверки и разорванные проходы за восточной аркой. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (59, 53): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'outer_wall_walk',
                      'terrain_type': 'outer_monolith_wall_walk',
                      'topology_tags': ['outer_wall_walk',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['east'], 'travel_cost': 1.0},
            'node_type': 'outer_wall_walk',
            'terrain_type': 'outer_monolith_wall_walk',
            'content': {'title': 'Ход внешней монолитной стены',
                        'description': 'Клетка у внешней стены района: восточный жилой разлом. Наружная сторона '
                                       'закрыта красным контуром карты; движение идет только по отмеченным проходам '
                                       'внутри D4.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'outer_wall_walk',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (55, 54): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['east'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Двор снабжения',
                        'description': 'Узел ручной топологии в районе: восточный жилой разлом. Видимые ориентиры: '
                                       'жилые корпуса, дворы проверки и разорванные проходы за восточной аркой. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (56, 54): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'buildable_plot',
                      'terrain_type': 'ruined_foundation',
                      'topology_tags': ['buildable_plot',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls'],
                      'buildable': True,
                      'buildable_kind': 'house_plot'},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'buildable_plot',
            'terrain_type': 'ruined_foundation',
            'content': {'title': 'Улица между блоками',
                        'description': 'Узел ручной топологии в районе: восточный жилой разлом. Видимые ориентиры: '
                                       'жилые корпуса, дворы проверки и разорванные проходы за восточной аркой. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'buildable_plot',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (57, 54): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Двор восточных корпусов',
                        'description': 'Узел ручной топологии в районе: восточный жилой разлом. Видимые ориентиры: '
                                       'жилые корпуса, дворы проверки и разорванные проходы за восточной аркой. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (58, 54): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'buildable_plot',
                      'terrain_type': 'ruined_foundation',
                      'topology_tags': ['buildable_plot',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls'],
                      'buildable': True,
                      'buildable_kind': 'house_plot'},
            'movement_profile': {'has_road': False, 'blocked_exits': ['east'], 'travel_cost': 1.25},
            'node_type': 'buildable_plot',
            'terrain_type': 'ruined_foundation',
            'content': {'title': 'Пристенный жилой проход',
                        'description': 'Узел ручной топологии в районе: восточный жилой разлом. Видимые ориентиры: '
                                       'жилые корпуса, дворы проверки и разорванные проходы за восточной аркой. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'buildable_plot',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}},
 (59, 54): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_2_1',
                      'node_type': 'outer_wall_walk',
                      'terrain_type': 'outer_monolith_wall_walk',
                      'topology_tags': ['outer_wall_walk',
                                        'residential_ruins',
                                        'overgrown_courtyards',
                                        'biomass_pressure',
                                        'cracked_halls']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['east'], 'travel_cost': 1.0},
            'node_type': 'outer_wall_walk',
            'terrain_type': 'outer_monolith_wall_walk',
            'content': {'title': 'Ход внешней монолитной стены',
                        'description': 'Клетка у внешней стены района: восточный жилой разлом. Наружная сторона '
                                       'закрыта красным контуром карты; движение идет только по отмеченным проходам '
                                       'внутри D4.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'outer_wall_walk',
                                             'residential_ruins',
                                             'overgrown_courtyards',
                                             'biomass_pressure',
                                             'cracked_halls']}}}
