from src.backend.features.world.resources.static.d4_types import StaticLocationMap

# D4 outer 5x5 block: X 45..49, Y 45..49.
STATIC_LOCATIONS: StaticLocationMap = {(45, 45): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'outer_wall_walk',
                      'terrain_type': 'outer_monolith_wall_walk',
                      'topology_tags': ['outer_wall_walk', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'west'], 'travel_cost': 1.0},
            'node_type': 'outer_wall_walk',
            'terrain_type': 'outer_monolith_wall_walk',
            'content': {'title': 'Ход внешней монолитной стены',
                        'description': 'Клетка у внешней стены района: северо-западный бастион. Наружная сторона '
                                       'закрыта красным контуром карты; движение идет только по отмеченным проходам '
                                       'внутри D4.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'outer_wall_walk',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (46, 45): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'outer_wall_walk',
                      'terrain_type': 'outer_monolith_wall_walk',
                      'topology_tags': ['outer_wall_walk', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north'], 'travel_cost': 1.0},
            'node_type': 'outer_wall_walk',
            'terrain_type': 'outer_monolith_wall_walk',
            'content': {'title': 'Ход внешней монолитной стены',
                        'description': 'Клетка у внешней стены района: северо-западный бастион. Наружная сторона '
                                       'закрыта красным контуром карты; движение идет только по отмеченным проходам '
                                       'внутри D4.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'outer_wall_walk',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (47, 45): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'outer_wall_walk',
                      'terrain_type': 'outer_monolith_wall_walk',
                      'topology_tags': ['outer_wall_walk', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north'], 'travel_cost': 1.0},
            'node_type': 'outer_wall_walk',
            'terrain_type': 'outer_monolith_wall_walk',
            'content': {'title': 'Ход внешней монолитной стены',
                        'description': 'Клетка у внешней стены района: северо-западный бастион. Наружная сторона '
                                       'закрыта красным контуром карты; движение идет только по отмеченным проходам '
                                       'внутри D4.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'outer_wall_walk',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (48, 45): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'outer_wall_walk',
                      'terrain_type': 'outer_monolith_wall_walk',
                      'topology_tags': ['outer_wall_walk', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north'], 'travel_cost': 1.0},
            'node_type': 'outer_wall_walk',
            'terrain_type': 'outer_monolith_wall_walk',
            'content': {'title': 'Ход внешней монолитной стены',
                        'description': 'Клетка у внешней стены района: северо-западный бастион. Наружная сторона '
                                       'закрыта красным контуром карты; движение идет только по отмеченным проходам '
                                       'внутри D4.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'outer_wall_walk',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (49, 45): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'outer_wall_walk',
                      'terrain_type': 'outer_monolith_wall_walk',
                      'topology_tags': ['outer_wall_walk', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north'], 'travel_cost': 1.0},
            'node_type': 'outer_wall_walk',
            'terrain_type': 'outer_monolith_wall_walk',
            'content': {'title': 'Ход внешней монолитной стены',
                        'description': 'Клетка у внешней стены района: северо-западный бастион. Наружная сторона '
                                       'закрыта красным контуром карты; движение идет только по отмеченным проходам '
                                       'внутри D4.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'outer_wall_walk',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (45, 46): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'outer_wall_walk',
                      'terrain_type': 'outer_monolith_wall_walk',
                      'topology_tags': ['outer_wall_walk', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['west'], 'travel_cost': 1.0},
            'node_type': 'outer_wall_walk',
            'terrain_type': 'outer_monolith_wall_walk',
            'content': {'title': 'Ход внешней монолитной стены',
                        'description': 'Клетка у внешней стены района: северо-западный бастион. Наружная сторона '
                                       'закрыта красным контуром карты; движение идет только по отмеченным проходам '
                                       'внутри D4.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'outer_wall_walk',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (46, 46): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'buildable_plot',
                      'terrain_type': 'ruined_foundation',
                      'topology_tags': ['buildable_plot', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure'],
                      'buildable': True,
                      'buildable_kind': 'house_plot'},
            'movement_profile': {'has_road': False, 'blocked_exits': ['east'], 'travel_cost': 1.25},
            'node_type': 'buildable_plot',
            'terrain_type': 'ruined_foundation',
            'content': {'title': 'Обходной проход',
                        'description': 'Узел ручной топологии в районе: северо-западный бастион. Видимые ориентиры: '
                                       'караульные дворы, низкие арки и сломанные участки оборонной линии. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'buildable_plot',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (47, 46): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Каменный карман',
                        'description': 'Узел ручной топологии в районе: северо-западный бастион. Видимые ориентиры: '
                                       'караульные дворы, низкие арки и сломанные участки оборонной линии. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (48, 46): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'buildable_plot',
                      'terrain_type': 'ruined_foundation',
                      'topology_tags': ['buildable_plot', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure'],
                      'buildable': True,
                      'buildable_kind': 'house_plot'},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'buildable_plot',
            'terrain_type': 'ruined_foundation',
            'content': {'title': 'Караульный двор',
                        'description': 'Узел ручной топологии в районе: северо-западный бастион. Видимые ориентиры: '
                                       'караульные дворы, низкие арки и сломанные участки оборонной линии. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'buildable_plot',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (49, 46): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['east'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Бастионная площадка',
                        'description': 'Узел ручной топологии в районе: северо-западный бастион. Видимые ориентиры: '
                                       'караульные дворы, низкие арки и сломанные участки оборонной линии. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (45, 47): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'outer_wall_walk',
                      'terrain_type': 'outer_monolith_wall_walk',
                      'topology_tags': ['outer_wall_walk', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['west'], 'travel_cost': 1.0},
            'node_type': 'outer_wall_walk',
            'terrain_type': 'outer_monolith_wall_walk',
            'content': {'title': 'Ход внешней монолитной стены',
                        'description': 'Клетка у внешней стены района: северо-западный бастион. Наружная сторона '
                                       'закрыта красным контуром карты; движение идет только по отмеченным проходам '
                                       'внутри D4.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'outer_wall_walk',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (46, 47): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['west'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Караульный двор',
                        'description': 'Узел ручной топологии в районе: северо-западный бастион. Видимые ориентиры: '
                                       'караульные дворы, низкие арки и сломанные участки оборонной линии. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (47, 47): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'rift',
                      'terrain_type': 'city_rift',
                      'topology_tags': ['rift', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure'],
                      'is_rift': True,
                      'rift_profile': {'id': 'd4_rift_rat_king', 'family_id': 'rat_swarm'},
                      'gate_lock_source': True,
                      'background_key': 'd4_rift_rat_king'},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.5},
            'node_type': 'rift',
            'terrain_type': 'city_rift',
            'content': {'title': 'Разлом Крысиного Короля',
                        'description': 'Опорная точка угрозы в районе: северо-западный бастион. Разлом занимает '
                                       'круглый провал старого двора; проходы вокруг него заданы вручную по карте '
                                       'региона.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'rift',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure',
                                             'pressure_source',
                                             'd4_rift_rat_king',
                                             'rat_king_pressure',
                                             'undercity_seep']}},
 (48, 47): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Двор под черной аркой',
                        'description': 'Узел ручной топологии в районе: северо-западный бастион. Видимые ориентиры: '
                                       'караульные дворы, низкие арки и сломанные участки оборонной линии. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (49, 47): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['west'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Обходной проход',
                        'description': 'Узел ручной топологии в районе: северо-западный бастион. Видимые ориентиры: '
                                       'караульные дворы, низкие арки и сломанные участки оборонной линии. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (45, 48): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'outer_wall_walk',
                      'terrain_type': 'outer_monolith_wall_walk',
                      'topology_tags': ['outer_wall_walk', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['west'], 'travel_cost': 1.0},
            'node_type': 'outer_wall_walk',
            'terrain_type': 'outer_monolith_wall_walk',
            'content': {'title': 'Ход внешней монолитной стены',
                        'description': 'Клетка у внешней стены района: северо-западный бастион. Наружная сторона '
                                       'закрыта красным контуром карты; движение идет только по отмеченным проходам '
                                       'внутри D4.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'outer_wall_walk',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (46, 48): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'buildable_plot',
                      'terrain_type': 'ruined_foundation',
                      'topology_tags': ['buildable_plot', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure'],
                      'buildable': True,
                      'buildable_kind': 'house_plot'},
            'movement_profile': {'has_road': False, 'blocked_exits': ['east'], 'travel_cost': 1.25},
            'node_type': 'buildable_plot',
            'terrain_type': 'ruined_foundation',
            'content': {'title': 'Двор под черной аркой',
                        'description': 'Узел ручной топологии в районе: северо-западный бастион. Видимые ориентиры: '
                                       'караульные дворы, низкие арки и сломанные участки оборонной линии. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'buildable_plot',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (47, 48): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Обходной проход',
                        'description': 'Узел ручной топологии в районе: северо-западный бастион. Видимые ориентиры: '
                                       'караульные дворы, низкие арки и сломанные участки оборонной линии. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (48, 48): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'buildable_plot',
                      'terrain_type': 'ruined_foundation',
                      'topology_tags': ['buildable_plot', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure'],
                      'buildable': True,
                      'buildable_kind': 'house_plot'},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'buildable_plot',
            'terrain_type': 'ruined_foundation',
            'content': {'title': 'Каменный карман',
                        'description': 'Узел ручной топологии в районе: северо-западный бастион. Видимые ориентиры: '
                                       'караульные дворы, низкие арки и сломанные участки оборонной линии. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'buildable_plot',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (49, 48): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['east'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Караульный двор',
                        'description': 'Узел ручной топологии в районе: северо-западный бастион. Видимые ориентиры: '
                                       'караульные дворы, низкие арки и сломанные участки оборонной линии. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (45, 49): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'outer_wall_walk',
                      'terrain_type': 'outer_monolith_wall_walk',
                      'topology_tags': ['outer_wall_walk', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['west'], 'travel_cost': 1.0},
            'node_type': 'outer_wall_walk',
            'terrain_type': 'outer_monolith_wall_walk',
            'content': {'title': 'Ход внешней монолитной стены',
                        'description': 'Клетка у внешней стены района: северо-западный бастион. Наружная сторона '
                                       'закрыта красным контуром карты; движение идет только по отмеченным проходам '
                                       'внутри D4.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'outer_wall_walk',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (46, 49): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['west'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Каменный карман',
                        'description': 'Узел ручной топологии в районе: северо-западный бастион. Видимые ориентиры: '
                                       'караульные дворы, низкие арки и сломанные участки оборонной линии. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (47, 49): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Караульный двор',
                        'description': 'Узел ручной топологии в районе: северо-западный бастион. Видимые ориентиры: '
                                       'караульные дворы, низкие арки и сломанные участки оборонной линии. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (48, 49): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Бастионная площадка',
                        'description': 'Узел ручной топологии в районе: северо-западный бастион. Видимые ориентиры: '
                                       'караульные дворы, низкие арки и сломанные участки оборонной линии. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}},
 (49, 49): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_0_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street', 'bastion', 'outer_wall', 'guard_ruins', 'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['west'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Двор под черной аркой',
                        'description': 'Узел ручной топологии в районе: северо-западный бастион. Видимые ориентиры: '
                                       'караульные дворы, низкие арки и сломанные участки оборонной линии. '
                                       'Художественный текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'bastion',
                                             'outer_wall',
                                             'guard_ruins',
                                             'stasis_pressure']}}}
