from src.backend.features.world.resources.static.d4_types import StaticLocationMap

# D4 outer 5x5 block: X 55..59, Y 45..49.
STATIC_LOCATIONS: StaticLocationMap = {
    (55, 45): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: северо-восточные обсерватории. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (56, 45): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: северо-восточные обсерватории. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (57, 45): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: северо-восточные обсерватории. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (58, 45): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: северо-восточные обсерватории. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (59, 45): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north", "east"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: северо-восточные обсерватории. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (55, 46): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["east"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Круглый зал высоты",
            "description": "Узел ручной топологии в районе: северо-восточные обсерватории. Видимые "
            "ориентиры: башенные руины, круглые дворы и открытые линии обзора. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (56, 46): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "buildable_plot",
            "terrain_type": "ruined_foundation",
            "topology_tags": ["buildable_plot", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
            "buildable": True,
            "buildable_kind": "house_plot",
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north", "west"], "travel_cost": 1.25},
        "node_type": "buildable_plot",
        "terrain_type": "ruined_foundation",
        "content": {
            "title": "Улица между башнями",
            "description": "Узел ручной топологии в районе: северо-восточные обсерватории. Видимые "
            "ориентиры: башенные руины, круглые дворы и открытые линии обзора. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "buildable_plot",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (57, 46): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north", "east"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Ниша сигнальных камней",
            "description": "Узел ручной топологии в районе: северо-восточные обсерватории. Видимые "
            "ориентиры: башенные руины, круглые дворы и открытые линии обзора. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (58, 46): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "buildable_plot",
            "terrain_type": "ruined_foundation",
            "topology_tags": ["buildable_plot", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
            "buildable": True,
            "buildable_kind": "house_plot",
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west", "south"], "travel_cost": 1.25},
        "node_type": "buildable_plot",
        "terrain_type": "ruined_foundation",
        "content": {
            "title": "Двор обсерваторной башни",
            "description": "Узел ручной топологии в районе: северо-восточные обсерватории. Видимые "
            "ориентиры: башенные руины, круглые дворы и открытые линии обзора. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "buildable_plot",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (59, 46): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["east"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: северо-восточные обсерватории. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (55, 47): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["east"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Ниша сигнальных камней",
            "description": "Узел ручной топологии в районе: северо-восточные обсерватории. Видимые "
            "ориентиры: башенные руины, круглые дворы и открытые линии обзора. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (56, 47): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Двор обсерваторной башни",
            "description": "Узел ручной топологии в районе: северо-восточные обсерватории. Видимые "
            "ориентиры: башенные руины, круглые дворы и открытые линии обзора. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (57, 47): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": [], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Смотровая площадка",
            "description": "Узел ручной топологии в районе: северо-восточные обсерватории. Видимые "
            "ориентиры: башенные руины, круглые дворы и открытые линии обзора. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (58, 47): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north", "east"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Круглый зал высоты",
            "description": "Узел ручной топологии в районе: северо-восточные обсерватории. Видимые "
            "ориентиры: башенные руины, круглые дворы и открытые линии обзора. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (59, 47): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west", "east"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: северо-восточные обсерватории. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (55, 48): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": [], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Смотровая площадка",
            "description": "Узел ручной топологии в районе: северо-восточные обсерватории. Видимые "
            "ориентиры: башенные руины, круглые дворы и открытые линии обзора. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (56, 48): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "buildable_plot",
            "terrain_type": "ruined_foundation",
            "topology_tags": ["buildable_plot", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
            "buildable": True,
            "buildable_kind": "house_plot",
        },
        "movement_profile": {"has_road": False, "blocked_exits": [], "travel_cost": 1.25},
        "node_type": "buildable_plot",
        "terrain_type": "ruined_foundation",
        "content": {
            "title": "Круглый зал высоты",
            "description": "Узел ручной топологии в районе: северо-восточные обсерватории. Видимые "
            "ориентиры: башенные руины, круглые дворы и открытые линии обзора. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "buildable_plot",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (57, 48): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "rift",
            "terrain_type": "city_rift",
            "topology_tags": ["rift", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
            "is_rift": True,
            "rift_profile": {"id": "d4_rift_wolf_breach", "family_id": "wolf_pack"},
            "gate_lock_source": True,
            "background_key": "d4_rift_wolf_breach",
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["south"], "travel_cost": 1.5},
        "node_type": "rift",
        "terrain_type": "city_rift",
        "content": {
            "title": "Волчий Пролом",
            "description": "Опорная точка угрозы в районе: северо-восточные обсерватории. Разлом занимает "
            "чаша бывшего зрительного двора; проходы вокруг него заданы вручную по карте "
            "региона.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "rift",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
                "pressure_source",
                "d4_rift_wolf_breach",
                "wolf_breach_pressure",
                "overgrown_kennel",
            ],
        },
    },
    (58, 48): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "buildable_plot",
            "terrain_type": "ruined_foundation",
            "topology_tags": ["buildable_plot", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
            "buildable": True,
            "buildable_kind": "house_plot",
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["east", "south"], "travel_cost": 1.25},
        "node_type": "buildable_plot",
        "terrain_type": "ruined_foundation",
        "content": {
            "title": "Ниша сигнальных камней",
            "description": "Узел ручной топологии в районе: северо-восточные обсерватории. Видимые "
            "ориентиры: башенные руины, круглые дворы и открытые линии обзора. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "buildable_plot",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (59, 48): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["east"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: северо-восточные обсерватории. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (55, 49): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": [], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Улица между башнями",
            "description": "Узел ручной топологии в районе: северо-восточные обсерватории. Видимые "
            "ориентиры: башенные руины, круглые дворы и открытые линии обзора. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (56, 49): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["south"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Ниша сигнальных камней",
            "description": "Узел ручной топологии в районе: северо-восточные обсерватории. Видимые "
            "ориентиры: башенные руины, круглые дворы и открытые линии обзора. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (57, 49): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Двор обсерваторной башни",
            "description": "Узел ручной топологии в районе: северо-восточные обсерватории. Видимые "
            "ориентиры: башенные руины, круглые дворы и открытые линии обзора. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (58, 49): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Смотровая площадка",
            "description": "Узел ручной топологии в районе: северо-восточные обсерватории. Видимые "
            "ориентиры: башенные руины, круглые дворы и открытые линии обзора. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
    (59, 49): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_0",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "observatory_ruins", "signal_stones", "high_vistas", "biomass_creep"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["east"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: северо-восточные обсерватории. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "observatory_ruins",
                "signal_stones",
                "high_vistas",
                "biomass_creep",
            ],
        },
    },
}
