from src.backend.features.world.resources.static.d4_types import StaticLocationMap

# D4 outer 5x5 block: X 50..54, Y 45..49.
STATIC_LOCATIONS: StaticLocationMap = {(50, 45): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'outer_wall_walk',
                      'terrain_type': 'outer_monolith_wall_walk',
                      'topology_tags': ['outer_wall_walk',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north'], 'travel_cost': 1.0},
            'node_type': 'outer_wall_walk',
            'terrain_type': 'outer_monolith_wall_walk',
            'content': {'title': 'Ход внешней монолитной стены',
                        'description': 'Клетка у внешней стены района: северный тракт. Наружная сторона закрыта '
                                       'красным контуром карты; движение идет только по отмеченным проходам внутри D4.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'outer_wall_walk',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (51, 45): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'outer_wall_walk',
                      'terrain_type': 'outer_monolith_wall_walk',
                      'topology_tags': ['outer_wall_walk',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north'], 'travel_cost': 1.0},
            'node_type': 'outer_wall_walk',
            'terrain_type': 'outer_monolith_wall_walk',
            'content': {'title': 'Ход внешней монолитной стены',
                        'description': 'Клетка у внешней стены района: северный тракт. Наружная сторона закрыта '
                                       'красным контуром карты; движение идет только по отмеченным проходам внутри D4.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'outer_wall_walk',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (52, 45): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'sealed_gate',
                      'terrain_type': 'city_gate_outer',
                      'topology_tags': ['sealed_gate',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure'],
                      'is_gate': True,
                      'gate_direction': 'north',
                      'exit_locked': True,
                      'unlock_condition': 'world_gate_unlock'},
            'movement_profile': {'has_road': True,
                                 'blocked_exits': [],
                                 'travel_cost': 1.0,
                                 'gated_exits': {'north': {'kind': 'outer_city_gate',
                                                           'state': 'locked',
                                                           'unlock_condition': 'world_gate_unlock',
                                                           'tags': ['city_gate',
                                                                    'sealed_gate',
                                                                    'old_capital_outer_wall']}}},
            'node_type': 'sealed_gate',
            'terrain_type': 'city_gate_outer',
            'content': {'title': 'Северные внешние ворота D4',
                        'description': 'Ворота на границе региона. Внутренний путь остается частью текущей карты, а '
                                       'выход наружу закрыт до перехода в соседний регион.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'sealed_gate',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure',
                                             'gate',
                                             'locked_exit']}},
 (53, 45): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'outer_wall_walk',
                      'terrain_type': 'outer_monolith_wall_walk',
                      'topology_tags': ['outer_wall_walk',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north'], 'travel_cost': 1.0},
            'node_type': 'outer_wall_walk',
            'terrain_type': 'outer_monolith_wall_walk',
            'content': {'title': 'Ход внешней монолитной стены',
                        'description': 'Клетка у внешней стены района: северный тракт. Наружная сторона закрыта '
                                       'красным контуром карты; движение идет только по отмеченным проходам внутри D4.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'outer_wall_walk',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (54, 45): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'outer_wall_walk',
                      'terrain_type': 'outer_monolith_wall_walk',
                      'topology_tags': ['outer_wall_walk',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north'], 'travel_cost': 1.0},
            'node_type': 'outer_wall_walk',
            'terrain_type': 'outer_monolith_wall_walk',
            'content': {'title': 'Ход внешней монолитной стены',
                        'description': 'Клетка у внешней стены района: северный тракт. Наружная сторона закрыта '
                                       'красным контуром карты; движение идет только по отмеченным проходам внутри D4.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'outer_wall_walk',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (50, 46): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'buildable_plot',
                      'terrain_type': 'ruined_foundation',
                      'topology_tags': ['buildable_plot',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure'],
                      'buildable': True,
                      'buildable_kind': 'house_plot'},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'buildable_plot',
            'terrain_type': 'ruined_foundation',
            'content': {'title': 'Процессионный двор',
                        'description': 'Узел ручной топологии в районе: северный тракт. Видимые ориентиры: прямая '
                                       'дорога к северным воротам, боковые фасады и треснувшие плиты. Художественный '
                                       'текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'buildable_plot',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (51, 46): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Переход к северной арке',
                        'description': 'Узел ручной топологии в районе: северный тракт. Видимые ориентиры: прямая '
                                       'дорога к северным воротам, боковые фасады и треснувшие плиты. Художественный '
                                       'текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (52, 46): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'main_road',
                      'terrain_type': 'ruin_road_main',
                      'topology_tags': ['main_road',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': True, 'blocked_exits': ['east'], 'travel_cost': 1.0},
            'node_type': 'main_road',
            'terrain_type': 'ruin_road_main',
            'content': {'title': 'Северный тракт к внешним воротам',
                        'description': 'Прямая дорога от внутреннего кольца к северным воротам. Боковые выходы открыты '
                                       'только там, где карта показывает просвет между строениями.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'main_road',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (53, 46): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Плиты северного тракта',
                        'description': 'Узел ручной топологии в районе: северный тракт. Видимые ориентиры: прямая '
                                       'дорога к северным воротам, боковые фасады и треснувшие плиты. Художественный '
                                       'текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (54, 46): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'buildable_plot',
                      'terrain_type': 'ruined_foundation',
                      'topology_tags': ['buildable_plot',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure'],
                      'buildable': True,
                      'buildable_kind': 'house_plot'},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'buildable_plot',
            'terrain_type': 'ruined_foundation',
            'content': {'title': 'Пустой фасад у дороги',
                        'description': 'Узел ручной топологии в районе: северный тракт. Видимые ориентиры: прямая '
                                       'дорога к северным воротам, боковые фасады и треснувшие плиты. Художественный '
                                       'текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'buildable_plot',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (50, 47): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Воротный участок',
                        'description': 'Узел ручной топологии в районе: северный тракт. Видимые ориентиры: прямая '
                                       'дорога к северным воротам, боковые фасады и треснувшие плиты. Художественный '
                                       'текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (51, 47): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Плиты северного тракта',
                        'description': 'Узел ручной топологии в районе: северный тракт. Видимые ориентиры: прямая '
                                       'дорога к северным воротам, боковые фасады и треснувшие плиты. Художественный '
                                       'текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (52, 47): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'main_road',
                      'terrain_type': 'ruin_road_main',
                      'topology_tags': ['main_road',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': True, 'blocked_exits': ['west'], 'travel_cost': 1.0},
            'node_type': 'main_road',
            'terrain_type': 'ruin_road_main',
            'content': {'title': 'Северный тракт к внешним воротам',
                        'description': 'Прямая дорога от внутреннего кольца к северным воротам. Боковые выходы открыты '
                                       'только там, где карта показывает просвет между строениями.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'main_road',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (53, 47): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Процессионный двор',
                        'description': 'Узел ручной топологии в районе: северный тракт. Видимые ориентиры: прямая '
                                       'дорога к северным воротам, боковые фасады и треснувшие плиты. Художественный '
                                       'текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (54, 47): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Переход к северной арке',
                        'description': 'Узел ручной топологии в районе: северный тракт. Видимые ориентиры: прямая '
                                       'дорога к северным воротам, боковые фасады и треснувшие плиты. Художественный '
                                       'текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (50, 48): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'buildable_plot',
                      'terrain_type': 'ruined_foundation',
                      'topology_tags': ['buildable_plot',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure'],
                      'buildable': True,
                      'buildable_kind': 'house_plot'},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'buildable_plot',
            'terrain_type': 'ruined_foundation',
            'content': {'title': 'Пустой фасад у дороги',
                        'description': 'Узел ручной топологии в районе: северный тракт. Видимые ориентиры: прямая '
                                       'дорога к северным воротам, боковые фасады и треснувшие плиты. Художественный '
                                       'текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'buildable_plot',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (51, 48): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Процессионный двор',
                        'description': 'Узел ручной топологии в районе: северный тракт. Видимые ориентиры: прямая '
                                       'дорога к северным воротам, боковые фасады и треснувшие плиты. Художественный '
                                       'текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (52, 48): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'main_road',
                      'terrain_type': 'ruin_road_main',
                      'topology_tags': ['main_road',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': True, 'blocked_exits': ['east'], 'travel_cost': 1.0},
            'node_type': 'main_road',
            'terrain_type': 'ruin_road_main',
            'content': {'title': 'Северный тракт к внешним воротам',
                        'description': 'Прямая дорога от внутреннего кольца к северным воротам. Боковые выходы открыты '
                                       'только там, где карта показывает просвет между строениями.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'main_road',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (53, 48): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Воротный участок',
                        'description': 'Узел ручной топологии в районе: северный тракт. Видимые ориентиры: прямая '
                                       'дорога к северным воротам, боковые фасады и треснувшие плиты. Художественный '
                                       'текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (54, 48): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'buildable_plot',
                      'terrain_type': 'ruined_foundation',
                      'topology_tags': ['buildable_plot',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure'],
                      'buildable': True,
                      'buildable_kind': 'house_plot'},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'buildable_plot',
            'terrain_type': 'ruined_foundation',
            'content': {'title': 'Плиты северного тракта',
                        'description': 'Узел ручной топологии в районе: северный тракт. Видимые ориентиры: прямая '
                                       'дорога к северным воротам, боковые фасады и треснувшие плиты. Художественный '
                                       'текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'buildable_plot',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (50, 49): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Переход к северной арке',
                        'description': 'Узел ручной топологии в районе: северный тракт. Видимые ориентиры: прямая '
                                       'дорога к северным воротам, боковые фасады и треснувшие плиты. Художественный '
                                       'текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (51, 49): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Воротный участок',
                        'description': 'Узел ручной топологии в районе: северный тракт. Видимые ориентиры: прямая '
                                       'дорога к северным воротам, боковые фасады и треснувшие плиты. Художественный '
                                       'текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (52, 49): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'main_road',
                      'terrain_type': 'ruin_road_main',
                      'topology_tags': ['main_road',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': True, 'blocked_exits': ['west'], 'travel_cost': 1.0},
            'node_type': 'main_road',
            'terrain_type': 'ruin_road_main',
            'content': {'title': 'Северный тракт к внешним воротам',
                        'description': 'Прямая дорога от внутреннего кольца к северным воротам. Боковые выходы открыты '
                                       'только там, где карта показывает просвет между строениями.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'main_road',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (53, 49): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Пустой фасад у дороги',
                        'description': 'Узел ручной топологии в районе: северный тракт. Видимые ориентиры: прямая '
                                       'дорога к северным воротам, боковые фасады и треснувшие плиты. Художественный '
                                       'текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}},
 (54, 49): {'sector_id': 'D4',
            'is_active': True,
            'services': [],
            'flags': {'is_active': True,
                      'is_safe_zone': False,
                      'is_old_capital': True,
                      'manual_topology': True,
                      'district_key': 'D4_1_0',
                      'node_type': 'side_street',
                      'terrain_type': 'city_ruins',
                      'topology_tags': ['side_street',
                                        'north_gate',
                                        'ancient_highway',
                                        'processional_road',
                                        'stasis_pressure']},
            'movement_profile': {'has_road': False, 'blocked_exits': ['north', 'south'], 'travel_cost': 1.25},
            'node_type': 'side_street',
            'terrain_type': 'city_ruins',
            'content': {'title': 'Процессионный двор',
                        'description': 'Узел ручной топологии в районе: северный тракт. Видимые ориентиры: прямая '
                                       'дорога к северным воротам, боковые фасады и треснувшие плиты. Художественный '
                                       'текст можно заменить позже, проходы уже заданы по карте.',
                        'environment_tags': ['ancient_city',
                                             'city_ruins',
                                             'former_capital_ruins',
                                             'manual_topology',
                                             'side_street',
                                             'north_gate',
                                             'ancient_highway',
                                             'processional_road',
                                             'stasis_pressure']}}}
