from src.backend.features.world.resources.static.d4_types import StaticLocationMap

# D4 outer 5x5 block: X 55..59, Y 55..59.
STATIC_LOCATIONS: StaticLocationMap = {
    (55, 55): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "map_intersection": True,
            "district_key": "D4_2_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": [], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Двор старого святилища",
            "description": "Разрушенные кварталы старого города в районе: юго-восточные святилища. Среди руин виднеются сломанные святилища, круглые основания механизмов и светящиеся колодцы.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (56, 55): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "map_intersection": True,
            "district_key": "D4_2_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": [], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Платформа механизма",
            "description": "Разрушенные кварталы старого города в районе: юго-восточные святилища. Среди руин виднеются сломанные святилища, круглые основания механизмов и светящиеся колодцы.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (57, 55): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": [], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Площадка с синими колодцами",
            "description": "Разрушенные кварталы старого города в районе: юго-восточные святилища. Среди руин виднеются сломанные святилища, круглые основания механизмов и светящиеся колодцы.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (58, 55): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Ритуальный проход",
            "description": "Разрушенные кварталы старого города в районе: юго-восточные святилища. Среди руин виднеются сломанные святилища, круглые основания механизмов и светящиеся колодцы.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (59, 55): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["east"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: юго-восточные святилища. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (55, 56): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "map_intersection": True,
            "district_key": "D4_2_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": [], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Площадка с синими колодцами",
            "description": "Разрушенные кварталы старого города в районе: юго-восточные святилища. Среди руин виднеются сломанные святилища, круглые основания механизмов и светящиеся колодцы.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (56, 56): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "buildable_plot",
            "terrain_type": "ruined_foundation",
            "topology_tags": ["buildable_plot", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
            "buildable": True,
            "buildable_kind": "house_plot",
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["south"], "travel_cost": 1.25},
        "node_type": "buildable_plot",
        "terrain_type": "ruined_foundation",
        "content": {
            "title": "Ритуальный проход",
            "description": "Разрушенные кварталы старого города в районе: юго-восточные святилища. Среди руин виднеются сломанные святилища, круглые основания механизмов и светящиеся колодцы.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "buildable_plot",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (57, 56): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "map_intersection": True,
            "district_key": "D4_2_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": [], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Тихий пристенный двор",
            "description": "Разрушенные кварталы старого города в районе: юго-восточные святилища. Среди руин виднеются сломанные святилища, круглые основания механизмов и светящиеся колодцы.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (58, 56): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "buildable_plot",
            "terrain_type": "ruined_foundation",
            "topology_tags": ["buildable_plot", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
            "buildable": True,
            "buildable_kind": "house_plot",
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north", "east"], "travel_cost": 1.25},
        "node_type": "buildable_plot",
        "terrain_type": "ruined_foundation",
        "content": {
            "title": "Двор старого святилища",
            "description": "Разрушенные кварталы старого города в районе: юго-восточные святилища. Среди руин виднеются сломанные святилища, круглые основания механизмов и светящиеся колодцы.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "buildable_plot",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (59, 56): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west", "east"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: юго-восточные святилища. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (55, 57): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["east"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Тихий пристенный двор",
            "description": "Разрушенные кварталы старого города в районе: юго-восточные святилища. Среди руин виднеются сломанные святилища, круглые основания механизмов и светящиеся колодцы.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (56, 57): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north", "west"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Двор старого святилища",
            "description": "Разрушенные кварталы старого города в районе: юго-восточные святилища. Среди руин виднеются сломанные святилища, круглые основания механизмов и светящиеся колодцы.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (57, 57): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "map_intersection": True,
            "district_key": "D4_2_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": [], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Платформа механизма",
            "description": "Разрушенные кварталы старого города в районе: юго-восточные святилища. Среди руин виднеются сломанные святилища, круглые основания механизмов и светящиеся колодцы.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (58, 57): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["east"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Площадка с синими колодцами",
            "description": "Разрушенные кварталы старого города в районе: юго-восточные святилища. Среди руин виднеются сломанные святилища, круглые основания механизмов и светящиеся колодцы.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (59, 57): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west", "east"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: юго-восточные святилища. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (55, 58): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west", "east"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Платформа механизма",
            "description": "Разрушенные кварталы старого города в районе: юго-восточные святилища. Среди руин виднеются сломанные святилища, круглые основания механизмов и светящиеся колодцы.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (56, 58): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "buildable_plot",
            "terrain_type": "ruined_foundation",
            "topology_tags": ["buildable_plot", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
            "buildable": True,
            "buildable_kind": "house_plot",
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["south"], "travel_cost": 1.25},
        "node_type": "buildable_plot",
        "terrain_type": "ruined_foundation",
        "content": {
            "title": "Площадка с синими колодцами",
            "description": "Разрушенные кварталы старого города в районе: юго-восточные святилища. Среди руин виднеются сломанные святилища, круглые основания механизмов и светящиеся колодцы.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "buildable_plot",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (57, 58): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "rift",
            "terrain_type": "city_rift",
            "topology_tags": ["rift", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
            "is_rift": True,
            "rift_profile": {"id": "d4_rift_goblin_scrapyard", "family_id": "goblin_tribe"},
            "gate_lock_source": True,
            "background_key": "d4_rift_goblin_scrapyard",
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["south"], "travel_cost": 1.5},
        "node_type": "rift",
        "terrain_type": "city_rift",
        "content": {
            "title": "Разлом Свалки",
            "description": "Опорная точка угрозы в районе: юго-восточные святилища. Разлом занимает двор "
            "между синими колодцами старого механизма; проходы вокруг него заданы вручную "
            "по карте региона.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "rift",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
                "pressure_source",
                "d4_rift_goblin_scrapyard",
                "goblin_scrapyard_pressure",
                "collapsed_workshop",
            ],
        },
    },
    (58, 58): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "buildable_plot",
            "terrain_type": "ruined_foundation",
            "topology_tags": ["buildable_plot", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
            "buildable": True,
            "buildable_kind": "house_plot",
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["east"], "travel_cost": 1.25},
        "node_type": "buildable_plot",
        "terrain_type": "ruined_foundation",
        "content": {
            "title": "Тихий пристенный двор",
            "description": "Разрушенные кварталы старого города в районе: юго-восточные святилища. Среди руин виднеются сломанные святилища, круглые основания механизмов и светящиеся колодцы.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "buildable_plot",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (59, 58): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["east"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: юго-восточные святилища. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (55, 59): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["south"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: юго-восточные святилища. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (56, 59): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north", "south"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: юго-восточные святилища. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (57, 59): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north", "south"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: юго-восточные святилища. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (58, 59): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["south"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: юго-восточные святилища. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
    (59, 59): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_2_2",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "shrine_ruins", "ritual_plazas", "plasma_pressure", "gold_veins"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["south", "east"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: юго-восточные святилища. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "shrine_ruins",
                "ritual_plazas",
                "plasma_pressure",
                "gold_veins",
            ],
        },
    },
}
