from src.backend.features.world.resources.static.d4_types import StaticLocationMap

# D4 outer 5x5 block: X 45..49, Y 55..59.
STATIC_LOCATIONS: StaticLocationMap = {
    (45, 55): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": [
                "outer_wall_walk",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: юго-западные мастерские. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (46, 55): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "artisan_ruins", "dead_workshops", "gravity_shear", "crystal_conduits"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north", "south"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Корпус мастерской",
            "description": "Узел ручной топологии в районе: юго-западные мастерские. Видимые ориентиры: "
            "тяжелые корпуса мастерских, заваленные рабочие дворы и старые каналы в камне. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (47, 55): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "artisan_ruins", "dead_workshops", "gravity_shear", "crystal_conduits"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["south"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Проход между цехами",
            "description": "Узел ручной топологии в районе: юго-западные мастерские. Видимые ориентиры: "
            "тяжелые корпуса мастерских, заваленные рабочие дворы и старые каналы в камне. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (48, 55): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "artisan_ruins", "dead_workshops", "gravity_shear", "crystal_conduits"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north", "west", "east"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Площадка механизма",
            "description": "Узел ручной топологии в районе: юго-западные мастерские. Видимые ориентиры: "
            "тяжелые корпуса мастерских, заваленные рабочие дворы и старые каналы в камне. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (49, 55): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "artisan_ruins", "dead_workshops", "gravity_shear", "crystal_conduits"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Завал старых работ",
            "description": "Узел ручной топологии в районе: юго-западные мастерские. Видимые ориентиры: "
            "тяжелые корпуса мастерских, заваленные рабочие дворы и старые каналы в камне. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (45, 56): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": [
                "outer_wall_walk",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: юго-западные мастерские. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (46, 56): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "buildable_plot",
            "terrain_type": "ruined_foundation",
            "topology_tags": ["buildable_plot", "artisan_ruins", "dead_workshops", "gravity_shear", "crystal_conduits"],
            "buildable": True,
            "buildable_kind": "house_plot",
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north", "west"], "travel_cost": 1.25},
        "node_type": "buildable_plot",
        "terrain_type": "ruined_foundation",
        "content": {
            "title": "Площадка механизма",
            "description": "Узел ручной топологии в районе: юго-западные мастерские. Видимые ориентиры: "
            "тяжелые корпуса мастерских, заваленные рабочие дворы и старые каналы в камне. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "buildable_plot",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (47, 56): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "artisan_ruins", "dead_workshops", "gravity_shear", "crystal_conduits"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Завал старых работ",
            "description": "Узел ручной топологии в районе: юго-западные мастерские. Видимые ориентиры: "
            "тяжелые корпуса мастерских, заваленные рабочие дворы и старые каналы в камне. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (48, 56): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "map_intersection": True,
            "district_key": "D4_0_2",
            "node_type": "buildable_plot",
            "terrain_type": "ruined_foundation",
            "topology_tags": ["buildable_plot", "artisan_ruins", "dead_workshops", "gravity_shear", "crystal_conduits"],
            "buildable": True,
            "buildable_kind": "house_plot",
        },
        "movement_profile": {"has_road": False, "blocked_exits": [], "travel_cost": 1.25},
        "node_type": "buildable_plot",
        "terrain_type": "ruined_foundation",
        "content": {
            "title": "Рабочий двор",
            "description": "Узел ручной топологии в районе: юго-западные мастерские. Видимые ориентиры: "
            "тяжелые корпуса мастерских, заваленные рабочие дворы и старые каналы в камне. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "buildable_plot",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (49, 56): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "artisan_ruins", "dead_workshops", "gravity_shear", "crystal_conduits"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["south", "east"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Корпус мастерской",
            "description": "Узел ручной топологии в районе: юго-западные мастерские. Видимые ориентиры: "
            "тяжелые корпуса мастерских, заваленные рабочие дворы и старые каналы в камне. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (45, 57): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": [
                "outer_wall_walk",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: юго-западные мастерские. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (46, 57): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "artisan_ruins", "dead_workshops", "gravity_shear", "crystal_conduits"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Рабочий двор",
            "description": "Узел ручной топологии в районе: юго-западные мастерские. Видимые ориентиры: "
            "тяжелые корпуса мастерских, заваленные рабочие дворы и старые каналы в камне. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (47, 57): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "map_intersection": True,
            "district_key": "D4_0_2",
            "node_type": "rift",
            "terrain_type": "city_rift",
            "topology_tags": ["rift", "artisan_ruins", "dead_workshops", "gravity_shear", "crystal_conduits"],
            "is_rift": True,
            "rift_profile": {"id": "d4_rift_bandit_barricade", "family_id": "bandit_gang"},
            "gate_lock_source": True,
            "background_key": "d4_rift_bandit_barricade",
        },
        "movement_profile": {"has_road": False, "blocked_exits": [], "travel_cost": 1.5},
        "node_type": "rift",
        "terrain_type": "city_rift",
        "content": {
            "title": "Разлом Баррикады",
            "description": "Опорная точка угрозы в районе: юго-западные мастерские. Разлом занимает "
            "разорванная площадка между корпусами мастерских; проходы вокруг него заданы "
            "вручную по карте региона.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "rift",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
                "pressure_source",
                "d4_rift_bandit_barricade",
                "bandit_barricade_pressure",
                "scavenger_barricade",
            ],
        },
    },
    (48, 57): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "artisan_ruins", "dead_workshops", "gravity_shear", "crystal_conduits"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": [], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Проход между цехами",
            "description": "Узел ручной топологии в районе: юго-западные мастерские. Видимые ориентиры: "
            "тяжелые корпуса мастерских, заваленные рабочие дворы и старые каналы в камне. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (49, 57): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "artisan_ruins", "dead_workshops", "gravity_shear", "crystal_conduits"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Площадка механизма",
            "description": "Узел ручной топологии в районе: юго-западные мастерские. Видимые ориентиры: "
            "тяжелые корпуса мастерских, заваленные рабочие дворы и старые каналы в камне. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (45, 58): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": [
                "outer_wall_walk",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: юго-западные мастерские. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (46, 58): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "buildable_plot",
            "terrain_type": "ruined_foundation",
            "topology_tags": ["buildable_plot", "artisan_ruins", "dead_workshops", "gravity_shear", "crystal_conduits"],
            "buildable": True,
            "buildable_kind": "house_plot",
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west", "south"], "travel_cost": 1.25},
        "node_type": "buildable_plot",
        "terrain_type": "ruined_foundation",
        "content": {
            "title": "Проход между цехами",
            "description": "Узел ручной топологии в районе: юго-западные мастерские. Видимые ориентиры: "
            "тяжелые корпуса мастерских, заваленные рабочие дворы и старые каналы в камне. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "buildable_plot",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (47, 58): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "artisan_ruins", "dead_workshops", "gravity_shear", "crystal_conduits"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["south"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Площадка механизма",
            "description": "Узел ручной топологии в районе: юго-западные мастерские. Видимые ориентиры: "
            "тяжелые корпуса мастерских, заваленные рабочие дворы и старые каналы в камне. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (48, 58): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "buildable_plot",
            "terrain_type": "ruined_foundation",
            "topology_tags": ["buildable_plot", "artisan_ruins", "dead_workshops", "gravity_shear", "crystal_conduits"],
            "buildable": True,
            "buildable_kind": "house_plot",
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["south", "east"], "travel_cost": 1.25},
        "node_type": "buildable_plot",
        "terrain_type": "ruined_foundation",
        "content": {
            "title": "Завал старых работ",
            "description": "Узел ручной топологии в районе: юго-западные мастерские. Видимые ориентиры: "
            "тяжелые корпуса мастерских, заваленные рабочие дворы и старые каналы в камне. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "buildable_plot",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (49, 58): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "artisan_ruins", "dead_workshops", "gravity_shear", "crystal_conduits"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["east"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Рабочий двор",
            "description": "Узел ручной топологии в районе: юго-западные мастерские. Видимые ориентиры: "
            "тяжелые корпуса мастерских, заваленные рабочие дворы и старые каналы в камне. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (45, 59): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": [
                "outer_wall_walk",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["south", "west"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: юго-западные мастерские. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (46, 59): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": [
                "outer_wall_walk",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["south"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: юго-западные мастерские. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (47, 59): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": [
                "outer_wall_walk",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["south"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: юго-западные мастерские. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (48, 59): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": [
                "outer_wall_walk",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["south"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: юго-западные мастерские. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
    (49, 59): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_2",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": [
                "outer_wall_walk",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["south"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: юго-западные мастерские. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "artisan_ruins",
                "dead_workshops",
                "gravity_shear",
                "crystal_conduits",
            ],
        },
    },
}
