from src.backend.features.world.resources.static.d4_types import StaticLocationMap

# D4 outer 5x5 block: X 45..49, Y 50..54.
STATIC_LOCATIONS: StaticLocationMap = {
    (45, 50): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "map_intersection": True,
            "district_key": "D4_0_1",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: западный рынок обломков. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (46, 50): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_1",
            "node_type": "buildable_plot",
            "terrain_type": "ruined_foundation",
            "topology_tags": ["buildable_plot", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
            "buildable": True,
            "buildable_kind": "house_plot",
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north"], "travel_cost": 1.25},
        "node_type": "buildable_plot",
        "terrain_type": "ruined_foundation",
        "content": {
            "title": "Двор западного перехода",
            "description": "Узел ручной топологии в районе: западный рынок обломков. Видимые ориентиры: "
            "широкие пустые площади, лавочные остовы и боковые улицы у западной стены. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "buildable_plot",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (47, 50): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "map_intersection": True,
            "district_key": "D4_0_1",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": [], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Лавочные ряды",
            "description": "Узел ручной топологии в районе: западный рынок обломков. Видимые ориентиры: "
            "широкие пустые площади, лавочные остовы и боковые улицы у западной стены. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (48, 50): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_1",
            "node_type": "buildable_plot",
            "terrain_type": "ruined_foundation",
            "topology_tags": ["buildable_plot", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
            "buildable": True,
            "buildable_kind": "house_plot",
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north", "east"], "travel_cost": 1.25},
        "node_type": "buildable_plot",
        "terrain_type": "ruined_foundation",
        "content": {
            "title": "Торговая площадь",
            "description": "Узел ручной топологии в районе: западный рынок обломков. Видимые ориентиры: "
            "широкие пустые площади, лавочные остовы и боковые улицы у западной стены. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "buildable_plot",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (49, 50): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_1",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Переулок обмена",
            "description": "Узел ручной топологии в районе: западный рынок обломков. Видимые ориентиры: "
            "широкие пустые площади, лавочные остовы и боковые улицы у западной стены. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (45, 51): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_1",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: западный рынок обломков. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (46, 51): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_1",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["south"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Торговая площадь",
            "description": "Узел ручной топологии в районе: западный рынок обломков. Видимые ориентиры: "
            "широкие пустые площади, лавочные остовы и боковые улицы у западной стены. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (47, 51): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "map_intersection": True,
            "district_key": "D4_0_1",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": [], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Переулок обмена",
            "description": "Узел ручной топологии в районе: западный рынок обломков. Видимые ориентиры: "
            "широкие пустые площади, лавочные остовы и боковые улицы у западной стены. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (48, 51): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_1",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Рыночная полоса",
            "description": "Узел ручной топологии в районе: западный рынок обломков. Видимые ориентиры: "
            "широкие пустые площади, лавочные остовы и боковые улицы у западной стены. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (49, 51): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_1",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": [], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Двор западного перехода",
            "description": "Узел ручной топологии в районе: западный рынок обломков. Видимые ориентиры: "
            "широкие пустые площади, лавочные остовы и боковые улицы у западной стены. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (45, 52): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_1",
            "node_type": "sealed_gate",
            "terrain_type": "city_gate_outer",
            "topology_tags": ["sealed_gate", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
            "is_gate": True,
            "gate_direction": "west",
            "exit_locked": True,
            "unlock_condition": "world_gate_unlock",
        },
        "movement_profile": {
            "has_road": True,
            "blocked_exits": [],
            "travel_cost": 1.0,
            "gated_exits": {
                "west": {
                    "kind": "outer_city_gate",
                    "state": "locked",
                    "unlock_condition": "world_gate_unlock",
                    "tags": ["city_gate", "sealed_gate", "old_capital_outer_wall"],
                }
            },
        },
        "node_type": "sealed_gate",
        "terrain_type": "city_gate_outer",
        "content": {
            "title": "Западные внешние ворота D4",
            "description": "Ворота на границе региона. Внутренний путь остается частью текущей карты, а "
            "выход наружу закрыт до перехода в соседний регион.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "sealed_gate",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
                "gate",
                "locked_exit",
            ],
        },
    },
    (46, 52): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_1",
            "node_type": "main_road",
            "terrain_type": "ruin_road_main",
            "topology_tags": ["main_road", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
        },
        "movement_profile": {"has_road": True, "blocked_exits": ["north", "south"], "travel_cost": 1.0},
        "node_type": "main_road",
        "terrain_type": "ruin_road_main",
        "content": {
            "title": "Западная дорога старого города",
            "description": "Поперечная дорога от внутреннего кольца к западным воротам. Закрытые фасады и "
            "завалы не считаются проходами.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "main_road",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (47, 52): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "map_intersection": True,
            "district_key": "D4_0_1",
            "node_type": "main_road",
            "terrain_type": "ruin_road_main",
            "topology_tags": ["main_road", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
        },
        "movement_profile": {"has_road": True, "blocked_exits": [], "travel_cost": 1.0},
        "node_type": "main_road",
        "terrain_type": "ruin_road_main",
        "content": {
            "title": "Западная дорога старого города",
            "description": "Поперечная дорога от внутреннего кольца к западным воротам. Закрытые фасады и "
            "завалы не считаются проходами.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "main_road",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (48, 52): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_1",
            "node_type": "main_road",
            "terrain_type": "ruin_road_main",
            "topology_tags": ["main_road", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
        },
        "movement_profile": {"has_road": True, "blocked_exits": ["north"], "travel_cost": 1.0},
        "node_type": "main_road",
        "terrain_type": "ruin_road_main",
        "content": {
            "title": "Западная дорога старого города",
            "description": "Поперечная дорога от внутреннего кольца к западным воротам. Закрытые фасады и "
            "завалы не считаются проходами.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "main_road",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (49, 52): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "inner_wall_ring": True,
            "map_intersection": True,
            "district_key": "D4_0_1",
            "node_type": "main_road",
            "terrain_type": "ruin_road_main",
            "topology_tags": [
                "main_road",
                "inner_wall_ring",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
        "movement_profile": {"has_road": True, "blocked_exits": [], "travel_cost": 1.0},
        "node_type": "main_road",
        "terrain_type": "ruin_road_main",
        "content": {
            "title": "Западная дорога старого города",
            "description": "Поперечная дорога от внутреннего кольца к западным воротам. Закрытые фасады и "
            "завалы не считаются проходами.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "main_road",
                "inner_wall_ring",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (45, 53): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_1",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: западный рынок обломков. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (46, 53): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_1",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": [], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Лавочные ряды",
            "description": "Узел ручной топологии в районе: западный рынок обломков. Видимые ориентиры: "
            "широкие пустые площади, лавочные остовы и боковые улицы у западной стены. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (47, 53): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_1",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west", "east"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Торговая площадь",
            "description": "Узел ручной топологии в районе: западный рынок обломков. Видимые ориентиры: "
            "широкие пустые площади, лавочные остовы и боковые улицы у западной стены. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (48, 53): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_1",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["north"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Переулок обмена",
            "description": "Узел ручной топологии в районе: западный рынок обломков. Видимые ориентиры: "
            "широкие пустые площади, лавочные остовы и боковые улицы у западной стены. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (49, 53): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_1",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Рыночная полоса",
            "description": "Узел ручной топологии в районе: западный рынок обломков. Видимые ориентиры: "
            "широкие пустые площади, лавочные остовы и боковые улицы у западной стены. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (45, 54): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_1",
            "node_type": "outer_wall_walk",
            "terrain_type": "outer_monolith_wall_walk",
            "topology_tags": ["outer_wall_walk", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west"], "travel_cost": 1.0},
        "node_type": "outer_wall_walk",
        "terrain_type": "outer_monolith_wall_walk",
        "content": {
            "title": "Ход внешней монолитной стены",
            "description": "Клетка у внешней стены района: западный рынок обломков. Наружная сторона "
            "закрыта красным контуром карты; движение идет только по отмеченным проходам "
            "внутри D4.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "outer_wall_walk",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (46, 54): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_1",
            "node_type": "buildable_plot",
            "terrain_type": "ruined_foundation",
            "topology_tags": ["buildable_plot", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
            "buildable": True,
            "buildable_kind": "house_plot",
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["west", "east"], "travel_cost": 1.25},
        "node_type": "buildable_plot",
        "terrain_type": "ruined_foundation",
        "content": {
            "title": "Переулок обмена",
            "description": "Узел ручной топологии в районе: западный рынок обломков. Видимые ориентиры: "
            "широкие пустые площади, лавочные остовы и боковые улицы у западной стены. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "buildable_plot",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (47, 54): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "map_intersection": True,
            "district_key": "D4_0_1",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": [], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Рыночная полоса",
            "description": "Узел ручной топологии в районе: западный рынок обломков. Видимые ориентиры: "
            "широкие пустые площади, лавочные остовы и боковые улицы у западной стены. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (48, 54): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "map_intersection": True,
            "district_key": "D4_0_1",
            "node_type": "buildable_plot",
            "terrain_type": "ruined_foundation",
            "topology_tags": ["buildable_plot", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
            "buildable": True,
            "buildable_kind": "house_plot",
        },
        "movement_profile": {"has_road": False, "blocked_exits": [], "travel_cost": 1.25},
        "node_type": "buildable_plot",
        "terrain_type": "ruined_foundation",
        "content": {
            "title": "Двор западного перехода",
            "description": "Узел ручной топологии в районе: западный рынок обломков. Видимые ориентиры: "
            "широкие пустые площади, лавочные остовы и боковые улицы у западной стены. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "buildable_plot",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
    (49, 54): {
        "sector_id": "D4",
        "is_active": True,
        "services": [],
        "flags": {
            "is_active": True,
            "is_safe_zone": False,
            "is_old_capital": True,
            "manual_topology": True,
            "district_key": "D4_0_1",
            "node_type": "side_street",
            "terrain_type": "city_ruins",
            "topology_tags": ["side_street", "broken_market", "scavenger_marks", "gravity_shear", "side_streets"],
        },
        "movement_profile": {"has_road": False, "blocked_exits": ["east"], "travel_cost": 1.25},
        "node_type": "side_street",
        "terrain_type": "city_ruins",
        "content": {
            "title": "Лавочные ряды",
            "description": "Узел ручной топологии в районе: западный рынок обломков. Видимые ориентиры: "
            "широкие пустые площади, лавочные остовы и боковые улицы у западной стены. "
            "Художественный текст можно заменить позже, проходы уже заданы по карте.",
            "environment_tags": [
                "ancient_city",
                "city_ruins",
                "former_capital_ruins",
                "manual_topology",
                "side_street",
                "broken_market",
                "scavenger_marks",
                "gravity_shear",
                "side_streets",
            ],
        },
    },
}
