from src.backend.resources.game_data.skills.schemas import SkillCategory, SkillDTO

NON_COMBAT_SKILLS = [
    # --- GATHERING ---
    SkillDTO(
        skill_key="mining",
        name_en="Mining",
        name_ru="Горное дело",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"perception": 2.0, "endurance": 1.0},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Добыча полезных ископаемых.",
    ),
    SkillDTO(
        skill_key="herbalism",
        name_en="Herbalism",
        name_ru="Травничество",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"perception": 2.0, "endurance": 1.0},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Сбор лекарственных растений.",
    ),
    SkillDTO(
        skill_key="skinning",
        name_en="Skinning",
        name_ru="Снятие шкур",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"perception": 2.0, "endurance": 1.0},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Обработка шкур животных.",
    ),
    SkillDTO(
        skill_key="woodcutting",
        name_en="Woodcutting",
        name_ru="Лесорубство",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"perception": 2.0, "endurance": 1.0},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Заготовка древесины.",
    ),
    SkillDTO(
        skill_key="hunting",
        name_en="Hunting",
        name_ru="Охота",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"perception": 2.0, "endurance": 1.0},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Охота на дичь.",
    ),
    SkillDTO(
        skill_key="archaeology",
        name_en="Archaeology",
        name_ru="Археология",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"perception": 2.0, "endurance": 1.0},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Изучение древностей.",
    ),
    SkillDTO(
        skill_key="gathering",
        name_en="Gathering",
        name_ru="Сбор",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"perception": 2.0, "endurance": 1.0},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Сбор различных ресурсов.",
    ),
    # --- CRAFTING ---
    SkillDTO(
        skill_key="alchemy",
        name_en="Alchemy",
        name_ru="Алхимия",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"intelligence": 2.0, "agility": 1.0},
        rate_mod=1.5,
        wall_mod=1.0,
        description="Приготовление зелий.",
    ),
    SkillDTO(
        skill_key="weapon_craft",
        name_en="Weapon Crafting",
        name_ru="Оружейное дело",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"intelligence": 2.0, "agility": 1.0},
        rate_mod=2.0,
        wall_mod=1.0,
        description="Создание оружия.",
    ),
    SkillDTO(
        skill_key="armor_craft",
        name_en="Armor Crafting",
        name_ru="Бронное дело",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"intelligence": 2.0, "agility": 1.0},
        rate_mod=2.0,
        wall_mod=1.0,
        description="Создание брони.",
    ),
    SkillDTO(
        skill_key="jewelry_craft",
        name_en="Jewelry Crafting",
        name_ru="Ювелирное дело",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"intelligence": 2.0, "agility": 1.0},
        rate_mod=2.0,
        wall_mod=1.0,
        description="Создание украшений.",
    ),
    SkillDTO(
        skill_key="artifact_craft",
        name_en="Artifact Crafting",
        name_ru="Создание артефактов",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"intelligence": 2.0, "agility": 1.0},
        rate_mod=2.5,
        wall_mod=1.5,
        description="Создание магических предметов.",
    ),
    # --- SCIENCE ---
    SkillDTO(
        skill_key="science",
        name_en="Science",
        name_ru="Наука",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"intelligence": 2.0, "perception": 1.0},
        rate_mod=1.5,
        wall_mod=1.0,
        description="Научные изыскания.",
    ),
    # --- SOCIAL ---
    SkillDTO(
        skill_key="accounting",
        name_en="Accounting",
        name_ru="Бухгалтерия",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"luck": 2.0, "charisma": 1.0},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Финансовый учет.",
    ),
    SkillDTO(
        skill_key="brokerage",
        name_en="Brokerage",
        name_ru="Посредничество",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"luck": 2.0, "charisma": 1.0},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Торговое посредничество.",
    ),
    SkillDTO(
        skill_key="contracts",
        name_en="Contracts",
        name_ru="Договоры",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"luck": 2.0, "charisma": 1.0},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Работа с контрактами.",
    ),
    SkillDTO(
        skill_key="trade_relations",
        name_en="Trade Relations",
        name_ru="Торговые связи",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"luck": 2.0, "charisma": 1.0},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Развитие торговых связей.",
    ),
    SkillDTO(
        skill_key="leadership",
        name_en="Leadership",
        name_ru="Лидерство",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"charisma": 2.0, "luck": 1.0},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Управление группой.",
    ),
    SkillDTO(
        skill_key="organization",
        name_en="Organization",
        name_ru="Организация",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"luck": 2.0, "charisma": 1.0},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Организационные навыки.",
    ),
    SkillDTO(
        skill_key="team_spirit",
        name_en="Team Spirit",
        name_ru="Командный дух",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"charisma": 2.0, "luck": 1.0},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Поддержание духа команды.",
    ),
    SkillDTO(
        skill_key="egoism",
        name_en="Egoism",
        name_ru="Эгоизм",
        category=SkillCategory.NON_COMBAT,
        stat_weights={"luck": 2.0, "charisma": 1.0},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Личная выгода.",
    ),
]
