from src.backend.resources.game_data.skills.schemas import SkillCategory, SkillDTO, SkillGroup

CRAFTING_SKILLS = [
    SkillDTO(
        skill_key="alchemy",
        name_en="Alchemy",
        name_ru="Алхимия",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.CRAFTING,
        stat_weights={"intelligence": 2, "wisdom": 1, "luck": 1},
        rate_mod=1.5,
        wall_mod=1.0,
        description="Создание зелий, эликсиров и трансмутация веществ.",
    ),
    SkillDTO(
        skill_key="weapon_craft",
        name_en="Weapon Crafting",
        name_ru="Оружейное дело",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.CRAFTING,
        stat_weights={"strength": 2, "agility": 1, "perception": 1},
        rate_mod=2.0,
        wall_mod=1.0,
        description="Изготовление и ремонт оружия.",
    ),
    SkillDTO(
        skill_key="armor_craft",
        name_en="Armor Crafting",
        name_ru="Бронное дело",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.CRAFTING,
        stat_weights={"strength": 2, "endurance": 2},  # Dual 2+2
        rate_mod=2.0,
        wall_mod=1.0,
        description="Изготовление и ремонт доспехов.",
    ),
    SkillDTO(
        skill_key="jewelry_craft",
        name_en="Jewelry Crafting",
        name_ru="Ювелирное дело",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.CRAFTING,
        stat_weights={"agility": 2, "perception": 1, "luck": 1},
        rate_mod=2.0,
        wall_mod=1.0,
        description="Создание ювелирных украшений и огранка камней.",
    ),
    SkillDTO(
        skill_key="artifact_craft",
        name_en="Artifact Crafting",
        name_ru="Создание артефактов",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.CRAFTING,
        stat_weights={"men": 2, "intelligence": 1, "wisdom": 1},
        rate_mod=2.5,
        wall_mod=1.5,
        description="Создание магических артефактов и предметов силы.",
    ),
]
