from src.backend.resources.game_data.skills.schemas import SkillCategory, SkillDTO, SkillGroup

GATHERING_SKILLS = [
    SkillDTO(
        skill_key="mining",
        name_en="Mining",
        name_ru="Горное дело",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.GATHERING,
        stat_weights={"strength": 2, "endurance": 2},  # Dual 2+2
        rate_mod=1.0,
        wall_mod=1.0,
        description="Добыча руды и драгоценных камней.",
    ),
    SkillDTO(
        skill_key="herbalism",
        name_en="Herbalism",
        name_ru="Травничество",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.GATHERING,
        stat_weights={"perception": 2, "wisdom": 1, "intelligence": 1},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Сбор трав, грибов и других растений.",
    ),
    SkillDTO(
        skill_key="skinning",
        name_en="Skinning",
        name_ru="Снятие шкур",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.GATHERING,
        stat_weights={"agility": 2, "perception": 1, "endurance": 1},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Снятие шкур с убитых животных.",
    ),
    SkillDTO(
        skill_key="woodcutting",
        name_en="Woodcutting",
        name_ru="Лесорубство",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.GATHERING,
        stat_weights={"strength": 2, "endurance": 2},  # Dual 2+2
        rate_mod=1.0,
        wall_mod=1.0,
        description="Рубка деревьев и заготовка древесины.",
    ),
    SkillDTO(
        skill_key="hunting",
        name_en="Hunting",
        name_ru="Охота",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.GATHERING,
        stat_weights={"perception": 2, "agility": 1, "endurance": 1},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Выслеживание и добыча диких животных.",
    ),
    SkillDTO(
        skill_key="archaeology",
        name_en="Archaeology",
        name_ru="Археология",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.GATHERING,
        stat_weights={"perception": 2, "wisdom": 1, "intelligence": 1},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Поиск и изучение древних артефактов.",
    ),
    SkillDTO(
        skill_key="gathering",
        name_en="Gathering",
        name_ru="Сбор",
        category=SkillCategory.NON_COMBAT,
        group=SkillGroup.GATHERING,
        stat_weights={"perception": 2, "endurance": 2},  # Dual 2+2
        rate_mod=1.0,
        wall_mod=1.0,
        description="Общий навык сбора ресурсов.",
    ),
]
