from src.backend.resources.game_data.skills.schemas import SkillCategory, SkillDTO, SkillGroup

WEAPON_MASTERY_SKILLS = [
    SkillDTO(
        skill_key="skill_swords",
        name_en="Swordsmanship",
        name_ru="Владение мечами",
        category=SkillCategory.COMBAT,
        group=SkillGroup.WEAPON_MASTERY,
        stat_weights={"strength": 2, "agility": 1, "endurance": 1},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Мастерство владения мечами, увеличивает урон и точность при использовании мечей.",
    ),
    SkillDTO(
        skill_key="skill_fencing",
        name_en="Fencing",
        name_ru="Фехтование",
        category=SkillCategory.COMBAT,
        group=SkillGroup.WEAPON_MASTERY,
        stat_weights={"agility": 2, "perception": 1, "strength": 1},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Искусство фехтования, повышает точность и шанс критического удара колющим оружием.",
    ),
    SkillDTO(
        skill_key="skill_polearms",
        name_en="Polearms",
        name_ru="Древковое оружие",
        category=SkillCategory.COMBAT,
        group=SkillGroup.WEAPON_MASTERY,
        stat_weights={"strength": 2, "agility": 1, "perception": 1},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Владение древковым оружием, позволяет держать врагов на дистанции.",
    ),
    SkillDTO(
        skill_key="skill_macing",
        name_en="Mace Fighting",
        name_ru="Дробящее оружие",
        category=SkillCategory.COMBAT,
        group=SkillGroup.WEAPON_MASTERY,
        stat_weights={"strength": 2, "endurance": 1, "men": 1},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Использование дробящего оружия, эффективно против бронированных целей.",
    ),
    SkillDTO(
        skill_key="skill_archery",
        name_en="Archery",
        name_ru="Стрельба из лука",
        category=SkillCategory.COMBAT,
        group=SkillGroup.WEAPON_MASTERY,
        stat_weights={"agility": 2, "perception": 1, "strength": 1},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Мастерство стрельбы из лука, позволяет поражать цели на расстоянии.",
    ),
    SkillDTO(
        skill_key="skill_unarmed",
        name_en="Unarmed Combat",
        name_ru="Рукопашный бой",
        category=SkillCategory.COMBAT,
        group=SkillGroup.WEAPON_MASTERY,
        stat_weights={"agility": 2, "strength": 1, "endurance": 1},
        rate_mod=1.0,
        wall_mod=1.0,
        description="Бой без оружия, использует тело как оружие.",
    ),
]
