from __future__ import annotations

from copy import deepcopy
from typing import Literal, TypedDict

EncounterDifficulty = Literal["easy", "normal", "hard"]
EncounterKind = Literal["ordinary", "guard", "boss"]
MonsterRole = Literal["minion", "veteran", "elite", "boss"]


class MonsterEncounterProfile(TypedDict):
    budget_multiplier: float
    min_units: int
    max_units: int
    start_role: MonsterRole
    allowed_roles: list[MonsterRole]
    required_roles: list[MonsterRole]
    role_caps: dict[MonsterRole, int]
    upgrade_order: list[MonsterRole]
    allow_repeated_members: bool
    prefer_distinct_members: bool


MONSTER_ENCOUNTER_PROFILES: dict[str, dict[EncounterKind, dict[EncounterDifficulty, MonsterEncounterProfile]]] = {
    "rat_swarm": {
        "ordinary": {
            "easy": {
                "budget_multiplier": 0.75,
                "min_units": 3,
                "max_units": 6,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran"],
                "required_roles": [],
                "role_caps": {"minion": 6, "veteran": 6, "elite": 0, "boss": 0},
                "upgrade_order": ["veteran"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "normal": {
                "budget_multiplier": 1.0,
                "min_units": 3,
                "max_units": 6,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran", "elite"],
                "required_roles": [],
                "role_caps": {"minion": 6, "veteran": 6, "elite": 2, "boss": 0},
                "upgrade_order": ["veteran", "elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "hard": {
                "budget_multiplier": 1.25,
                "min_units": 3,
                "max_units": 6,
                "start_role": "veteran",
                "allowed_roles": ["veteran", "elite"],
                "required_roles": [],
                "role_caps": {"minion": 0, "veteran": 6, "elite": 3, "boss": 0},
                "upgrade_order": ["elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
        },
        "guard": {
            "easy": {
                "budget_multiplier": 0.85,
                "min_units": 3,
                "max_units": 6,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran"],
                "required_roles": ["veteran"],
                "role_caps": {"minion": 6, "veteran": 3, "elite": 0, "boss": 0},
                "upgrade_order": ["veteran"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "normal": {
                "budget_multiplier": 1.1,
                "min_units": 3,
                "max_units": 6,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran", "elite"],
                "required_roles": ["veteran"],
                "role_caps": {"minion": 6, "veteran": 6, "elite": 2, "boss": 0},
                "upgrade_order": ["veteran", "elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "hard": {
                "budget_multiplier": 1.3,
                "min_units": 3,
                "max_units": 6,
                "start_role": "veteran",
                "allowed_roles": ["veteran", "elite"],
                "required_roles": ["elite"],
                "role_caps": {"minion": 0, "veteran": 6, "elite": 3, "boss": 0},
                "upgrade_order": ["elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
        },
        "boss": {
            "easy": {
                "budget_multiplier": 1.0,
                "min_units": 2,
                "max_units": 4,
                "start_role": "veteran",
                "allowed_roles": ["veteran", "elite"],
                "required_roles": ["veteran", "elite"],
                "role_caps": {"minion": 0, "veteran": 3, "elite": 1, "boss": 0},
                "upgrade_order": ["elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "normal": {
                "budget_multiplier": 1.2,
                "min_units": 3,
                "max_units": 5,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran", "elite", "boss"],
                "required_roles": ["boss"],
                "role_caps": {"minion": 5, "veteran": 4, "elite": 1, "boss": 1},
                "upgrade_order": ["veteran", "elite", "boss"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "hard": {
                "budget_multiplier": 1.45,
                "min_units": 4,
                "max_units": 6,
                "start_role": "veteran",
                "allowed_roles": ["veteran", "elite", "boss"],
                "required_roles": ["boss"],
                "role_caps": {"minion": 0, "veteran": 6, "elite": 2, "boss": 1},
                "upgrade_order": ["elite", "boss"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
        },
    },
    "goblin_tribe": {
        "ordinary": {
            "easy": {
                "budget_multiplier": 0.75,
                "min_units": 2,
                "max_units": 5,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran"],
                "required_roles": [],
                "role_caps": {"minion": 5, "veteran": 5, "elite": 0, "boss": 0},
                "upgrade_order": ["veteran"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "normal": {
                "budget_multiplier": 1.0,
                "min_units": 2,
                "max_units": 5,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran", "elite"],
                "required_roles": [],
                "role_caps": {"minion": 5, "veteran": 5, "elite": 1, "boss": 0},
                "upgrade_order": ["veteran", "elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "hard": {
                "budget_multiplier": 1.25,
                "min_units": 2,
                "max_units": 5,
                "start_role": "veteran",
                "allowed_roles": ["veteran", "elite"],
                "required_roles": [],
                "role_caps": {"minion": 0, "veteran": 5, "elite": 2, "boss": 0},
                "upgrade_order": ["elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
        },
        "guard": {
            "easy": {
                "budget_multiplier": 0.85,
                "min_units": 2,
                "max_units": 4,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran"],
                "required_roles": ["veteran"],
                "role_caps": {"minion": 4, "veteran": 2, "elite": 0, "boss": 0},
                "upgrade_order": ["veteran"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "normal": {
                "budget_multiplier": 1.1,
                "min_units": 2,
                "max_units": 5,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran", "elite"],
                "required_roles": ["veteran"],
                "role_caps": {"minion": 5, "veteran": 5, "elite": 1, "boss": 0},
                "upgrade_order": ["veteran", "elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "hard": {
                "budget_multiplier": 1.3,
                "min_units": 3,
                "max_units": 5,
                "start_role": "veteran",
                "allowed_roles": ["veteran", "elite"],
                "required_roles": ["elite"],
                "role_caps": {"minion": 0, "veteran": 5, "elite": 2, "boss": 0},
                "upgrade_order": ["elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
        },
        "boss": {
            "easy": {
                "budget_multiplier": 1.0,
                "min_units": 2,
                "max_units": 3,
                "start_role": "veteran",
                "allowed_roles": ["veteran", "elite"],
                "required_roles": ["veteran", "elite"],
                "role_caps": {"minion": 0, "veteran": 2, "elite": 1, "boss": 0},
                "upgrade_order": ["elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "normal": {
                "budget_multiplier": 1.2,
                "min_units": 2,
                "max_units": 4,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran", "elite", "boss"],
                "required_roles": ["boss"],
                "role_caps": {"minion": 4, "veteran": 3, "elite": 1, "boss": 1},
                "upgrade_order": ["veteran", "elite", "boss"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "hard": {
                "budget_multiplier": 1.45,
                "min_units": 3,
                "max_units": 5,
                "start_role": "veteran",
                "allowed_roles": ["veteran", "elite", "boss"],
                "required_roles": ["boss"],
                "role_caps": {"minion": 0, "veteran": 5, "elite": 2, "boss": 1},
                "upgrade_order": ["elite", "boss"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
        },
    },
    "wolf_pack": {
        "ordinary": {
            "easy": {
                "budget_multiplier": 0.75,
                "min_units": 2,
                "max_units": 4,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran"],
                "required_roles": [],
                "role_caps": {"minion": 4, "veteran": 4, "elite": 0, "boss": 0},
                "upgrade_order": ["veteran"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "normal": {
                "budget_multiplier": 1.0,
                "min_units": 2,
                "max_units": 4,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran", "elite"],
                "required_roles": [],
                "role_caps": {"minion": 4, "veteran": 4, "elite": 1, "boss": 0},
                "upgrade_order": ["veteran", "elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "hard": {
                "budget_multiplier": 1.25,
                "min_units": 2,
                "max_units": 4,
                "start_role": "veteran",
                "allowed_roles": ["veteran", "elite"],
                "required_roles": [],
                "role_caps": {"minion": 0, "veteran": 4, "elite": 2, "boss": 0},
                "upgrade_order": ["elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
        },
        "guard": {
            "easy": {
                "budget_multiplier": 0.85,
                "min_units": 2,
                "max_units": 3,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran"],
                "required_roles": ["veteran"],
                "role_caps": {"minion": 3, "veteran": 2, "elite": 0, "boss": 0},
                "upgrade_order": ["veteran"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "normal": {
                "budget_multiplier": 1.1,
                "min_units": 2,
                "max_units": 4,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran", "elite"],
                "required_roles": ["veteran"],
                "role_caps": {"minion": 4, "veteran": 4, "elite": 1, "boss": 0},
                "upgrade_order": ["veteran", "elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "hard": {
                "budget_multiplier": 1.3,
                "min_units": 2,
                "max_units": 4,
                "start_role": "veteran",
                "allowed_roles": ["veteran", "elite"],
                "required_roles": ["elite"],
                "role_caps": {"minion": 0, "veteran": 4, "elite": 2, "boss": 0},
                "upgrade_order": ["elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
        },
        "boss": {
            "easy": {
                "budget_multiplier": 1.0,
                "min_units": 2,
                "max_units": 3,
                "start_role": "veteran",
                "allowed_roles": ["veteran", "elite"],
                "required_roles": ["veteran", "elite"],
                "role_caps": {"minion": 0, "veteran": 2, "elite": 1, "boss": 0},
                "upgrade_order": ["elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "normal": {
                "budget_multiplier": 1.2,
                "min_units": 2,
                "max_units": 4,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran", "elite", "boss"],
                "required_roles": ["boss"],
                "role_caps": {"minion": 4, "veteran": 3, "elite": 1, "boss": 1},
                "upgrade_order": ["veteran", "elite", "boss"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "hard": {
                "budget_multiplier": 1.45,
                "min_units": 3,
                "max_units": 4,
                "start_role": "veteran",
                "allowed_roles": ["veteran", "elite", "boss"],
                "required_roles": ["boss"],
                "role_caps": {"minion": 0, "veteran": 4, "elite": 2, "boss": 1},
                "upgrade_order": ["elite", "boss"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
        },
    },
    "bandit_gang": {
        "ordinary": {
            "easy": {
                "budget_multiplier": 0.75,
                "min_units": 1,
                "max_units": 3,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran"],
                "required_roles": [],
                "role_caps": {"minion": 3, "veteran": 3, "elite": 0, "boss": 0},
                "upgrade_order": ["veteran"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "normal": {
                "budget_multiplier": 1.0,
                "min_units": 1,
                "max_units": 3,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran", "elite"],
                "required_roles": [],
                "role_caps": {"minion": 3, "veteran": 3, "elite": 1, "boss": 0},
                "upgrade_order": ["veteran", "elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "hard": {
                "budget_multiplier": 1.25,
                "min_units": 2,
                "max_units": 3,
                "start_role": "veteran",
                "allowed_roles": ["veteran", "elite"],
                "required_roles": [],
                "role_caps": {"minion": 0, "veteran": 3, "elite": 2, "boss": 0},
                "upgrade_order": ["elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
        },
        "guard": {
            "easy": {
                "budget_multiplier": 0.85,
                "min_units": 1,
                "max_units": 3,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran"],
                "required_roles": ["veteran"],
                "role_caps": {"minion": 3, "veteran": 2, "elite": 0, "boss": 0},
                "upgrade_order": ["veteran"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "normal": {
                "budget_multiplier": 1.1,
                "min_units": 2,
                "max_units": 3,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran", "elite"],
                "required_roles": ["veteran"],
                "role_caps": {"minion": 3, "veteran": 3, "elite": 1, "boss": 0},
                "upgrade_order": ["veteran", "elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "hard": {
                "budget_multiplier": 1.3,
                "min_units": 2,
                "max_units": 3,
                "start_role": "veteran",
                "allowed_roles": ["veteran", "elite"],
                "required_roles": ["elite"],
                "role_caps": {"minion": 0, "veteran": 3, "elite": 2, "boss": 0},
                "upgrade_order": ["elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
        },
        "boss": {
            "easy": {
                "budget_multiplier": 1.0,
                "min_units": 2,
                "max_units": 3,
                "start_role": "veteran",
                "allowed_roles": ["veteran", "elite"],
                "required_roles": ["veteran", "elite"],
                "role_caps": {"minion": 0, "veteran": 2, "elite": 1, "boss": 0},
                "upgrade_order": ["elite"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "normal": {
                "budget_multiplier": 1.2,
                "min_units": 2,
                "max_units": 3,
                "start_role": "minion",
                "allowed_roles": ["minion", "veteran", "elite", "boss"],
                "required_roles": ["boss"],
                "role_caps": {"minion": 3, "veteran": 2, "elite": 1, "boss": 1},
                "upgrade_order": ["veteran", "elite", "boss"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
            "hard": {
                "budget_multiplier": 1.45,
                "min_units": 2,
                "max_units": 3,
                "start_role": "veteran",
                "allowed_roles": ["veteran", "elite", "boss"],
                "required_roles": ["boss"],
                "role_caps": {"minion": 0, "veteran": 3, "elite": 2, "boss": 1},
                "upgrade_order": ["elite", "boss"],
                "allow_repeated_members": True,
                "prefer_distinct_members": True,
            },
        },
    },
}


def get_monster_encounter_profile(
    family_id: str,
    kind: EncounterKind,
    difficulty: EncounterDifficulty,
) -> MonsterEncounterProfile | None:
    family_profiles = MONSTER_ENCOUNTER_PROFILES.get(family_id)
    if family_profiles is None:
        return None
    kind_profiles = family_profiles.get(kind)
    if kind_profiles is None:
        return None
    profile = kind_profiles.get(difficulty)
    return deepcopy(profile) if profile is not None else None


__all__ = [
    "EncounterDifficulty",
    "EncounterKind",
    "MONSTER_ENCOUNTER_PROFILES",
    "MonsterEncounterProfile",
    "MonsterRole",
    "get_monster_encounter_profile",
]
