from src.backend.features.items.resources.schemas import BaseItemDTO

HEAVY_ARMOR_DB = {
    "helmet": BaseItemDTO(
        id="helmet",
        name_ru="Шлем",
        narrative_description="Закрывает голову от скользящих ударов и случайных осколков.",
        slot="head_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_heavy_armor",
        armor_class="heavy",
        allowed_materials=["ingots"],
        base_power=4,
        base_durability=60,
        damage_spread=0.0,
        narrative_tags=["helmet", "heavy", "visor", "protection"],
        implicit_bonuses={
            "evasion_penalty": -0.02,
        },
    ),
    "plate_chest": BaseItemDTO(
        id="plate_chest",
        name_ru="Кираса",
        narrative_description="Тяжелая металлическая кираса принимает основной удар корпусом и почти не прощает слабую стойку.",
        slot="chest_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_heavy_armor",
        armor_class="heavy",
        allowed_materials=["ingots"],
        base_power=10,
        base_durability=100,
        damage_spread=0.0,
        narrative_tags=["plate", "heavy", "metal"],
        implicit_bonuses={
            "evasion_penalty": -0.15,
            "thorns_damage_flat": 1.0,
        },
    ),
    "scale_mail": BaseItemDTO(
        id="scale_mail",
        name_ru="Чешуйчатая броня",
        narrative_description="Слой перекрывающихся пластин дает тяжелую защиту, но остается гибче цельной плиты.",
        slot="chest_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_heavy_armor",
        armor_class="heavy",
        allowed_materials=["ingots", "leathers"],
        base_power=8,
        base_durability=85,
        damage_spread=0.0,
        narrative_tags=["scale_mail", "heavy", "layered"],
        implicit_bonuses={
            "evasion_penalty": -0.10,
            "bleed_resistance": 0.08,
        },
    ),
    "gauntlets": BaseItemDTO(
        id="gauntlets",
        name_ru="Латные рукавицы",
        narrative_description="Жесткие рукавицы защищают кисти и добавляют вес каждому силовому удару.",
        slot="arms_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_heavy_armor",
        armor_class="heavy",
        allowed_materials=["ingots"],
        base_power=3,
        damage_spread=0.0,
        base_durability=70,
        narrative_tags=["gauntlets", "heavy", "hands", "plate"],
        implicit_bonuses={
            "physical_damage_bonus": 0.04,
            "evasion_penalty": -0.02,
        },
    ),
    "greaves": BaseItemDTO(
        id="greaves",
        name_ru="Поножи",
        narrative_description="Тяжелые поножи прикрывают голени и помогают держать стойку под давлением.",
        slot="legs_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_heavy_armor",
        armor_class="heavy",
        allowed_materials=["ingots"],
        base_power=4,
        damage_spread=0.0,
        base_durability=80,
        narrative_tags=["greaves", "heavy", "legs", "plate"],
        implicit_bonuses={
            "evasion_penalty": -0.04,
        },
    ),
    "sabatons": BaseItemDTO(
        id="sabatons",
        name_ru="Латные сапоги",
        narrative_description="Металлическая обувь для тяжелой стойки и защиты стоп на плохой земле.",
        slot="feetwear",
        type="armor",
        defense_type="physical",
        related_skill="skill_heavy_armor",
        armor_class="heavy",
        allowed_materials=["ingots"],
        base_power=3,
        damage_spread=0.0,
        base_durability=70,
        narrative_tags=["sabatons", "heavy", "feetwear", "plate"],
        implicit_bonuses={
            "shock_resistance": 0.10,
            "evasion_penalty": -0.03,
        },
    ),
}

__all__ = ["HEAVY_ARMOR_DB"]
