from src.backend.features.items.resources.schemas import BaseItemDTO

HEAVY_ARMOR_DB = {
    "helmet": BaseItemDTO(
        id="helmet",
        name_ru="Шлем",
        narrative_description="Тяжелый шлем закрывает голову от скользящих ударов и помогает удержать контроль под давлением.",
        slot="head_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_heavy_armor",
        armor_class="heavy",
        allowed_materials=["ingots"],
        base_power=3,
        base_durability=60,
        damage_spread=0.0,
        narrative_tags=["helmet", "heavy", "visor", "protection"],
        implicit_bonuses={
            "anti_dodge_chance": -0.020,
            "main_hand_accuracy_penalty": 0.005,
        },
    ),
    "plate_chest": BaseItemDTO(
        id="plate_chest",
        name_ru="Кираса",
        narrative_description="Тяжелая металлическая кираса принимает основной удар корпусом и почти не прощает слабую стойку.",
        slot="chest_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_heavy_armor",
        armor_class="heavy",
        allowed_materials=["ingots"],
        base_power=9,
        base_durability=100,
        damage_spread=0.0,
        narrative_tags=["plate", "heavy", "metal"],
        implicit_bonuses={
            "evasion_penalty": -0.070,
            "main_hand_accuracy_penalty": 0.015,
            "off_hand_accuracy_penalty": 0.015,
        },
    ),
    "gauntlets": BaseItemDTO(
        id="gauntlets",
        name_ru="Латные рукавицы",
        narrative_description="Жесткие рукавицы защищают кисти и превращают плотную оборону в болезненный контакт.",
        slot="arms_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_heavy_armor",
        armor_class="heavy",
        allowed_materials=["ingots"],
        base_power=3,
        damage_spread=0.0,
        base_durability=70,
        narrative_tags=["gauntlets", "heavy", "hands", "plate"],
        implicit_bonuses={
            "main_hand_accuracy_penalty": 0.015,
            "off_hand_accuracy_penalty": 0.015,
        },
    ),
    "greaves": BaseItemDTO(
        id="greaves",
        name_ru="Поножи",
        narrative_description="Тяжелые поножи прикрывают ноги и помогают удержать стойку после жесткого попадания.",
        slot="legs_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_heavy_armor",
        armor_class="heavy",
        allowed_materials=["ingots"],
        base_power=5,
        damage_spread=0.0,
        base_durability=80,
        narrative_tags=["greaves", "heavy", "legs", "plate"],
        implicit_bonuses={
            "evasion_penalty": -0.025,
        },
    ),
}
