from src.backend.features.items.resources.schemas import BaseItemDTO

LIGHT_ARMOR_DB = {
    "hood": BaseItemDTO(
        id="hood",
        name_ru="Капюшон разведчика",
        narrative_description="Легкий капюшон закрывает голову, не мешая обзору и быстрым уходам с линии удара.",
        slot="head_armor",
        type="armor",
        defense_type="magical",
        related_skill="skill_light_armor",
        armor_class="light",
        allowed_materials=["cloths", "leathers"],
        base_power=2,
        base_durability=30,
        damage_spread=0.0,
        narrative_tags=["hood", "light", "scout"],
        implicit_bonuses={
            "anti_dodge_chance": -0.005,
        },
    ),
    "leather_armor": BaseItemDTO(
        id="leather_armor",
        name_ru="Легкий кожаный доспех",
        narrative_description="Подогнанный кожаный доспех для бойца, который переживает удар за счет движения.",
        slot="chest_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_light_armor",
        armor_class="light",
        allowed_materials=["leathers"],
        base_power=4,
        base_durability=45,
        damage_spread=0.0,
        narrative_tags=["leather_armor", "light", "mobile", "scout"],
        implicit_bonuses={
            "evasion_penalty": -0.010,
        },
    ),
    "soft_bracers": BaseItemDTO(
        id="soft_bracers",
        name_ru="Мягкие наручи",
        narrative_description="Гибкие наручи защищают предплечья, сохраняя свободу для ответного движения.",
        slot="arms_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_light_armor",
        armor_class="light",
        allowed_materials=["cloths", "leathers"],
        base_power=2,
        base_durability=35,
        damage_spread=0.0,
        narrative_tags=["bracers", "light", "mobile"],
        implicit_bonuses={
            "main_hand_accuracy_penalty": 0.005,
            "off_hand_accuracy_penalty": 0.005,
        },
    ),
    "scout_leggings": BaseItemDTO(
        id="scout_leggings",
        name_ru="Поножи разведчика",
        narrative_description="Легкая защита бедер и коленей для быстрых шагов, перекатов и смены дистанции.",
        slot="legs_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_light_armor",
        armor_class="light",
        allowed_materials=["cloths", "leathers"],
        base_power=2,
        base_durability=35,
        damage_spread=0.0,
        narrative_tags=["leggings", "light", "scout"],
        implicit_bonuses={},
    ),
}
