from src.backend.features.items.resources.schemas import BaseItemDTO

LIGHT_ARMOR_DB = {
    "hood": BaseItemDTO(
        id="hood",
        name_ru="Капюшон",
        narrative_description="Мягкий капюшон прикрывает голову и удерживает слабую магическую защиту.",
        slot="head_armor",
        type="armor",
        defense_type="magical",
        related_skill="skill_light_armor",
        armor_class="light",
        allowed_materials=["cloths"],
        base_power=1,
        base_durability=30,
        damage_spread=0.0,
        narrative_tags=["hood", "light", "cloth"],
        implicit_bonuses={
            "magical_resistance": 0.05,
            "debuff_avoidance": 0.03,
        },
    ),
    "robe": BaseItemDTO(
        id="robe",
        name_ru="Мантия",
        narrative_description="Свободная мантия почти не сковывает движения и удерживает магический резонанс.",
        slot="chest_armor",
        type="armor",
        defense_type="magical",
        related_skill="skill_light_armor",
        armor_class="light",
        allowed_materials=["cloths"],
        base_power=2,
        base_durability=40,
        damage_spread=0.0,
        narrative_tags=["robe", "light", "cloth", "resonance"],
        implicit_bonuses={
            "magical_resistance": 0.10,
            "evasion": 0.05,
        },
    ),
    "leather_armor": BaseItemDTO(
        id="leather_armor",
        name_ru="Легкий кожаный доспех",
        narrative_description="Легкий кожаный доспех для тех, кто выбирает подвижность вместо массы.",
        slot="chest_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_light_armor",
        armor_class="light",
        allowed_materials=["leathers"],
        base_power=3,
        base_durability=45,
        damage_spread=0.0,
        narrative_tags=["leather_armor", "light", "mobile", "scout"],
        implicit_bonuses={
            "evasion": 0.10,
            "counter_attack_chance": 0.05,
        },
    ),
    "sandals": BaseItemDTO(
        id="sandals",
        name_ru="Сандалии",
        narrative_description="Легкие сандалии подходят для сухой земли и быстрой, бесшумной походки.",
        slot="feetwear",
        type="armor",
        defense_type="magical",
        related_skill="skill_light_armor",
        armor_class="light",
        allowed_materials=["cloths", "leathers"],
        base_power=1,
        base_durability=25,
        damage_spread=0.0,
        narrative_tags=["sandals", "light", "footwear"],
        implicit_bonuses={
            "evasion": 0.05,
            "environment_heat_resistance": 2.0,
        },
    ),
}

__all__ = ["LIGHT_ARMOR_DB"]
