from src.backend.features.items.resources.schemas import BaseItemDTO

MEDIUM_ARMOR_DB = {
    "goggles": BaseItemDTO(
        id="goggles",
        name_ru="Защитные очки",
        narrative_description="Простые очки против пыли, искр и мелких осколков, оставляющие обзор открытым.",
        slot="head_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_medium_armor",
        armor_class="medium",
        allowed_materials=["leathers", "ingots"],
        base_power=1,
        damage_spread=0.0,
        base_durability=30,
        narrative_tags=["goggles", "medium", "engineer", "vision"],
        implicit_bonuses={
            "physical_accuracy": 0.05,
        },
    ),
    "leather_cap": BaseItemDTO(
        id="leather_cap",
        name_ru="Кожаный шлем",
        narrative_description="Легкий кожаный шлем не закрывает обзор и смягчает слабые удары.",
        slot="head_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_medium_armor",
        armor_class="medium",
        allowed_materials=["leathers"],
        base_power=2,
        base_durability=40,
        damage_spread=0.0,
        narrative_tags=["cap", "medium", "leather"],
        implicit_bonuses={
            "physical_accuracy": 0.04,
        },
    ),
    "jerkin": BaseItemDTO(
        id="jerkin",
        name_ru="Куртка",
        narrative_description="Плотная кожаная куртка защищает корпус, почти не мешая разворотам и коротким рывкам.",
        slot="chest_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_medium_armor",
        armor_class="medium",
        allowed_materials=["leathers"],
        base_power=5,
        damage_spread=0.0,
        base_durability=60,
        narrative_tags=["jerkin", "medium", "leather", "scout"],
        implicit_bonuses={
            "evasion": 0.04,
            "physical_crit_chance": 0.03,
            "bleed_resistance": 0.08,
        },
    ),
    "chainmail": BaseItemDTO(
        id="chainmail",
        name_ru="Кольчуга",
        narrative_description="Гибкая кольчуга гасит разрезы и оставляет телу свободу движения.",
        slot="chest_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_medium_armor",
        armor_class="medium",
        allowed_materials=["ingots"],
        base_power=7,
        base_durability=75,
        damage_spread=0.0,
        narrative_tags=["chainmail", "medium", "rings"],
        implicit_bonuses={
            "bleed_resistance": 0.10,
            "evasion_penalty": -0.03,
        },
    ),
    "brigandine": BaseItemDTO(
        id="brigandine",
        name_ru="Бригантина",
        narrative_description="Кожаная основа с заклепанными пластинами дает сбалансированную защиту без полной тяжести лат.",
        slot="chest_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_medium_armor",
        armor_class="medium",
        allowed_materials=["leathers", "ingots"],
        base_power=6,
        base_durability=70,
        damage_spread=0.0,
        narrative_tags=["brigandine", "medium", "balanced"],
        implicit_bonuses={
            "evasion_penalty": -0.04,
            "bleed_resistance": 0.06,
        },
    ),
    "breeches": BaseItemDTO(
        id="breeches",
        name_ru="Прочные штаны",
        narrative_description="Усиленные кожей штаны для движения по руинам, грязи и острым обломкам.",
        slot="legs_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_medium_armor",
        armor_class="medium",
        allowed_materials=["leathers"],
        base_power=2,
        damage_spread=0.0,
        base_durability=45,
        narrative_tags=["breeches", "medium", "pants", "travel"],
        implicit_bonuses={
            "evasion": 0.02,
        },
    ),
    "boots": BaseItemDTO(
        id="boots",
        name_ru="Сапоги",
        narrative_description="Плотные сапоги защищают ноги на камне, грязи и обломках.",
        slot="feetwear",
        type="armor",
        defense_type="physical",
        related_skill="skill_medium_armor",
        armor_class="medium",
        allowed_materials=["leathers"],
        base_power=2,
        base_durability=50,
        damage_spread=0.0,
        narrative_tags=["boots", "medium", "travel"],
        implicit_bonuses={
            "evasion": 0.04,
        },
    ),
}

__all__ = ["MEDIUM_ARMOR_DB"]
