from src.backend.features.items.resources.schemas import BaseItemDTO

MEDIUM_ARMOR_DB = {
    "leather_cap": BaseItemDTO(
        id="leather_cap",
        name_ru="Кожаный шлем",
        narrative_description="Усиленный кожаный шлем оставляет обзор открытым и помогает держать защитную стойку.",
        slot="head_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_medium_armor",
        armor_class="medium",
        allowed_materials=["leathers"],
        base_power=1,
        base_durability=40,
        damage_spread=0.0,
        narrative_tags=["cap", "medium", "leather"],
        implicit_bonuses={
            "anti_dodge_chance": -0.010,
        },
    ),
    "jerkin": BaseItemDTO(
        id="jerkin",
        name_ru="Куртка",
        narrative_description="Плотная кожаная куртка принимает слабые удары корпусом, не ломая темп боя полностью.",
        slot="chest_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_medium_armor",
        armor_class="medium",
        allowed_materials=["leathers"],
        base_power=4,
        damage_spread=0.0,
        base_durability=60,
        narrative_tags=["jerkin", "medium", "leather", "balanced"],
        implicit_bonuses={
            "evasion_penalty": -0.030,
            "main_hand_accuracy_penalty": 0.010,
        },
    ),
    "reinforced_gloves": BaseItemDTO(
        id="reinforced_gloves",
        name_ru="Усиленные перчатки",
        narrative_description="Жесткие вставки на перчатках помогают принять оружие на руку и сразу ответить.",
        slot="arms_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_medium_armor",
        armor_class="medium",
        allowed_materials=["leathers", "ingots"],
        base_power=1,
        damage_spread=0.0,
        base_durability=45,
        narrative_tags=["gloves", "medium", "reinforced"],
        implicit_bonuses={
            "main_hand_accuracy_penalty": 0.010,
            "off_hand_accuracy_penalty": 0.010,
        },
    ),
    "breeches": BaseItemDTO(
        id="breeches",
        name_ru="Прочные штаны",
        narrative_description="Усиленные кожей штаны для движения по руинам, грязи и острым обломкам.",
        slot="legs_armor",
        type="armor",
        defense_type="physical",
        related_skill="skill_medium_armor",
        armor_class="medium",
        allowed_materials=["leathers"],
        base_power=2,
        damage_spread=0.0,
        base_durability=45,
        narrative_tags=["breeches", "medium", "pants", "travel"],
        implicit_bonuses={},
    ),
}
