"""initial_scenario_refactoring

Revision ID: 17c737fe4c7c
Revises:
Create Date: 2026-04-30 10:04:19.529060

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "17c737fe4c7c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scenario_master",
        sa.Column("display_name", sa.String(length=255), server_default="Unknown Quest", nullable=False),
    )
    op.add_column("scenario_nodes", sa.Column("display_name", sa.String(length=255), nullable=True))
    op.add_column("scenario_nodes", sa.Column("text", sa.String(), server_default="", nullable=False))
    op.add_column("scenario_nodes", sa.Column("icon", sa.String(length=50), nullable=True))
    op.add_column(
        "scenario_nodes",
        sa.Column("alerts", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scenario_nodes", "alerts")
    op.drop_column("scenario_nodes", "icon")
    op.drop_column("scenario_nodes", "text")
    op.drop_column("scenario_nodes", "display_name")
    op.drop_column("scenario_master", "display_name")
    # ### end Alembic commands ###
