"""add_character_avatar

Revision ID: 304e1d662a7a
Revises: 17c737fe4c7c
Create Date: 2026-04-30 23:12:04.143665

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "304e1d662a7a"  # pragma: allowlist secret
down_revision: str | Sequence[str] | None = "17c737fe4c7c"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("characters", sa.Column("avatar_url", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters", "avatar_url")
    # ### end Alembic commands ###
