"""fix_scenario_nodes_schema

Revision ID: d0014c57f7f6
Revises: 304e1d662a7a
Create Date: 2026-05-01 11:52:26.875974

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d0014c57f7f6"
down_revision: str | Sequence[str] | None = "304e1d662a7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scenario_nodes",
        sa.Column("system_messages", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
    )
    op.drop_column("scenario_nodes", "alerts")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scenario_nodes",
        sa.Column(
            "alerts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("scenario_nodes", "system_messages")
    # ### end Alembic commands ###
