"""
СЕМЕЙСТВО: АБЕРРАЦИИ / ПУСТОТА (Психика, искажение, безумие)
============================================================
Логика: искажение -> безумие -> поглощение
"""

from ..monster_structs import MonsterFamily

ABERRATIONS_FAMILY: MonsterFamily = {
    "id": "void_spawn",
    "archetype": "demon",
    "organization_type": "solitary",  # TSP Base: 100
    "default_tags": ["aberration", "void", "eldritch", "psychic"],
    "hierarchy": {
        "minions": ["void_leech", "gazer", "flesh_crawler"],
        "veterans": ["tentacle_beast", "mind_flayer_initiate", "shifter"],
        "elites": ["shambling_horror", "void_walker", "reality_warper"],
        "boss": ["elder_brain", "cosmic_horror", "gate_of_madness"],
    },
    "variants": {
        # --- 1. Мелкие ужасы (Minions) [TSP ~100] ---
        "void_leech": {
            "id": "void_leech",
            "role": "minion",
            "cost": 20,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A floating, slug-like creature that drains mental energy.",
            "extra_tags": ["leech", "psychic"],
            "base_stats": {
                "strength": 10,
                "agility": 20,
                "endurance": 15,
                "intellect": 20,
                "memory": 15,
                "mental": 30,
                "perception": 20,
                "projection": 1,
                "prediction": 5,  # Итого: 136
            },
            "fixed_loadout": {},
            "skills": ["attack_lifesteal", "debuff_weaken"],
        },
        "gazer": {
            "id": "gazer",
            "role": "minion",
            "cost": 20,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A floating eyeball held aloft by smaller, twitching eyes. Its gaze causes confusion.",
            "extra_tags": ["gazer", "beholderkin"],
            "base_stats": {
                "strength": 5,
                "agility": 25,
                "endurance": 10,
                "intellect": 25,
                "memory": 20,
                "mental": 30,
                "perception": 40,
                "projection": 1,
                "prediction": 5,  # Итого: 161
            },
            "fixed_loadout": {},
            "skills": ["attack_ranged", "debuff_stun"],
        },
        "flesh_crawler": {
            "id": "flesh_crawler",
            "role": "minion",
            "cost": 20,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A mass of flesh and limbs that drags itself across the ground.",
            "extra_tags": ["flesh", "amorphous"],
            "base_stats": {
                "strength": 25,
                "agility": 15,
                "endurance": 25,
                "intellect": 1,
                "memory": 1,
                "mental": 20,
                "perception": 20,
                "projection": 1,
                "prediction": 5,  # Итого: 113
            },
            "fixed_loadout": {},
            "skills": ["attack_heavy", "debuff_slow"],
        },
        # --- 2. Опытные кошмары (Veterans) [TSP ~150] ---
        "tentacle_beast": {
            "id": "tentacle_beast",
            "role": "veteran",
            "cost": 50,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A creature composed of writhing tentacles. It grabs and crushes.",
            "extra_tags": ["tentacles", "grappler"],
            "base_stats": {
                "strength": 35,
                "agility": 25,
                "endurance": 30,
                "intellect": 10,
                "memory": 10,
                "mental": 25,
                "perception": 30,
                "projection": 1,
                "prediction": 5,  # Итого: 171
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "debuff_stun"],
        },
        "mind_flayer_initiate": {
            "id": "mind_flayer_initiate",
            "role": "veteran",
            "cost": 50,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A humanoid figure with facial tentacles, learning to blast minds.",
            "extra_tags": ["mind_flayer", "psychic"],
            "base_stats": {
                "strength": 20,
                "agility": 20,
                "endurance": 20,
                "intellect": 35,
                "memory": 30,
                "mental": 50,
                "perception": 35,
                "projection": 10,
                "prediction": 5,  # Итого: 225 (псионик)
            },
            "fixed_loadout": {},
            "skills": ["attack_ranged", "attack_ranged"],
        },
        "shifter": {
            "id": "shifter",
            "role": "veteran",
            "cost": 50,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A creature that constantly changes its shape, making it hard to hit.",
            "extra_tags": ["shapeshifter", "unstable"],
            "base_stats": {
                "strength": 25,
                "agility": 35,
                "endurance": 25,
                "intellect": 15,
                "memory": 15,
                "mental": 30,
                "perception": 30,
                "projection": 1,
                "prediction": 25,  # Итого: 201
            },
            "fixed_loadout": {},
            "skills": ["buff_evasion", "special_unique"],
        },
        # --- 3. Элита (Elites) [TSP ~250] ---
        "shambling_horror": {
            "id": "shambling_horror",
            "role": "elite",
            "cost": 150,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A large, amorphous blob of eyes, mouths, and limbs. Its presence inspires madness.",
            "extra_tags": ["amorphous", "terror"],
            "base_stats": {
                "strength": 45,
                "agility": 15,
                "endurance": 55,
                "intellect": 20,
                "memory": 20,
                "mental": 60,
                "perception": 40,
                "projection": 1,
                "prediction": 5,  # Итого: 261
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "debuff_weaken", "debuff_weaken"],
        },
        "void_walker": {
            "id": "void_walker",
            "role": "elite",
            "cost": 150,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "A humanoid silhouette made of pure darkness, seemingly absorbing light.",
            "extra_tags": ["void", "shadow", "teleport"],
            "base_stats": {
                "strength": 35,
                "agility": 40,
                "endurance": 35,
                "intellect": 25,
                "memory": 25,
                "mental": 50,
                "perception": 35,
                "projection": 1,
                "prediction": 20,  # Итого: 266
            },
            "fixed_loadout": {},
            "skills": ["stealth", "attack_heavy", "debuff_blind"],
        },
        "reality_warper": {
            "id": "reality_warper",
            "role": "elite",
            "cost": 150,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "A creature that bends space around it, causing attacks to miss.",
            "extra_tags": ["magic", "reality_bender"],
            "base_stats": {
                "strength": 25,
                "agility": 30,
                "endurance": 40,
                "intellect": 40,
                "memory": 35,
                "mental": 70,
                "perception": 45,
                "projection": 1,
                "prediction": 30,  # Итого: 316
            },
            "fixed_loadout": {},
            "skills": ["buff_reflect", "special_unique", "debuff_slow"],
        },
        # --- 4. Неописуемое (Bosses) [TSP ~400] ---
        "elder_brain": {
            "id": "elder_brain",
            "role": "boss",
            "cost": 600,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "A massive, pulsating brain in a vat of fluid. It commands all lesser creatures with its mind.",
            "extra_tags": ["leader", "psychic", "stationary"],
            "base_stats": {
                "strength": 10,
                "agility": 0,
                "endurance": 100,
                "intellect": 100,
                "memory": 80,
                "mental": 200,
                "perception": 80,
                "projection": 20,
                "prediction": 20,  # Итого: 610 (псионик)
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "debuff_stun", "summon_minion", "debuff_weaken"],
        },
        "cosmic_horror": {
            "id": "cosmic_horror",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 7,
            "narrative_hint": "A being from beyond the stars, its form incomprehensible to the mortal mind.",
            "extra_tags": ["eldritch", "terror", "colossal"],
            "base_stats": {
                "strength": 80,
                "agility": 25,
                "endurance": 120,
                "intellect": 60,
                "memory": 60,
                "mental": 150,
                "perception": 50,
                "projection": 1,
                "prediction": 10,  # Итого: 556
            },
            "fixed_loadout": {},
            "skills": ["special_unique", "special_unique", "attack_aoe"],
        },
        "gate_of_madness": {
            "id": "gate_of_madness",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 7,
            "narrative_hint": "Not a creature, but a living portal to the void, spawning horrors and driving viewers insane.",
            "extra_tags": ["portal", "summoner", "stationary"],
            "base_stats": {
                "strength": 0,
                "agility": 0,
                "endurance": 150,
                "intellect": 50,
                "memory": 50,
                "mental": 250,
                "perception": 50,
                "projection": 1,
                "prediction": 50,  # Итого: 601
            },
            "fixed_loadout": {},
            "skills": ["summon_minion", "summon_minion", "debuff_weaken", "debuff_stun"],
        },
    },
}
