"""
СЕМЕЙСТВО: АНГЕЛЫ (Свет, порядок, контроль)
===========================================
Логика: свет -> порядок -> контроль
"""

from ..monster_structs import MonsterFamily

ANGELS_FAMILY: MonsterFamily = {
    "id": "angelic_host",
    "archetype": "humanoid",
    "organization_type": "legion",  # TSP Base: 70
    "default_tags": ["angel", "light", "holy", "order"],
    "hierarchy": {
        "minions": ["cherubim", "light_warden", "guardian_spirit", "seraphic_scout"],
        "veterans": ["angelic_soldier", "swordbearer", "lumina_knight", "sky_sentinel"],
        "elites": ["seraph_knight", "high_guardian", "light_marshal", "celestial_champion"],
        "boss": ["archangel", "radiant_overlord", "dawnbringer", "seraphic_lord"],
    },
    "variants": {
        # --- 1. Мелкие (Minions) [TSP ~70] ---
        "cherubim": {
            "id": "cherubim",
            "role": "minion",
            "cost": 20,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A small, winged figure with a child-like face. Radiates a soft glow.",
            "extra_tags": ["support", "healer", "ranged"],
            "base_stats": {
                "strength": 4,
                "agility": 12,
                "endurance": 6,
                "intellect": 10,
                "memory": 10,
                "mental": 10,
                "perception": 10,
                "projection": 10,
                "prediction": 5,  # Итого: 77
            },
            "fixed_loadout": {},
            "skills": ["attack_ranged", "buff_heal", "buff_rage"],
        },
        "light_warden": {
            "id": "light_warden",
            "role": "minion",
            "cost": 20,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A floating construct of light and armor. Guards sacred places.",
            "extra_tags": ["construct", "guardian"],
            "base_stats": {
                "strength": 12,
                "agility": 8,
                "endurance": 14,
                "intellect": 6,
                "memory": 6,
                "mental": 15,
                "perception": 10,
                "projection": 5,
                "prediction": 2,  # Итого: 78
            },
            "fixed_loadout": {"main_hand": "spear", "chest_armor": "plate_chest"},
            "skills": ["attack_ranged", "buff_defense"],
        },
        "guardian_spirit": {
            "id": "guardian_spirit",
            "role": "minion",
            "cost": 20,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A translucent spirit in the shape of a warrior. Immune to fear.",
            "extra_tags": ["spirit", "ethereal"],
            "base_stats": {
                "strength": 10,
                "agility": 10,
                "endurance": 10,
                "intellect": 8,
                "memory": 8,
                "mental": 20,
                "perception": 8,
                "projection": 5,
                "prediction": 2,  # Итого: 81
            },
            "fixed_loadout": {"main_hand": "sword"},
            "skills": ["attack_basic", "buff_defense"],
        },
        "seraphic_scout": {
            "id": "seraphic_scout",
            "role": "minion",
            "cost": 20,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A swift angel with four wings. Watches from above.",
            "extra_tags": ["scout", "fast", "flying"],
            "base_stats": {
                "strength": 8,
                "agility": 18,
                "endurance": 8,
                "intellect": 8,
                "memory": 8,
                "mental": 10,
                "perception": 16,
                "projection": 5,
                "prediction": 5,  # Итого: 86
            },
            "fixed_loadout": {"main_hand": "bow"},
            "skills": ["attack_ranged"],
        },
        # --- 2. Стражи / Бойцы (Veterans) [TSP ~105] ---
        "angelic_soldier": {
            "id": "angelic_soldier",
            "role": "veteran",
            "cost": 50,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A disciplined warrior of light in shining armor.",
            "extra_tags": ["soldier", "infantry", "shield"],
            "base_stats": {
                "strength": 16,
                "agility": 12,
                "endurance": 16,
                "intellect": 8,
                "memory": 8,
                "mental": 15,
                "perception": 10,
                "projection": 8,
                "prediction": 5,  # Итого: 98
            },
            "fixed_loadout": {
                "main_hand": "sword",
                "off_hand": "shield",
                "chest_armor": "plate_chest",
                "head_armor": "helmet",
            },
            "skills": ["attack_heavy", "debuff_stun", "buff_defense"],
        },
        "swordbearer": {
            "id": "swordbearer",
            "role": "veteran",
            "cost": 50,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "An angel wielding a massive flaming sword.",
            "extra_tags": ["fire", "greatsword"],
            "base_stats": {
                "strength": 20,
                "agility": 14,
                "endurance": 14,
                "intellect": 8,
                "memory": 8,
                "mental": 15,
                "perception": 10,
                "projection": 8,
                "prediction": 5,  # Итого: 102
            },
            "fixed_loadout": {"main_hand": "greatsword", "chest_armor": "plate_chest"},
            "skills": ["debuff_burn", "attack_aoe"],
        },
        "lumina_knight": {
            "id": "lumina_knight",
            "role": "veteran",
            "cost": 50,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A knight whose armor is made of solidified light.",
            "extra_tags": ["knight", "light", "tank"],
            "base_stats": {
                "strength": 14,
                "agility": 10,
                "endurance": 20,
                "intellect": 10,
                "memory": 10,
                "mental": 20,
                "perception": 10,
                "projection": 10,
                "prediction": 5,  # Итого: 109
            },
            "fixed_loadout": {"main_hand": "mace", "off_hand": "shield"},
            "skills": ["debuff_blind", "attack_aoe", "buff_heal"],
        },
        "sky_sentinel": {
            "id": "sky_sentinel",
            "role": "veteran",
            "cost": 50,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "An angel with powerful wings and a long spear. Dives into battle.",
            "extra_tags": ["flying", "sentinel"],
            "base_stats": {
                "strength": 16,
                "agility": 18,
                "endurance": 14,
                "intellect": 8,
                "memory": 8,
                "mental": 15,
                "perception": 14,
                "projection": 8,
                "prediction": 5,  # Итого: 106
            },
            "fixed_loadout": {"main_hand": "spear", "chest_armor": "plate_chest"},
            "skills": ["attack_heavy", "attack_pierce", "attack_aoe"],
        },
        # --- 3. Элита (Elites) [TSP ~175] ---
        "seraph_knight": {
            "id": "seraph_knight",
            "role": "elite",
            "cost": 150,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "A high-ranking angel with six wings. Wields dual blades of light.",
            "extra_tags": ["seraph", "knight", "dual_wield"],
            "base_stats": {
                "strength": 25,
                "agility": 25,
                "endurance": 20,
                "intellect": 15,
                "memory": 15,
                "mental": 25,
                "perception": 15,
                "projection": 15,
                "prediction": 10,  # Итого: 165
            },
            "fixed_loadout": {"main_hand": "sword", "off_hand": "sword", "chest_armor": "plate_chest"},
            "skills": ["attack_fast", "debuff_burn", "attack_execute"],
        },
        "high_guardian": {
            "id": "high_guardian",
            "role": "elite",
            "cost": 150,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "A towering figure in golden armor. An immovable object.",
            "extra_tags": ["guardian", "heavy_armor", "unbreakable"],
            "base_stats": {
                "strength": 30,
                "agility": 10,
                "endurance": 40,
                "intellect": 10,
                "memory": 10,
                "mental": 30,
                "perception": 10,
                "projection": 10,
                "prediction": 5,  # Итого: 155 (но броня)
            },
            "fixed_loadout": {"main_hand": "warhammer", "off_hand": "tower_shield", "chest_armor": "plate_chest"},
            "skills": ["buff_defense", "attack_heavy", "buff_defense"],
        },
        "light_marshal": {
            "id": "light_marshal",
            "role": "elite",
            "cost": 150,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "A commander of the angelic host. Inspires allies with his presence.",
            "extra_tags": ["marshal", "commander", "aura"],
            "base_stats": {
                "strength": 20,
                "agility": 15,
                "endurance": 25,
                "intellect": 20,
                "memory": 20,
                "mental": 30,
                "perception": 20,
                "projection": 25,
                "prediction": 10,  # Итого: 185
            },
            "fixed_loadout": {"main_hand": "sword", "chest_armor": "plate_chest", "head_armor": "helmet"},
            "skills": ["buff_rage", "buff_rage", "buff_heal"],
        },
        "celestial_champion": {
            "id": "celestial_champion",
            "role": "elite",
            "cost": 150,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "The champion of the heavens. A perfect warrior.",
            "extra_tags": ["champion", "celestial"],
            "base_stats": {
                "strength": 35,
                "agility": 20,
                "endurance": 30,
                "intellect": 15,
                "memory": 15,
                "mental": 25,
                "perception": 15,
                "projection": 20,
                "prediction": 10,  # Итого: 185
            },
            "fixed_loadout": {"main_hand": "greatsword", "chest_armor": "plate_chest"},
            "skills": ["attack_aoe", "attack_execute", "buff_heal"],
        },
        # --- 4. Архангелы / Боссы (Bosses) [TSP ~280] ---
        "archangel": {
            "id": "archangel",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 7,
            "narrative_hint": "A being of pure light and power. His voice sounds like thunder.",
            "extra_tags": ["archangel", "leader"],
            "base_stats": {
                "strength": 40,
                "agility": 30,
                "endurance": 40,
                "intellect": 30,
                "memory": 30,
                "mental": 50,
                "perception": 30,
                "projection": 40,
                "prediction": 20,  # Итого: 310
            },
            "fixed_loadout": {"main_hand": "flaming_sword"},
            "skills": ["attack_aoe", "attack_execute", "summon_minion"],
        },
        "radiant_overlord": {
            "id": "radiant_overlord",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 7,
            "narrative_hint": "A ruler of a celestial realm. Blinds enemies with his radiance.",
            "extra_tags": ["overlord", "radiant", "ruler"],
            "base_stats": {
                "strength": 30,
                "agility": 20,
                "endurance": 50,
                "intellect": 40,
                "memory": 40,
                "mental": 60,
                "perception": 30,
                "projection": 40,
                "prediction": 20,  # Итого: 330
            },
            "fixed_loadout": {"main_hand": "scepter"},
            "skills": ["debuff_blind", "attack_aoe", "special_unique", "attack_execute"],
        },
        "dawnbringer": {
            "id": "dawnbringer",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 7,
            "narrative_hint": "The herald of the dawn. Brings hope to allies and destruction to enemies.",
            "extra_tags": ["herald", "dawn"],
            "base_stats": {
                "strength": 50,
                "agility": 30,
                "endurance": 50,
                "intellect": 25,
                "memory": 25,
                "mental": 40,
                "perception": 30,
                "projection": 40,
                "prediction": 25,  # Итого: 315
            },
            "fixed_loadout": {"main_hand": "morningstar"},
            "skills": ["attack_heavy", "attack_aoe", "buff_heal", "buff_rage"],
        },
        "seraphic_lord": {
            "id": "seraphic_lord",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 7,
            "narrative_hint": "The highest of angels. Has six wings and eyes burning with holy fire.",
            "extra_tags": ["seraph", "godlike"],
            "base_stats": {
                "strength": 60,
                "agility": 40,
                "endurance": 60,
                "intellect": 50,
                "memory": 50,
                "mental": 100,
                "perception": 50,
                "projection": 60,
                "prediction": 30,  # Итого: 500
            },
            "fixed_loadout": {"main_hand": "sword_of_light"},
            "skills": ["special_unique", "special_unique", "special_unique"],
        },
    },
}
