from ..monster_structs import MonsterFamily

BANDITS_FAMILY: MonsterFamily = {
    "id": "bandit_gang",
    "archetype": "humanoid",
    "organization_type": "gang",  # TSP Base: 50
    "default_tags": ["human", "outlaw", "survivor", "marauder"],
    "family_modifiers": [
        {"target": "accuracy", "value": -0.10, "per_tier": 0.0},
        {"target": "physical_resistance", "value": 0.03, "per_tier": 0.01},
        {"target": "anti_dodge_chance", "value": 0.04, "per_tier": 0.01},
        {"target": "control_resistance", "value": 0.04, "per_tier": 0.01},
    ],
    "loot_profile": {
        "salvage_type": "humanoid_gear",
        "loot_mode": "equipment",
        "allowed_loadout_slots": "full_humanoid",
        "equipment_drop_policy": "fixed_loadout",
        "drops_as_equipment": True,
        "equipment_quality": "poor_to_common",
        "materials": ["coin_scraps", "torn_cloth", "worn_leather"],
    },
    "hierarchy": {
        "minions": ["bandit_thug", "bandit_poacher", "bandit_lookout", "bandit_knife_rat"],
        "veterans": ["bandit_raider", "bandit_billhook", "bandit_hedge_wizard"],
        "elites": ["bandit_captain", "bandit_kingpin", "bandit_warlord"],
        "boss": ["bandit_cutthroat", "bandit_blackguard"],
    },
    "variants": {
        # === 1. Мелкая сошка (Minions) [TSP ~50] ===
        "bandit_thug": {
            "id": "bandit_thug",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 2,
            "narrative_hint": "A desperate settler turned marauder, armed with a crude axe and a wooden shield.",
            "base_stats": {
                "strength": 10,
                "agility": 8,
                "endurance": 10,
                "intellect": 4,
                "memory": 3,
                "mental": 5,
                "perception": 6,
                "projection": 2,
                "prediction": 5,  # Итого: 53
            },
            "fixed_loadout": {
                "main_hand": "hatchet",
                "off_hand": "buckler",
                "chest_armor": "jerkin",
            },
            "skills": ["skill_macing", "skill_medium_armor"],
        },
        "bandit_poacher": {
            "id": "bandit_poacher",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 2,
            "narrative_hint": "A former hunter, now an outlaw. Uses a simple short bow and wears leather scraps.",
            "base_stats": {
                "strength": 8,
                "agility": 12,
                "endurance": 8,
                "intellect": 5,
                "memory": 4,
                "mental": 6,
                "perception": 10,
                "projection": 2,
                "prediction": 6,  # Итого: 61
            },
            "fixed_loadout": {
                "two_hand": "shortbow",
                "quiver": "quiver_training",
                "chest_armor": "jerkin",
            },
            "skills": ["skill_archery", "skill_medium_armor", "skill_ranged_combat"],
        },
        "bandit_lookout": {
            "id": "bandit_lookout",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 2,
            "narrative_hint": "A nervous lookout with a spear and patched leather, watching ruined streets for prey.",
            "extra_tags": ["watcher", "spear", "scout"],
            "base_stats": {
                "strength": 8,
                "agility": 10,
                "endurance": 8,
                "intellect": 5,
                "memory": 4,
                "mental": 5,
                "perception": 12,
                "projection": 2,
                "prediction": 6,
            },
            "fixed_loadout": {
                "main_hand": "spear",
                "chest_armor": "jerkin",
            },
            "skills": ["skill_polearms", "skill_medium_armor"],
        },
        "bandit_knife_rat": {
            "id": "bandit_knife_rat",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 2,
            "narrative_hint": "A thin alley fighter carrying a chipped dagger and too much confidence.",
            "extra_tags": ["dagger", "ambusher", "street"],
            "base_stats": {
                "strength": 7,
                "agility": 13,
                "endurance": 7,
                "intellect": 4,
                "memory": 3,
                "mental": 5,
                "perception": 8,
                "projection": 2,
                "prediction": 7,
            },
            "fixed_loadout": {
                "main_hand": "dagger",
                "chest_armor": "jerkin",
            },
            "skills": ["skill_fencing", "skill_medium_armor"],
        },
        # === 2. Головорезы (Veterans) [TSP ~75] ===
        "bandit_cutthroat": {
            "id": "bandit_cutthroat",
            "role": "boss",
            "cost": 600,
            "min_tier": 2,
            "max_tier": 2,
            "narrative_hint": "A quick and ruthless knife-boss with two daggers, likely a former city rogue.",
            "base_stats": {
                "strength": 22,
                "agility": 30,
                "endurance": 22,
                "intellect": 10,
                "memory": 8,
                "mental": 14,
                "perception": 16,
                "projection": 8,
                "prediction": 18,
            },
            "fixed_loadout": {
                "main_hand": "dagger",
                "off_hand": "dagger",
                "chest_armor": "jerkin",
            },
            "skills": [
                "skill_fencing",
                "skill_medium_armor",
                "skill_dual_wield",
                "skill_tactics",
                "skill_parrying",
                "skill_anatomy",
            ],
        },
        "bandit_raider": {
            "id": "bandit_raider",
            "role": "veteran",
            "cost": 50,
            "min_tier": 0,
            "max_tier": 2,
            "narrative_hint": "A hard-handed raider with a mace and shield, used to breaking doors and skulls.",
            "extra_tags": ["raider", "shield", "bruiser"],
            "base_stats": {
                "strength": 16,
                "agility": 10,
                "endurance": 16,
                "intellect": 5,
                "memory": 4,
                "mental": 8,
                "perception": 8,
                "projection": 4,
                "prediction": 6,
            },
            "fixed_loadout": {
                "main_hand": "mace",
                "off_hand": "shield",
                "chest_armor": "jerkin",
            },
            "skills": ["skill_macing", "skill_medium_armor", "skill_shield_mastery"],
        },
        "bandit_billhook": {
            "id": "bandit_billhook",
            "role": "veteran",
            "cost": 50,
            "min_tier": 0,
            "max_tier": 2,
            "narrative_hint": "A ruined-road enforcer with a hooked polearm for dragging victims off balance.",
            "extra_tags": ["polearm", "disabler", "roadside"],
            "base_stats": {
                "strength": 14,
                "agility": 12,
                "endurance": 14,
                "intellect": 5,
                "memory": 5,
                "mental": 7,
                "perception": 10,
                "projection": 3,
                "prediction": 8,
            },
            "fixed_loadout": {
                "main_hand": "spear",
                "chest_armor": "jerkin",
            },
            "skills": ["skill_polearms", "skill_medium_armor"],
        },
        # === 3. Элита (Elites) [TSP ~125] ===
        "bandit_captain": {
            "id": "bandit_captain",
            "role": "elite",
            "cost": 150,
            "min_tier": 1,
            "max_tier": 2,
            "narrative_hint": "The leader of this small gang, a hardened survivor with a sword, shield, and reinforced mail.",
            "base_stats": {
                "strength": 20,
                "agility": 14,
                "endurance": 20,
                "intellect": 8,
                "memory": 6,
                "mental": 12,
                "perception": 10,
                "projection": 12,
                "prediction": 6,  # Итого: 108
            },
            "fixed_loadout": {
                "main_hand": "sword",
                "off_hand": "shield",
                "chest_armor": "jerkin",
            },
            "skills": [
                "skill_swords",
                "skill_medium_armor",
                "skill_shield_mastery",
                "skill_tactics",
                "skill_parrying",
            ],
        },
        "bandit_hedge_wizard": {
            "id": "bandit_hedge_wizard",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 2,
            "narrative_hint": "An outcast who dabbles in forbidden magic, using a crude staff to cast chaotic spells.",
            "base_stats": {
                "strength": 6,
                "agility": 10,
                "endurance": 10,
                "intellect": 20,
                "memory": 14,
                "mental": 20,
                "perception": 10,
                "projection": 6,
                "prediction": 4,  # Итого: 100
            },
            "fixed_loadout": {
                "two_hand": "quarterstaff",
                "chest_armor": "leather_armor",
            },
            "skills": ["skill_polearms", "skill_light_armor", "skill_two_handed"],
        },
        "bandit_blackguard": {
            "id": "bandit_blackguard",
            "role": "boss",
            "cost": 600,
            "min_tier": 2,
            "max_tier": 2,
            "narrative_hint": "A disciplined killer in stolen armor, carrying a heavy mace and a tower shield.",
            "extra_tags": ["blackguard", "heavy", "guard"],
            "base_stats": {
                "strength": 34,
                "agility": 14,
                "endurance": 38,
                "intellect": 10,
                "memory": 8,
                "mental": 18,
                "perception": 14,
                "projection": 12,
                "prediction": 12,
            },
            "fixed_loadout": {
                "main_hand": "mace",
                "off_hand": "shield",
                "chest_armor": "plate_chest",
            },
            "skills": [
                "skill_macing",
                "skill_heavy_armor",
                "skill_shield_mastery",
                "skill_tactics",
                "skill_parrying",
                "skill_anatomy",
            ],
        },
        # === 4. Босс (Bosses) [TSP ~200] ===
        "bandit_kingpin": {
            "id": "bandit_kingpin",
            "role": "elite",
            "cost": 150,
            "min_tier": 1,
            "max_tier": 2,
            "narrative_hint": "A road executioner who favors a heavy two-handed weapon and a direct charge.",
            "base_stats": {
                "strength": 30,
                "agility": 20,
                "endurance": 30,
                "intellect": 14,
                "memory": 10,
                "mental": 15,
                "perception": 15,
                "projection": 20,
                "prediction": 15,  # Итого: 169
            },
            "fixed_loadout": {
                "two_hand": "warhammer",
                "chest_armor": "plate_chest",
            },
            "skills": [
                "skill_macing",
                "skill_heavy_armor",
                "skill_two_handed",
                "skill_tactics",
                "skill_anatomy",
            ],
        },
        "bandit_warlord": {
            "id": "bandit_warlord",
            "role": "elite",
            "cost": 150,
            "min_tier": 1,
            "max_tier": 2,
            "narrative_hint": "A hard-eyed bandit marksman who keeps the line pinned while allies close in.",
            "extra_tags": ["marksman", "commander", "ranged"],
            "base_stats": {
                "strength": 18,
                "agility": 24,
                "endurance": 20,
                "intellect": 12,
                "memory": 10,
                "mental": 14,
                "perception": 24,
                "projection": 10,
                "prediction": 12,
            },
            "fixed_loadout": {
                "two_hand": "longbow",
                "quiver": "quiver_bodkin",
                "chest_armor": "leather_armor",
            },
            "skills": [
                "skill_archery",
                "skill_light_armor",
                "skill_ranged_combat",
                "skill_tactics",
                "skill_anatomy",
            ],
        },
    },
}
