from ..monster_structs import MonsterFamily

BANDITS_FAMILY: MonsterFamily = {
    "id": "bandit_gang",
    "archetype": "humanoid",
    "organization_type": "gang",  # TSP Base: 50
    "default_tags": ["human", "outlaw", "survivor", "marauder"],
    "skill_kit": {
        "base": {
            "skill_swords": 0.20,
            "skill_macing": 0.20,
            "skill_one_handed": 0.20,
            "skill_light_armor": 0.15,
        },
        "role_bonus": {
            "minion": {},
            "veteran": {"skill_swords": 0.15, "skill_macing": 0.15, "skill_one_handed": 0.15},
            "elite": {"skill_swords": 0.35, "skill_macing": 0.35, "skill_one_handed": 0.35, "skill_tactics": 0.20},
            "boss": {
                "skill_swords": 0.70,
                "skill_macing": 0.70,
                "skill_one_handed": 0.70,
                "skill_tactics": 0.50,
            },
        },
    },
    "family_modifiers": [
        {"target": "physical_resistance", "value": 0.03, "per_tier": 0.01},
        {"target": "anti_dodge_chance", "value": 0.04, "per_tier": 0.01},
        {"target": "control_resistance", "value": 0.04, "per_tier": 0.01},
    ],
    "loot_profile": {
        "salvage_type": "humanoid_gear",
        "loot_mode": "equipment",
        "allowed_loadout_slots": "full_humanoid",
        "equipment_drop_policy": "fixed_loadout",
        "drops_as_equipment": True,
        "equipment_quality": "poor_to_common",
        "materials": ["coin_scraps", "torn_cloth", "worn_leather"],
    },
    "hierarchy": {
        "minions": ["bandit_thug", "bandit_poacher", "bandit_lookout", "bandit_knife_rat"],
        "veterans": ["bandit_cutthroat", "bandit_raider", "bandit_billhook"],
        "elites": ["bandit_captain", "bandit_hedge_wizard", "bandit_blackguard"],
        "boss": ["bandit_kingpin", "bandit_warlord"],
    },
    "variants": {
        # === 1. Мелкая сошка (Minions) [TSP ~50] ===
        "bandit_thug": {
            "id": "bandit_thug",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 2,
            "narrative_hint": "A desperate settler turned marauder, armed with a crude axe and a wooden shield.",
            "base_stats": {
                "strength": 10,
                "agility": 8,
                "endurance": 10,
                "intellect": 4,
                "memory": 3,
                "mental": 5,
                "perception": 6,
                "projection": 2,
                "prediction": 5,  # Итого: 53
            },
            "fixed_loadout": {
                "main_hand": "hatchet",
                "off_hand": "buckler",
                "chest_armor": "jerkin",
            },
        },
        "bandit_poacher": {
            "id": "bandit_poacher",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 2,
            "narrative_hint": "A former hunter, now an outlaw. Uses a simple short bow and wears leather scraps.",
            "base_stats": {
                "strength": 8,
                "agility": 12,
                "endurance": 8,
                "intellect": 5,
                "memory": 4,
                "mental": 6,
                "perception": 10,
                "projection": 2,
                "prediction": 6,  # Итого: 61
            },
            "fixed_loadout": {
                "two_hand": "shortbow",
                "chest_armor": "jerkin",
            },
            "skill_overrides": {"skill_archery": 0.20, "skill_one_handed": None},
        },
        "bandit_lookout": {
            "id": "bandit_lookout",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 2,
            "narrative_hint": "A nervous lookout with a spear and patched leather, watching ruined streets for prey.",
            "extra_tags": ["watcher", "spear", "scout"],
            "base_stats": {
                "strength": 8,
                "agility": 10,
                "endurance": 8,
                "intellect": 5,
                "memory": 4,
                "mental": 5,
                "perception": 12,
                "projection": 2,
                "prediction": 6,
            },
            "fixed_loadout": {
                "main_hand": "spear",
                "chest_armor": "jerkin",
            },
            "skill_overrides": {"skill_polearms": 0.20, "skill_one_handed": None},
        },
        "bandit_knife_rat": {
            "id": "bandit_knife_rat",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 2,
            "narrative_hint": "A thin alley fighter carrying a chipped dagger and too much confidence.",
            "extra_tags": ["dagger", "ambusher", "street"],
            "base_stats": {
                "strength": 7,
                "agility": 13,
                "endurance": 7,
                "intellect": 4,
                "memory": 3,
                "mental": 5,
                "perception": 8,
                "projection": 2,
                "prediction": 7,
            },
            "fixed_loadout": {
                "main_hand": "dagger",
                "chest_armor": "jerkin",
            },
            "skill_overrides": {"skill_fencing": 0.20, "skill_one_handed": 0.10},
        },
        # === 2. Головорезы (Veterans) [TSP ~75] ===
        "bandit_cutthroat": {
            "id": "bandit_cutthroat",
            "role": "veteran",
            "cost": 50,
            "min_tier": 0,
            "max_tier": 2,
            "narrative_hint": "A quick and ruthless fighter with two daggers, likely a former city rogue.",
            "base_stats": {
                "strength": 10,
                "agility": 18,
                "endurance": 10,
                "intellect": 6,
                "memory": 4,
                "mental": 8,
                "perception": 10,
                "projection": 3,
                "prediction": 10,  # Итого: 79
            },
            "fixed_loadout": {
                "main_hand": "dagger",
                "off_hand": "dagger",
                "chest_armor": "jerkin",
            },
            "skill_overrides": {"skill_dual_wield": 0.20},
        },
        "bandit_raider": {
            "id": "bandit_raider",
            "role": "veteran",
            "cost": 50,
            "min_tier": 0,
            "max_tier": 2,
            "narrative_hint": "A hard-handed raider with a mace and shield, used to breaking doors and skulls.",
            "extra_tags": ["raider", "shield", "bruiser"],
            "base_stats": {
                "strength": 16,
                "agility": 10,
                "endurance": 16,
                "intellect": 5,
                "memory": 4,
                "mental": 8,
                "perception": 8,
                "projection": 4,
                "prediction": 6,
            },
            "fixed_loadout": {
                "main_hand": "mace",
                "off_hand": "shield",
                "chest_armor": "jerkin",
            },
            "skill_overrides": {"skill_macing": 0.25, "skill_shield_mastery": 0.20},
        },
        "bandit_billhook": {
            "id": "bandit_billhook",
            "role": "veteran",
            "cost": 50,
            "min_tier": 0,
            "max_tier": 2,
            "narrative_hint": "A ruined-road enforcer with a hooked polearm for dragging victims off balance.",
            "extra_tags": ["polearm", "disabler", "roadside"],
            "base_stats": {
                "strength": 14,
                "agility": 12,
                "endurance": 14,
                "intellect": 5,
                "memory": 5,
                "mental": 7,
                "perception": 10,
                "projection": 3,
                "prediction": 8,
            },
            "fixed_loadout": {
                "main_hand": "spear",
                "chest_armor": "jerkin",
            },
            "skill_overrides": {"skill_polearms": 0.30, "skill_one_handed": None},
        },
        # === 3. Элита (Elites) [TSP ~125] ===
        "bandit_captain": {
            "id": "bandit_captain",
            "role": "elite",
            "cost": 150,
            "min_tier": 1,
            "max_tier": 2,
            "narrative_hint": "The leader of this small gang, a hardened survivor with a stolen longsword and reinforced armor.",
            "base_stats": {
                "strength": 20,
                "agility": 14,
                "endurance": 20,
                "intellect": 8,
                "memory": 6,
                "mental": 12,
                "perception": 10,
                "projection": 12,
                "prediction": 6,  # Итого: 108
            },
            "fixed_loadout": {
                "main_hand": "sword",
                "off_hand": "shield",
                "chest_armor": "plate_chest",
            },
            "skill_overrides": {"skill_heavy_armor": 0.20, "skill_shield_mastery": 0.25},
        },
        "bandit_hedge_wizard": {
            "id": "bandit_hedge_wizard",
            "role": "elite",
            "cost": 150,
            "min_tier": 1,
            "max_tier": 2,
            "narrative_hint": "An outcast who dabbles in forbidden magic, using a crude staff to cast chaotic spells.",
            "base_stats": {
                "strength": 6,
                "agility": 10,
                "endurance": 10,
                "intellect": 20,
                "memory": 14,
                "mental": 20,
                "perception": 10,
                "projection": 6,
                "prediction": 4,  # Итого: 100
            },
            "fixed_loadout": {
                "two_hand": "quarterstaff",
                "chest_armor": "leather_armor",
            },
            "skill_overrides": {"skill_two_handed": 0.20, "skill_light_armor": 0.25},
        },
        "bandit_blackguard": {
            "id": "bandit_blackguard",
            "role": "elite",
            "cost": 150,
            "min_tier": 1,
            "max_tier": 2,
            "narrative_hint": "A disciplined killer in stolen armor, carrying a heavy mace and a tower shield.",
            "extra_tags": ["blackguard", "heavy", "guard"],
            "base_stats": {
                "strength": 24,
                "agility": 10,
                "endurance": 26,
                "intellect": 7,
                "memory": 6,
                "mental": 12,
                "perception": 10,
                "projection": 8,
                "prediction": 8,
            },
            "fixed_loadout": {
                "main_hand": "mace",
                "off_hand": "shield",
                "chest_armor": "plate_chest",
            },
            "skill_overrides": {"skill_macing": 0.35, "skill_heavy_armor": 0.25, "skill_shield_mastery": 0.25},
        },
        # === 4. Босс (Bosses) [TSP ~200] ===
        "bandit_kingpin": {
            "id": "bandit_kingpin",
            "role": "boss",
            "cost": 600,
            "min_tier": 2,
            "max_tier": 2,
            "narrative_hint": "The ruthless leader of all local marauders. Wields a heavy two-handed axe and is surprisingly quick.",
            "base_stats": {
                "strength": 30,
                "agility": 20,
                "endurance": 30,
                "intellect": 14,
                "memory": 10,
                "mental": 15,
                "perception": 15,
                "projection": 20,
                "prediction": 15,  # Итого: 169
            },
            "fixed_loadout": {
                "two_hand": "warhammer",
                "chest_armor": "plate_chest",
            },
            "skill_overrides": {"skill_two_handed": 0.60, "skill_heavy_armor": 0.45},
        },
        "bandit_warlord": {
            "id": "bandit_warlord",
            "role": "boss",
            "cost": 600,
            "min_tier": 2,
            "max_tier": 2,
            "narrative_hint": "A brutal road warlord with a stolen longsword, a battered shield, and a gang that obeys fear.",
            "extra_tags": ["warlord", "commander", "shield"],
            "base_stats": {
                "strength": 28,
                "agility": 18,
                "endurance": 32,
                "intellect": 16,
                "memory": 10,
                "mental": 18,
                "perception": 16,
                "projection": 18,
                "prediction": 14,
            },
            "fixed_loadout": {
                "main_hand": "sword",
                "off_hand": "shield",
                "chest_armor": "plate_chest",
            },
            "skill_overrides": {
                "skill_swords": 0.65,
                "skill_one_handed": 0.50,
                "skill_heavy_armor": 0.40,
                "skill_shield_mastery": 0.35,
            },
        },
    },
}
