"""
СЕМЕЙСТВО: ТЕМНЫЕ ЭЛЬФЫ (Ловкость, яд, тьма)
============================================
Логика: ловкость -> яд -> тьма
"""

from ..monster_structs import MonsterFamily

DARK_ELVES_FAMILY: MonsterFamily = {
    "id": "dark_elf_house",
    "archetype": "humanoid",
    "organization_type": "clan",  # TSP Base: 70
    "default_tags": ["dark_elf", "drow", "poison", "shadow"],
    "hierarchy": {
        "minions": ["dark_scout", "shadow_initiate", "poison_fang", "night_sentry"],
        "veterans": ["dark_warrior", "shadow_blade", "venom_knight", "night_hunter"],
        "elites": ["dark_champion", "shadow_marshal", "venom_lord", "night_commander"],
        "boss": ["dark_overlord", "shadow_tyrant", "venom_archon", "night_king"],
    },
    "variants": {
        # --- 1. Новички / Ассасины (Minions) [TSP ~70] ---
        "dark_scout": {
            "id": "dark_scout",
            "role": "minion",
            "cost": 20,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A lithe elf in dark leather, moving silently through the shadows.",
            "extra_tags": ["scout", "stealth"],
            "base_stats": {
                "strength": 8,
                "agility": 20,
                "endurance": 8,
                "intellect": 6,
                "memory": 6,
                "mental": 8,
                "perception": 14,
                "projection": 2,
                "prediction": 4,  # Итого: 76
            },
            "fixed_loadout": {"main_hand": "dagger", "chest_garment": "leather_vest"},
            "skills": ["stealth", "attack_heavy"],
        },
        "shadow_initiate": {
            "id": "shadow_initiate",
            "role": "minion",
            "cost": 20,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A young elf learning the arts of shadow magic. Wields a simple blade.",
            "extra_tags": ["magic", "initiate"],
            "base_stats": {
                "strength": 6,
                "agility": 14,
                "endurance": 6,
                "intellect": 12,
                "memory": 10,
                "mental": 10,
                "perception": 10,
                "projection": 4,
                "prediction": 4,  # Итого: 76
            },
            "fixed_loadout": {"main_hand": "shortsword", "chest_garment": "robe"},
            "skills": ["attack_ranged", "stealth"],
        },
        "poison_fang": {
            "id": "poison_fang",
            "role": "minion",
            "cost": 20,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "An assassin with green-stained daggers. Smiles cruelly.",
            "extra_tags": ["assassin", "poison"],
            "base_stats": {
                "strength": 8,
                "agility": 18,
                "endurance": 8,
                "intellect": 8,
                "memory": 6,
                "mental": 6,
                "perception": 10,
                "projection": 2,
                "prediction": 4,  # Итого: 70
            },
            "fixed_loadout": {"main_hand": "dagger", "off_hand": "dagger"},
            "skills": ["debuff_poison", "debuff_poison"],
        },
        "night_sentry": {
            "id": "night_sentry",
            "role": "minion",
            "cost": 20,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A guard with a crossbow, watching from the darkness.",
            "extra_tags": ["sentry", "ranged"],
            "base_stats": {
                "strength": 10,
                "agility": 16,
                "endurance": 10,
                "intellect": 6,
                "memory": 6,
                "mental": 6,
                "perception": 16,
                "projection": 2,
                "prediction": 4,  # Итого: 76
            },
            "fixed_loadout": {"main_hand": "crossbow", "chest_armor": "leather_armor"},
            "skills": ["attack_ranged", "buff_defense"],
        },
        # --- 2. Воины (Veterans) [TSP ~105] ---
        "dark_warrior": {
            "id": "dark_warrior",
            "role": "veteran",
            "cost": 50,
            "min_tier": 5,
            "max_tier": 8,
            "narrative_hint": "A disciplined soldier in chainmail. Wields a curved sword.",
            "extra_tags": ["warrior", "shield"],
            "base_stats": {
                "strength": 16,
                "agility": 16,
                "endurance": 14,
                "intellect": 8,
                "memory": 8,
                "mental": 10,
                "perception": 12,
                "projection": 4,
                "prediction": 5,  # Итого: 93
            },
            "fixed_loadout": {"main_hand": "scimitar", "off_hand": "shield", "chest_armor": "chainmail"},
            "skills": ["attack_basic", "counter_attack", "debuff_weaken"],
        },
        "shadow_blade": {
            "id": "shadow_blade",
            "role": "veteran",
            "cost": 50,
            "min_tier": 5,
            "max_tier": 8,
            "narrative_hint": "A master of stealth and swordplay. Moves faster than the eye can follow.",
            "extra_tags": ["assassin", "master", "stealth"],
            "base_stats": {
                "strength": 12,
                "agility": 25,
                "endurance": 10,
                "intellect": 10,
                "memory": 8,
                "mental": 12,
                "perception": 14,
                "projection": 4,
                "prediction": 8,  # Итого: 103
            },
            "fixed_loadout": {"main_hand": "katana", "off_hand": "wakizashi"},
            "skills": ["attack_execute", "debuff_blind"],
        },
        "venom_knight": {
            "id": "venom_knight",
            "role": "veteran",
            "cost": 50,
            "min_tier": 5,
            "max_tier": 8,
            "narrative_hint": "A knight in armor coated with poison. Even a scratch is deadly.",
            "extra_tags": ["knight", "poison", "heavy_armor"],
            "base_stats": {
                "strength": 18,
                "agility": 12,
                "endurance": 18,
                "intellect": 8,
                "memory": 8,
                "mental": 10,
                "perception": 10,
                "projection": 4,
                "prediction": 5,  # Итого: 93
            },
            "fixed_loadout": {"main_hand": "spear", "chest_armor": "plate_chest"},
            "skills": ["debuff_poison", "debuff_poison", "debuff_weaken"],
        },
        "night_hunter": {
            "id": "night_hunter",
            "role": "veteran",
            "cost": 50,
            "min_tier": 5,
            "max_tier": 8,
            "narrative_hint": "A ranger who hunts in the pitch black. Never misses.",
            "extra_tags": ["hunter", "ranger", "ranged"],
            "base_stats": {
                "strength": 14,
                "agility": 22,
                "endurance": 12,
                "intellect": 10,
                "memory": 10,
                "mental": 10,
                "perception": 20,
                "projection": 2,
                "prediction": 8,  # Итого: 108
            },
            "fixed_loadout": {"main_hand": "longbow", "chest_garment": "cloak"},
            "skills": ["attack_ranged", "special_trap", "debuff_armor_break"],
        },
        # --- 3. Элита (Elites) [TSP ~175] ---
        "dark_champion": {
            "id": "dark_champion",
            "role": "elite",
            "cost": 150,
            "min_tier": 6,
            "max_tier": 9,
            "narrative_hint": "The champion of a noble house. Wields a magical blade.",
            "extra_tags": ["champion", "noble"],
            "base_stats": {
                "strength": 25,
                "agility": 20,
                "endurance": 25,
                "intellect": 12,
                "memory": 12,
                "mental": 15,
                "perception": 14,
                "projection": 10,
                "prediction": 8,  # Итого: 141
            },
            "fixed_loadout": {"main_hand": "greatsword", "chest_armor": "plate_chest"},
            "skills": ["attack_heavy", "debuff_weaken", "buff_rage"],
        },
        "shadow_marshal": {
            "id": "shadow_marshal",
            "role": "elite",
            "cost": 150,
            "min_tier": 6,
            "max_tier": 9,
            "narrative_hint": "A commander who uses shadows to control the battlefield.",
            "extra_tags": ["marshal", "commander", "shadow"],
            "base_stats": {
                "strength": 18,
                "agility": 22,
                "endurance": 18,
                "intellect": 18,
                "memory": 16,
                "mental": 20,
                "perception": 18,
                "projection": 15,
                "prediction": 5,  # Итого: 150
            },
            "fixed_loadout": {"main_hand": "rapier", "off_hand": "dagger"},
            "skills": ["buff_rage", "stealth", "debuff_weaken"],
        },
        "venom_lord": {
            "id": "venom_lord",
            "role": "elite",
            "cost": 150,
            "min_tier": 6,
            "max_tier": 9,
            "narrative_hint": "A master alchemist and warrior. Surrounded by a cloud of toxins.",
            "extra_tags": ["lord", "poison", "alchemist"],
            "base_stats": {
                "strength": 14,
                "agility": 18,
                "endurance": 20,
                "intellect": 25,
                "memory": 20,
                "mental": 15,
                "perception": 16,
                "projection": 8,
                "prediction": 5,  # Итого: 141
            },
            "fixed_loadout": {"main_hand": "staff"},
            "skills": ["debuff_poison", "debuff_armor_break", "summon_minion"],
        },
        "night_commander": {
            "id": "night_commander",
            "role": "elite",
            "cost": 150,
            "min_tier": 6,
            "max_tier": 9,
            "narrative_hint": "A tactical genius who leads raids on the surface world.",
            "extra_tags": ["commander", "tactician"],
            "base_stats": {
                "strength": 20,
                "agility": 20,
                "endurance": 20,
                "intellect": 18,
                "memory": 18,
                "mental": 20,
                "perception": 20,
                "projection": 18,
                "prediction": 10,  # Итого: 164
            },
            "fixed_loadout": {"main_hand": "sword", "off_hand": "shield", "head_armor": "helmet"},
            "skills": ["attack_heavy", "buff_rage", "debuff_stun"],
        },
        # --- 4. Владыки / Боссы (Bosses) [TSP ~280] ---
        "dark_overlord": {
            "id": "dark_overlord",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 10,
            "narrative_hint": "The ruler of a dark elf city. Radiates power and malice.",
            "extra_tags": ["overlord", "ruler"],
            "base_stats": {
                "strength": 40,
                "agility": 40,
                "endurance": 50,
                "intellect": 30,
                "memory": 30,
                "mental": 40,
                "perception": 30,
                "projection": 30,
                "prediction": 15,  # Итого: 305
            },
            "fixed_loadout": {"main_hand": "demon_blade", "chest_armor": "adamantite_plate"},
            "skills": ["attack_heavy", "summon_minion", "debuff_stun", "debuff_blind"],
        },
        "shadow_tyrant": {
            "id": "shadow_tyrant",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 10,
            "narrative_hint": "A being that has merged with the shadow plane. Almost impossible to hit.",
            "extra_tags": ["tyrant", "shadow", "ethereal"],
            "base_stats": {
                "strength": 30,
                "agility": 60,
                "endurance": 30,
                "intellect": 40,
                "memory": 30,
                "mental": 50,
                "perception": 40,
                "projection": 10,
                "prediction": 20,  # Итого: 310
            },
            "fixed_loadout": {"main_hand": "shadow_daggers"},
            "skills": ["buff_evasion", "attack_aoe", "debuff_blind"],
        },
        "venom_archon": {
            "id": "venom_archon",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 10,
            "narrative_hint": "A twisted elf mutated by spider venom. Half-spider, half-elf.",
            "extra_tags": ["archon", "venom", "spider"],
            "base_stats": {
                "strength": 45,
                "agility": 30,
                "endurance": 50,
                "intellect": 25,
                "memory": 25,
                "mental": 30,
                "perception": 25,
                "projection": 10,
                "prediction": 10,  # Итого: 250
            },
            "fixed_loadout": {},
            "skills": ["debuff_stun", "debuff_poison", "summon_minion", "debuff_bleed"],
        },
        "night_king": {
            "id": "night_king",
            "role": "boss",
            "cost": 600,
            "min_tier": 8,
            "max_tier": 11,
            "narrative_hint": "An ancient elf who remembers the time before the sun. Wields the power of the void.",
            "extra_tags": ["king", "ancient", "void"],
            "base_stats": {
                "strength": 30,
                "agility": 30,
                "endurance": 40,
                "intellect": 50,
                "memory": 50,
                "mental": 60,
                "perception": 40,
                "projection": 40,
                "prediction": 25,  # Итого: 365
            },
            "fixed_loadout": {"main_hand": "void_staff"},
            "skills": ["special_unique", "special_unique", "attack_execute", "special_unique"],
        },
    },
}
