"""
СЕМЕЙСТВО: ЛЕТУЧИЕ ТВАРИ (Хаос и дезориентация)
===============================================
Логика: хаос -> дезориентация -> добивание
"""

from ..monster_structs import MonsterFamily

FLYING_FAMILY: MonsterFamily = {
    "id": "bat_colony",
    "archetype": "beast",
    "organization_type": "swarm",  # TSP Base: 30
    "default_tags": ["beast", "flying", "bat", "chaos"],
    "hierarchy": {
        "minions": ["cave_bat", "night_flutter"],
        "veterans": ["blood_drainer", "claw_diver", "screech_bat", "dust_wing"],
        "elites": ["swarm_wing", "night_terror"],
        "boss": ["vampire_lord", "ancient_wyvern"],
    },
    "variants": {
        # --- 1. Мелкие (Minions) [TSP ~30] ---
        "cave_bat": {
            "id": "cave_bat",
            "role": "minion",
            "cost": 20,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A shared bat with leathery wings. Flutters erratically.",
            "extra_tags": ["shared", "weak"],
            "base_stats": {
                "strength": 2,
                "agility": 14,
                "endurance": 2,
                "intellect": 1,
                "memory": 1,
                "mental": 2,
                "perception": 8,
                "projection": 1,
                "prediction": 2,  # Итого: 33
            },
            "fixed_loadout": {},
            "skills": ["attack_basic"],
        },
        "night_flutter": {
            "id": "night_flutter",
            "role": "minion",
            "cost": 20,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A tiny, moth-like bat. Hard to hit.",
            "extra_tags": ["fast", "agile"],
            "base_stats": {
                "strength": 1,
                "agility": 18,
                "endurance": 1,
                "intellect": 1,
                "memory": 1,
                "mental": 2,
                "perception": 10,
                "projection": 1,
                "prediction": 4,  # Итого: 39
            },
            "fixed_loadout": {},
            "skills": ["buff_evasion", "debuff_weaken"],
        },
        # --- 2. Охотники (Veterans) [TSP ~45] ---
        "blood_drainer": {
            "id": "blood_drainer",
            "role": "veteran",
            "cost": 50,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A bat with elongated fangs and a red tint to its fur.",
            "extra_tags": ["vampiric", "lifesteal"],
            "base_stats": {
                "strength": 4,
                "agility": 12,
                "endurance": 4,
                "intellect": 2,
                "memory": 2,
                "mental": 4,
                "perception": 8,
                "projection": 1,
                "prediction": 2,  # Итого: 39 (компенсация вампиризмом)
            },
            "fixed_loadout": {},
            "skills": ["attack_lifesteal", "debuff_stun"],
        },
        "claw_diver": {
            "id": "claw_diver",
            "role": "veteran",
            "cost": 50,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A bat with unusually sharp claws on its wings. Dives from above.",
            "extra_tags": ["striker", "sharp"],
            "base_stats": {
                "strength": 6,
                "agility": 14,
                "endurance": 6,
                "intellect": 2,
                "memory": 2,
                "mental": 4,
                "perception": 10,
                "projection": 1,
                "prediction": 2,  # Итого: 47
            },
            "fixed_loadout": {},
            "skills": ["attack_heavy", "debuff_bleed"],
        },
        "screech_bat": {
            "id": "screech_bat",
            "role": "veteran",
            "cost": 50,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A bat with a massive chest and throat. Emits sonic waves.",
            "extra_tags": ["sonic", "debuff"],
            "base_stats": {
                "strength": 4,
                "agility": 10,
                "endurance": 6,
                "intellect": 3,
                "memory": 3,
                "mental": 6,
                "perception": 12,
                "projection": 2,
                "prediction": 2,  # Итого: 48
            },
            "fixed_loadout": {},
            "skills": ["debuff_stun", "debuff_stun"],
        },
        "dust_wing": {
            "id": "dust_wing",
            "role": "veteran",
            "cost": 50,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A bat covered in fine, irritating dust. Creates clouds when it flaps.",
            "extra_tags": ["dust", "blind"],
            "base_stats": {
                "strength": 4,
                "agility": 12,
                "endurance": 4,
                "intellect": 2,
                "memory": 2,
                "mental": 4,
                "perception": 8,
                "projection": 1,
                "prediction": 2,  # Итого: 39 (компенсация ослеплением)
            },
            "fixed_loadout": {},
            "skills": ["debuff_blind", "debuff_blind"],
        },
        # --- 3. Альфы (Elites) [TSP ~75] ---
        "swarm_wing": {
            "id": "swarm_wing",
            "role": "elite",
            "cost": 150,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A large bat that seems to be the center of the swarm's movement.",
            "extra_tags": ["leader", "aura"],
            "base_stats": {
                "strength": 8,
                "agility": 16,
                "endurance": 10,
                "intellect": 5,
                "memory": 5,
                "mental": 8,
                "perception": 14,
                "projection": 6,
                "prediction": 4,  # Итого: 76
            },
            "fixed_loadout": {},
            "skills": ["buff_rage", "attack_fast", "buff_rage"],
        },
        "night_terror": {
            "id": "night_terror",
            "role": "elite",
            "cost": 150,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A monstrous bat, silent as the grave. Its eyes glow with malice.",
            "extra_tags": ["terror", "fear", "stealth"],
            "base_stats": {
                "strength": 12,
                "agility": 14,
                "endurance": 14,
                "intellect": 6,
                "memory": 6,
                "mental": 10,
                "perception": 12,
                "projection": 4,
                "prediction": 6,  # Итого: 84
            },
            "fixed_loadout": {},
            "skills": ["attack_heavy", "debuff_weaken", "buff_evasion"],
        },
        # --- 4. Боссы (Bosses) [TSP ~120] ---
        "vampire_lord": {
            "id": "vampire_lord",
            "role": "boss",
            "cost": 600,
            "min_tier": 5,
            "max_tier": 8,
            "narrative_hint": "An ancient vampire in bat form, radiating dark power.",
            "extra_tags": ["vampire", "lord", "ancient"],
            "base_stats": {
                "strength": 18,
                "agility": 20,
                "endurance": 20,
                "intellect": 15,
                "memory": 15,
                "mental": 25,
                "perception": 18,
                "projection": 15,
                "prediction": 10,  # Итого: 156
            },
            "fixed_loadout": {},
            "skills": ["attack_lifesteal", "special_unique", "debuff_stun", "attack_lifesteal"],
        },
        "ancient_wyvern": {
            "id": "ancient_wyvern",
            "role": "boss",
            "cost": 600,
            "min_tier": 5,
            "max_tier": 8,
            "narrative_hint": "A distant relative of dragons, ruling the skies with poison and claws.",
            "extra_tags": ["wyvern", "dragonkin", "poison"],
            "base_stats": {
                "strength": 25,
                "agility": 15,
                "endurance": 30,
                "intellect": 8,
                "memory": 10,
                "mental": 15,
                "perception": 16,
                "projection": 10,
                "prediction": 5,  # Итого: 134
            },
            "fixed_loadout": {},
            "skills": ["debuff_poison", "attack_pierce", "attack_heavy", "attack_aoe"],
        },
    },
}
