"""
СЕМЕЙСТВО: ГОБЛИНЫ (Техно-хаос и выживание)
=========================================
Логика: хитрость -> инструменты -> взрыв
"""

from ..monster_structs import MonsterFamily

GOBLINS_FAMILY: MonsterFamily = {
    "id": "goblin_tribe",
    "archetype": "humanoid",
    "organization_type": "horde",  # TSP Base: 30
    "default_tags": ["goblin", "small", "cunning", "tinkerer"],
    "skill_kit": {
        "base": {
            "skill_swords": 0.15,
            "skill_macing": 0.10,
            "skill_polearms": 0.10,
            "skill_one_handed": 0.15,
            "skill_light_armor": 0.10,
            "skill_tactics": 0.10,
        },
        "role_bonus": {
            "minion": {},
            "veteran": {"skill_polearms": 0.15, "skill_one_handed": 0.15, "skill_tactics": 0.10},
            "elite": {"skill_swords": 0.30, "skill_one_handed": 0.30, "skill_tactics": 0.30},
            "boss": {"skill_macing": 0.65, "skill_one_handed": 0.65, "skill_tactics": 0.55, "skill_leadership": 0.35},
        },
    },
    "loot_profile": {
        "salvage_type": "humanoid_gear",
        "loot_mode": "equipment",
        "allowed_loadout_slots": "full_humanoid",
        "equipment_drop_policy": "fixed_loadout",
        "drops_as_equipment": True,
        "equipment_quality": "poor_to_common",
        "materials": ["scrap_metal", "torn_cloth", "cracked_tool"],
    },
    "hierarchy": {
        "minions": ["goblin_sneak", "goblin_scavenger", "goblin_cutter", "goblin_sparkpick"],
        "veterans": ["goblin_spearman", "goblin_slinger", "goblin_scrapguard"],
        "elites": ["goblin_tinkerer", "goblin_bomber", "goblin_trapmaster"],
        "boss": ["goblin_chief", "scrap_king"],
    },
    "variants": {
        # --- 1. Мелочь (Minions) [TSP ~30] ---
        "goblin_sneak": {
            "id": "goblin_sneak",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 4,
            "narrative_hint": "A small goblin with a hooded cloak and a pair of sharp daggers, moves silently.",
            "extra_tags": ["stealth", "assassin"],
            "base_stats": {
                "strength": 4,
                "agility": 12,
                "endurance": 4,
                "intellect": 4,
                "memory": 2,
                "mental": 2,
                "perception": 6,
                "projection": 1,
                "prediction": 5,  # Итого: 40 (чуть выше базы из-за luck/agi)
            },
            "fixed_loadout": {"main_hand": "dagger", "off_hand": "dagger", "chest_garment": "linen_shirt"},
            "skill_overrides": {"skill_dual_wield": 0.15},
        },
        "goblin_scavenger": {
            "id": "goblin_scavenger",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 4,
            "narrative_hint": "A goblin carrying a large, overflowing backpack. Wields a simple club.",
            "extra_tags": ["scavenger", "hoarder"],
            "base_stats": {
                "strength": 6,
                "agility": 6,
                "endurance": 6,
                "intellect": 4,
                "memory": 2,
                "mental": 2,
                "perception": 4,
                "projection": 1,
                "prediction": 4,  # Итого: 35
            },
            "fixed_loadout": {"main_hand": "mace", "chest_garment": "linen_shirt"},
        },
        "goblin_cutter": {
            "id": "goblin_cutter",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 4,
            "narrative_hint": "A mean little goblin with a chipped knife and a habit of aiming for tendons.",
            "extra_tags": ["knife", "bleeder", "ambusher"],
            "base_stats": {
                "strength": 5,
                "agility": 13,
                "endurance": 5,
                "intellect": 3,
                "memory": 2,
                "mental": 3,
                "perception": 6,
                "projection": 1,
                "prediction": 5,
            },
            "fixed_loadout": {"main_hand": "dagger", "chest_garment": "linen_shirt"},
            "skill_overrides": {"skill_fencing": 0.18, "skill_one_handed": 0.08},
        },
        "goblin_sparkpick": {
            "id": "goblin_sparkpick",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 4,
            "narrative_hint": "A scavenger carrying a bent tool that spits unstable ether sparks when swung.",
            "extra_tags": ["scrap", "ether", "reckless"],
            "base_stats": {
                "strength": 6,
                "agility": 8,
                "endurance": 6,
                "intellect": 6,
                "memory": 3,
                "mental": 4,
                "perception": 5,
                "projection": 2,
                "prediction": 4,
            },
            "fixed_loadout": {"main_hand": "hatchet", "chest_garment": "linen_shirt"},
        },
        # --- 2. Бойцы (Veterans) [TSP ~45] ---
        "goblin_spearman": {
            "id": "goblin_spearman",
            "role": "veteran",
            "cost": 50,
            "min_tier": 0,
            "max_tier": 5,
            "narrative_hint": "A disciplined goblin with a long spear and a crude wooden shield.",
            "extra_tags": ["infantry", "shield"],
            "base_stats": {
                "strength": 8,
                "agility": 8,
                "endurance": 10,
                "intellect": 4,
                "memory": 3,
                "mental": 4,
                "perception": 6,
                "projection": 2,
                "prediction": 3,  # Итого: 48
            },
            "fixed_loadout": {"main_hand": "spear", "off_hand": "shield", "chest_armor": "jerkin"},
        },
        "goblin_slinger": {
            "id": "goblin_slinger",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 5,
            "narrative_hint": "A fast goblin with a sling, constantly moving and throwing rocks.",
            "extra_tags": ["ranged", "fast"],
            "base_stats": {
                "strength": 4,
                "agility": 14,
                "endurance": 6,
                "intellect": 4,
                "memory": 4,
                "mental": 3,
                "perception": 8,
                "projection": 2,
                "prediction": 4,  # Итого: 49
            },
            "fixed_loadout": {"main_hand": "sling", "chest_garment": "linen_shirt"},
            "skill_overrides": {"skill_archery": 0.20, "skill_one_handed": None},
        },
        "goblin_scrapguard": {
            "id": "goblin_scrapguard",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 5,
            "narrative_hint": "A squat goblin hiding behind a crude shield packed with scavenged metal plates.",
            "extra_tags": ["shield", "defender", "scrap"],
            "base_stats": {
                "strength": 10,
                "agility": 6,
                "endurance": 14,
                "intellect": 5,
                "memory": 4,
                "mental": 5,
                "perception": 6,
                "projection": 3,
                "prediction": 4,
            },
            "fixed_loadout": {"main_hand": "mace", "off_hand": "shield", "chest_armor": "jerkin"},
            "skill_overrides": {"skill_macing": 0.20, "skill_shield_mastery": 0.25},
        },
        # --- 3. Инженеры (Elites) [TSP ~75] ---
        "goblin_tinkerer": {
            "id": "goblin_tinkerer",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 6,
            "narrative_hint": "A goblin with goggles and a belt full of tools. Throws caltrops and sets traps.",
            "extra_tags": ["engineer", "trapper"],
            "base_stats": {
                "strength": 6,
                "agility": 12,
                "endurance": 10,
                "intellect": 15,
                "memory": 8,
                "mental": 6,
                "perception": 12,
                "projection": 4,
                "prediction": 6,  # Итого: 79
            },
            "fixed_loadout": {"main_hand": "dagger", "chest_garment": "apron", "head_armor": "goggles"},
            "skill_overrides": {"skill_tactics": 0.45},
        },
        "goblin_bomber": {
            "id": "goblin_bomber",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 6,
            "narrative_hint": "A goblin with a manic grin and a sack of crude explosives.",
            "extra_tags": ["bomber", "explosives", "reckless"],
            "base_stats": {
                "strength": 8,
                "agility": 12,
                "endurance": 12,
                "intellect": 10,
                "memory": 4,
                "mental": 8,
                "perception": 8,
                "projection": 4,
                "prediction": 10,  # Итого: 76
            },
            "fixed_loadout": {"main_hand": "sling", "chest_armor": "jerkin"},
            "skill_overrides": {"skill_archery": 0.25, "skill_tactics": 0.40},
        },
        "goblin_trapmaster": {
            "id": "goblin_trapmaster",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 6,
            "narrative_hint": "A patient goblin engineer covered in twine, hooks, and stolen monolith fragments.",
            "extra_tags": ["trapper", "engineer", "controller"],
            "base_stats": {
                "strength": 8,
                "agility": 14,
                "endurance": 12,
                "intellect": 18,
                "memory": 10,
                "mental": 8,
                "perception": 16,
                "projection": 5,
                "prediction": 8,
            },
            "fixed_loadout": {
                "main_hand": "dagger",
                "chest_garment": "apron",
                "head_armor": "goggles",
                "belt_accessory": "belt",
            },
            "skill_overrides": {"skill_tactics": 0.55, "skill_fencing": 0.18},
        },
        # --- 4. Вожди (Bosses) [TSP ~120] ---
        "goblin_chief": {
            "id": "goblin_chief",
            "role": "boss",
            "cost": 600,
            "min_tier": 3,
            "max_tier": 7,
            "narrative_hint": "A larger, smarter goblin wearing a crude crown and better armor. Shouts commands.",
            "extra_tags": ["leader", "commander"],
            "base_stats": {
                "strength": 18,
                "agility": 14,
                "endurance": 20,
                "intellect": 10,
                "memory": 10,
                "mental": 12,
                "perception": 12,
                "projection": 12,
                "prediction": 8,  # Итого: 116
            },
            "fixed_loadout": {"main_hand": "battle_axe", "chest_armor": "plate_chest", "head_armor": "helmet"},
            "skill_overrides": {"skill_heavy_armor": 0.25},
        },
        "scrap_king": {
            "id": "scrap_king",
            "role": "boss",
            "cost": 600,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A huge goblin sitting on a throne of junk, wearing a makeshift power armor.",
            "extra_tags": ["king", "heavy_armor", "engineer"],
            "base_stats": {
                "strength": 25,
                "agility": 8,
                "endurance": 30,
                "intellect": 15,
                "memory": 10,
                "mental": 15,
                "perception": 10,
                "projection": 15,
                "prediction": 5,  # Итого: 133
            },
            "fixed_loadout": {
                "two_hand": "warhammer",
                "chest_armor": "plate_chest",
                "head_armor": "helmet",
                "arms_armor": "gauntlets",
                "legs_armor": "greaves",
            },
            "skill_overrides": {"skill_two_handed": 0.55, "skill_heavy_armor": 0.45},
        },
    },
}
