"""
СЕМЕЙСТВО: ГОБЛИНЫ (Техно-хаос и выживание)
=========================================
Логика: хитрость -> инструменты -> взрыв
"""

from ..monster_structs import MonsterFamily
from ..stat_ladders import build_role_ladder_stats as _build_role_ladder_stats


def build_role_ladder_stats(role, priority):
    return _build_role_ladder_stats(role, priority, organization_type="horde")


GOBLINS_FAMILY: MonsterFamily = {
    "id": "goblin_tribe",
    "resource_version": 1.2,
    "archetype": "humanoid",
    "organization_type": "horde",  # TSP Base: 30
    "default_tags": ["goblin", "small", "cunning", "tinkerer"],
    "family_modifiers": [
        {"target": "accuracy", "value": -0.10, "per_tier": 0.0},
        {"target": "dodge_chance", "value": 0.06, "per_tier": 0.01},
        {"target": "poison_efficiency", "value": 0.04, "per_tier": 0.01},
        {"target": "magical_resistance", "value": -0.04, "per_tier": 0.0},
    ],
    "loot_profile": {
        "salvage_type": "humanoid_gear",
        "loot_mode": "equipment",
        "allowed_loadout_slots": "full_humanoid",
        "equipment_drop_policy": "fixed_loadout",
        "drops_as_equipment": True,
        "equipment_quality": "poor_to_common",
        "materials": ["scrap_metal", "torn_cloth", "cracked_tool"],
    },
    "hierarchy": {
        "minions": ["goblin_sneak", "goblin_scavenger", "goblin_cutter", "goblin_sparkpick"],
        "veterans": ["goblin_spearman", "goblin_slinger", "goblin_scrapguard"],
        "elites": ["goblin_tinkerer", "goblin_bomber", "goblin_trapmaster"],
        "boss": ["goblin_chief", "scrap_king"],
    },
    "variants": {
        # --- 1. Мелочь (Minions) [TSP ~30] ---
        "goblin_sneak": {
            "id": "goblin_sneak",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 4,
            "narrative_hint": "A small goblin with a hooded cloak and a pair of sharp daggers, moves silently.",
            "extra_tags": ["stealth", "assassin"],
            "base_stats": build_role_ladder_stats(
                "minion",
                (
                    "agility",
                    "perception",
                    "endurance",
                    "strength",
                    "intellect",
                    "prediction",
                    "mental",
                    "memory",
                    "projection",
                ),
            ),
            "fixed_loadout": {"main_hand": "dagger", "off_hand": "dagger"},
            "skills": ["skill_fencing", "skill_dual_wield"],
        },
        "goblin_scavenger": {
            "id": "goblin_scavenger",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 4,
            "narrative_hint": "A goblin carrying a large, overflowing backpack. Wields a simple club.",
            "extra_tags": ["scavenger", "hoarder"],
            "base_stats": build_role_ladder_stats(
                "minion",
                (
                    "agility",
                    "endurance",
                    "strength",
                    "perception",
                    "intellect",
                    "prediction",
                    "mental",
                    "memory",
                    "projection",
                ),
            ),
            "fixed_loadout": {"main_hand": "mace"},
            "skills": ["skill_macing"],
        },
        "goblin_cutter": {
            "id": "goblin_cutter",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 4,
            "narrative_hint": "A mean little goblin with a chipped knife and a habit of aiming for tendons.",
            "extra_tags": ["knife", "bleeder", "ambusher"],
            "base_stats": build_role_ladder_stats(
                "minion",
                (
                    "agility",
                    "endurance",
                    "perception",
                    "strength",
                    "intellect",
                    "mental",
                    "prediction",
                    "memory",
                    "projection",
                ),
            ),
            "fixed_loadout": {"main_hand": "dagger"},
            "skills": ["skill_fencing"],
        },
        "goblin_sparkpick": {
            "id": "goblin_sparkpick",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 4,
            "narrative_hint": "A scavenger carrying a bent tool that spits unstable ether sparks when swung.",
            "extra_tags": ["scrap", "ether", "reckless"],
            "base_stats": build_role_ladder_stats(
                "minion",
                (
                    "agility",
                    "endurance",
                    "strength",
                    "intellect",
                    "perception",
                    "mental",
                    "memory",
                    "projection",
                    "prediction",
                ),
            ),
            "fixed_loadout": {"main_hand": "hatchet"},
            "skills": ["skill_macing"],
        },
        # --- 2. Бойцы (Veterans) [TSP ~45] ---
        "goblin_spearman": {
            "id": "goblin_spearman",
            "role": "veteran",
            "cost": 50,
            "min_tier": 0,
            "max_tier": 5,
            "narrative_hint": "A disciplined goblin with a long spear and a crude wooden shield.",
            "extra_tags": ["infantry", "shield"],
            "base_stats": build_role_ladder_stats(
                "veteran",
                (
                    "endurance",
                    "agility",
                    "strength",
                    "perception",
                    "intellect",
                    "mental",
                    "memory",
                    "projection",
                    "prediction",
                ),
            ),
            "fixed_loadout": {"main_hand": "spear", "off_hand": "shield", "chest_armor": "jerkin"},
            "skills": ["skill_polearms", "skill_medium_armor", "skill_shield_mastery"],
        },
        "goblin_slinger": {
            "id": "goblin_slinger",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 5,
            "narrative_hint": "A fast goblin with a short bow and a simple quiver of training arrows.",
            "extra_tags": ["ranged", "archer", "fast"],
            "base_stats": build_role_ladder_stats(
                "veteran",
                (
                    "agility",
                    "perception",
                    "endurance",
                    "strength",
                    "intellect",
                    "memory",
                    "mental",
                    "prediction",
                    "projection",
                ),
            ),
            "fixed_loadout": {"two_hand": "shortbow", "quiver": "quiver_training"},
            "skills": ["skill_archery", "skill_ranged_combat"],
        },
        "goblin_scrapguard": {
            "id": "goblin_scrapguard",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 5,
            "narrative_hint": "A squat goblin hiding behind a crude shield packed with scavenged metal plates.",
            "extra_tags": ["shield", "defender", "scrap"],
            "base_stats": build_role_ladder_stats(
                "veteran",
                (
                    "endurance",
                    "strength",
                    "agility",
                    "perception",
                    "mental",
                    "intellect",
                    "memory",
                    "projection",
                    "prediction",
                ),
            ),
            "fixed_loadout": {"main_hand": "mace", "off_hand": "shield", "chest_armor": "jerkin"},
            "skills": ["skill_macing", "skill_medium_armor", "skill_shield_mastery"],
        },
        # --- 3. Инженеры (Elites) [TSP ~75] ---
        "goblin_tinkerer": {
            "id": "goblin_tinkerer",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 6,
            "narrative_hint": "A goblin with a leather cap and a belt full of tools. Throws caltrops and sets traps.",
            "extra_tags": ["engineer", "trapper"],
            "base_stats": build_role_ladder_stats(
                "elite",
                (
                    "intellect",
                    "agility",
                    "perception",
                    "endurance",
                    "memory",
                    "strength",
                    "mental",
                    "projection",
                    "prediction",
                ),
            ),
            "fixed_loadout": {"main_hand": "dagger"},
            "skills": ["skill_fencing", "skill_tactics"],
        },
        "goblin_bomber": {
            "id": "goblin_bomber",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 6,
            "narrative_hint": "A goblin with a manic grin and a sack of crude explosives.",
            "extra_tags": ["bomber", "explosives", "reckless"],
            "base_stats": build_role_ladder_stats(
                "elite",
                (
                    "agility",
                    "endurance",
                    "intellect",
                    "perception",
                    "strength",
                    "mental",
                    "prediction",
                    "memory",
                    "projection",
                ),
            ),
            "fixed_loadout": {"main_hand": "sling", "chest_armor": "jerkin"},
            "skills": ["skill_archery", "skill_medium_armor", "skill_ranged_combat", "skill_tactics"],
        },
        "goblin_trapmaster": {
            "id": "goblin_trapmaster",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 6,
            "narrative_hint": "A patient goblin engineer covered in twine, hooks, and stolen monolith fragments.",
            "extra_tags": ["trapper", "engineer", "controller"],
            "base_stats": build_role_ladder_stats(
                "elite",
                (
                    "intellect",
                    "perception",
                    "agility",
                    "endurance",
                    "memory",
                    "strength",
                    "mental",
                    "prediction",
                    "projection",
                ),
            ),
            "fixed_loadout": {"main_hand": "dagger"},
            "skills": ["skill_fencing", "skill_tactics", "skill_anatomy"],
        },
        # --- 4. Вожди (Bosses) [TSP ~120] ---
        "goblin_chief": {
            "id": "goblin_chief",
            "role": "boss",
            "cost": 600,
            "min_tier": 3,
            "max_tier": 7,
            "narrative_hint": "A larger, smarter goblin wearing a crude crown and better armor. Shouts commands.",
            "extra_tags": ["leader", "commander"],
            "base_stats": build_role_ladder_stats(
                "boss",
                (
                    "endurance",
                    "strength",
                    "agility",
                    "mental",
                    "perception",
                    "projection",
                    "intellect",
                    "memory",
                    "prediction",
                ),
            ),
            "fixed_loadout": {"main_hand": "battle_axe", "chest_armor": "plate_chest"},
            "skills": ["skill_macing", "skill_heavy_armor", "skill_tactics", "skill_anatomy"],
        },
        "scrap_king": {
            "id": "scrap_king",
            "role": "boss",
            "cost": 600,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A huge goblin sitting on a throne of junk, wearing a makeshift power armor.",
            "extra_tags": ["king", "heavy_armor", "engineer"],
            "base_stats": build_role_ladder_stats(
                "boss",
                (
                    "endurance",
                    "strength",
                    "intellect",
                    "mental",
                    "projection",
                    "memory",
                    "perception",
                    "agility",
                    "prediction",
                ),
            ),
            "fixed_loadout": {
                "two_hand": "warhammer",
                "chest_armor": "plate_chest",
            },
            "skills": ["skill_macing", "skill_heavy_armor", "skill_two_handed", "skill_tactics", "skill_anatomy"],
        },
    },
}
