"""
СЕМЕЙСТВО: ОРКИ
===============
"""

from ..monster_structs import MonsterFamily

ORCS_FAMILY: MonsterFamily = {
    "id": "orc_clan",
    "archetype": "humanoid",
    "organization_type": "clan",
    "default_tags": ["orc", "savage", "green_skin", "tribal"],
    "hierarchy": {
        "minions": ["orc_peon", "orc_grunt"],
        "veterans": ["orc_archer", "orc_scout", "orc_raider"],
        "elites": ["orc_berserker", "orc_shaman"],
        "boss": ["orc_overlord"],
    },
    "variants": {
        # --- 1. Пехота (Minions) ---
        "orc_peon": {
            "id": "orc_peon",
            "role": "minion",
            "cost": 20,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "Hunched worker, carrying supplies, fearful eyes.",
            "extra_tags": ["worker", "weak"],
            "base_stats": {
                "strength": 8,
                "agility": 6,
                "endurance": 6,
                "intelligence": 2,
                "wisdom": 2,
                "men": 4,
                "perception": 4,
                "charisma": 1,
                "luck": 2,
            },
            "fixed_loadout": {"main_hand": "club", "chest_garment": "shirt", "feet_armor": "boots"},
            "skills": ["attack_basic"],
        },
        "orc_grunt": {
            "id": "orc_grunt",
            "role": "minion",
            "cost": 20,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "Standard infantry, scarred, disciplined growl.",
            "extra_tags": ["infantry", "strong", "shield"],
            "base_stats": {
                "strength": 12,
                "agility": 8,
                "endurance": 12,
                "intelligence": 3,
                "wisdom": 3,
                "men": 5,
                "perception": 5,
                "charisma": 3,
                "luck": 3,
            },
            "fixed_loadout": {
                "main_hand": "axe",
                "off_hand": "shield",
                "chest_armor": "leather_armor",
                "legs_armor": "leather_leggings",
                "feet_armor": "leather_boots",
            },
            "skills": ["attack_heavy", "buff_defense"],
        },
        # --- 2. Опытные бойцы (Veterans) ---
        "orc_archer": {
            "id": "orc_archer",
            "role": "veteran",
            "cost": 50,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "Muscular archer, squinting eyes, quiver on back.",
            "extra_tags": ["ranged", "archer"],
            "base_stats": {
                "strength": 10,
                "agility": 12,
                "endurance": 8,
                "intelligence": 4,
                "wisdom": 4,
                "men": 6,
                "perception": 12,
                "charisma": 2,
                "luck": 5,
            },
            "fixed_loadout": {
                "main_hand": "bow",
                "off_hand": "dagger",
                "chest_armor": "leather_armor",
                "head_armor": "helmet",
            },
            "skills": ["attack_ranged", "attack_pierce"],
        },
        "orc_scout": {
            "id": "orc_scout",
            "role": "veteran",
            "cost": 50,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "Camouflaged paint, moving silently, dual blades.",
            "extra_tags": ["stealth", "fast", "agile"],
            "base_stats": {
                "strength": 10,
                "agility": 15,
                "endurance": 9,
                "intelligence": 5,
                "wisdom": 5,
                "men": 8,
                "perception": 15,
                "charisma": 3,
                "luck": 8,
            },
            "fixed_loadout": {
                "main_hand": "dagger",
                "off_hand": "dagger",
                "chest_armor": "leather_armor",
                "outer_garment": "cloak",
                "feet_armor": "boots",
            },
            "skills": ["attack_heavy", "attack_basic"],
        },
        "orc_raider": {
            "id": "orc_raider",
            "role": "veteran",
            "cost": 50,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A mounted orc (or just fast), wielding a torch and a blade.",
            "extra_tags": ["fast", "fire"],
            "base_stats": {
                "strength": 14,
                "agility": 12,
                "endurance": 14,
                "intelligence": 4,
                "wisdom": 4,
                "men": 8,
                "perception": 10,
                "charisma": 4,
                "luck": 5,
            },
            "fixed_loadout": {"main_hand": "sword", "off_hand": "torch", "chest_armor": "chainmail"},
            "skills": ["attack_fast", "debuff_burn"],
        },
        # --- 3. Элита (Elites) ---
        "orc_berserker": {
            "id": "orc_berserker",
            "role": "elite",
            "cost": 150,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "Massive, foaming mouth, dual wielding axes, no armor.",
            "extra_tags": ["berserk", "furious", "unarmored"],
            "base_stats": {
                "strength": 20,
                "agility": 10,
                "endurance": 18,
                "intelligence": 2,
                "wisdom": 2,
                "men": 12,
                "perception": 6,
                "charisma": 2,
                "luck": 4,
            },
            "fixed_loadout": {
                "main_hand": "axe",
                "off_hand": "axe",
                "chest_garment": "shirt",
                "legs_garment": "trousers",
            },
            "skills": ["buff_rage", "attack_aoe", "buff_rage"],
        },
        "orc_shaman": {
            "id": "orc_shaman",
            "role": "elite",
            "cost": 150,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "Covered in bones and totems, glowing staff.",
            "extra_tags": ["magic", "mystic", "bones", "spiritual"],
            "base_stats": {
                "strength": 6,
                "agility": 6,
                "endurance": 10,
                "intelligence": 16,
                "wisdom": 14,
                "men": 20,
                "perception": 10,
                "charisma": 8,
                "luck": 6,
            },
            "fixed_loadout": {"main_hand": "staff", "chest_armor": "robe", "head_armor": "helmet", "amulet": "amulet"},
            "skills": ["attack_ranged", "buff_rage", "buff_heal"],
        },
        # --- 4. Босс (Boss) ---
        "orc_overlord": {
            "id": "orc_overlord",
            "role": "boss",
            "cost": 600,
            "min_tier": 5,
            "max_tier": 8,
            "narrative_hint": "Towering warlord, heavy plate, commanding presence.",
            "extra_tags": ["leader", "heavy_armor", "commander"],
            "base_stats": {
                "strength": 28,
                "agility": 8,
                "endurance": 30,
                "intelligence": 10,
                "wisdom": 12,
                "men": 15,
                "perception": 12,
                "charisma": 20,
                "luck": 10,
            },
            "fixed_loadout": {
                "main_hand": "greatsword",
                "chest_armor": "plate_chest",
                "head_armor": "helmet",
                "gloves_garment": "gloves",
                "feet_armor": "boots",
                "outer_garment": "cloak",
                "ring_1": "ring",
            },
            "skills": ["attack_aoe", "buff_rage", "attack_execute"],
        },
    },
}
