"""
СЕМЕЙСТВО: КРЫСЫ (Численность, заражение, давление массой)
=========================================================
Логика: количество -> паника -> болезнь
"""

from ..monster_structs import MonsterFamily
from ..stat_ladders import build_role_ladder_stats as _build_role_ladder_stats


def build_role_ladder_stats(role, priority):
    return _build_role_ladder_stats(role, priority, organization_type="swarm")


RATS_FAMILY: MonsterFamily = {
    "id": "rat_swarm",
    "resource_version": 1.1,
    "archetype": "beast",
    "organization_type": "swarm",  # TSP Base: 30
    "default_tags": ["beast", "rat", "disease", "swarm"],
    "family_modifiers": [
        {"target": "accuracy", "value": -0.10, "per_tier": 0.0},
        {"target": "poison_efficiency", "value": 0.05, "per_tier": 0.02},
        {"target": "poison_resistance", "value": 0.06, "per_tier": 0.01},
        {"target": "bleed_resistance", "value": 0.04, "per_tier": 0.01},
        {"target": "anti_dodge_chance", "value": 0.03, "per_tier": 0.01},
    ],
    "loot_profile": {
        "salvage_type": "beast_parts",
        "loot_mode": "salvage",
        "allowed_loadout_slots": "natural_only",
        "equipment_drop_policy": "none",
        "drops_as_equipment": False,
        "materials": ["fang", "hide_scrap", "bone", "tainted_sample"],
    },
    "hierarchy": {
        "minions": ["sewer_rat", "scavenger_rat", "swarm_rat"],
        "veterans": ["tunnel_rat", "pack_rat", "screecher"],
        "elites": ["plague_rat", "rotfang", "blight_carrier"],
        "boss": ["rat_brute", "brood_alpha", "rat_king"],
    },
    "variants": {
        # --- 1. Мелкие (Minions) [TSP ~30] ---
        "sewer_rat": {
            "id": "sewer_rat",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "A dirty, wet rat with matted fur. Scavenges for food.",
            "extra_tags": ["shared", "weak"],
            "base_stats": build_role_ladder_stats(
                "minion",
                (
                    "agility",
                    "endurance",
                    "strength",
                    "perception",
                    "mental",
                    "prediction",
                    "intellect",
                    "memory",
                    "projection",
                ),
            ),
            "fixed_loadout": {"main_hand": "rat_bite_claws", "chest_armor": "rat_light_hide"},
            "skills": ["skill_fencing", "skill_light_armor"],
        },
        "scavenger_rat": {
            "id": "scavenger_rat",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "A rat dragging a piece of refuse. Will fight to protect its treasure.",
            "extra_tags": ["scavenger", "hoarder"],
            "base_stats": build_role_ladder_stats(
                "minion",
                (
                    "agility",
                    "strength",
                    "endurance",
                    "perception",
                    "mental",
                    "prediction",
                    "intellect",
                    "memory",
                    "projection",
                ),
            ),
            "fixed_loadout": {"main_hand": "rat_bite_claws", "chest_armor": "rat_light_hide"},
            "skills": ["skill_fencing", "skill_light_armor"],
        },
        "swarm_rat": {
            "id": "swarm_rat",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "One of hundreds. Individually weak, but terrifying in numbers.",
            "extra_tags": ["swarm", "frenzied"],
            "base_stats": build_role_ladder_stats(
                "minion",
                (
                    "agility",
                    "endurance",
                    "strength",
                    "perception",
                    "mental",
                    "prediction",
                    "intellect",
                    "memory",
                    "projection",
                ),
            ),
            "fixed_loadout": {"main_hand": "rat_bite_claws", "chest_armor": "rat_light_hide"},
            "skills": ["skill_fencing", "skill_light_armor"],
        },
        # --- 2. Опытные бойцы (Veterans) [TSP ~45] ---
        "tunnel_rat": {
            "id": "tunnel_rat",
            "role": "veteran",
            "cost": 50,
            "min_tier": 0,
            "max_tier": 4,
            "narrative_hint": "A rat with large claws for digging. Moves silently in the dark.",
            "extra_tags": ["stealth", "digger"],
            "base_stats": build_role_ladder_stats(
                "veteran",
                (
                    "agility",
                    "endurance",
                    "strength",
                    "perception",
                    "mental",
                    "prediction",
                    "intellect",
                    "memory",
                    "projection",
                ),
            ),
            "fixed_loadout": {"main_hand": "rat_veteran_claws", "chest_armor": "rat_medium_hide"},
            "skills": ["skill_fencing", "skill_medium_armor"],
        },
        "pack_rat": {
            "id": "pack_rat",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A rat that never fights alone. Always looks for allies.",
            "extra_tags": ["pack_tactics", "social"],
            "base_stats": build_role_ladder_stats(
                "veteran",
                (
                    "endurance",
                    "strength",
                    "agility",
                    "perception",
                    "mental",
                    "intellect",
                    "prediction",
                    "memory",
                    "projection",
                ),
            ),
            "fixed_loadout": {"main_hand": "rat_veteran_claws", "chest_armor": "rat_light_hide"},
            "skills": ["skill_fencing", "skill_light_armor"],
        },
        "screecher": {
            "id": "screecher",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A rat with an oversized throat pouch. Emits ear-piercing shrieks.",
            "extra_tags": ["support", "alarm"],
            "base_stats": build_role_ladder_stats(
                "veteran",
                (
                    "agility",
                    "perception",
                    "endurance",
                    "strength",
                    "mental",
                    "intellect",
                    "prediction",
                    "memory",
                    "projection",
                ),
            ),
            "fixed_loadout": {"main_hand": "rat_veteran_claws", "chest_armor": "rat_medium_hide"},
            "skills": ["skill_fencing", "skill_medium_armor"],
        },
        # --- 3. Элита (Elites) [TSP ~75] ---
        "plague_rat": {
            "id": "plague_rat",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A rat covered in weeping sores and green pustules. Leaves a trail of sickness.",
            "extra_tags": ["plague", "poison", "aura"],
            "base_stats": build_role_ladder_stats(
                "elite",
                (
                    "endurance",
                    "strength",
                    "agility",
                    "mental",
                    "perception",
                    "intellect",
                    "memory",
                    "projection",
                    "prediction",
                ),
            ),
            "fixed_loadout": {"main_hand": "rat_elite_claws", "chest_armor": "rat_medium_hide"},
            "skills": ["skill_fencing", "skill_medium_armor", "skill_anatomy"],
        },
        "rotfang": {
            "id": "rotfang",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A large rat with dripping, rotten fangs. Its bite causes necrosis.",
            "extra_tags": ["necrosis", "bleed"],
            "base_stats": build_role_ladder_stats(
                "elite",
                (
                    "strength",
                    "agility",
                    "endurance",
                    "perception",
                    "mental",
                    "intellect",
                    "memory",
                    "prediction",
                    "projection",
                ),
            ),
            "fixed_loadout": {"main_hand": "rat_elite_claws", "chest_armor": "rat_heavy_hide"},
            "skills": ["skill_fencing", "skill_heavy_armor", "skill_anatomy"],
        },
        "blight_carrier": {
            "id": "blight_carrier",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A bloated rat that explodes upon death, spreading disease.",
            "extra_tags": ["explosive", "blight"],
            "base_stats": build_role_ladder_stats(
                "elite",
                (
                    "endurance",
                    "strength",
                    "mental",
                    "agility",
                    "perception",
                    "intellect",
                    "memory",
                    "projection",
                    "prediction",
                ),
            ),
            "fixed_loadout": {"main_hand": "rat_elite_claws", "chest_armor": "rat_medium_hide"},
            "skills": ["skill_fencing", "skill_medium_armor", "skill_anatomy"],
        },
        # --- 4. Боссы (Bosses) [TSP ~120] ---
        "rat_brute": {
            "id": "rat_brute",
            "role": "boss",
            "cost": 600,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A hulking, muscular rat, possibly mutated. Smashes through obstacles.",
            "extra_tags": ["brute", "mutated", "strong"],
            "base_stats": build_role_ladder_stats(
                "boss",
                (
                    "endurance",
                    "strength",
                    "mental",
                    "agility",
                    "perception",
                    "projection",
                    "prediction",
                    "intellect",
                    "memory",
                ),
            ),
            "fixed_loadout": {"main_hand": "rat_boss_claws", "chest_armor": "rat_heavy_hide"},
            "skills": ["skill_fencing", "skill_heavy_armor", "skill_tactics", "skill_anatomy"],
        },
        "brood_alpha": {
            "id": "brood_alpha",
            "role": "boss",
            "cost": 600,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A cunning alpha rat that directs the swarm with chirps and gestures.",
            "extra_tags": ["leader", "alpha", "tactician"],
            "base_stats": build_role_ladder_stats(
                "boss",
                (
                    "agility",
                    "endurance",
                    "strength",
                    "perception",
                    "mental",
                    "intellect",
                    "projection",
                    "memory",
                    "prediction",
                ),
            ),
            "fixed_loadout": {"main_hand": "rat_boss_claws", "chest_armor": "rat_heavy_hide"},
            "skills": ["skill_fencing", "skill_heavy_armor", "skill_tactics", "skill_anatomy"],
        },
        "rat_king": {
            "id": "rat_king",
            "role": "boss",
            "cost": 600,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A horrific amalgamation of several rats joined at the tail. Moves as one entity.",
            "extra_tags": ["king", "abomination", "hive_mind"],
            "base_stats": build_role_ladder_stats(
                "boss",
                (
                    "endurance",
                    "strength",
                    "mental",
                    "perception",
                    "projection",
                    "intellect",
                    "memory",
                    "agility",
                    "prediction",
                ),
            ),
            "fixed_loadout": {"main_hand": "rat_boss_claws", "chest_armor": "rat_heavy_hide"},
            "skills": ["skill_fencing", "skill_heavy_armor", "skill_tactics", "skill_anatomy"],
        },
    },
}
