"""
СЕМЕЙСТВО: ЗМЕИ (Засада, укус, отступление)
===========================================
Логика: засада -> укус -> отступление
"""

from ..monster_structs import MonsterFamily

SNAKES_FAMILY: MonsterFamily = {
    "id": "snake_den",
    "archetype": "beast",
    "organization_type": "solitary",  # TSP Base: 100 (Одиночки)
    "default_tags": ["beast", "snake", "venomous", "ambush"],
    "hierarchy": {
        "minions": ["nestling", "hatchling"],
        "veterans": ["coil_striker", "brush_serpent", "venom_fang", "neuro_viper"],
        "elites": ["constrictor", "serpent_alpha"],
        "boss": ["basilisk", "world_serpent"],
    },
    "variants": {
        # --- 1. Молодь / Фон (Minions) [TSP ~100] ---
        "nestling": {
            "id": "nestling",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "A tiny snake, barely out of the egg. Hisses defensively.",
            "extra_tags": ["young", "weak"],
            "base_stats": {
                "strength": 10,
                "agility": 30,
                "endurance": 20,
                "intellect": 5,
                "memory": 5,
                "mental": 10,
                "perception": 15,
                "projection": 1,
                "prediction": 5,  # Итого: 101
            },
            "fixed_loadout": {},
            "skills": ["attack_basic"],
        },
        "hatchling": {
            "id": "hatchling",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "A young, fast snake. Slithers away at the first sign of danger.",
            "extra_tags": ["young", "fast"],
            "base_stats": {
                "strength": 15,
                "agility": 35,
                "endurance": 15,
                "intellect": 5,
                "memory": 5,
                "mental": 10,
                "perception": 15,
                "projection": 1,
                "prediction": 5,  # Итого: 106
            },
            "fixed_loadout": {},
            "skills": ["attack_fast"],
        },
        # --- 2. Охотники (Veterans) [TSP ~150] ---
        "coil_striker": {
            "id": "coil_striker",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A muscular snake coiled like a spring. Ready to launch itself.",
            "extra_tags": ["striker", "fast"],
            "base_stats": {
                "strength": 30,
                "agility": 40,
                "endurance": 30,
                "intellect": 8,
                "memory": 8,
                "mental": 15,
                "perception": 20,
                "projection": 1,
                "prediction": 5,  # Итого: 157
            },
            "fixed_loadout": {},
            "skills": ["attack_heavy", "attack_basic"],
        },
        "brush_serpent": {
            "id": "brush_serpent",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A snake with scales that perfectly match the surrounding foliage.",
            "extra_tags": ["stealth", "ambusher"],
            "base_stats": {
                "strength": 25,
                "agility": 35,
                "endurance": 30,
                "intellect": 10,
                "memory": 10,
                "mental": 15,
                "perception": 25,
                "projection": 1,
                "prediction": 5,  # Итого: 156
            },
            "fixed_loadout": {},
            "skills": ["buff_evasion", "attack_heavy"],
        },
        "venom_fang": {
            "id": "venom_fang",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A brightly colored snake with dripping fangs. Hisses a warning.",
            "extra_tags": ["poison", "ranged"],
            "base_stats": {
                "strength": 20,
                "agility": 30,
                "endurance": 25,
                "intellect": 10,
                "memory": 10,
                "mental": 20,
                "perception": 20,
                "projection": 2,
                "prediction": 5,  # Итого: 142
            },
            "fixed_loadout": {},
            "skills": ["debuff_poison", "debuff_poison"],
        },
        "neuro_viper": {
            "id": "neuro_viper",
            "role": "veteran",
            "cost": 50,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A sleek, dark viper. Its venom attacks the nervous system.",
            "extra_tags": ["poison", "control"],
            "base_stats": {
                "strength": 15,
                "agility": 45,
                "endurance": 20,
                "intellect": 12,
                "memory": 12,
                "mental": 25,
                "perception": 25,
                "projection": 2,
                "prediction": 5,  # Итого: 161
            },
            "fixed_loadout": {},
            "skills": ["debuff_stun", "debuff_slow"],
        },
        # --- 3. Доминирующие (Elites) [TSP ~250] ---
        "constrictor": {
            "id": "constrictor",
            "role": "elite",
            "cost": 150,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A massive, thick-bodied snake capable of crushing bones.",
            "extra_tags": ["brute", "grappler"],
            "base_stats": {
                "strength": 60,
                "agility": 20,
                "endurance": 80,
                "intellect": 10,
                "memory": 10,
                "mental": 30,
                "perception": 20,
                "projection": 5,
                "prediction": 5,  # Итого: 240
            },
            "fixed_loadout": {},
            "skills": ["attack_heavy", "debuff_stun", "debuff_bleed"],
        },
        "serpent_alpha": {
            "id": "serpent_alpha",
            "role": "elite",
            "cost": 150,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A large, scarred snake that seems to command others nearby.",
            "extra_tags": ["leader", "alpha"],
            "base_stats": {
                "strength": 40,
                "agility": 40,
                "endurance": 50,
                "intellect": 15,
                "memory": 15,
                "mental": 35,
                "perception": 30,
                "projection": 15,
                "prediction": 10,  # Итого: 250
            },
            "fixed_loadout": {},
            "skills": ["buff_rage", "attack_fast", "debuff_weaken"],
        },
        # --- 4. Боссы (Bosses) [TSP ~400] ---
        "basilisk": {
            "id": "basilisk",
            "role": "boss",
            "cost": 600,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A legendary serpent with a gaze that turns flesh to stone.",
            "extra_tags": ["legendary", "petrify"],
            "base_stats": {
                "strength": 60,
                "agility": 30,
                "endurance": 80,
                "intellect": 25,
                "memory": 30,
                "mental": 60,
                "perception": 50,
                "projection": 30,
                "prediction": 20,  # Итого: 385
            },
            "fixed_loadout": {},
            "skills": ["debuff_stun", "debuff_poison", "attack_aoe"],
        },
        "world_serpent": {
            "id": "world_serpent",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 7,
            "narrative_hint": "An ancient, colossal snake that seems to be part of the earth itself.",
            "extra_tags": ["ancient", "colossal"],
            "base_stats": {
                "strength": 100,
                "agility": 20,
                "endurance": 150,
                "intellect": 40,
                "memory": 50,
                "mental": 80,
                "perception": 50,
                "projection": 40,
                "prediction": 20,  # Итого: 550
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "attack_execute", "debuff_poison"],
        },
    },
}
