"""
СЕМЕЙСТВО: ПАУКИ (Территория, сети, контроль)
=============================================
Логика: сеть -> засада -> подавление
"""

from ..monster_structs import MonsterFamily

SPIDERS_FAMILY: MonsterFamily = {
    "id": "spider_colony",
    "archetype": "beast",
    "organization_type": "swarm",  # TSP Base: 30
    "default_tags": ["beast", "spider", "venomous", "web"],
    "hierarchy": {
        "minions": ["spiderling", "skitterer", "cave_spider"],
        "veterans": ["web_stalker", "venom_spider", "ambush_spinner"],
        "elites": ["web_guardian", "brood_keeper", "silk_binder"],
        "boss": ["matriarch", "venom_tyrant", "ancient_weaver"],
    },
    "variants": {
        # --- 1. Мелкие (Minions) [TSP ~30] ---
        "spiderling": {
            "id": "spiderling",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 2,
            "narrative_hint": "A small, pale spider, barely the size of a cat. Moves in swarms.",
            "extra_tags": ["swarm", "weak"],
            "base_stats": {
                "strength": 2,
                "agility": 12,
                "endurance": 4,
                "intellect": 1,
                "memory": 1,
                "mental": 2,
                "perception": 6,
                "projection": 1,
                "prediction": 2,  # Итого: 31
            },
            "fixed_loadout": {},
            "skills": ["attack_basic", "attack_aoe"],
        },
        "skitterer": {
            "id": "skitterer",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "A long-legged spider that moves with blinding speed.",
            "extra_tags": ["fast", "agile"],
            "base_stats": {
                "strength": 4,
                "agility": 16,
                "endurance": 4,
                "intellect": 1,
                "memory": 1,
                "mental": 2,
                "perception": 6,
                "projection": 1,
                "prediction": 4,  # Итого: 39
            },
            "fixed_loadout": {},
            "skills": ["attack_fast", "buff_evasion"],
        },
        "cave_spider": {
            "id": "cave_spider",
            "role": "minion",
            "cost": 20,
            "min_tier": 1,
            "max_tier": 5,
            "narrative_hint": "A standard cave spider with thick chitin and sharp mandibles.",
            "extra_tags": ["standard", "cave"],
            "base_stats": {
                "strength": 8,
                "agility": 8,
                "endurance": 8,
                "intellect": 1,
                "memory": 1,
                "mental": 2,
                "perception": 4,
                "projection": 1,
                "prediction": 2,  # Итого: 35
            },
            "fixed_loadout": {},
            "skills": ["attack_basic", "debuff_slow"],
        },
        # --- 2. Охотники (Veterans) [TSP ~45] ---
        "web_stalker": {
            "id": "web_stalker",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 6,
            "narrative_hint": "A dark spider that blends into the shadows. Waits for prey to get stuck.",
            "extra_tags": ["trapper", "stealth"],
            "base_stats": {
                "strength": 6,
                "agility": 12,
                "endurance": 8,
                "intellect": 2,
                "memory": 2,
                "mental": 4,
                "perception": 10,
                "projection": 1,
                "prediction": 3,  # Итого: 48
            },
            "fixed_loadout": {},
            "skills": ["special_trap", "attack_heavy"],
        },
        "venom_spider": {
            "id": "venom_spider",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 6,
            "narrative_hint": "A brightly colored spider dripping with green venom.",
            "extra_tags": ["poison", "ranged"],
            "base_stats": {
                "strength": 4,
                "agility": 10,
                "endurance": 6,
                "intellect": 2,
                "memory": 2,
                "mental": 4,
                "perception": 8,
                "projection": 1,
                "prediction": 3,  # Итого: 40 (компенсация ядом)
            },
            "fixed_loadout": {},
            "skills": ["debuff_poison", "debuff_poison"],
        },
        "ambush_spinner": {
            "id": "ambush_spinner",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 6,
            "narrative_hint": "A spider that buries itself in the ground, waiting to strike.",
            "extra_tags": ["ambush", "surprise"],
            "base_stats": {
                "strength": 8,
                "agility": 14,
                "endurance": 8,
                "intellect": 2,
                "memory": 2,
                "mental": 4,
                "perception": 10,
                "projection": 1,
                "prediction": 4,  # Итого: 53
            },
            "fixed_loadout": {},
            "skills": ["attack_heavy", "attack_heavy"],
        },
        # --- 3. Контролеры территории (Elites) [TSP ~75] ---
        "web_guardian": {
            "id": "web_guardian",
            "role": "elite",
            "cost": 150,
            "min_tier": 3,
            "max_tier": 7,
            "narrative_hint": "A large, heavily armored spider guarding the entrance to the nest.",
            "extra_tags": ["guardian", "heavy_armor"],
            "base_stats": {
                "strength": 14,
                "agility": 6,
                "endurance": 20,
                "intellect": 2,
                "memory": 2,
                "mental": 8,
                "perception": 8,
                "projection": 1,
                "prediction": 3,  # Итого: 64 (но очень жирный)
            },
            "fixed_loadout": {},
            "skills": ["buff_defense", "debuff_stun", "special_trap"],
        },
        "brood_keeper": {
            "id": "brood_keeper",
            "role": "elite",
            "cost": 150,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A bloated spider surrounded by hundreds of tiny spiderlings.",
            "extra_tags": ["summoner", "support"],
            "base_stats": {
                "strength": 8,
                "agility": 6,
                "endurance": 16,
                "intellect": 4,
                "memory": 4,
                "mental": 10,
                "perception": 8,
                "projection": 6,
                "prediction": 4,  # Итого: 66 (сила в призыве)
            },
            "fixed_loadout": {},
            "skills": ["summon_minion", "buff_rage", "attack_lifesteal"],
        },
        "silk_binder": {
            "id": "silk_binder",
            "role": "elite",
            "cost": 150,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A spider with elongated limbs, weaving complex magical webs.",
            "extra_tags": ["controller", "magic"],
            "base_stats": {
                "strength": 6,
                "agility": 14,
                "endurance": 10,
                "intellect": 8,
                "memory": 8,
                "mental": 12,
                "perception": 12,
                "projection": 2,
                "prediction": 4,  # Итого: 76
            },
            "fixed_loadout": {},
            "skills": ["debuff_slow", "debuff_stun", "debuff_slow"],
        },
        # --- 4. Альфы (Bosses) [TSP ~120] ---
        "matriarch": {
            "id": "matriarch",
            "role": "boss",
            "cost": 600,
            "min_tier": 5,
            "max_tier": 7,
            "narrative_hint": "A colossal spider queen, her abdomen pulsing with eggs. The ground shakes when she moves.",
            "extra_tags": ["queen", "leader", "summoner"],
            "base_stats": {
                "strength": 20,
                "agility": 10,
                "endurance": 30,
                "intellect": 10,
                "memory": 10,
                "mental": 20,
                "perception": 15,
                "projection": 10,
                "prediction": 8,  # Итого: 133
            },
            "fixed_loadout": {},
            "skills": ["debuff_weaken", "debuff_slow", "attack_execute", "summon_minion"],
        },
        "venom_tyrant": {
            "id": "venom_tyrant",
            "role": "boss",
            "cost": 600,
            "min_tier": 6,
            "max_tier": 7,
            "narrative_hint": "A giant spider glowing with toxic energy. Its venom melts stone.",
            "extra_tags": ["tyrant", "acid", "poison"],
            "base_stats": {
                "strength": 18,
                "agility": 16,
                "endurance": 25,
                "intellect": 6,
                "memory": 8,
                "mental": 15,
                "perception": 14,
                "projection": 5,
                "prediction": 8,  # Итого: 115
            },
            "fixed_loadout": {},
            "skills": ["debuff_armor_break", "debuff_poison", "debuff_poison", "debuff_armor_break"],
        },
        "ancient_weaver": {
            "id": "ancient_weaver",
            "role": "boss",
            "cost": 600,
            "min_tier": 7,
            "max_tier": 7,
            "narrative_hint": "An impossibly old spider, weaving threads of fate and magic.",
            "extra_tags": ["ancient", "magic", "fate"],
            "base_stats": {
                "strength": 10,
                "agility": 10,
                "endurance": 20,
                "intellect": 25,
                "memory": 25,
                "mental": 30,
                "perception": 20,
                "projection": 10,
                "prediction": 15,  # Итого: 165
            },
            "fixed_loadout": {},
            "skills": ["special_unique", "attack_ranged", "debuff_slow", "special_unique"],
        },
    },
}
