"""
СЕМЕЙСТВО: НЕЖИТЬ (Иерархия подчинения)
=======================================
Логика: воля некроманта -> контроль
"""

from ..monster_structs import MonsterFamily

UNDEAD_FAMILY: MonsterFamily = {
    "id": "undead_legion",
    "archetype": "undead",
    "organization_type": "horde",  # TSP Base: 30
    "default_tags": ["undead", "fearless", "dark_magic"],
    "hierarchy": {
        "minions": ["skeleton_servant", "rotting_corpse", "bone_walker"],
        "veterans": ["skeleton_soldier", "grave_guard", "zombie_brute"],
        "elites": ["death_knight", "wight", "bone_champion"],
        "boss": ["lich_acolyte", "necromancer", "lich_lord"],
    },
    "variants": {
        # --- 1. Пешки (Minions) [TSP ~30] ---
        "skeleton_servant": {
            "id": "skeleton_servant",
            "role": "minion",
            "cost": 20,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A fragile skeleton holding a rusty tool or weapon. Moves with jerky motions.",
            "extra_tags": ["skeleton", "weak"],
            "base_stats": {
                "strength": 6,
                "agility": 8,
                "endurance": 6,
                "intellect": 1,
                "memory": 1,
                "mental": 10,  # Нежить не знает страха
                "perception": 4,
                "projection": 1,
                "prediction": 1,  # Итого: 38 (из-за Men)
            },
            "fixed_loadout": {"main_hand": "dagger", "chest_garment": "shirt"},
            "skills": ["attack_basic"],
        },
        "rotting_corpse": {
            "id": "rotting_corpse",
            "role": "minion",
            "cost": 20,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A shambling corpse, surrounded by flies. Smells of decay.",
            "extra_tags": ["zombie", "disease"],
            "base_stats": {
                "strength": 8,
                "agility": 2,
                "endurance": 12,
                "intellect": 1,
                "memory": 1,
                "mental": 10,
                "perception": 2,
                "projection": 1,
                "prediction": 1,  # Итого: 38
            },
            "fixed_loadout": {"chest_garment": "shirt", "legs_garment": "trousers"},
            "skills": ["attack_basic", "debuff_poison"],
        },
        "bone_walker": {
            "id": "bone_walker",
            "role": "minion",
            "cost": 20,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A skeleton reinforced with extra bones. Looks sturdier than a servant.",
            "extra_tags": ["skeleton", "sturdy"],
            "base_stats": {
                "strength": 8,
                "agility": 6,
                "endurance": 8,
                "intellect": 2,
                "memory": 2,
                "mental": 10,
                "perception": 4,
                "projection": 1,
                "prediction": 2,  # Итого: 43
            },
            "fixed_loadout": {"main_hand": "mace", "off_hand": "buckler"},
            "skills": ["attack_heavy"],
        },
        # --- 2. Воины (Veterans) [TSP ~45] ---
        "skeleton_soldier": {
            "id": "skeleton_soldier",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A skeleton in tattered military gear. Holds a formation.",
            "extra_tags": ["skeleton", "soldier", "shield"],
            "base_stats": {
                "strength": 10,
                "agility": 8,
                "endurance": 10,
                "intellect": 2,
                "memory": 2,
                "mental": 10,
                "perception": 6,
                "projection": 1,
                "prediction": 2,  # Итого: 51
            },
            "fixed_loadout": {
                "main_hand": "sword",
                "off_hand": "shield",
                "chest_armor": "jerkin",
                "head_armor": "helmet",
            },
            "skills": ["attack_basic", "buff_defense"],
        },
        "grave_guard": {
            "id": "grave_guard",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A heavily armored skeleton with a large shield. Stands guard eternally.",
            "extra_tags": ["skeleton", "heavy_armor", "guardian"],
            "base_stats": {
                "strength": 12,
                "agility": 4,
                "endurance": 14,
                "intellect": 2,
                "memory": 2,
                "mental": 10,
                "perception": 6,
                "projection": 1,
                "prediction": 2,  # Итого: 53
            },
            "fixed_loadout": {
                "main_hand": "mace",
                "off_hand": "shield",
                "chest_armor": "plate_chest",
                "head_armor": "helmet",
                "legs_armor": "greaves",
            },
            "skills": ["debuff_stun", "buff_defense"],
        },
        "zombie_brute": {
            "id": "zombie_brute",
            "role": "veteran",
            "cost": 50,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A massive, bloated zombie. Its skin is tough as leather.",
            "extra_tags": ["zombie", "brute", "tough"],
            "base_stats": {
                "strength": 18,
                "agility": 2,
                "endurance": 20,
                "intellect": 1,
                "memory": 1,
                "mental": 10,
                "perception": 2,
                "projection": 1,
                "prediction": 1,  # Итого: 56
            },
            "fixed_loadout": {"main_hand": "warhammer"},
            "skills": ["attack_heavy", "explode_on_death"],
        },
        # --- 3. Элита (Elites) [TSP ~75] ---
        "death_knight": {
            "id": "death_knight",
            "role": "elite",
            "cost": 150,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A fallen knight in black plate armor. Eyes glow with cold blue light.",
            "extra_tags": ["knight", "heavy_armor", "cold"],
            "base_stats": {
                "strength": 18,
                "agility": 8,
                "endurance": 18,
                "intellect": 6,
                "memory": 6,
                "mental": 12,
                "perception": 8,
                "projection": 8,
                "prediction": 4,  # Итого: 88
            },
            "fixed_loadout": {
                "main_hand": "greatsword",
                "chest_armor": "plate_chest",
                "head_armor": "helmet",
                "arms_armor": "gauntlets",
                "legs_armor": "greaves",
                "feetwear": "sabatons",
            },
            "skills": ["debuff_stun", "attack_heavy", "debuff_weaken"],
        },
        "wight": {
            "id": "wight",
            "role": "elite",
            "cost": 150,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A desiccated corpse that moves with unnatural speed. Drains life.",
            "extra_tags": ["fast", "lifesteal"],
            "base_stats": {
                "strength": 12,
                "agility": 16,
                "endurance": 12,
                "intellect": 8,
                "memory": 8,
                "mental": 12,
                "perception": 10,
                "projection": 4,
                "prediction": 6,  # Итого: 88
            },
            "fixed_loadout": {"main_hand": "sword", "off_hand": "dagger", "chest_garment": "cloak"},
            "skills": ["attack_lifesteal", "debuff_stun"],
        },
        "bone_champion": {
            "id": "bone_champion",
            "role": "elite",
            "cost": 150,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A skeleton warrior of immense skill, wielding dual blades.",
            "extra_tags": ["skeleton", "champion", "dual_wield"],
            "base_stats": {
                "strength": 14,
                "agility": 18,
                "endurance": 14,
                "intellect": 6,
                "memory": 6,
                "mental": 10,
                "perception": 12,
                "projection": 4,
                "prediction": 8,  # Итого: 92
            },
            "fixed_loadout": {"main_hand": "katana", "off_hand": "wakizashi", "chest_armor": "plate_chest"},
            "skills": ["attack_aoe", "attack_aoe"],
        },
        # --- 4. Командиры (Bosses) [TSP ~120] ---
        "lich_acolyte": {
            "id": "lich_acolyte",
            "role": "boss",
            "cost": 600,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A skeletal mage in tattered robes, wielding a staff of dark power.",
            "extra_tags": ["lich", "mage", "summoner"],
            "base_stats": {
                "strength": 6,
                "agility": 8,
                "endurance": 12,
                "intellect": 20,
                "memory": 18,
                "mental": 20,
                "perception": 14,
                "projection": 12,
                "prediction": 8,  # Итого: 118
            },
            "fixed_loadout": {"main_hand": "quarterstaff", "chest_garment": "robe", "head_armor": "hood"},
            "skills": ["attack_ranged", "summon_minion", "buff_defense"],
        },
        "necromancer": {
            "id": "necromancer",
            "role": "boss",
            "cost": 600,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A human (or once human) in dark robes, surrounded by an aura of death.",
            "extra_tags": ["human", "necromancer", "summoner"],
            "base_stats": {
                "strength": 8,
                "agility": 10,
                "endurance": 14,
                "intellect": 22,
                "memory": 20,
                "mental": 25,
                "perception": 16,
                "projection": 15,
                "prediction": 10,  # Итого: 140
            },
            "fixed_loadout": {
                "main_hand": "dagger",
                "off_hand": "grimoire",
                "chest_garment": "robe",
                "amulet": "amulet",
            },
            "skills": ["summon_minion", "debuff_weaken", "debuff_stun"],
        },
        "lich_lord": {
            "id": "lich_lord",
            "role": "boss",
            "cost": 600,
            "min_tier": 5,
            "max_tier": 8,
            "narrative_hint": "An ancient lich floating above the ground. Radiates absolute power and cold.",
            "extra_tags": ["lich", "lord", "ancient"],
            "base_stats": {
                "strength": 10,
                "agility": 12,
                "endurance": 20,
                "intellect": 30,
                "memory": 30,
                "mental": 40,
                "perception": 20,
                "projection": 20,
                "prediction": 15,  # Итого: 197
            },
            "fixed_loadout": {
                "main_hand": "quarterstaff",
                "chest_garment": "robe",
                "head_armor": "hood",
                "amulet": "amulet",
                "ring_1": "ring",
                "ring_2": "ring",
            },
            "skills": ["attack_execute", "buff_heal", "attack_aoe", "summon_minion"],
        },
    },
}
