"""
СЕМЕЙСТВО: ВОЛКИ (Охота и координация)
======================================
Логика: позиционирование -> фланг -> добивание
"""

from ..monster_structs import MonsterFamily

WOLVES_FAMILY: MonsterFamily = {
    "id": "wolf_pack",
    "archetype": "beast",
    "organization_type": "pack",  # TSP Base: 50
    "default_tags": ["beast", "wolf", "predator", "pack"],
    "family_modifiers": [
        {"target": "accuracy", "value": -0.10, "per_tier": 0.0},
        {"target": "physical_resistance", "value": 0.03, "per_tier": 0.01},
        {"target": "physical_damage_bonus", "value": 0.04, "per_tier": 0.015},
        {"target": "dodge_chance", "value": 0.04, "per_tier": 0.01},
        {"target": "bleed_damage_bonus", "value": 2.0, "per_tier": 1.0},
    ],
    "loot_profile": {
        "salvage_type": "beast_parts",
        "loot_mode": "salvage",
        "allowed_loadout_slots": "natural_only",
        "equipment_drop_policy": "none",
        "drops_as_equipment": False,
        "materials": ["fang", "hide_scrap", "bone", "pelt"],
    },
    "hierarchy": {
        "minions": ["cub", "runner", "mangy_biter"],
        "veterans": ["stalker", "flanker", "snapper"],
        "elites": ["pack_leader", "dire_wolf", "old_fang"],
        "boss": ["alpha_prime", "winter_maw", "blood_howl"],
    },
    "variants": {
        # --- 1. Молодняк (Minions) [TSP ~50] ---
        "cub": {
            "id": "cub",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "A young wolf, inexperienced but eager. Soft fur and sharp little teeth.",
            "extra_tags": ["young", "weak"],
            "base_stats": {
                "strength": 8,
                "agility": 12,
                "endurance": 8,
                "intellect": 2,
                "memory": 2,
                "mental": 4,
                "perception": 8,
                "projection": 1,
                "prediction": 3,  # Итого: 48
            },
            "fixed_loadout": {"main_hand": "wolf_young_fangs", "chest_armor": "wolf_hide"},
            "skills": ["skill_fencing", "skill_light_armor"],
        },
        "runner": {
            "id": "runner",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "A lean wolf built for speed. Scouts ahead of the pack.",
            "extra_tags": ["fast", "scout"],
            "base_stats": {
                "strength": 10,
                "agility": 16,
                "endurance": 10,
                "intellect": 3,
                "memory": 2,
                "mental": 4,
                "perception": 10,
                "projection": 1,
                "prediction": 3,  # Итого: 59
            },
            "fixed_loadout": {"main_hand": "wolf_young_fangs", "chest_armor": "wolf_hide"},
            "skills": ["skill_fencing", "skill_light_armor"],
        },
        "mangy_biter": {
            "id": "mangy_biter",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "A scarred, underfed wolf that darts in low and snaps at exposed limbs.",
            "extra_tags": ["mangy", "ambusher", "bleeder"],
            "base_stats": {
                "strength": 9,
                "agility": 14,
                "endurance": 9,
                "intellect": 2,
                "memory": 2,
                "mental": 4,
                "perception": 9,
                "projection": 1,
                "prediction": 4,
            },
            "fixed_loadout": {"main_hand": "wolf_young_fangs", "chest_armor": "wolf_hide"},
            "skills": ["skill_fencing", "skill_light_armor"],
        },
        # --- 2. Охотники (Veterans) [TSP ~75] ---
        "stalker": {
            "id": "stalker",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A wolf that moves low to the ground, blending with the terrain.",
            "extra_tags": ["stealth", "hunter"],
            "base_stats": {
                "strength": 14,
                "agility": 14,
                "endurance": 14,
                "intellect": 4,
                "memory": 4,
                "mental": 6,
                "perception": 14,
                "projection": 1,
                "prediction": 4,  # Итого: 75
            },
            "fixed_loadout": {"main_hand": "wolf_bite_claws", "chest_armor": "wolf_hide"},
            "skills": ["skill_fencing", "skill_light_armor"],
        },
        "flanker": {
            "id": "flanker",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A clever wolf that always tries to get behind its prey.",
            "extra_tags": ["tactical", "fast"],
            "base_stats": {
                "strength": 12,
                "agility": 18,
                "endurance": 12,
                "intellect": 5,
                "memory": 4,
                "mental": 6,
                "perception": 12,
                "projection": 2,
                "prediction": 4,  # Итого: 75
            },
            "fixed_loadout": {"main_hand": "wolf_bite_claws", "chest_armor": "wolf_medium_hide"},
            "skills": ["skill_fencing", "skill_medium_armor"],
        },
        "snapper": {
            "id": "snapper",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A wolf with powerful jaws, focused on finishing off wounded prey.",
            "extra_tags": ["executioner", "strong_jaw"],
            "base_stats": {
                "strength": 18,
                "agility": 10,
                "endurance": 16,
                "intellect": 3,
                "memory": 3,
                "mental": 8,
                "perception": 10,
                "projection": 1,
                "prediction": 4,  # Итого: 73
            },
            "fixed_loadout": {"main_hand": "wolf_bite_claws", "chest_armor": "wolf_hide"},
            "skills": ["skill_fencing", "skill_light_armor"],
        },
        # --- 3. Альфы (Elites) [TSP ~125] ---
        "pack_leader": {
            "id": "pack_leader",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A large wolf with a confident stance. Howls to coordinate the pack.",
            "extra_tags": ["leader", "support", "alpha"],
            "base_stats": {
                "strength": 20,
                "agility": 16,
                "endurance": 20,
                "intellect": 8,
                "memory": 6,
                "mental": 12,
                "perception": 14,
                "projection": 10,
                "prediction": 5,  # Итого: 111
            },
            "fixed_loadout": {"main_hand": "wolf_elite_fangs", "chest_armor": "wolf_medium_hide"},
            "skills": ["skill_fencing", "skill_medium_armor", "skill_tactics", "skill_anatomy"],
        },
        "dire_wolf": {
            "id": "dire_wolf",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A massive, prehistoric wolf. Its fur is thick and its eyes burn with hunger.",
            "extra_tags": ["dire", "heavy", "brute"],
            "base_stats": {
                "strength": 30,
                "agility": 12,
                "endurance": 30,
                "intellect": 4,
                "memory": 4,
                "mental": 15,
                "perception": 12,
                "projection": 4,
                "prediction": 5,  # Итого: 116
            },
            "fixed_loadout": {"main_hand": "wolf_elite_fangs", "chest_armor": "wolf_heavy_hide"},
            "skills": ["skill_fencing", "skill_heavy_armor", "skill_anatomy"],
        },
        "old_fang": {
            "id": "old_fang",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "An old, scarred wolf. Missing an ear, but moves with deadly efficiency.",
            "extra_tags": ["veteran", "cunning"],
            "base_stats": {
                "strength": 18,
                "agility": 14,
                "endurance": 18,
                "intellect": 10,
                "memory": 10,
                "mental": 15,
                "perception": 18,
                "projection": 6,
                "prediction": 10,  # Итого: 119
            },
            "fixed_loadout": {"main_hand": "wolf_elite_fangs", "chest_armor": "wolf_medium_hide"},
            "skills": ["skill_fencing", "skill_medium_armor", "skill_tactics", "skill_anatomy"],
        },
        # --- 4. Боссы (Bosses) [TSP ~200] ---
        "alpha_prime": {
            "id": "alpha_prime",
            "role": "boss",
            "cost": 600,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "The apex predator. A wolf of perfect form and terrifying power.",
            "extra_tags": ["alpha", "prime", "legendary"],
            "base_stats": {
                "strength": 35,
                "agility": 30,
                "endurance": 40,
                "intellect": 12,
                "memory": 10,
                "mental": 25,
                "perception": 20,
                "projection": 15,
                "prediction": 10,  # Итого: 197
            },
            "fixed_loadout": {"main_hand": "wolf_alpha_fangs", "chest_armor": "wolf_heavy_hide"},
            "skills": ["skill_fencing", "skill_heavy_armor", "skill_tactics", "skill_anatomy"],
        },
        "winter_maw": {
            "id": "winter_maw",
            "role": "boss",
            "cost": 600,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A giant white wolf, exhaling frost. Its bite freezes the blood.",
            "extra_tags": ["ice", "elemental", "winter"],
            "base_stats": {
                "strength": 40,
                "agility": 20,
                "endurance": 50,
                "intellect": 10,
                "memory": 14,
                "mental": 30,
                "perception": 16,
                "projection": 10,
                "prediction": 8,  # Итого: 198
            },
            "fixed_loadout": {"main_hand": "wolf_alpha_fangs", "chest_armor": "wolf_heavy_hide"},
            "skills": ["skill_fencing", "skill_heavy_armor", "skill_tactics", "skill_anatomy"],
        },
        "blood_howl": {
            "id": "blood_howl",
            "role": "boss",
            "cost": 600,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A wolf with fur stained red. It feeds on the fear of its prey.",
            "extra_tags": ["blood", "vampiric", "terror"],
            "base_stats": {
                "strength": 30,
                "agility": 35,
                "endurance": 35,
                "intellect": 14,
                "memory": 12,
                "mental": 35,
                "perception": 20,
                "projection": 12,
                "prediction": 12,  # Итого: 205
            },
            "fixed_loadout": {"main_hand": "wolf_alpha_fangs", "chest_armor": "wolf_heavy_hide"},
            "skills": ["skill_fencing", "skill_heavy_armor", "skill_tactics", "skill_anatomy"],
        },
    },
}
