"""
СЕМЕЙСТВО: ВОЛКИ (Охота и координация)
======================================
Логика: позиционирование -> фланг -> добивание
"""

from ..monster_structs import MonsterFamily
from ..stat_ladders import build_role_ladder_stats as _build_role_ladder_stats


def build_role_ladder_stats(role, priority):
    return _build_role_ladder_stats(role, priority, organization_type="pack")


WOLVES_FAMILY: MonsterFamily = {
    "id": "wolf_pack",
    "resource_version": 1.4,
    "archetype": "beast",
    "organization_type": "pack",  # TSP Base: 50
    "default_tags": ["beast", "wolf", "predator", "pack"],
    "family_modifiers": [
        {"target": "physical_resistance", "value": 0.03, "per_tier": 0.01},
        {"target": "physical_damage_bonus", "value": 0.04, "per_tier": 0.015},
        {"target": "dodge_chance", "value": 0.04, "per_tier": 0.01},
        {"target": "bleed_damage_bonus", "value": 2.0, "per_tier": 1.0},
    ],
    "loot_profile": {
        "salvage_type": "beast_parts",
        "loot_mode": "salvage",
        "allowed_loadout_slots": "natural_only",
        "equipment_drop_policy": "none",
        "drops_as_equipment": False,
        "materials": ["fang", "hide_scrap", "bone", "pelt"],
    },
    "hierarchy": {
        "minions": ["cub", "runner", "mangy_biter"],
        "veterans": ["stalker", "flanker", "snapper"],
        "elites": ["pack_leader", "dire_wolf", "old_fang"],
        "boss": ["alpha_prime", "winter_maw", "blood_howl"],
    },
    "variants": {
        # --- 1. Молодняк (Minions) [TSP ~50] ---
        "cub": {
            "id": "cub",
            "role": "minion",
            "spawn_weight": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "A young wolf, inexperienced but eager. Soft fur and sharp little teeth.",
            "extra_tags": ["young", "weak"],
            "base_stats": build_role_ladder_stats(
                "minion",
                (
                    "agility",
                    "strength",
                    "endurance",
                    "perception",
                    "mental",
                    "prediction",
                    "intellect",
                    "memory",
                    "projection",
                ),
            ),
            "fixed_loadout": {
                "main_hand": "wolf_young_fangs",
                "off_hand": "wolf_young_claws",
                "chest_armor": "wolf_hide",
                "amulet": "wolf_pack_mark",
            },
            "skills": ["skill_fencing", "skill_dual_wield", "skill_light_armor"],
        },
        "runner": {
            "id": "runner",
            "role": "minion",
            "spawn_weight": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "A lean wolf built for speed. Scouts ahead of the pack.",
            "extra_tags": ["fast", "scout"],
            "base_stats": build_role_ladder_stats(
                "minion",
                (
                    "agility",
                    "strength",
                    "endurance",
                    "perception",
                    "mental",
                    "intellect",
                    "prediction",
                    "memory",
                    "projection",
                ),
            ),
            "fixed_loadout": {
                "main_hand": "wolf_young_fangs",
                "off_hand": "wolf_young_claws",
                "chest_armor": "wolf_hide",
                "amulet": "wolf_pack_mark",
            },
            "skills": ["skill_fencing", "skill_dual_wield", "skill_light_armor"],
        },
        "mangy_biter": {
            "id": "mangy_biter",
            "role": "minion",
            "spawn_weight": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "A scarred, underfed wolf that darts in low and snaps at exposed limbs.",
            "extra_tags": ["mangy", "ambusher", "bleeder"],
            "base_stats": build_role_ladder_stats(
                "minion",
                (
                    "agility",
                    "strength",
                    "endurance",
                    "perception",
                    "mental",
                    "prediction",
                    "intellect",
                    "memory",
                    "projection",
                ),
            ),
            "fixed_loadout": {
                "main_hand": "wolf_young_fangs",
                "off_hand": "wolf_locking_fangs",
                "chest_armor": "wolf_hide",
                "amulet": "wolf_pack_mark",
            },
            "skills": ["skill_fencing", "skill_dual_wield", "skill_light_armor"],
        },
        # --- 2. Охотники (Veterans) [TSP ~75] ---
        "stalker": {
            "id": "stalker",
            "role": "veteran",
            "spawn_weight": 50,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A wolf that moves low to the ground, blending with the terrain.",
            "extra_tags": ["stealth", "hunter"],
            "base_stats": build_role_ladder_stats(
                "veteran",
                (
                    "strength",
                    "agility",
                    "endurance",
                    "perception",
                    "mental",
                    "intellect",
                    "memory",
                    "prediction",
                    "projection",
                ),
            ),
            "fixed_loadout": {
                "main_hand": "wolf_bite_claws",
                "off_hand": "wolf_raking_claws",
                "chest_armor": "wolf_hide",
                "amulet": "wolf_pack_mark",
            },
            "skills": ["skill_fencing", "skill_dual_wield", "skill_light_armor"],
        },
        "flanker": {
            "id": "flanker",
            "role": "veteran",
            "spawn_weight": 50,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A clever wolf that always tries to get behind its prey.",
            "extra_tags": ["tactical", "fast"],
            "base_stats": build_role_ladder_stats(
                "veteran",
                (
                    "agility",
                    "strength",
                    "endurance",
                    "perception",
                    "mental",
                    "intellect",
                    "memory",
                    "prediction",
                    "projection",
                ),
            ),
            "fixed_loadout": {
                "main_hand": "wolf_bite_claws",
                "off_hand": "wolf_raking_claws",
                "chest_armor": "wolf_medium_hide",
                "amulet": "wolf_pack_mark",
            },
            "skills": ["skill_fencing", "skill_dual_wield", "skill_medium_armor"],
        },
        "snapper": {
            "id": "snapper",
            "role": "veteran",
            "spawn_weight": 50,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A wolf with powerful jaws, focused on finishing off wounded prey.",
            "extra_tags": ["executioner", "strong_jaw"],
            "base_stats": build_role_ladder_stats(
                "veteran",
                (
                    "strength",
                    "endurance",
                    "agility",
                    "perception",
                    "mental",
                    "prediction",
                    "intellect",
                    "memory",
                    "projection",
                ),
            ),
            "fixed_loadout": {
                "main_hand": "wolf_bite_claws",
                "off_hand": "wolf_locking_fangs",
                "chest_armor": "wolf_hide",
                "amulet": "wolf_pack_mark",
            },
            "skills": ["skill_fencing", "skill_dual_wield", "skill_light_armor"],
        },
        # --- 3. Альфы (Elites) [TSP ~125] ---
        "pack_leader": {
            "id": "pack_leader",
            "role": "elite",
            "spawn_weight": 150,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A large wolf with a confident stance. Howls to coordinate the pack.",
            "extra_tags": ["leader", "support", "alpha"],
            "base_stats": build_role_ladder_stats(
                "elite",
                (
                    "strength",
                    "endurance",
                    "agility",
                    "perception",
                    "mental",
                    "projection",
                    "intellect",
                    "memory",
                    "prediction",
                ),
            ),
            "fixed_loadout": {
                "main_hand": "wolf_elite_fangs",
                "off_hand": "wolf_braced_mane",
                "chest_armor": "wolf_medium_hide",
                "amulet": "wolf_pack_mark",
            },
            "skills": ["skill_fencing", "skill_shield_mastery", "skill_medium_armor", "skill_tactics", "skill_anatomy"],
        },
        "dire_wolf": {
            "id": "dire_wolf",
            "role": "elite",
            "spawn_weight": 150,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A massive, prehistoric wolf. Its fur is thick and its eyes burn with hunger.",
            "extra_tags": ["dire", "heavy", "brute"],
            "base_stats": build_role_ladder_stats(
                "elite",
                (
                    "strength",
                    "endurance",
                    "mental",
                    "agility",
                    "perception",
                    "prediction",
                    "intellect",
                    "memory",
                    "projection",
                ),
            ),
            "fixed_loadout": {
                "main_hand": "wolf_elite_fangs",
                "off_hand": "wolf_bone_shoulders",
                "chest_armor": "wolf_heavy_hide",
                "amulet": "wolf_pack_mark",
            },
            "skills": ["skill_fencing", "skill_shield_mastery", "skill_heavy_armor", "skill_anatomy"],
        },
        "old_fang": {
            "id": "old_fang",
            "role": "elite",
            "spawn_weight": 150,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "An old, scarred wolf. Missing an ear, but moves with deadly efficiency.",
            "extra_tags": ["veteran", "cunning"],
            "base_stats": build_role_ladder_stats(
                "elite",
                (
                    "strength",
                    "endurance",
                    "perception",
                    "mental",
                    "agility",
                    "intellect",
                    "memory",
                    "prediction",
                    "projection",
                ),
            ),
            "fixed_loadout": {
                "main_hand": "wolf_elite_fangs",
                "off_hand": "wolf_locking_fangs",
                "chest_armor": "wolf_medium_hide",
                "amulet": "wolf_pack_mark",
            },
            "skills": ["skill_fencing", "skill_dual_wield", "skill_medium_armor", "skill_tactics", "skill_anatomy"],
        },
        # --- 4. Боссы (Bosses) [TSP ~200] ---
        "alpha_prime": {
            "id": "alpha_prime",
            "role": "boss",
            "spawn_weight": 600,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "The apex predator. A wolf of perfect form and terrifying power.",
            "extra_tags": ["alpha", "prime", "legendary"],
            "base_stats": build_role_ladder_stats(
                "boss",
                (
                    "endurance",
                    "strength",
                    "agility",
                    "mental",
                    "perception",
                    "projection",
                    "intellect",
                    "memory",
                    "prediction",
                ),
            ),
            "fixed_loadout": {
                "main_hand": "wolf_alpha_fangs",
                "off_hand": "wolf_bone_shoulders",
                "chest_armor": "wolf_heavy_hide",
                "amulet": "wolf_pack_mark",
            },
            "skills": ["skill_fencing", "skill_shield_mastery", "skill_heavy_armor", "skill_tactics", "skill_anatomy"],
        },
        "winter_maw": {
            "id": "winter_maw",
            "role": "boss",
            "spawn_weight": 600,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A giant white wolf, exhaling frost. Its bite freezes the blood.",
            "extra_tags": ["ice", "elemental", "winter"],
            "base_stats": build_role_ladder_stats(
                "boss",
                (
                    "endurance",
                    "strength",
                    "mental",
                    "agility",
                    "perception",
                    "memory",
                    "intellect",
                    "projection",
                    "prediction",
                ),
            ),
            "fixed_loadout": {
                "main_hand": "wolf_alpha_fangs",
                "off_hand": "wolf_braced_mane",
                "chest_armor": "wolf_heavy_hide",
                "amulet": "wolf_pack_mark",
            },
            "skills": ["skill_fencing", "skill_shield_mastery", "skill_heavy_armor", "skill_tactics", "skill_anatomy"],
        },
        "blood_howl": {
            "id": "blood_howl",
            "role": "boss",
            "spawn_weight": 600,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A wolf with fur stained red. It feeds on the fear of its prey.",
            "extra_tags": ["blood", "vampiric", "terror"],
            "base_stats": build_role_ladder_stats(
                "boss",
                (
                    "agility",
                    "endurance",
                    "mental",
                    "strength",
                    "perception",
                    "intellect",
                    "memory",
                    "projection",
                    "prediction",
                ),
            ),
            "fixed_loadout": {
                "main_hand": "wolf_alpha_fangs",
                "off_hand": "wolf_raking_claws",
                "chest_armor": "wolf_heavy_hide",
                "amulet": "wolf_pack_mark",
            },
            "skills": ["skill_fencing", "skill_dual_wield", "skill_heavy_armor", "skill_tactics", "skill_anatomy"],
        },
    },
}
