from __future__ import annotations

from src.backend.features.character.dto.modifiers import CombatModifiersDTO

GEAR_SCORE_BASE = 0.0
GEAR_SCORE_MINIMUM = 1

# Starter balancing weights for combat-effective modifiers.
# Percent values are stored as 0..1, so they intentionally use larger weights.
GEAR_SCORE_WEIGHTS: dict[str, float] = {
    # Resources and combat regen used by the combat pipeline.
    "hp": 0.04,
    "hp_regen": 2.0,
    "en": 0.02,
    "en_regen": 2.0,
    "stamina": 0.015,
    "stamina_regen": 1.0,
    # Hand and item attack stats read by resolver.support.offensive_lookup.get_offensive_val.
    "main_hand_damage_base": 1.2,
    "main_hand_damage_spread": -80.0,
    "main_hand_armor_penetration_pct": 70.0,
    "main_hand_armor_ignore_chance": 90.0,
    "main_hand_accuracy": 55.0,
    "main_hand_accuracy_penalty": -55.0,
    "main_hand_crit_chance": 70.0,
    "main_hand_crit_cap": 20.0,
    "off_hand_damage_base": 0.8,
    "off_hand_damage_spread": -50.0,
    "off_hand_armor_penetration_pct": 45.0,
    "off_hand_armor_ignore_chance": 60.0,
    "off_hand_accuracy": 35.0,
    "off_hand_accuracy_penalty": -35.0,
    "off_hand_crit_chance": 45.0,
    "off_hand_crit_cap": 15.0,
    "item_damage_base": 0.4,
    "item_damage_spread": -20.0,
    "item_armor_penetration_pct": 20.0,
    "item_armor_ignore_chance": 30.0,
    "item_accuracy": 15.0,
    "item_accuracy_penalty": -15.0,
    "item_crit_chance": 20.0,
    "item_crit_cap": 10.0,
    # Physical and magical damage math currently used by resolver.
    # Weapon stat power is already assembled into hand damage bases before scoring.
    "physical_damage_bonus": 1.0,
    "accuracy": 55.0,
    "physical_suppression": 70.0,
    "armor_penetration_pct": 70.0,
    "armor_penetration_flat": 0.8,
    "armor_ignore_chance": 90.0,
    "crit_chance": 70.0,
    "magical_damage": 1.0,
    "magical_damage_spread": -80.0,
    "magical_accuracy": 55.0,
    "magical_penetration": 70.0,
    "magical_crit_chance": 70.0,
    "magical_crit_cap": 20.0,
    # Avoidance, mitigation, shield, and counter stages.
    "evasion": 80.0,
    "dodge_cap": 20.0,
    "anti_dodge_chance": 50.0,
    "parry": 80.0,
    "parry_cap": 20.0,
    "block": 80.0,
    "shield_block_cap": 20.0,
    "physical_resistance": 60.0,
    "magic_resist": 60.0,
    "resistance_cap": 20.0,
    # Physical armor and shield guard now feed a diminishing percent-armor curve,
    # so raw power should not score like direct flat damage prevention.
    "armor": 0.35,
    "magic_armor": 0.8,
    "shield_guard_power": 0.35,
    "shield_absorb_ratio": 50.0,
    "shield_reflect_ratio": 20.0,
    # Elemental resistances are read dynamically by damage flags.
    "fire_resistance": 35.0,
    "water_resistance": 35.0,
    "air_resistance": 35.0,
    "earth_resistance": 35.0,
    "light_resistance": 35.0,
    "arcane_resistance": 35.0,
    "nature_resistance": 35.0,
    # Special mechanics directly read by resolver/mechanics.
    "counter_attack_chance": 75.0,
    "counter_attack_cap": 20.0,
    "damage_mult": 80.0,
    "hand_size": 3.0,
}

GEAR_SCORE_GROUPS: dict[str, tuple[str, ...]] = {
    "resources": (
        "hp",
        "hp_regen",
        "en",
        "en_regen",
        "stamina",
        "stamina_regen",
    ),
    "offense": (
        "main_hand_damage_base",
        "main_hand_damage_spread",
        "main_hand_armor_penetration_pct",
        "main_hand_armor_ignore_chance",
        "main_hand_accuracy",
        "main_hand_accuracy_penalty",
        "main_hand_crit_chance",
        "main_hand_crit_cap",
        "off_hand_damage_base",
        "off_hand_damage_spread",
        "off_hand_armor_penetration_pct",
        "off_hand_armor_ignore_chance",
        "off_hand_accuracy",
        "off_hand_accuracy_penalty",
        "off_hand_crit_chance",
        "off_hand_crit_cap",
        "item_damage_base",
        "item_damage_spread",
        "item_armor_penetration_pct",
        "item_armor_ignore_chance",
        "item_accuracy",
        "item_accuracy_penalty",
        "item_crit_chance",
        "item_crit_cap",
        "physical_damage_bonus",
        "accuracy",
        "physical_suppression",
        "armor_penetration_pct",
        "armor_penetration_flat",
        "armor_ignore_chance",
        "crit_chance",
        "magical_damage",
        "magical_damage_spread",
        "magical_accuracy",
        "magical_penetration",
        "magical_crit_chance",
        "magical_crit_cap",
        "anti_dodge_chance",
    ),
    "defense": (
        "evasion",
        "dodge_cap",
        "parry",
        "parry_cap",
        "block",
        "shield_block_cap",
        "physical_resistance",
        "magic_resist",
        "resistance_cap",
        "armor",
        "magic_armor",
        "shield_guard_power",
        "shield_absorb_ratio",
        "shield_reflect_ratio",
        "fire_resistance",
        "water_resistance",
        "air_resistance",
        "earth_resistance",
        "light_resistance",
        "arcane_resistance",
        "nature_resistance",
        "counter_attack_chance",
        "counter_attack_cap",
    ),
    "utility": (
        "damage_mult",
        "hand_size",
    ),
}

GEAR_SCORE_BASELINES: dict[str, float] = {
    "main_hand_damage_spread": 0.1,
    "main_hand_crit_cap": 0.75,
    "off_hand_damage_spread": 0.1,
    "off_hand_crit_cap": 0.75,
    "item_damage_spread": 0.1,
    "item_crit_cap": 0.75,
    "magical_damage_spread": 0.1,
    "magical_crit_cap": 0.75,
    "dodge_cap": 0.75,
    "parry_cap": 0.50,
    "shield_block_cap": 0.75,
    "shield_absorb_ratio": 0.40,
    "shield_reflect_ratio": 1.00,
    "resistance_cap": 0.85,
    "counter_attack_cap": 0.50,
    "vampiric_trigger_cap": 1.0,
    "damage_mult": 1.0,
    "pet_efficiency_mult": 1.0,
    "hand_size": 3.0,
    "spell_land_chance": 1.0,
    "stamina_regen": 1.0,
}

GEAR_SCORE_CAPS: dict[str, float] = {
    "hp": 2000.0,
    "en": 1000.0,
    "stamina": 1500.0,
    "armor": 500.0,
    "magic_armor": 500.0,
    "magical_damage": 500.0,
    "main_hand_damage_base": 500.0,
    "off_hand_damage_base": 500.0,
}

GEAR_SCORE_CONFIG = {
    "base": GEAR_SCORE_BASE,
    "minimum": GEAR_SCORE_MINIMUM,
    "weights": GEAR_SCORE_WEIGHTS,
    "baselines": GEAR_SCORE_BASELINES,
    "caps": GEAR_SCORE_CAPS,
}

COMBAT_MODIFIER_KEYS = frozenset(CombatModifiersDTO.model_fields)

__all__ = [
    "COMBAT_MODIFIER_KEYS",
    "GEAR_SCORE_BASE",
    "GEAR_SCORE_BASELINES",
    "GEAR_SCORE_CAPS",
    "GEAR_SCORE_CONFIG",
    "GEAR_SCORE_GROUPS",
    "GEAR_SCORE_MINIMUM",
    "GEAR_SCORE_WEIGHTS",
]
