HP_PER_BODY_ATTRIBUTE = 4.0 / 3.0
HP_REGEN_PER_BODY_ATTRIBUTE = 0.1 / 3.0
ENERGY_PER_CORE_ATTRIBUTE = 2.0 / 3.0
ENERGY_REGEN_PER_CORE_ATTRIBUTE = 0.5 / 3.0
CONCENTRATION_PER_SENSOR_ATTRIBUTE = 5.0 / 3.0
CONCENTRATION_REGEN_BASE = 1.0
CONCENTRATION_REGEN_PER_SENSOR_ATTRIBUTE = 0.1
REGEN_TICK_SECONDS = 2.0

__all__ = [
    "CONCENTRATION_PER_SENSOR_ATTRIBUTE",
    "CONCENTRATION_REGEN_BASE",
    "CONCENTRATION_REGEN_PER_SENSOR_ATTRIBUTE",
    "ENERGY_PER_CORE_ATTRIBUTE",
    "ENERGY_REGEN_PER_CORE_ATTRIBUTE",
    "HP_PER_BODY_ATTRIBUTE",
    "HP_REGEN_PER_BODY_ATTRIBUTE",
    "REGEN_TICK_SECONDS",
]
