HP_PER_ENDURANCE_ATTRIBUTE = 3.0
HP_REGEN_PER_ENDURANCE_ATTRIBUTE = 0.1
ENERGY_PER_CORE_ATTRIBUTE = 2.0
ENERGY_REGEN_PER_CORE_ATTRIBUTE = 0.25
CONCENTRATION_PER_SENSOR_ATTRIBUTE = 2.7
CONCENTRATION_REGEN_BASE = 1.0
CONCENTRATION_REGEN_PER_SENSOR_ATTRIBUTE = 0.2
REGEN_TICK_SECONDS = 2.0

__all__ = [
    "CONCENTRATION_PER_SENSOR_ATTRIBUTE",
    "CONCENTRATION_REGEN_BASE",
    "CONCENTRATION_REGEN_PER_SENSOR_ATTRIBUTE",
    "ENERGY_PER_CORE_ATTRIBUTE",
    "ENERGY_REGEN_PER_CORE_ATTRIBUTE",
    "HP_PER_ENDURANCE_ATTRIBUTE",
    "HP_REGEN_PER_ENDURANCE_ATTRIBUTE",
    "REGEN_TICK_SECONDS",
]
