"""
СЕМЕЙСТВО: ВОЛКИ (Охота и координация)
======================================
Логика: позиционирование -> фланг -> добивание
"""

from ..monster_structs import MonsterFamily

WOLVES_FAMILY: MonsterFamily = {
    "id": "wolf_pack",
    "archetype": "beast",
    "organization_type": "pack",  # TSP Base: 50
    "default_tags": ["beast", "wolf", "predator", "pack"],
    "hierarchy": {
        "minions": ["cub", "runner"],
        "veterans": ["stalker", "flanker", "snapper"],
        "elites": ["pack_leader", "dire_wolf", "old_fang"],
        "boss": ["alpha_prime", "winter_maw", "blood_howl"],
    },
    "variants": {
        # --- 1. Молодняк (Minions) [TSP ~50] ---
        "cub": {
            "id": "cub",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "A young wolf, inexperienced but eager. Soft fur and sharp little teeth.",
            "extra_tags": ["young", "weak"],
            "base_stats": {
                "strength": 8,
                "agility": 12,
                "endurance": 8,
                "intelligence": 2,
                "wisdom": 2,
                "men": 4,
                "perception": 8,
                "charisma": 1,
                "luck": 3,  # Итого: 48
            },
            "fixed_loadout": {},
            "skills": ["attack_basic", "debuff_weaken"],
        },
        "runner": {
            "id": "runner",
            "role": "minion",
            "cost": 20,
            "min_tier": 0,
            "max_tier": 3,
            "narrative_hint": "A lean wolf built for speed. Scouts ahead of the pack.",
            "extra_tags": ["fast", "scout"],
            "base_stats": {
                "strength": 10,
                "agility": 16,
                "endurance": 10,
                "intelligence": 3,
                "wisdom": 2,
                "men": 4,
                "perception": 10,
                "charisma": 1,
                "luck": 3,  # Итого: 59
            },
            "fixed_loadout": {},
            "skills": ["debuff_weaken"],
        },
        # --- 2. Охотники (Veterans) [TSP ~75] ---
        "stalker": {
            "id": "stalker",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A wolf that moves low to the ground, blending with the terrain.",
            "extra_tags": ["stealth", "hunter"],
            "base_stats": {
                "strength": 14,
                "agility": 14,
                "endurance": 14,
                "intelligence": 4,
                "wisdom": 4,
                "men": 6,
                "perception": 14,
                "charisma": 1,
                "luck": 4,  # Итого: 75
            },
            "fixed_loadout": {},
            "skills": ["attack_heavy"],
        },
        "flanker": {
            "id": "flanker",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A clever wolf that always tries to get behind its prey.",
            "extra_tags": ["tactical", "fast"],
            "base_stats": {
                "strength": 12,
                "agility": 18,
                "endurance": 12,
                "intelligence": 5,
                "wisdom": 4,
                "men": 6,
                "perception": 12,
                "charisma": 2,
                "luck": 4,  # Итого: 75
            },
            "fixed_loadout": {},
            "skills": ["attack_fast", "debuff_weaken"],
        },
        "snapper": {
            "id": "snapper",
            "role": "veteran",
            "cost": 50,
            "min_tier": 1,
            "max_tier": 4,
            "narrative_hint": "A wolf with powerful jaws, focused on finishing off wounded prey.",
            "extra_tags": ["executioner", "strong_jaw"],
            "base_stats": {
                "strength": 18,
                "agility": 10,
                "endurance": 16,
                "intelligence": 3,
                "wisdom": 3,
                "men": 8,
                "perception": 10,
                "charisma": 1,
                "luck": 4,  # Итого: 73
            },
            "fixed_loadout": {},
            "skills": ["attack_execute", "debuff_stun"],
        },
        # --- 3. Альфы (Elites) [TSP ~125] ---
        "pack_leader": {
            "id": "pack_leader",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A large wolf with a confident stance. Howls to coordinate the pack.",
            "extra_tags": ["leader", "support", "alpha"],
            "base_stats": {
                "strength": 20,
                "agility": 16,
                "endurance": 20,
                "intelligence": 8,
                "wisdom": 6,
                "men": 12,
                "perception": 14,
                "charisma": 10,
                "luck": 5,  # Итого: 111
            },
            "fixed_loadout": {},
            "skills": ["buff_rage", "attack_fast"],
        },
        "dire_wolf": {
            "id": "dire_wolf",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "A massive, prehistoric wolf. Its fur is thick and its eyes burn with hunger.",
            "extra_tags": ["dire", "heavy", "brute"],
            "base_stats": {
                "strength": 30,
                "agility": 12,
                "endurance": 30,
                "intelligence": 4,
                "wisdom": 4,
                "men": 15,
                "perception": 12,
                "charisma": 4,
                "luck": 5,  # Итого: 116
            },
            "fixed_loadout": {},
            "skills": ["debuff_bleed", "debuff_stun"],
        },
        "old_fang": {
            "id": "old_fang",
            "role": "elite",
            "cost": 150,
            "min_tier": 2,
            "max_tier": 5,
            "narrative_hint": "An old, scarred wolf. Missing an ear, but moves with deadly efficiency.",
            "extra_tags": ["veteran", "cunning"],
            "base_stats": {
                "strength": 18,
                "agility": 14,
                "endurance": 18,
                "intelligence": 10,
                "wisdom": 10,
                "men": 15,
                "perception": 18,
                "charisma": 6,
                "luck": 10,  # Итого: 119
            },
            "fixed_loadout": {},
            "skills": ["buff_evasion", "attack_execute", "buff_rage"],
        },
        # --- 4. Боссы (Bosses) [TSP ~200] ---
        "alpha_prime": {
            "id": "alpha_prime",
            "role": "boss",
            "cost": 600,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "The apex predator. A wolf of perfect form and terrifying power.",
            "extra_tags": ["alpha", "prime", "legendary"],
            "base_stats": {
                "strength": 35,
                "agility": 30,
                "endurance": 40,
                "intelligence": 12,
                "wisdom": 10,
                "men": 25,
                "perception": 20,
                "charisma": 15,
                "luck": 10,  # Итого: 197
            },
            "fixed_loadout": {},
            "skills": ["buff_rage", "summon_minion", "attack_fast", "debuff_stun"],
        },
        "winter_maw": {
            "id": "winter_maw",
            "role": "boss",
            "cost": 600,
            "min_tier": 3,
            "max_tier": 6,
            "narrative_hint": "A giant white wolf, exhaling frost. Its bite freezes the blood.",
            "extra_tags": ["ice", "elemental", "winter"],
            "base_stats": {
                "strength": 40,
                "agility": 20,
                "endurance": 50,
                "intelligence": 10,
                "wisdom": 14,
                "men": 30,
                "perception": 16,
                "charisma": 10,
                "luck": 8,  # Итого: 198
            },
            "fixed_loadout": {},
            "skills": ["attack_aoe", "buff_defense", "attack_aoe", "attack_heavy"],
        },
        "blood_howl": {
            "id": "blood_howl",
            "role": "boss",
            "cost": 600,
            "min_tier": 4,
            "max_tier": 7,
            "narrative_hint": "A wolf with fur stained red. It feeds on the fear of its prey.",
            "extra_tags": ["blood", "vampiric", "terror"],
            "base_stats": {
                "strength": 30,
                "agility": 35,
                "endurance": 35,
                "intelligence": 14,
                "wisdom": 12,
                "men": 35,
                "perception": 20,
                "charisma": 12,
                "luck": 12,  # Итого: 205
            },
            "fixed_loadout": {},
            "skills": ["buff_rage", "debuff_weaken", "attack_lifesteal", "attack_execute"],
        },
    },
}
