from src.backend.features.items.resources.schemas import BaseItemDTO

MONSTER_NATURAL_EQUIPMENT_DB: dict[str, BaseItemDTO] = {
    "rat_bite_claws": BaseItemDTO(
        id="rat_bite_claws",
        name_ru="Крысиные клыки и когти",
        narrative_description="Зубы и когти мелкого зверя. В бою работают как естественное оружие, в добыче идут на лом и материалы.",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        base_power=2,
        damage_spread=0.2,
        base_durability=1,
        related_skill="skill_fencing",
        narrative_tags=["natural_weapon", "fangs", "claws", "rat"],
        implicit_bonuses={"physical_crit_chance": 0.03, "bleed_damage_bonus": 0.05},
        triggers=["crit.weapon_serrated_bleed_crit"],
    ),
    "wolf_fangs_claws": BaseItemDTO(
        id="wolf_fangs_claws",
        name_ru="Волчьи клыки и когти",
        narrative_description="Пасть и когти хищника. Опасны в бою, но после смерти становятся трофейными частями.",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        base_power=5,
        damage_spread=0.15,
        base_durability=1,
        related_skill="skill_fencing",
        narrative_tags=["natural_weapon", "fangs", "claws", "wolf"],
        implicit_bonuses={"physical_crit_chance": 0.08, "bleed_damage_bonus": 0.12},
        triggers=["crit.weapon_serrated_bleed_crit"],
    ),
    "light_hide": BaseItemDTO(
        id="light_hide",
        name_ru="Легкая звериная шкура",
        narrative_description="Подвижная естественная защита мелкого зверя.",
        slot="chest_armor",
        type="armor",
        defense_type="physical",
        armor_class="light",
        base_power=2,
        damage_spread=0.0,
        base_durability=1,
        related_skill="skill_light_armor",
        narrative_tags=["natural_armor", "hide", "light"],
        implicit_bonuses={"physical_resistance": 0.02, "dodge_chance": 0.03},
    ),
    "medium_hide": BaseItemDTO(
        id="medium_hide",
        name_ru="Плотная звериная шкура",
        narrative_description="Естественная защита крупного зверя.",
        slot="chest_armor",
        type="armor",
        defense_type="physical",
        armor_class="medium",
        base_power=4,
        damage_spread=0.0,
        base_durability=1,
        related_skill="skill_medium_armor",
        narrative_tags=["natural_armor", "hide", "medium"],
        implicit_bonuses={"physical_resistance": 0.05, "bleed_resistance": 0.05},
    ),
    "heavy_hide": BaseItemDTO(
        id="heavy_hide",
        name_ru="Толстая звериная шкура",
        narrative_description="Тяжелая естественная защита массивного зверя.",
        slot="chest_armor",
        type="armor",
        defense_type="physical",
        armor_class="heavy",
        base_power=7,
        damage_spread=0.0,
        base_durability=1,
        related_skill="skill_heavy_armor",
        narrative_tags=["natural_armor", "hide", "heavy"],
        implicit_bonuses={"physical_resistance": 0.08, "dodge_chance": -0.05, "bleed_resistance": 0.1},
    ),
    "carapace": BaseItemDTO(
        id="carapace",
        name_ru="Хитиновый панцирь",
        narrative_description="Жесткий панцирь насекомого или паука.",
        slot="chest_armor",
        type="armor",
        defense_type="physical",
        armor_class="heavy",
        base_power=8,
        damage_spread=0.0,
        base_durability=1,
        related_skill="skill_heavy_armor",
        narrative_tags=["natural_armor", "carapace", "chitin"],
        implicit_bonuses={"physical_resistance": 0.09, "anti_crit_chance": 0.08, "dodge_chance": -0.08},
    ),
    "anchor_stasis_crown_blade": BaseItemDTO(
        id="anchor_stasis_crown_blade",
        name_ru="Лезвие Северного Стазиса",
        narrative_description="Сгусток остановленного времени, которым проекция северного якоря рассекает движение.",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        base_power=95,
        damage_spread=0.08,
        base_durability=1,
        related_skill="skill_swords",
        narrative_tags=["anchor", "stasis", "frost", "time_stasis", "boss_weapon", "one_handed"],
        implicit_bonuses={
            "main_hand_accuracy": 0.25,
            "physical_crit_chance": 0.15,
            "main_hand_crit_cap": 0.8,
            "anti_dodge_chance": 0.25,
            "water_resistance": 0.35,
        },
        triggers=["accuracy.true_strike"],
    ),
    "anchor_entropy_cinder_maul": BaseItemDTO(
        id="anchor_entropy_cinder_maul",
        name_ru="Пепельный Молот Южной Энтропии",
        narrative_description="Тяжелая проекция распада: удар не режет, а заставляет материю уступать.",
        slot="two_hand",
        type="weapon",
        damage_type="physical",
        base_power=125,
        damage_spread=0.22,
        base_durability=1,
        related_skill="skill_macing",
        narrative_tags=["anchor", "entropy", "ash_storm", "thermal_shock", "boss_weapon", "two_handed"],
        implicit_bonuses={
            "main_hand_accuracy": 0.2,
            "physical_crit_chance": 0.1,
            "main_hand_crit_cap": 0.75,
            "armor_penetration_pct": 0.35,
            "fire_resistance": 0.4,
        },
        triggers=["crit.burn_on_crit"],
    ),
    "anchor_gravity_storm_lance": BaseItemDTO(
        id="anchor_gravity_storm_lance",
        name_ru="Штормовое Копье Западной Гравитации",
        narrative_description="Копье, которое бьет по линии падения, даже если падение направлено вверх.",
        slot="main_hand",
        type="weapon",
        damage_type="physical",
        base_power=105,
        damage_spread=0.12,
        base_durability=1,
        related_skill="skill_polearms",
        narrative_tags=["anchor", "gravity", "reverse_gravity", "lightning", "boss_weapon", "one_handed"],
        implicit_bonuses={
            "main_hand_accuracy": 0.3,
            "physical_crit_chance": 0.18,
            "main_hand_crit_cap": 0.85,
            "evasion": 0.18,
        },
        triggers=["accuracy.true_strike"],
    ),
    "anchor_evolution_bloom_talons": BaseItemDTO(
        id="anchor_evolution_bloom_talons",
        name_ru="Когти Восточной Эволюции",
        narrative_description="Живой клинок из хищной ткани, меняющий форму под слабость добычи.",
        slot="main_hand",
        extra_slots=["off_hand"],
        type="weapon",
        damage_type="physical",
        base_power=100,
        damage_spread=0.18,
        base_durability=1,
        related_skill="skill_fencing",
        narrative_tags=["anchor", "evolution", "living_jungle", "toxic_spores", "boss_weapon", "dual_wield"],
        implicit_bonuses={
            "main_hand_accuracy": 0.25,
            "physical_crit_chance": 0.2,
            "main_hand_crit_cap": 0.8,
            "bleed_damage_bonus": 0.25,
            "poison_resistance": 0.4,
        },
        triggers=["crit.weapon_serrated_bleed_crit"],
    ),
    "anchor_projection_aegis": BaseItemDTO(
        id="anchor_projection_aegis",
        name_ru="Оболочка Анкорной Проекции",
        narrative_description="Плотная оболочка высшей силы. Ее можно пробить, но обычный бой для этого не предназначен.",
        slot="chest_armor",
        type="armor",
        defense_type="physical",
        armor_class="heavy",
        base_power=65,
        damage_spread=0.0,
        base_durability=1,
        related_skill="skill_heavy_armor",
        narrative_tags=["anchor", "projection", "natural_armor", "raid_boss"],
        implicit_bonuses={
            "physical_resistance": 0.35,
            "magic_resistance": 0.25,
            "control_resistance": 0.35,
            "bleed_resistance": 0.2,
        },
    ),
}
