from src.backend.features.items.resources.schemas import BaseItemDTO

MONSTER_NATURAL_EQUIPMENT_DB: dict[str, BaseItemDTO] = {
    "rat_bite_claws": BaseItemDTO(
        id="rat_bite_claws",
        name_ru="Крысиные клыки и когти",
        narrative_description="Зубы и когти мелкого зверя. В бою работают как естественное оружие, в добыче идут на лом и материалы.",
        slot="main_hand",
        type="monster_natural_weapon",
        damage_type="physical",
        base_power=2,
        damage_spread=0.2,
        base_durability=1,
        related_skill="skill_unarmed",
        narrative_tags=["natural_weapon", "fangs", "claws", "rat"],
        implicit_bonuses={"physical_crit_chance": 0.03, "bleed_damage_bonus": 0.05},
        triggers=["crit.bleed_on_crit"],
    ),
    "wolf_fangs_claws": BaseItemDTO(
        id="wolf_fangs_claws",
        name_ru="Волчьи клыки и когти",
        narrative_description="Пасть и когти хищника. Опасны в бою, но после смерти становятся трофейными частями.",
        slot="main_hand",
        type="monster_natural_weapon",
        damage_type="physical",
        base_power=5,
        damage_spread=0.15,
        base_durability=1,
        related_skill="skill_unarmed",
        narrative_tags=["natural_weapon", "fangs", "claws", "wolf"],
        implicit_bonuses={"physical_crit_chance": 0.08, "bleed_damage_bonus": 0.12},
        triggers=["crit.bleed_on_crit"],
    ),
    "light_hide": BaseItemDTO(
        id="light_hide",
        name_ru="Легкая звериная шкура",
        narrative_description="Подвижная естественная защита мелкого зверя.",
        slot="chest_armor",
        type="monster_natural_armor",
        defense_type="physical",
        armor_class="light",
        base_power=2,
        damage_spread=0.0,
        base_durability=1,
        related_skill="skill_light_armor",
        narrative_tags=["natural_armor", "hide", "light"],
        implicit_bonuses={"physical_resistance": 0.02, "dodge_chance": 0.03},
    ),
    "medium_hide": BaseItemDTO(
        id="medium_hide",
        name_ru="Плотная звериная шкура",
        narrative_description="Естественная защита крупного зверя.",
        slot="chest_armor",
        type="monster_natural_armor",
        defense_type="physical",
        armor_class="medium",
        base_power=4,
        damage_spread=0.0,
        base_durability=1,
        related_skill="skill_medium_armor",
        narrative_tags=["natural_armor", "hide", "medium"],
        implicit_bonuses={"physical_resistance": 0.05, "bleed_resistance": 0.05},
    ),
    "heavy_hide": BaseItemDTO(
        id="heavy_hide",
        name_ru="Толстая звериная шкура",
        narrative_description="Тяжелая естественная защита массивного зверя.",
        slot="chest_armor",
        type="monster_natural_armor",
        defense_type="physical",
        armor_class="heavy",
        base_power=7,
        damage_spread=0.0,
        base_durability=1,
        related_skill="skill_heavy_armor",
        narrative_tags=["natural_armor", "hide", "heavy"],
        implicit_bonuses={"physical_resistance": 0.08, "dodge_chance": -0.05, "bleed_resistance": 0.1},
    ),
    "carapace": BaseItemDTO(
        id="carapace",
        name_ru="Хитиновый панцирь",
        narrative_description="Жесткий панцирь насекомого или паука.",
        slot="chest_armor",
        type="monster_natural_armor",
        defense_type="physical",
        armor_class="heavy",
        base_power=8,
        damage_spread=0.0,
        base_durability=1,
        related_skill="skill_heavy_armor",
        narrative_tags=["natural_armor", "carapace", "chitin"],
        implicit_bonuses={"physical_resistance": 0.09, "anti_crit_chance": 0.08, "dodge_chance": -0.08},
    ),
}

