from src.backend.infrastructure.game_config.base import BaseGameConfig, ConfigEntryMeta


class CombatConfig(BaseGameConfig):
    namespace = "combat"

    # Parry / Block
    PARRY_SKILL_MULT_PER_POINT: float = 4.0
    SHIELD_BLOCK_POWER_TO_CHANCE: float = 0.015
    SHIELD_BLOCK_EVASION_BONUS_RATE: float = 1.0
    SHIELD_BLOCK_BASE_CAP: float = 0.45
    SHIELD_BLOCK_MASTERY_CAP_BONUS: float = 0.30
    SHIELD_GUARD_ABSORB_RATE: float = 0.35
    SHIELD_GUARD_EVASION_PENALTY_RATE: float = 0.45
    SHIELD_GUARD_EVASION_PENALTY_FLOOR: float = 0.35
    SHIELD_COUNTER_CAP: float = 0.50
    SHIELD_COUNTER_DAMAGE_RATIO: float = 0.50
    SHIELD_OPENING_EVASION_RATE: float = 1.0
    SHIELD_OPENING_MIN_STRENGTH: float = 0.10
    SHIELD_OPENING_MAX_STRENGTH: float = 0.30
    ARMOR_LIGHT_COEF: float = 0.014
    ARMOR_MEDIUM_COEF: float = 0.018
    ARMOR_HEAVY_COEF: float = 0.027
    ARMOR_LIGHT_CAP: float = 0.90
    ARMOR_MEDIUM_CAP: float = 0.90
    ARMOR_HEAVY_CAP: float = 0.90

    # Accuracy
    BASE_ACCURACY_CHANCE: float = 0.60
    SKILL_ACCURACY_BONUS_AT_FULL: float = 0.40
    ACCURACY_CHANCE_CAP: float = 0.90
    ACCURACY_PENALTY_WEAPON_SKILL_REDUCTION_AT_FULL: float = 0.45
    ACCURACY_PENALTY_STYLE_SKILL_REDUCTION_AT_FULL: float = 0.45
    ACCURACY_PENALTY_MIN_MULTIPLIER: float = 0.10

    # Tokens
    TOKEN_BONUS_CHANCE: float = 0.30

    # Unarmed combat
    UNARMED_MIN_EFFICIENCY: float = 0.5
    UNARMED_MAX_EFFICIENCY: float = 3.0
    UNARMED_NOVICE_SPREAD: float = 0.5
    UNARMED_MASTER_SPREAD: float = 0.1

    # Chaos system
    CHAOS_FIRST_CHECK_DELAY_SECONDS: int = 300
    SESSION_TTL_SECONDS: int = 3600

    # Timeouts
    MIN_TIMEOUT: float = 20.0
    MOVE_RESPONSE_SETTLE_DELAY_SECONDS: float = 0.6

    # UI Accuracy
    STAT_SHEET_BASE_HIT_CHANCE: float = 0.60

    config_metadata = {
        "PARRY_SKILL_MULT_PER_POINT": ConfigEntryMeta(
            label="Множитель навыка парирования",
            description="Сколько навык parrying добавляет к шансу парирования. Больше значение делает обученных бойцов заметно сильнее в защите.",
            group="Парирование и щит",
            unit="multiplier",
            min_value=0.0,
            max_value=10.0,
            step=0.1,
            risk="medium",
            live_scope="new_exchange",
            tags=("combat", "balance", "defense"),
        ),
        "SHIELD_BLOCK_POWER_TO_CHANCE": ConfigEntryMeta(
            label="Шанс блока от power щита",
            description="Сколько базового shield block chance дает единица power щита до evasion и mastery gate.",
            group="Парирование и щит",
            unit="ratio",
            min_value=0.0,
            max_value=0.2,
            step=0.001,
            risk="high",
            live_scope="new_exchange",
            tags=("combat", "balance", "shield"),
        ),
        "SHIELD_BLOCK_EVASION_BONUS_RATE": ConfigEntryMeta(
            label="Усиление блока от evasion",
            description="Коэффициент, с которым uncapped evasion повышает шанс shield block.",
            group="Парирование и щит",
            unit="multiplier",
            min_value=0.0,
            max_value=5.0,
            step=0.05,
            risk="high",
            live_scope="new_exchange",
            tags=("combat", "balance", "shield"),
        ),
        "SHIELD_BLOCK_BASE_CAP": ConfigEntryMeta(
            label="Базовый cap shield block",
            description="Потолок shield block chance до расширения от skill_shield_mastery.",
            group="Парирование и щит",
            unit="ratio",
            min_value=0.0,
            max_value=1.0,
            step=0.01,
            risk="high",
            live_scope="new_exchange",
            tags=("combat", "balance", "shield"),
        ),
        "SHIELD_BLOCK_MASTERY_CAP_BONUS": ConfigEntryMeta(
            label="Расширение cap shield block",
            description="Сколько cap shield block добавляет полное skill_shield_mastery.",
            group="Парирование и щит",
            unit="ratio",
            min_value=0.0,
            max_value=1.0,
            step=0.01,
            risk="high",
            live_scope="new_exchange",
            tags=("combat", "balance", "shield"),
        ),
        "SHIELD_GUARD_ABSORB_RATE": ConfigEntryMeta(
            label="Absorb rate shield guard",
            description="Коэффициент временной guard-брони от суммы shield power и physical endurance power.",
            group="Парирование и щит",
            unit="multiplier",
            min_value=0.0,
            max_value=5.0,
            step=0.01,
            risk="high",
            live_scope="new_exchange",
            tags=("combat", "balance", "shield"),
        ),
        "SHIELD_GUARD_EVASION_PENALTY_RATE": ConfigEntryMeta(
            label="Штраф guard от evasion",
            description="Коэффициент, с которым evasion снижает силу каждого успешного shield block.",
            group="Парирование и щит",
            unit="multiplier",
            min_value=0.0,
            max_value=5.0,
            step=0.05,
            risk="high",
            live_scope="new_exchange",
            tags=("combat", "balance", "shield"),
        ),
        "SHIELD_GUARD_EVASION_PENALTY_FLOOR": ConfigEntryMeta(
            label="Минимум guard после evasion",
            description="Нижняя граница множителя guard после штрафа от evasion.",
            group="Парирование и щит",
            unit="ratio",
            min_value=0.0,
            max_value=1.0,
            step=0.01,
            risk="medium",
            live_scope="new_exchange",
            tags=("combat", "balance", "shield"),
        ),
        "SHIELD_COUNTER_CAP": ConfigEntryMeta(
            label="Cap shield counter",
            description="Максимальный шанс instant shield counter после успешного shield block.",
            group="Парирование и щит",
            unit="ratio",
            min_value=0.0,
            max_value=1.0,
            step=0.01,
            risk="high",
            live_scope="new_exchange",
            tags=("combat", "balance", "shield"),
        ),
        "SHIELD_COUNTER_DAMAGE_RATIO": ConfigEntryMeta(
            label="Доля урона shield counter",
            description="Доля main-hand base damage, которую использует instant shield counter до mastery gate.",
            group="Парирование и щит",
            unit="ratio",
            min_value=0.0,
            max_value=2.0,
            step=0.01,
            risk="high",
            live_scope="new_exchange",
            tags=("combat", "balance", "shield"),
        ),
        "SHIELD_OPENING_EVASION_RATE": ConfigEntryMeta(
            label="Evasion tradeoff opening",
            description="Коэффициент, с которым evasion щитовика ослабляет силу shield_opening.",
            group="Парирование и щит",
            unit="multiplier",
            min_value=0.0,
            max_value=5.0,
            step=0.05,
            risk="medium",
            live_scope="new_exchange",
            tags=("combat", "balance", "shield"),
        ),
        "SHIELD_OPENING_MIN_STRENGTH": ConfigEntryMeta(
            label="Минимум shield opening",
            description="Минимальная сила shield_opening до mastery gate при высоком evasion щитовика.",
            group="Парирование и щит",
            unit="ratio",
            min_value=0.0,
            max_value=1.0,
            step=0.01,
            risk="medium",
            live_scope="new_exchange",
            tags=("combat", "balance", "shield"),
        ),
        "SHIELD_OPENING_MAX_STRENGTH": ConfigEntryMeta(
            label="Максимум shield opening",
            description="Максимальная сила shield_opening до mastery gate при низком evasion щитовика.",
            group="Парирование и щит",
            unit="ratio",
            min_value=0.0,
            max_value=1.0,
            step=0.01,
            risk="medium",
            live_scope="new_exchange",
            tags=("combat", "balance", "shield"),
        ),
        "ARMOR_LIGHT_COEF": ConfigEntryMeta(
            label="Коэффициент легкой брони",
            description="Как быстро item armor power легкого комплекта превращается в процентное поглощение урона.",
            group="Броня",
            unit="multiplier",
            min_value=0.0,
            max_value=1.0,
            step=0.001,
            risk="high",
            live_scope="new_exchange",
            tags=("combat", "balance", "armor"),
        ),
        "ARMOR_MEDIUM_COEF": ConfigEntryMeta(
            label="Коэффициент средней брони",
            description="Как быстро item armor power среднего комплекта превращается в процентное поглощение урона.",
            group="Броня",
            unit="multiplier",
            min_value=0.0,
            max_value=1.0,
            step=0.001,
            risk="high",
            live_scope="new_exchange",
            tags=("combat", "balance", "armor"),
        ),
        "ARMOR_HEAVY_COEF": ConfigEntryMeta(
            label="Коэффициент тяжелой брони",
            description="Как быстро item armor power тяжелого комплекта превращается в процентное поглощение урона.",
            group="Броня",
            unit="multiplier",
            min_value=0.0,
            max_value=1.0,
            step=0.001,
            risk="high",
            live_scope="new_exchange",
            tags=("combat", "balance", "armor"),
        ),
        "ARMOR_LIGHT_CAP": ConfigEntryMeta(
            label="Cap легкой брони",
            description="Максимальный процент поглощения урона от armor-stage для легкой брони.",
            group="Броня",
            unit="ratio",
            min_value=0.0,
            max_value=1.0,
            step=0.01,
            risk="high",
            live_scope="new_exchange",
            tags=("combat", "balance", "armor"),
        ),
        "ARMOR_MEDIUM_CAP": ConfigEntryMeta(
            label="Cap средней брони",
            description="Максимальный процент поглощения урона от armor-stage для средней брони.",
            group="Броня",
            unit="ratio",
            min_value=0.0,
            max_value=1.0,
            step=0.01,
            risk="high",
            live_scope="new_exchange",
            tags=("combat", "balance", "armor"),
        ),
        "ARMOR_HEAVY_CAP": ConfigEntryMeta(
            label="Cap тяжелой брони",
            description="Максимальный процент поглощения урона от armor-stage для тяжелой брони.",
            group="Броня",
            unit="ratio",
            min_value=0.0,
            max_value=1.0,
            step=0.01,
            risk="high",
            live_scope="new_exchange",
            tags=("combat", "balance", "armor"),
        ),
        "BASE_ACCURACY_CHANCE": ConfigEntryMeta(
            label="Базовый шанс попадания",
            description="Стартовая вероятность попадания до бонусов навыка, штрафов оружия/стиля и cap.",
            group="Точность",
            unit="ratio",
            min_value=0.0,
            max_value=1.0,
            step=0.01,
            risk="high",
            live_scope="new_exchange",
            tags=("combat", "balance", "accuracy"),
        ),
        "SKILL_ACCURACY_BONUS_AT_FULL": ConfigEntryMeta(
            label="Бонус точности от полного навыка",
            description="Сколько точности добавляет профильный навык оружия или магии при значении навыка 1.0.",
            group="Точность",
            unit="ratio",
            min_value=0.0,
            max_value=1.0,
            step=0.01,
            risk="medium",
            live_scope="new_exchange",
            tags=("combat", "balance", "accuracy"),
        ),
        "ACCURACY_CHANCE_CAP": ConfigEntryMeta(
            label="Потолок шанса попадания",
            description="Максимальная итоговая вероятность попадания после всех бонусов и штрафов.",
            group="Точность",
            unit="ratio",
            min_value=0.0,
            max_value=1.0,
            step=0.01,
            risk="high",
            live_scope="new_exchange",
            tags=("combat", "balance", "accuracy"),
        ),
        "ACCURACY_PENALTY_WEAPON_SKILL_REDUCTION_AT_FULL": ConfigEntryMeta(
            label="Снижение штрафа точности оружием",
            description="Как сильно профильное владение оружием снижает штраф точности при полном навыке.",
            group="Точность",
            unit="ratio",
            min_value=0.0,
            max_value=1.0,
            step=0.01,
            risk="medium",
            live_scope="new_exchange",
            tags=("combat", "balance", "accuracy"),
        ),
        "ACCURACY_PENALTY_STYLE_SKILL_REDUCTION_AT_FULL": ConfigEntryMeta(
            label="Снижение штрафа точности стилем",
            description="Как сильно тактический стиль снижает штраф точности при полном навыке.",
            group="Точность",
            unit="ratio",
            min_value=0.0,
            max_value=1.0,
            step=0.01,
            risk="medium",
            live_scope="new_exchange",
            tags=("combat", "balance", "accuracy"),
        ),
        "ACCURACY_PENALTY_MIN_MULTIPLIER": ConfigEntryMeta(
            label="Минимальный множитель штрафа точности",
            description="Нижняя граница штрафного множителя. Не дает навыкам полностью убрать penalty branch.",
            group="Точность",
            unit="multiplier",
            min_value=0.0,
            max_value=1.0,
            step=0.01,
            risk="medium",
            live_scope="new_exchange",
            tags=("combat", "balance", "accuracy"),
        ),
        "TOKEN_BONUS_CHANCE": ConfigEntryMeta(
            label="Шанс бонусного токена",
            description="Вероятность получить дополнительный боевой token при token roll.",
            group="Ресурсы боя",
            unit="ratio",
            min_value=0.0,
            max_value=1.0,
            step=0.01,
            risk="medium",
            live_scope="new_exchange",
            tags=("combat", "balance", "tokens"),
        ),
        "UNARMED_MIN_EFFICIENCY": ConfigEntryMeta(
            label="Минимальная эффективность безоружки",
            description="Множитель силы для unarmed атаки при нулевом skill_unarmed.",
            group="Безоружный бой",
            unit="multiplier",
            min_value=0.0,
            max_value=5.0,
            step=0.1,
            risk="medium",
            live_scope="new_exchange",
            tags=("combat", "balance", "unarmed"),
        ),
        "UNARMED_MAX_EFFICIENCY": ConfigEntryMeta(
            label="Максимальная эффективность безоружки",
            description="Множитель силы для unarmed атаки при полном skill_unarmed.",
            group="Безоружный бой",
            unit="multiplier",
            min_value=0.0,
            max_value=10.0,
            step=0.1,
            risk="medium",
            live_scope="new_exchange",
            tags=("combat", "balance", "unarmed"),
        ),
        "UNARMED_NOVICE_SPREAD": ConfigEntryMeta(
            label="Разброс безоружки новичка",
            description="Damage spread для unarmed атаки при нулевом навыке.",
            group="Безоружный бой",
            unit="ratio",
            min_value=0.0,
            max_value=1.0,
            step=0.01,
            risk="low",
            live_scope="new_exchange",
            tags=("combat", "balance", "unarmed"),
        ),
        "UNARMED_MASTER_SPREAD": ConfigEntryMeta(
            label="Разброс безоружки мастера",
            description="Минимальный damage spread для unarmed атаки при высоком навыке.",
            group="Безоружный бой",
            unit="ratio",
            min_value=0.0,
            max_value=1.0,
            step=0.01,
            risk="low",
            live_scope="new_exchange",
            tags=("combat", "balance", "unarmed"),
        ),
        "CHAOS_FIRST_CHECK_DELAY_SECONDS": ConfigEntryMeta(
            label="Задержка первой проверки хаоса",
            description="Сколько секунд после старта боя ждать до первого chaos check.",
            group="Сессии и фоновые проверки",
            unit="seconds",
            min_value=0.0,
            max_value=3600.0,
            step=10.0,
            risk="medium",
            live_scope="next_check",
            tags=("combat", "runtime", "chaos"),
        ),
        "SESSION_TTL_SECONDS": ConfigEntryMeta(
            label="Время жизни боевой сессии",
            description="TTL Redis-состояния боя. 3600 = один час.",
            group="Сессии и фоновые проверки",
            unit="seconds",
            min_value=60.0,
            max_value=86400.0,
            step=60.0,
            risk="high",
            live_scope="new_session",
            tags=("combat", "runtime", "ttl"),
        ),
        "MIN_TIMEOUT": ConfigEntryMeta(
            label="Минимальный таймаут хода",
            description="Базовый таймаут для хода (в секундах), если игрок не AFK.",
            group="Сессии и фоновые проверки",
            unit="seconds",
            min_value=5.0,
            max_value=120.0,
            step=1.0,
            risk="medium",
            live_scope="new_exchange",
            tags=("combat", "runtime", "timeout"),
        ),
        "MOVE_RESPONSE_SETTLE_DELAY_SECONDS": ConfigEntryMeta(
            label="Задержка обработки хода",
            description="Искусственная задержка (в секундах) перед отдачей результата, чтобы дать движку время на обработку.",
            group="Сессии и фоновые проверки",
            unit="seconds",
            min_value=0.0,
            max_value=5.0,
            step=0.1,
            risk="low",
            live_scope="new_exchange",
            tags=("combat", "runtime", "delay"),
        ),
        "STAT_SHEET_BASE_HIT_CHANCE": ConfigEntryMeta(
            label="UI Базовый шанс попадания",
            description="Базовый шанс попадания для отображения в статистике персонажа.",
            group="Точность",
            unit="ratio",
            min_value=0.0,
            max_value=1.0,
            step=0.01,
            risk="low",
            live_scope="immediate",
            tags=("combat", "ui", "accuracy"),
        ),
    }
